variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "80"
  ORD_SOUMET_TMPFS: "10G"
  ORD_SOUMET_M: "100G"
  ORD_SOUMET_W: "60"
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - package
  - deploy
  - run_intel_icelake
  - run_gnu_9.3.0_mpich
  - run_gnu_12.1.0_openmpi

before_script:
  - export CLICOLOR_FORCE=1
  - source ~/ci-admin/env/init.sh

# U2 GNU 9.3.0 with oneAPI
build:gnu-9.3.0-mpich:
  stage: build
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - git submodule update --recursive --init
    - . ./.eccc_setup_gnu
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake-all
    - time make -j $NCPUS work
  artifacts:
    expire_in: 2 hrs
    paths:
    - work-rhel-8-amd64-64-gnu-9.3.0
    - gem_dbase

# U2 GNU 12.1.0 with OpenMPI
build:gnu-12.1.0-openmpi:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - git submodule update --recursive --init
    - . ./.eccc_setup_gnu_12
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake-all
    - time make -j $NCPUS work
  allow_failure: true
  artifacts:
    expire_in: 2 hrs
    paths:
    - work-rhel-8-amd-64-gnu-12.1.0
    - gem_dbase

#----- rhel-8-icelake-64-intel-2022.1.2

# U2 Intel 2022 with RPN-SI sources
build:intel-with-sources-rhel-8-icelake-64-intel-2022.1.2:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - git submodule update --recursive --init
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake-all
    - time make -j $NCPUS
  allow_failure: true

# U2 Intel 2022 with installed RPN-SI libs
# Used for testing configs and for SSM package
build:rhel-8-icelake-64-intel-2022.1.2:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake
    - time make -j $NCPUS work
  artifacts:
    expire_in: 2 hrs
    paths:
    - build-rhel-8-icelake-64-intel-2022.1.2
    - work-rhel-8-icelake-64-intel-2022.1.2
    - gem_dbase

package:rhel-8-icelake-64-intel-2022.1.2:
   stage: package
   only:
      - tags
      - dev
      - feat_ops_publish
      - schedules
   dependencies:
      - build:rhel-8-icelake-64-intel-2022.1.2
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - . ./.eccc_setup_intel
      - set -e
      - cd build-rhel-8-icelake-64-intel-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

# U2 Intel 2021 with installed RPN-SI libs
# Used for SSM package
build:rhel-8-icelake-64-intel-2021.4.0:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel_2021.4.0
    - . ./.initial_setup
    - make cmake
    - time make -j $NCPUS
  artifacts:
    expire_in: 2 hrs
    paths:
    - build-rhel-8-icelake-64-intel-2021.4.0

package:rhel-8-icelake-64-intel-2021.4.0:
   stage: package
   only:
      - tags
      - dev
      - feat_ops_publish
      - schedules
   dependencies:
      - build:rhel-8-icelake-64-intel-2021.4.0
   script:
      - set +e
      - . ~/ci-env/latest/profile.sh
      - . ./.eccc_setup_intel_2021.4.0
      - set -e
      - cd build-rhel-8-icelake-64-intel-2021.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

deploy:staging:
   stage: deploy
   only:
      - tags
      - dev
      - feat_ops_publish
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh gem gem "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

#----- Running configurations for rhel-8-icelake-64-intel-2022.1.2
5.2GEM_GY_FISL_H_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=5.2GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_W7cascP_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  allow_failure: true
  only:
  - dev
  - tags
  - 5.2_cmake
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_W7cascP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_dcmip163r100_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_dcmip163r100
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_wil7_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_wil7
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_cfgs_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_P_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_P
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_H_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_LU_FISL_H_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_LU_OFFC_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_OFFC
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

PTOPO_GYH_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_GYH
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

PTOPO_LUP_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_LUP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

RSTRT_GYP_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=RSTRT_cfgs_GYP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

THEO_bubbleG_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=THEO_cfgs_bubbleG
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
    - test "${_status}" == "ED"

THEO_schar_intel:
  stage: run_intel_icelake
  dependencies:
  - build:rhel-8-icelake-64-intel-2022.1.2
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=THEO_cfgs_schar
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
    - test "${_status}" == "ED"

5.2GEM_GY_FISL_H_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=5.2GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_W7cascP_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=CANO_cfgs_W7cascP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_dcmip163r100_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=CANO_cfgs_dcmip163r100
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

CANO_wil7_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=CANO_cfgs_wil7
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_cfgs_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=GEM_cfgs
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_P_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_P
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_H_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_LU_FISL_H_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

GEM_LU_OFFC_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_OFFC
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

PTOPO_GYH_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_GYH
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

PTOPO_LUP_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_LUP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

RSTRT_GYP_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=RSTRT_cfgs_GYP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"

THEO_bubbleG_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=THEO_cfgs_bubbleG
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
    - test "${_status}" == "ED"

THEO_schar_gnu:
  stage: run_gnu_9.3.0_mpich
  dependencies:
  - build:gnu-9.3.0-mpich
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - cd $GEM_WORK
    - CFG=THEO_cfgs_schar
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
    - test "${_status}" == "ED"

5.2GEM_GY_FISL_H_gnu_12:
  stage: run_gnu_12.1.0_openmpi
  dependencies:
  - build:gnu-12.1.0-openmpi
  when: always
  only:
  - dev
  - tags
  - 5.2_cmake
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=5.2GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo -inorder 1;
      fi
    - test "${_status}" == "ED"
