variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_W: "30"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_TMPFS: "1G"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - source ~/ci-admin/env/init.sh
  - export CLICOLOR_FORCE=1

# U3 Intel 2025
build_intel:
  stage: build
  when: always
  script:
    - set +e
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - make cmake
    - make -j `nproc`
