# Define MACH source files
set(CHEMSRC
   base/chm_businit.F90
   base/chm_cffeps_init.F90
   base/chm_consphychm_mod.F90
   base/chm_datime_mod.F90
   base/chm_exe.F90
   base/chm_fst_closefile.F90
   base/chm_fst_openfile.F90
   base/chm_getphybus_struct.F90
   base/chm_headers_mod.F90
   base/chm_init.F90
   base/chm_load_emissions.F90
   base/chm_load_metvar.F90
   base/chm_load_store_tracers.F90
   base/chm_metvar_mod.F90
   base/chm_mjrpts_get_emissions.F90
   base/chm_mjrpts_get_size.F90
   base/chm_mjrpts_get_stkinfo.F90
   base/chm_mjrpts_sortinfo_mod.F90
   base/chm_nml.F90
   base/chm_nml_mod.F90
   base/chm_phyvar_mod.F90
   base/chm_pkg_fields_init.F90
   base/chm_ptopo_grid_mod.F90
   base/chm_set_dbg_point.F90
   base/chm_species_idx_mod.F90
   base/chm_species_info_mod.F90
   base/chm_utils_mod.F90
   base/difuvdfj_2d.F90
   base/gocart_so2so4.F90
   base/mach_adom2_drive.F90
   base/mach_adom2_rates_mod.F90
   base/mach_adom2kpp_main.F90
   base/mach_adom2kppb_main.F90
   base/mach_adom2yb_main.F90
   base/mach_aurams_cldcv2d.F90
   base/mach_aurams_headers_mod.F90
   base/mach_aurams_prntrow.F90
   base/mach_aurams_tsysms.F90
   base/mach_biog_beis.F90
   base/mach_biog_main.F90
   base/mach_biog_parcalc.F90
   base/mach_calc_diag.F90
   base/mach_calc_season.F90
   base/mach_cam_aeroact.F90
   base/mach_cam_aerocld.F90
   base/mach_cam_aeroprop.F90
   base/mach_cam_cas.F90
   base/mach_cam_cas_split.F90
   base/mach_cam_coagd.F90
   base/mach_cam_condsoa.F90
   base/mach_cam_drydep1.F90
   base/mach_cam_drydep2.F90
   base/mach_cam_drydep_main.F90
   base/mach_cam_drypar.F90
   base/mach_cam_flux.F90
   base/mach_cam_headers_mod.F90
   base/mach_cam_intrsec1_inner.F90
   base/mach_cam_intrsec1_outer.F90
   base/mach_cam_intrsec_inner.F90
   base/mach_cam_intrsec_outer.F90
   base/mach_cam_main.F90
   base/mach_cam_rain.F90
   base/mach_cam_scaveng.F90
   base/mach_cam_sfss.F90
   base/mach_cam_sulfate.F90
   base/mach_cam_utils_mod.F90
   base/mach_canopy_levels.F90
   base/mach_canopy_transfer.F90
   base/mach_cffeps_calc.F90
   base/mach_cffeps_diurnal_mod.F90
   base/mach_cffeps_emissions_mod.F90
   base/mach_cffeps_energy.F90
   base/mach_cffeps_fbp_mod.F90
   base/mach_cffeps_main.F90
   base/mach_cffeps_mod.F90
   base/mach_cffeps_plumes_mod.F90
   base/mach_cffeps_procalc.F90
   base/mach_cffeps_speciations_mod.F90
   base/mach_diff_boundary.F90
   base/mach_diff_flux.F90
   base/mach_diff_prep.F90
   base/mach_diff_rpnphy.F90
   base/mach_diffusion.F90
   base/mach_drydep_mod.F90
   base/mach_gas_bidi.F90
   base/mach_gas_canopy.F90
   base/mach_gas_drydep_main.F90
   base/mach_gas_drydep_ra.F90
   base/mach_gas_drydep_ra2.F90
   base/mach_gas_drydep_solver.F90
   base/mach_gas_drydep_solver2.F90
   base/mach_gas_drydep_stat.F90
   base/mach_gas_headers_mod.F90
   base/mach_gas_main.F90
   base/mach_gas_messy.F90
   base/mach_gas_strato.F90
   base/mach_headers_mod.F90
   base/mach_hetv_activity.F90
   base/mach_hetv_case1.F90
   base/mach_hetv_case10.F90
   base/mach_hetv_case11.F90
   base/mach_hetv_case12.F90
   base/mach_hetv_case2.F90
   base/mach_hetv_case3.F90
   base/mach_hetv_case4.F90
   base/mach_hetv_case5.F90
   base/mach_hetv_case6.F90
   base/mach_hetv_case7.F90
   base/mach_hetv_case8.F90
   base/mach_hetv_case9.F90
   base/mach_hetv_corrhno3.F90
   base/mach_hetv_headers_mod.F90
   base/mach_hetv_hetchem.F90
   base/mach_hetv_hetvcall.F90
   base/mach_hetv_main_12cases.F90
   base/mach_hetv_main_2cases.F90
   base/mach_hetv_mod.F90
   base/mach_hetv_poly3v.F90
   base/mach_hetv_rebin.F90
   base/mach_hetv_water.F90
   base/mach_incld_concmp.F90
   base/mach_incld_diffun.F90
   base/mach_incld_dochem.F90
   base/mach_incld_fff.F90
   base/mach_incld_findh.F90
   base/mach_incld_fn_dtnew.F90
   base/mach_incld_funeq.F90
   base/mach_incld_headers_mod.F90
   base/mach_incld_intrqf.F90
   base/mach_incld_intsca_il.F90
   base/mach_incld_main.F90
   base/mach_incld_mod.F90
   base/mach_incld_rates.F90
   base/mach_incld_soleq.F90
   base/mach_incld_steady_mod.F90
   base/mach_incld_upaqr_mod.F90
   base/mach_input_check.F90
   base/mach_kpp_Integrator.F90
   base/mach_kpp_adom2_Function.F90
   base/mach_kpp_adom2_Jacobian.F90
   base/mach_kpp_adom2_JacobianSP.F90
   base/mach_kpp_adom2_LinearAlgebra.F90
   base/mach_kpp_adom2_rates.F90
   base/mach_kpp_interface.F90
   base/mach_kpp_saprc07_rates.F90
   base/mach_kpp_saprc07c_Function.F90
   base/mach_kpp_saprc07c_Jacobian.F90
   base/mach_kpp_saprc07c_JacobianSP.F90
   base/mach_kpp_saprc07c_LinearAlgebra.F90
   base/mach_kpp_saprc07cs_Function.F90
   base/mach_kpp_saprc07cs_Jacobian.F90
   base/mach_kpp_saprc07cs_JacobianSP.F90
   base/mach_kpp_saprc07cs_LinearAlgebra.F90
   base/mach_kppb_adom2_interface.F90
   base/mach_kppb_adom2day_rodas3.F90
   base/mach_kppb_adom2night_rodas3.F90
   base/mach_lai_adjust.F90
   base/mach_landuse.F90
   base/mach_main.F90
   base/mach_marine_halo.F90
   base/mach_messy_jval_mod.F90
   base/mach_mie_data_mod.F90
   base/mach_mie_opt.F90
   base/mach_output.F90
   base/mach_pkg_adom2_mod.F90
   base/mach_pkg_cam_mod.F90
   base/mach_pkg_debug_mod.F90
   base/mach_pkg_diag_mod.F90
   base/mach_pkg_gas_mod.F90
   base/mach_pkg_messy_mod.F90
   base/mach_pkg_misc_mod.F90
   base/mach_pkg_saprc_mod.F90
   base/mach_pkg_tendencies_mod.F90
   base/mach_plumerise.F90
   base/mach_plumerise_weight.F90
   base/mach_plumerise_weight4fire.F90
   base/mach_pm_chem.F90
   base/mach_saprc_main.F90
   base/mach_soa_jiang.F90
   base/mach_soa_odum.F90
   base/mach_soa_odum_mod.F90
   base/mach_stepinit.F90
   base/mach_suncos.F90
   base/mach_tridiag.F90
   base/mach_vit_diffusivity.F90
 )
set(GEMMODSRC
     gemmod/rpnphy/condensation.F90
     gemmod/rpnphy/microphy_my2.F90
     gemmod/rpnphy/microphy_p3.F90
     gemmod/rpnphy/phyexe.F90
 )
