!-------------------------------------- LICENCE BEGIN -------------------------
!Environment Canada - Atmospheric Science and Technology License/Disclaimer,
!                     version 3; Last Modified: May 7, 2008.
!This is free but copyrighted software; you can use/redistribute/modify it under the terms
!of the Environment Canada - Atmospheric Science and Technology License/Disclaimer
!version 3 or (at your option) any later version that should be found at:
!http://collaboration.cmc.ec.gc.ca/science/rpn.comm/license.html

!This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
!without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
!See the above mentioned License/Disclaimer for more details.
!You should have received a copy of the License/Disclaimer along with this software;
!if not, you can write to: EC-RPN COMM Group, 2121 TransCanada, suite 500, Dorval (Quebec),
!CANADA, H9P 1J3; or send e-mail to service.rpn@ec.gc.ca
!-------------------------------------- LICENCE END ---------------------------


subroutine ISCCP_SIM_DRIVER(CLDPT, CLDTP, CLDTAU, CLDEP, CLDFRAC,   &! OUTPUT
     SUNLIT, &
     CLW_SUB, CIC_SUB, PRESSG, SHJ, SHTJ,    &! INPUT
     IL1, IL2, ILG, LAY, LEV, &
     COSZ, GT, T, Q, MG, ML)
   use tdpack_const
   implicit none
!!!#include <arch_specific.hf>

#include "nbsnbl.cdk"
#include "mcica.cdk"

   !@Author Jason Cole Dec. 16, 2005
   !@Object PART OF THE ISCCP CLOUD SIMULATOR PACKAGE

   !---------------------------------------------------------------------------
   ! This code generates is a slightly modified version of the ISCCP simulator.
   ! Rather than use the cloud generator provided with the simulator this version
   ! uses as input subcolumns generated by the stochastic cloud generator of Barker
   ! and Rasiasen.  I.e., the ISCCP simulator works on the same clouds as the radiation
   ! in the Monte Carlo Independent Column Approximation.
   !---------------------------------------------------------------------------

   ! INPUT DATA

   integer, intent(IN) :: &
        IL1, &
        IL2, &
        ILG, &
        LAY, &
        LEV

   real, intent(IN) :: &
        CLW_SUB(ILG,LAY,NX_LOC), &
        CIC_SUB(ILG,LAY,NX_LOC), &
        PRESSG(ILG), &
        SHJ(ILG,LAY), &
        SHTJ(ILG,LEV), &
        COSZ(ILG), &
        GT(ILG), &
        T(ILG,LAY), &
        Q(ILG,LAY), &
        MG(ILG), &
        ML(ILG)


   ! OUTPUT DATA


   real, intent(OUT) :: &
        CLDPT(ILG,NTAU*NPTOP), &
        CLDTP(ILG), &
        CLDTAU(ILG), &
        CLDEP(ILG), &
        CLDFRAC(ILG), &
        SUNLIT(ILG)


   ! WORK DATA


   real :: &
        CLDMASK(ILG,LAY), &
        TAU_VIS(ILG,LAY), &
        EMS_CLD(ILG,LAY), &
        PFULL(ILG,LAY), &
        CIC(ILG,LAY), &
        CLW(ILG,LAY), &
        DZ(ILG,LAY), &
        PHALF(ILG,LEV), &
        EMS_SFC(ILG), &
        TAU_SUB(ILG), &
        PTOP_SUB(ILG), &
        RAN_NUM(ILG), &
        REI(ILG,LAY), &
        REL(ILG,LAY), &
        AIRD(ILG,LAY)

   integer :: &
        RAN_INDEX(ILG), &
        SUNLIT_LOC(ILG)


   ! LOCAL DATA (SCALAR)


   integer :: &
        ICOL, &
        IND1, &
        IL, &
        ILAY, &
        ITAU, &
        IPRES, &
        IT, &
        IP, &
        ITP

   real :: &
        INVREL, &
        INVREI, &
        TAULIQVIS, &
        TAULIQIR, &
        TAUICEVIS, &
        TAUICEIR, &
        TAU_IR, &
        A, &
        B, &
        C, &
        DP1, &
        DP2, &
        DP3, &
        DP_LOC


   ! PARAMETERS


   real, parameter :: COSZ_MIN = 0.2          ! CUTOFF FOR DAYLIGHT PER ISCCP
   real, parameter :: THIRD    = 0.3333333333333
   real, parameter :: RU       = 1.6487213

   ! LOWER BOUNDS CLOUD TAU AND CLOUD TOP PRESSURE BINS
   real, parameter :: P_TOP_BNDS(NPTOP) = (/0.0  ,180.0,310.0,440.0, &
        560.0, 680.0, 800.0/)
   real, parameter :: TAU_BNDS(NTAU) = (/0.0 ,0.3 ,1.3,3.6,9.4, &
        23.0,60.0/)

   real, parameter :: TAUCHK = 0.000001 !-1.*log(0.9999999)

   ! ZERO OUT SOME ARRAYS


   do ILAY = 1, LAY
      do IL = IL1, IL2
         TAU_VIS(IL,ILAY) = 0.0
      end do ! IL
   end do ! ILAY

   do IL = IL1, IL2
      CLDTP(IL)   = 0.0
      CLDTAU(IL)  = 0.0
      CLDEP(IL)   = 0.0
      CLDFRAC(IL) = 0.0
      SUNLIT(IL)  = 0.0
   end do ! IL

   do ITP = 1, NPTOP*NTAU
      do IL = IL1, IL2
         CLDPT(IL,ITP) = 0.0
      end do ! IL
   end do ! ITP


   !----------------------------------------------------------------------C
   !     COMPUTE THE AIR DENSITY IN KG/M^3 AND THE LAYER THICKNESS IN M   C
   !----------------------------------------------------------------------C


   do ILAY = 1, LAY
      do IL = IL1, IL2
         AIRD(IL,ILAY) =  SHJ(IL,ILAY) * PRESSG(IL) &
              / ( T(IL,ILAY) * RGASD )
         DP1=0.5*(SHJ(IL,min(ILAY+1,LAY))-SHJ(IL,max(ILAY-1,1)))
         DP2=0.5*(SHJ(IL,1)+SHJ(IL,2))
         DP3=0.5*(1.-SHJ(IL,LAY))
         if (ILAY .eq. 1) then
            DP_LOC = DP2
         else if (ILAY .eq. LAY) then
            DP_LOC = DP3
         else
            DP_LOC = DP1
         endif

         DP_LOC= max(DP_LOC*PRESSG(IL),0.)
         DZ(IL,ILAY)= DP_LOC/(AIRD(IL,ILAY)*GRAV)
      end do ! IL
   end do ! ILAY

   ! SET SURFACE EMISSIVITY TO 0.9999999
   ! SHOULD BE PASSED IN WHEN SURFACE EMISSIVITY IS COMPUTED BY
   ! GCM

   do IL = IL1, IL2
      EMS_SFC(IL) = 0.9999999
   end do ! IL

   ! SUNLIT ARRAY
   do IL = IL1, IL2
      if (COSZ(IL) .ge. COSZ_MIN) then
         SUNLIT_LOC(IL) = 1
      else
         SUNLIT_LOC(IL) = 0
      end if
   end do

   ! COMPUTE PRESSURES

   do IL = IL1, IL2
      PHALF(IL,LEV) = SHTJ(IL,LEV)*PRESSG(IL)
   end do ! IL

   do ILAY = 1, LAY
      do IL = IL1, IL2
         PHALF(IL,ILAY) = SHTJ(IL,ILAY)*PRESSG(IL)
         PFULL(IL,ILAY) = SHJ(IL,ILAY)*PRESSG(IL)
      end do ! IL
   end do ! ILAY

   ! LOOP OVER THE SUBCOLUMNS TO SAMPLE FROM, RANDOMLY SELECT SUBCOLUMNS
   ! AND APPLY THE ISCCP SIMULATOR ALGORIGHTM TO THE SUBCOLUMNS.
   ! THE RESULTS FOR EACH SUBCOLUMN ARE THEN ACCUMULATED TO GIVE A
   ! GCM COLUMN MEAN.

   do ICOL = 1, NSUBCOL

      ! RANDOMLY SELECT A SUBCOLUMN

      call random_number(RAN_NUM)
      do Il = IL1, IL2
         IND1 = int(RAN_NUM(IL)*real(NX_LOC))
         if (IND1 .gt. NX_LOC) IND1 = NX_LOC
         if (IND1 .lt. 1)      IND1 = 1
         RAN_INDEX(IL) = IND1
      end do ! IL
      do IL = IL1, IL2
         IND1 = RAN_INDEX(IL)
         do ILAY = 1, LAY
            CLW(IL,ILAY) = CLW_SUB(IL,ILAY,IND1)
            CIC(IL,ILAY) = CIC_SUB(IL,ILAY,IND1)
            if ((CLW(IL,ILAY)+CIC(IL,ILAY)) .gt. 1.0e-9) then
               CLDMASK(IL,ILAY) = 1.0
            else
               CLDMASK(IL,ILAY) = 0.0
            end if
         end do ! ILAY
      end do ! IL

      ! COMPUTE THE CLOUD OPTICAL THICKNESS AT ~0.6 AND ~10.5 MICRONS
      ! THESE VALUES ARE FROM J. LI (JAN. 22, 2006)

      ! COMPUTE THE CLOUD EFFECTIVE RADII

      call COMPUTE_RE1(REI, REL, &
           CLW, CIC, AIRD, &
           MG, ML, ILG, LAY)

      !         WRITE(22,*) MAXVAL(REI),MAXVAL(REL),MINVAL(REI),MINVAL(REL)

      ! COMPUTE THE CLOUD OPTICAL THICKNESS AT ~0.6 AND ~10.5 MICRONS
      ! THESE CO-EFFICIENTS ARE FROM J. LI (JAN. 22, 2006)

      do ILAY = 1, LAY
         do IL = IL1, IL2

            if (CLDMASK(IL,ILAY) .gt. 0.0) then

               INVREL = 1.0/REL(IL,ILAY)
               INVREI = 1.0/REI(IL,ILAY)

               ! COMPUTE OPTICAL THICKNESS WATER CLOUDS
               if (CLW(IL,ILAY) .gt. 0.0) then
                  TAULIQVIS = CLW(IL,ILAY)*(4.483e-04 + INVREL * (1.501 &
                       + INVREL*(7.441e-01 - INVREL * 9.620e-01)))
                  TAULIQIR  = CLW(IL,ILAY)*(0.14532e-01 - 0.47449e-03 &
                       * REL(IL,ILAY) + INVREL*(0.22898e+01 - INVREL &
                       * (0.92402e+01 - INVREL * 0.100999e+02)))
               else
                  TAULIQVIS = 0.0
                  TAULIQIR  = 0.0
               end if

               ! COMPUTE OPTICAL THICKNESS ICE CLOUDS
               if (CIC(IL,ILAY) .gt. 0.0) then
                  TAUICEVIS = CIC(IL,ILAY) &
                       * (-0.303108e-04 + 0.251805e+01 * INVREI)

                  TAUICEIR = CIC(IL,ILAY) * (-7.627102e-03 + 3.406420 &
                       * INVREI - 1.732583e+01 * (INVREI**2))
               else
                  TAUICEVIS = 0.0
                  TAUICEIR  = 0.0
               end if

               TAU_VIS(IL,ILAY) = (TAULIQVIS + TAUICEVIS)*DZ(IL,ILAY)
               TAU_IR           = (TAULIQIR  + TAUICEIR)*DZ(IL,ILAY)
               EMS_CLD(IL,ILAY) = 1.0-exp(-RU*TAU_IR)
            else
               TAU_VIS(IL,ILAY)  = 0.0
               EMS_CLD(IL,ILAY) = 0.0
            end if

         end do              ! IL
      end do                 ! ILAY

      ! CALL THE ISCCP SIMULATOR
      call ISCCP_SIM1(TAU_SUB, PTOP_SUB,                   &! OUTPUT
           IL1, IL2,ILG, LAY, CLD_HGT,                    &! INPUT
           PFULL, PHALF, Q, CLDMASK, TAU_VIS, EMS_CLD, T, &
           GT, EMS_SFC)

      ! CONVERT PTOP FROM Pa TO hPa

      do IL = IL1, IL2
         PTOP_SUB(IL) = PTOP_SUB(IL)/100.0
      end do

      ! COMPUTE THE VARIOUS ISCCP QUANTITIES

      do IL = IL1, IL2
         ! ADD CONTRIBUTIONS TO THE HISTOGRAM OF CLOUD TOP PRESSURE AND CLOUD OPTICAL THICKNESS
         ! DO SO IF SUN IS UP
         if (SUNLIT_LOC(IL) .gt. 0) then

            IPRES = 0

            IP = 1
            if (PTOP_SUB(IL) .gt. P_TOP_BNDS(IP) .and. &
                 PTOP_SUB(IL) .lt. P_TOP_BNDS(IP+1)) then
               IPRES = IP
            end if

            do IP = 2, NPTOP-1
               if (PTOP_SUB(IL) .ge. P_TOP_BNDS(IP) .and. &
                    PTOP_SUB(IL) .lt. P_TOP_BNDS(IP+1)) then
                  IPRES = IP
               end if
            end do ! IP

            if (PTOP_SUB(IL) .ge. P_TOP_BNDS(NPTOP)) IPRES=NPTOP

            ITAU = 0
            IT = 1
            if (TAU_SUB(IL) .gt. TAUCHK .and. &
                 TAU_SUB(IL) .lt. TAU_BNDS(IT+1)) then
               ITAU = IT
            end if

            do IT = 2, NTAU-1
               if (TAU_SUB(IL) .ge. TAU_BNDS(IT) .and. &
                    TAU_SUB(IL) .lt. TAU_BNDS(IT+1)) then
                  ITAU = IT
               end if
            end do ! IT

            if (TAU_SUB(IL) .ge. TAU_BNDS(NPTOP)) ITAU=NTAU

            if (IPRES .gt. 0 .and. ITAU .gt. 0) then
               ITP = (IPRES-1)*NTAU+ITAU
               CLDPT(IL,ITP) = CLDPT(IL,ITP) + 1.0
            end if
         end if
      end do ! IL

      ! ACCUMULATE THE DOMAIN-MEAN PROPERTIES

      do IL = IL1, IL2
         if (SUNLIT_LOC(IL) .gt. 0   .and. &
              PTOP_SUB(IL)  .gt. 0.0 .and. &
              TAU_SUB(IL)   .gt. TAUCHK) then

            ! LINEAR TAU
            CLDTAU(IL) = CLDTAU(IL) + TAU_SUB(IL)

            ! CLOUD LOG MEAN VISIBLE OPTICAL THICKNESS (ACTUALLY ALBEDO (RADIATIVE) MEAN)
            CLDEP(IL) = CLDEP(IL) &
                 + real(INVTAU(min(nint(100.0*TAU_SUB(IL)),45000)))

            ! CLOUD MEAN CLOUD TOP PRESSURE
            CLDTP(IL) = CLDTP(IL) + PTOP_SUB(IL)

            ! TOTAL CLOUD FRACTION
            CLDFRAC(IL) = CLDFRAC(IL) + 1.0
         end if
      end do ! IL
   end do ! ICOL

   ! NOW THAT WE HAVE WORKED OVER THE ALL OF THE SUBCOLUMNS COMPUTE THE
   ! PROPER MEANS

   do IL = IL1, IL2
      ! VARIABLES RELATED TO CLOUD OPTICAL THICKNESS AND VARIABLITY
      if (SUNLIT_LOC(IL) .gt. 0) then
         if (CLDFRAC(IL) .gt. 0.0) then
            CLDTAU(IL)  = CLDTAU(IL)/CLDFRAC(IL)
            A           = CLDEP(IL)/CLDFRAC(IL)
            B           = TAUTAB(min(255,max(1,nint(A))))
            C           = min(B,CLDTAU(IL))
            CLDEP(IL)   = 1.0-C/CLDTAU(IL)
            CLDTAU(IL)  = B ! USE RADIATIVELY AVERAGED CLOUD OPTICAL THICKNESS
            CLDTP(IL)   = CLDTP(IL)/CLDFRAC(IL)
            CLDFRAC(IL) = CLDFRAC(IL)/real(NSUBCOL)
            do ITP = 1, NPTOP*NTAU
               CLDPT(IL,ITP) = CLDPT(IL,ITP)/real(NSUBCOL)
            end do ! ITP
         else
            CLDTAU(IL)  = -999.0
            CLDEP(IL)   = -999.0
            CLDTP(IL)   = -999.0
            CLDFRAC(IL) = 0.0
         end if
      else
         CLDTAU(IL)  = -999.0
         CLDEP(IL)   = -999.0
         CLDTP(IL)   = -999.0
         CLDFRAC(IL) = -999.0
         do ITP = 1, NPTOP*NTAU
            CLDPT(IL,ITP) = -999.0
         end do ! ITP
      end if
      SUNLIT(IL) = real(SUNLIT_LOC(IL))
   end do ! IL

end subroutine ISCCP_SIM_DRIVER

