$(info using default setup)
# this is for vanilla gcc/gfortran/mpicc/mpif90 to be adjusted on target system

CFLAGS  = -fpic -O2
FCFLAGS = -fpic -fno-second-underscore -fcray-pointer -O2

CC      = gcc
FC      = gfortran
F90C    = fortran
MPICC   = mpicc
MPIFC   = mpif77
MPIF90C = mpif90

# end of vanilla gcc/gfortran/mpicc/mpif90 defaults

