# Window for running binaries must have the compiler environment that
# goes with the binaries created.

# make sure you source the .common_setup file to set the environment
#  variables needed to run GEM
. ./.common_setup [intel|gnu]

cd gem/work[...]
#-ptopo [npx] x [npy] x [OMP_NUM_THREADS] where npx, npy is for MPI topology

#test configuration
runprep.sh -dircfg configurations/GEM_cfgs
runmod.sh  -dircfg configurations/GEM_cfgs

#GY (actually uses double cpus)- in this example: uses 16 cpus
runprep.sh -dircfg configurations/GEM_cfgs_GY_FISL_P
runmod.sh  -dircfg configurations/GEM_cfgs_GY_FISL_P -ptopo 2x2x2

#Schaer case - must run with -ptopo 10x1
runprep.sh -dircfg configurations/THEO_cfgs_schar
runmod.sh  -dircfg configurations/THEO_cfgs_schar -ptopo 10x1
\rm schaer
flipit -i RUNMOD/output/cfg_0000/laststep_0000000450/000-000/dm2011012200-000-000_004 -o schaer
#Use xrec to visualise the records
xrec -imflds schaer

#Bubble case - must run with -ptopo 5x1
runprep.sh -dircfg configurations/THEO_cfgs_bubbleG
runmod.sh  -dircfg configurations/THEO_cfgs_bubbleG -ptopo 5x1
\rm bubble
flipit -i RUNMOD/output/cfg_0000/laststep_0000000216/000-000/dm2011012200-000-000_001 -o bubble
#Use xrec to visualise the records
xrec -imflds bubble
Choose variable TH, step 120
Display contour 0

#Use voir to see what records are produced in the FST files
voir -iment RUNMOD/output/cfg_0000/laststep_0000000024/000-000/dm2009042700-000-000_010

#Use xrec to visualise the records
xrec -imflds RUNMOD/output/cfg_0000/laststep_0000000024/000-000/dm2009042700-000-000_010

#Use fststat to look at statistical means on the records
fststat -fst RUNMOD/output/cfg_0000/laststep_0000000024/000-000/dm2009042700-000-000_010

#pgsm is a program to interpolate records to a different grid
pgsm -iment <input FST> -ozsrt <output FST> -i <pgsm.directives>

#editfst is a program to manipulate records into another file
editfst -s <input FST> -d <output FST> -i <editfst.directives>
