#!/bin/ksh

/bin/rm -rf RSTRT_cfgs_* PREP/* RUNMOD/*
cp -r ${SRC_TESTS}/RSTRT_cfgs_* .

for i in RSTRT_cfgs_* ; do
  echo TREATING: $i
  CFG=$i
  if [ -z "${NORUN_GEM}" ] ; then
    /bin/rm -f RESULTS/$EXP/listings/${CFG}_prep.lis RESULTS/$EXP/listings/${CFG}_mod.lis
    printf "couleur_model=red\n" > RESULTS/$EXP/status/${CFG}_MODEL
    . $CFG/cfg_0000/configexp.cfg
    _status="ABORT"
    . r.call.dot runprep.sh -dircfg $CFG 1> RESULTS/$EXP/listings/${CFG}_prep.lis_1 2>&1
    if [ "${_status}" == "ED" ] ; then
       _status="ABORT"
       . r.call.dot runmod.sh -dircfg $CFG -ptopo $GEMTEST_ptopo -inorder > RESULTS/$EXP/listings/${CFG}_mod.lis_1 2>&1
      if [ "${_status}" == "ED" ] ; then
         _status="ABORT"
         . r.call.dot runprep.sh -dircfg $CFG -cfg 1:1 1> RESULTS/$EXP/listings/${CFG}_prep.lis_2 2>&1
         . $CFG/cfg_0001/configexp.cfg
         _status="ABORT"
         . r.call.dot runmod.sh -dircfg $CFG -cfg 1:1 -ptopo $GEMTEST_ptopo -inorder >  RESULTS/$EXP/listings/${CFG}_mod.lis_2 2>&1
         if [ "${_status}" == "RS" ] ; then
            _status="ABORT"
            . r.call.dot runmod.sh -dircfg $CFG -cfg 1:1 -ptopo $GEMTEST_ptopo -inorder >> RESULTS/$EXP/listings/${CFG}_mod.lis_2 2>&1
         fi
         if [ "${_status}" == "ED" ] ; then
           printf "couleur_model=yellow\n" > RESULTS/$EXP/status/${CFG}_MODEL
         fi
       fi
    fi
  fi

  if [ -f RESULTS/$EXP/status/${CFG}_MODEL ] ; then
    . RESULTS/$EXP/status/${CFG}_MODEL
  else
    couleur_model=red
  fi
  COULEUR="red"

  if [ "${couleur_model}" == "yellow" ] ; then
    if [ -e RESULTS/$EXP/listings/${CFG}_mod.lis_1 -a -e RESULTS/$EXP/listings/${CFG}_mod.lis_2 ] ; then
      n=$(grep "GEM_RUN: END OF THE TIME LOOP AT TIMESTEP" RESULTS/$EXP/listings/${CFG}_mod.lis_1 --text | tail -1 | awk '{printf $NF}')
      nc=$((5-$(echo $n | wc -c)))
      grep -i mean: RESULTS/$EXP/listings/${CFG}_mod.lis_1 --text | grep "oe-00000-00000:$(printf "%${nc}s $n")" --text > t1
      grep -i mean: RESULTS/$EXP/listings/${CFG}_mod.lis_2 --text | grep "oe-00000-00000:$(printf "%${nc}s $n")" --text > t2
      nb=$(cat t1 | wc -l)
      cnt=$(diff t1 t2 | wc -l)
      if [ $nb -gt 0 -a $cnt -lt 1 ] ; then
        COULEUR=green
      fi
    fi
  fi
  result=RESULTS/$EXP/status/${CFG}_couleur
  printf "couleur=$COULEUR\n" > $result
  . $result
  printf "   $(basename $result | sed 's/_couleur//') ===> $couleur\n"
done
