#!/bin/bash
#
# ex: goas_maestro -cfg configurations/GEM_cfgs_GY_FISL_H
#     goas_maestro -f -exp HRDPS_H -module /home/mid001/modeles/GEMDM/v_5.2.0-a6/module_gem -ptopo 8x5
#
arguments=$*
eval `cclargs_lite $0 \
  -exp      "$PWD"  "$PWD"  "[]" \
  -cfg      "$PWD/configurations/GEM_cfgs" "$PWD/configurations/GEM_cfgs" "[]" \
  -xfer     ""      ""      "[]" \
  -module   ""      ""      "[]" \
  -ptopo    "1x1x1" "1x1x1" "[]" \
  -t        "10"    "10"    "[]" \
  -f        "0"     "1"     "[]" \
  -nosubmit "0"     "1"     "[]" \
  ++ $arguments`

cd ${exp}
GEM_INSTALL=$(dirname $PWD)
REF=${GEM_INSTALL}/gem-maestro/GEM_RI_MAESTRO
module=${module:-${GEM_INSTALL}/gem-maestro/gem_module}

if [ ! -s .eccc_setup ] ; then
   printf "\n Experiment directory ${exp} is NOT conformed - exiting\n\n"
   exit 1
fi
if [ -z "${ATM_MODEL_VERSION}" ] ; then
   . .eccc_setup
fi

expgem=$(basename ${GEM_INSTALL})
mach=$(basename $PWD)
expM=$(basename $cfg)
XFER="\${TRUE_HOST}:\${SEQ_EXP_HOME}/hub/\${TRUE_HOST}/gridpt/prog/gem"
XFER=${xfer:-${XFER}}

NAME_exp=goas/${ATM_MODEL_VERSION}/${expgem}/${expM}
suite_name=${HOME}/.suites/${NAME_exp}/$mach

if [ -d $suite_name ] ; then
   if [ $f -gt 0 ] ; then
      /bin/rm -rf $suite_name
   else
      printf "\n    experiment directory $suite_name already exist ==> use -f\n\n"
      exit 1
   fi
fi

mkdir -p $suite_name suites
ln -sf $suite_name suites/${expgem}
cp -r ${REF}/* $suite_name
ici=$PWD

CONFIG=$(true_path ${cfg}/cfg_0000 2> /dev/null || true)
if [ -z "${CONFIG}" ] ; then
   printf  "\n  Invalid config directory ${cfg} - ABORT\n\n"
   exit
fi

cd $suite_name
ln -s ${CONFIG}/configexp.cfg experiment.cfg
ln -s $module modules/gem
export SEQ_EXP_HOME=${suite_name}
cd ${suite_name}
makelinks
cd ${exp}
#
GRDTYP=$(fetchnml.sh grd_typ_s grid ${CONFIG}/gem_settings.nml)
if [[ ${GRDTYP} == "GY" ]] ; then
  cpu_mult=2
else
  cpu_mult=1
fi

nodesetres -n /gem/Runmod -v wallclock=${t} cpu_multiplier=${cpu_mult} \
                             cpu=${ptopo} soumet_args="-waste 100"

cat ${CONFIG}/configexp.cfg | sed '/GEM_version=/d' | sed '/GEM_ovbin=/d' | sed '/GEM_settings=/d' | sed '/GEM_outcfg=/d' | sed '/ATM_MODEL_DFILES_DEFAULT=/d' | sed '/GEM_xfer=/d' | sed '/GEM_headscript_E=/d' | sed '/GEM_phy_intable=/d' | sed '/GEM_check_settings=/d' > tmp$$

echo "ATM_MODEL_DFILES_DEFAULT=${ATM_MODEL_DFILES}" > ${CONFIG}/configexp.cfg
cat tmp$$ >> ${CONFIG}/configexp.cfg
/bin/rm -f tmp$$
cat >> ${CONFIG}/configexp.cfg <<EOF
GEM_ovbin=${GEM_INSTALL}
GEM_settings=${CONFIG}/gem_settings.nml
GEM_outcfg=${CONFIG}/outcfg.out
GEM_phy_intable=${CONFIG}/physics_input_table
#GEM_headscript_E=
GEM_version="GOAS:${GEM_INSTALL}:${ATM_MODEL_VERSION}"
rmn_date=20220509
. r.load.dot rpn/utils/\${rmn_date}
EOF

set -ex
if [ ${nosubmit} -eq 0 ] ; then
   maestro -s submit -n /gem -d 0000000000 -i
fi

printf  "\n  Directory $suite_name is now available\n\n"
