#!/bin/bash
#PBS -N job_name
#PBS -l nodes=1:ppn=56
#PBS -l walltime=00:05:00             
  
# Change to the directory that the job was submitted from
#qsub mybatchjob.pbs -q skl28
module swap PrgEnv-cray PrgEnv-intel
module swap craype-broadwell craype-x86-skylake
cd /home/users/p02583/scratch/gem_on_a_stick_5.1.a6-benchmark/work/work-SLES-12.3-x86_64-intel-19.0.0.117/
./runprep -dircfg LAM_cfgs > list_prep
./runmod -dircfg LAM_cfgs -ptopo 2x2x1 > list_mod
