set(WITH_SYSTEM_RPN FALSE CACHE BOOL "Control whether to use installed RPN-SI libs")
message(STATUS "(EC) WITH_SYSTEM_RPN = ${WITH_SYSTEM_RPN}")

# Use installed RPN libraries (WITH_SYSTEM_RPN=TRUE)
if ((WITH_SYSTEM_RPN) OR (CACHE WITH_SYSTEM_RPN) OR (ENV{WITH_SYSTEM_RPN}))
  find_package(RMN ${RMN_REQ_VERSION} REQUIRED)
  # Needed for gnu
  if (RMN_FOUND) 
    find_path(RMN_INCLUDE_DIR_EXTRA
      NAMES convert_ip123.inc
      PATHS ${EC_INCLUDE_PATH})
  endif()
  find_package(tdpack ${tdpack_REQ_VERSION} CONFIG)
  find_package(rpncomm ${rpncomm_REQ_VERSION} CONFIG)
  find_package(VGRID ${VGRID_REQ_VERSION} REQUIRED)
  find_package(MASSV)

# Use sources for RPN libraries (WITH_SYSTEM_RPN=FALSE)
else()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpn-si/rmn/CMakeLists.txt)
    set(rmn_SRC "rmn" CACHE STRING "rmn sources")
    set(rmn_PUBLIC_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/src/rpn-si/rmn/src/PUBLIC_INCLUDES" CACHE PATH "rmn public include directory" FORCE)
    set(rmn_INCLUDE_DIR "${CMAKE_BINARY_DIR}/src/rmn" CACHE PATH "rmn include directory" FORCE)
    set(rmn_FOUND TRUE CACHE BOOL "Control whether rmn library was found")
    set(RMN_FOUND TRUE CACHE BOOL "Control whether rmn library was found")
    # TODO: move this declaration to "target_include_directories" in submodules
    include_directories(${rmn_INCLUDE_DIR} ${rmn_PUBLIC_INCLUDE_DIR} )
    add_subdirectory(rpn-si/rmn rmn)
   else()
     message(ERROR " -- (EC) No rmn directory found!")
  endif()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpn-si/tdpack/CMakeLists.txt)
    add_subdirectory(rpn-si/tdpack tdpack)
    set(tdpack_SRC "tdpack" CACHE STRING "tdpack sources")
    set(tdpack_INCLUDE_DIRS "${CMAKE_BINARY_DIR}/src/tdpack" CACHE PATH "tdpack include directory" FORCE)
    set(tdpack_FOUND TRUE CACHE BOOL "Control whether tdpack was found")
  else()
    message(ERROR " -- (EC) No tdpack directory found!")
  endif()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpn-si/vgrid/CMakeLists.txt)
    add_subdirectory(rpn-si/vgrid vgrid)
    set(vgrid_SRC "vgrid" CACHE STRING "vgrid sources")
    set(VGRID_INCLUDE_DIR "${CMAKE_BINARY_DIR}/src/vgrid/lib" CACHE PATH "vgrid generated include directory" FORCE)
    set(VGRID_FOUND TRUE CACHE BOOL "Control whether vgrid was found")
  else()
    message(ERROR " -- (EC) No vgrid directory found!")
  endif()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpn-si/massv/CMakeLists.txt)
    add_subdirectory(rpn-si/massv massv)
    set(massv_SRC "massv" CACHE STRING "massv library")
    set(MASSV_FOUND TRUE CACHE BOOL "Control whether massv library was found")
   else()
     message(ERROR " -- (EC) No massv directory found!")
  endif()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpn-si/rpncomm/CMakeLists.txt)
    set(rpncomm_SRC "rpncomm" CACHE STRING "rpncomm sources")
    set(rpncomm_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/src/rpn-si/rpncomm/src" CACHE PATH "rpncomm include directory" FORCE)
    set(rpncomm_GEN_INCLUDE_DIR "${CMAKE_BINARY_DIR}/src/rpncomm/src" CACHE PATH "rpncomm include directory" FORCE)
    set(rpncomm_FOUND TRUE CACHE BOOL "Control whether rpncomm library was found")
    add_subdirectory(rpn-si/rpncomm rpncomm)
  else()
    message(ERROR " -- (EC) No rpncomm directory found!")
  endif()
endif()

# Use or not sources for modelutils, rpnphy and gemdyn, according to environment variables
set(WITH_SYSTEM_MODELUTILS FALSE CACHE BOOL "Control whether to use installed modelutils libs")
message(STATUS "(EC) WITH_SYSTEM_MODELUTILS = ${WITH_SYSTEM_MODELUTILS}")
if ((WITH_SYSTEM_MODELUTILS) OR (CACHE WITH_SYSTEM_MODELUTILS) OR (ENV{WITH_SYSTEM_MODELUTILS}))
  find_package(modelutils ${modelutils_REQ_VERSION} CONFIG)
else()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/modelutils/CMakeLists.txt)
    set(modelutils_SRC "modelutils" CACHE STRING "modelutils sources")
    set(modelutils_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/src/modelutils/include" CACHE PATH "modelutils include directory" FORCE)
    set(modelutils_MODULES_DIR "${CMAKE_BINARY_DIR}/src/modelutils/modelutils/modules" CACHE PATH "modelutils modules directory" FORCE)
    set(modelutils_FOUND TRUE CACHE BOOL "Control whether modelutils library was found")
    add_subdirectory(modelutils modelutils)
  else()
    message(ERROR " -- (EC) No modelutils directory found!")
  endif()
endif()

set(WITH_SYSTEM_RPNPHY FALSE CACHE BOOL "Control whether to use installed rpnphy libs")
message(STATUS "(EC) WITH_SYSTEM_RPNPHY = ${WITH_SYSTEM_RPNPHY}")
if ((WITH_SYSTEM_RPNPHY) OR (CACHE WITH_SYSTEM_RPNPHY) OR (ENV{WITH_SYSTEM_RPNPHY}))
  find_package(rpnphy ${rpnphy_REQ_VERSION} CONFIG)
else()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/rpnphy/CMakeLists.txt)
    set(rpnphy_SRC "rpnphy" CACHE STRING "rpnphy sources")
    set(rpnphy_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/src/rpnphy/include" CACHE PATH "rpnphy include directory" FORCE)
    set(rpnphy_MODULES_DIR "${CMAKE_BINARY_DIR}/src/rpnphy/rpnphy/modules" CACHE PATH "rpnphy modules directory" FORCE)
    set(rpnphy_FOUND TRUE CACHE BOOL "Control whether rpnphy library was found")
    add_subdirectory(rpnphy rpnphy)
  else()
    message(ERROR " -- (EC) No rpnphy directory found!")
  endif()
endif()

set(WITH_SYSTEM_GEMDYN FALSE CACHE BOOL "Control whether to use installed gemdyn libs")
message(STATUS "(EC) WITH_SYSTEM_GEMDYN = ${WITH_SYSTEM_GEMDYN}")
if ((WITH_SYSTEM_GEMDYN) OR (CACHE WITH_SYSTEM_GEMDYN) OR (ENV{WITH_SYSTEM_GEMDYN}))
  find_package(gemdyn ${gemdyn_REQ_VERSION} CONFIG)
else()
  if (EXISTS ${CMAKE_SOURCE_DIR}/src/gemdyn/CMakeLists.txt)
    set(gemdyn_SRC "gemdyn" CACHE STRING "gemdyn sources")
    add_subdirectory(gemdyn gemdyn)
  else()
    message(ERROR " -- (EC) No gemdyn directory found!")
  endif()
endif()

add_subdirectory(gem gem)
add_subdirectory(rpn-si/cclargs cclargs)
add_subdirectory(rpn-si/fstinfo fstinfo)
add_subdirectory(rpn-si/filetype filetype)

# Declare the dependencies of all the components, whether sources where used or not
if ( (EXISTS ${CMAKE_SOURCE_DIR}/src/modelutils/CMakeLists.txt) AND (NOT "${modelutils_SRC}" STREQUAL "") AND ( NOT "${vgrid_SRC}" STREQUAL "" OR NOT "${rpncomm_SRC}" STREQUAL "" OR NOT "${rmn_SRC}" STREQUAL "" ))
  add_dependencies(modelutils ${vgrid_SRC} ${rpncomm_SRC} ${rmn_SRC})
endif()
  
if ( (EXISTS ${CMAKE_SOURCE_DIR}/src/rpnphy/CMakeLists.txt) AND (NOT "${rpnphy_SRC}" STREQUAL "") AND ( NOT "${modelutils_SRC}" STREQUAL "" OR NOT "${vgrid_SRC}" STREQUAL "" OR NOT "${rpncomm_SRC}" STREQUAL "" OR NOT "${rmn_SRC}" STREQUAL "" ))
  add_dependencies(rpnphy ${modelutils_SRC} ${vgrid_SRC} ${rpncomm_SRC} ${rmn_SRC})
  add_dependencies(rpnphy_chm_stubs ${modelutils_SRC} ${vgrid_SRC} ${rpncomm_SRC} ${rmn_SRC})
endif()

if ( (EXISTS ${CMAKE_SOURCE_DIR}/src/gemdyn/CMakeLists.txt) AND (NOT "${gemdyn_SRC}" STREQUAL "") AND (NOT "${rpnphy_SRC}" STREQUAL "" OR NOT "${modelutils_SRC}" STREQUAL "" OR NOT "${vgrid_SRC}" STREQUAL "" OR NOT "${rpncomm_SRC}" STREQUAL "" OR NOT "${rmn_SRC}" STREQUAL "" OR NOT "${massv_SRC}" STREQUAL ""))
  add_dependencies(gemdyn ${rpnphy_SRC} ${modelutils_SRC} ${vgrid_SRC} ${rpncomm_SRC} ${rmn_SRC} ${massv_SRC})
endif()
