!---------------------------------- LICENCE BEGIN -------------------------------
! GEM-MACH - Atmospheric chemistry library for the GEM numerical atmospheric model
! Copyright (C) 2007-2013 - Air Quality Research Division &
!                           National Prediction Operations division
!                           Environnement Canada
! This library is free software; you can redistribute it and/or
! modify it under the terms of the GNU Lesser General Public
! License as published by the Free Software Foundation; either
! version 2.1 of the License, or (at your option) any later version.
!
! This library is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
! Lesser General Public License for more details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with this library; if not, write to the Free Software
! Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
!---------------------------------- LICENCE END ---------------------------------

!============================================================================!
!         Environnement Canada         |        Environment Canada           !
!                                      |                                     !
! - Service meteorologique du Canada   | - Meteorological Service of Canada  !
! - Direction generale des sciences    | - Science and Technology Branch     !
!   et de la technologie               |                                     !
!============================================================================!
!                            http://www.ec.gc.ca                             !
!============================================================================!
!
! Projet/Project : GEM-MACH
! Fichier/File   : mach_kppb_adom2_interface.ftn90
! Creation       : K. Toyota, J. Chen, C. Stroud & M. Russell, Dec 2017 for GEM-MACH
!
! Description    : "KPPb" version of interface for the RODAS-3 solver for ADOM-II gas-phase chemistry
!
! Extra info     : This file contains additional subroutines, namely:
!                  - Shuffle_user2kpp_{day,night} (shuffle the species listing order for RODAS-3)
!                  - Shuffle_kpp2user_{day,night} (shuffle the species listing order back)
!                  - Update_RCONST_{day,night}    (Copy the hard-coded rate constants for RODAS-3)
!
! Adapted from   : Rosenbrock-rodas3 subroutine(s) generated by KPP v2.2.3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!  By default the code employs the KPP sparse linear algebra routines     !
!                                                                         !
!    (C)  Adrian Sandu, August 2004                                       !
!    Virginia Polytechnic Institute and State University                  !
!    Contact: sandu@cs.vt.edu                                             !
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  !                               !
!    This implementation is part of KPP - the Kinetic PreProcessor        !
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!
! Arguments:  IN
!               delt     -> chm. timestep interval (min)
!               rgs      -> Reaction rate coefficients
!               bgs      -> Reaction product stochiometric coefficients
!
!             INOUT
!               conc     -> Concentrations of gaseous species (ppmv)
!               hs       -> Initial guess for solver timestep interval (min)
!
!               atol_in  -> Absolute tolerance for solution convergence used by the solver
!               rtol_in  -> Relative tolerance for solution convergecne used by the solver
!============================================================================
!
!!if_on
subroutine mach_kppb_adom2_interface(conc, rgs, bgs, atol_in, rtol_in, hs, &
                                     day_night_flag)
  use mach_pkg_adom2_mod, only: nreac, nprcf, nspec
!!if_off
  use chm_utils_mod,      only: chm_timestep, chm_error_l
  use mach_pkg_adom2_mod, only: nvar, nfix, nreact
  use mach_gas_headers_mod, only: mach_kppb_adom2day_rodas3, &
                                  mach_kppb_adom2night_rodas3
  implicit none
!
!!if_on
  real(kind=8),    intent(inout) :: hs
  real(kind=8),    intent(in)    :: atol_in, rtol_in
  real(kind=8),    intent(in)    :: rgs(nreac), bgs(nprcf)
  real(kind=8),    intent(inout) :: conc(nspec)
  integer(kind=4), intent(in)    :: day_night_flag
!!if_off

! NREACT - Number of reactions
  integer(kind=4), parameter            :: nreact_night = 96
  real(kind=8), dimension(nreact)       :: rconst_day
  real(kind=8), dimension(nreact_night) :: rconst_night
  integer(kind=4)                       :: ier
  real(kind=8), dimension(nvar)         :: atol, rtol, var
  real(kind=8), dimension(nfix)         :: fix
  real(kind=4)                          :: delt

  rtol(1:nvar) = rtol_in
  atol(1:nvar) = atol_in

!  Timestep in minutes
  delt = chm_timestep / 60.0

  var = conc(1:nvar)
  fix = conc(nvar+1:nspec)
  if (day_night_flag == 1) then
     call shuffle_user2kpp_day(var, nvar)
     call update_rconst_day(rconst_day, rgs, nreact)

     call mach_kppb_adom2day_rodas3(nvar, var, nfix, fix, nreact, rconst_day, &
                                    nprcf, bgs, delt, hs, rtol, atol, ier)
     call shuffle_kpp2user_day(var, nvar)
  else
     call shuffle_user2kpp_night(var, nvar)
     call update_rconst_night(rconst_night, rgs, nreact_night)

     call mach_kppb_adom2night_rodas3(nvar, var, nfix, fix, nreact_night, rconst_night, &
                                      nprcf, bgs, delt, hs, rtol, atol, ier)
     call shuffle_kpp2user_night(var, nvar)
  end if

  conc(1:nvar) = var

  if (ier < 0) then
     write(*, *) 'Solver Error: IERR=', ier
     write(*, *) 'Day / night flag=', day_night_flag
     write(*, *) 'conc:', var
     write(*, *) 'fix:', fix
     if (day_night_flag == 1) then
        write(*, *) 'RXD:',rconst_day(1:nreact)
     else
        write(*, *) 'RXD:',rconst_night(1:nreact_night)
     end if
     write(*, *) 'mach_kppb_adom2_interface: KPPb solver RODAS3 unsuccessful, exiting'
     chm_error_l = .true.
     return
  end if

  return

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Contains ! Subroutines internal to mach_kppb_adom2day_interface
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp_day ( V, nspc )
  IMPLICIT NONE
!     v   input   concentration in user's order
!         output  concentration in order for kpp solver
  integer(kind=4), intent(in) :: nspc
  real(kind=8), intent(inout) :: V(nspc)
! local variables
  real(kind=8) :: V_USER(nspc)
! initialisation
  v_user = v
! shuffle
! variable concentrations
! kpp        adom

  V(21) = V_USER(1)
  V(1) = V_USER(2)
  V(34) = V_USER(3)
  V(32) = V_USER(4)
  V(28) = V_USER(5)
  V(3) = V_USER(6)
  V(20) = V_USER(7)
  V(4) = V_USER(8)
  V(5) = V_USER(9)
  V(8) = V_USER(10)
  V(25) = V_USER(11)
  V(23) = V_USER(12)
  V(9) = V_USER(13)
  V(11) = V_USER(14)
  V(39) = V_USER(15)
  V(38) = V_USER(16)
  V(27) = V_USER(17)
  V(18) = V_USER(18)
  V(10) = V_USER(19)
  V(19) = V_USER(20)
  V(17) = V_USER(21)
  V(6) = V_USER(22)
  V(22) = V_USER(23)
  V(24) = V_USER(24)
  V(37) = V_USER(25)
  V(40) = V_USER(26)
  V(35) = V_USER(27)
  V(14) = V_USER(28)
  V(2) = V_USER(29)
  V(26) = V_USER(30)
  V(30) = V_USER(31)
  V(7) = V_USER(32)
  V(12) = V_USER(33)
  V(33) = V_USER(34)
  V(31) = V_USER(35)
  V(29) = V_USER(36)
  V(36) = V_USER(37)
  V(13) = V_USER(38)
  V(15) = V_USER(39)
  V(16) = V_USER(40)

  RETURN
END SUBROUTINE Shuffle_user2kpp_day

SUBROUTINE Shuffle_kpp2user_day ( V_USER, nspc )
  IMPLICIT NONE
! v_user   input  concentration in order for kpp solver
!          output concentration in user's order
  integer(kind=4), intent(in) :: nspc
  real(kind=8), intent(inout) :: V_user(nspc)
! local variables
  real(kind=8) :: V(nspc)
! initialisation
  v= v_user
! shuffle
!      adom      kpp

  V_USER(1) = V(21)
  V_USER(2) = V(1)
  V_USER(3) = V(34)
  V_USER(4) = V(32)
  V_USER(5) = V(28)
  V_USER(6) = V(3)
  V_USER(7) = V(20)
  V_USER(8) = V(4)
  V_USER(9) = V(5)
  V_USER(10) = V(8)
  V_USER(11) = V(25)
  V_USER(12) = V(23)
  V_USER(13) = V(9)
  V_USER(14) = V(11)
  V_USER(15) = V(39)
  V_USER(16) = V(38)
  V_USER(17) = V(27)
  V_USER(18) = V(18)
  V_USER(19) = V(10)
  V_USER(20) = V(19)
  V_USER(21) = V(17)
  V_USER(22) = V(6)
  V_USER(23) = V(22)
  V_USER(24) = V(24)
  V_USER(25) = V(37)
  V_USER(26) = V(40)
  V_USER(27) = V(35)
  V_USER(28) = V(14)
  V_USER(29) = V(2)
  V_USER(30) = V(26)
  V_USER(31) = V(30)
  V_USER(32) = V(7)
  V_USER(33) = V(12)
  V_USER(34) = V(33)
  V_USER(35) = V(31)
  V_USER(36) = V(29)
  V_USER(37) = V(36)
  V_USER(38) = V(13)
  V_USER(39) = V(15)
  V_USER(40) = V(16)

  RETURN
END SUBROUTINE Shuffle_kpp2user_day

SUBROUTINE Update_RCONST_day(rconst, g_rate, nreact_kpp)
  IMPLICIT NONE
  integer(kind=4), intent (in) :: nreact_kpp
  real(kind=8),    intent (in) :: g_rate(nreac)
  real(kind=8),    intent(out) :: rconst(nreact_kpp)

  RCONST(1) = (G_RATE(1))
  RCONST(2) = (G_RATE(2))
  RCONST(3) = (G_RATE(3))
  RCONST(4) = (G_RATE(4))
  RCONST(5) = (G_RATE(5))
  RCONST(6) = (G_RATE(6))
  RCONST(7) = (G_RATE(7))
  RCONST(8) = (G_RATE(8))
  RCONST(9) = (G_RATE(9))
  RCONST(10) = (G_RATE(10))
  RCONST(11) = (G_RATE(11))
  RCONST(12) = (G_RATE(12))
  RCONST(13) = (G_RATE(13))
  RCONST(14) = (G_RATE(14))
  RCONST(15) = (G_RATE(15))
  RCONST(16) = (G_RATE(16))
  RCONST(17) = (G_RATE(17))
  RCONST(18) = (G_RATE(18))
  RCONST(19) = (G_RATE(19))
  RCONST(20) = (G_RATE(20))
  RCONST(21) = (G_RATE(21))
  RCONST(22) = (G_RATE(22))
  RCONST(23) = (G_RATE(23))
  RCONST(24) = (G_RATE(24))
  RCONST(25) = (G_RATE(25))
  RCONST(26) = (G_RATE(26))
  RCONST(27) = (G_RATE(27))
  RCONST(28) = (G_RATE(28))
  RCONST(29) = (G_RATE(29))
  RCONST(30) = (G_RATE(30))
  RCONST(31) = (G_RATE(31))
  RCONST(32) = (G_RATE(32))
  RCONST(33) = (G_RATE(33))
  RCONST(34) = (G_RATE(34))
  RCONST(35) = (G_RATE(35)+G_RATE(36))
  RCONST(36) = (G_RATE(37))
  RCONST(37) = (G_RATE(38))
  RCONST(38) = (G_RATE(39))
  RCONST(39) = (G_RATE(40))
  RCONST(40) = (G_RATE(41)+G_RATE(42))
  RCONST(41) = (G_RATE(43))
  RCONST(42) = (G_RATE(44))
  RCONST(43) = (G_RATE(45))
  RCONST(44) = (G_RATE(46))
  RCONST(45) = (G_RATE(47))
  RCONST(46) = (G_RATE(48))
  RCONST(47) = (G_RATE(49))
  RCONST(48) = (G_RATE(50))
  RCONST(49) = (G_RATE(51))
  RCONST(50) = (G_RATE(52))
  RCONST(51) = (G_RATE(53))
  RCONST(52) = (G_RATE(54))
  RCONST(53) = (G_RATE(55))
  RCONST(54) = (G_RATE(56))
  RCONST(55) = (G_RATE(57))
  RCONST(56) = (G_RATE(58))
  RCONST(57) = (G_RATE(59))
  RCONST(58) = (G_RATE(60))
  RCONST(59) = (G_RATE(61))
  RCONST(60) = (G_RATE(62))
  RCONST(61) = (G_RATE(63))
  RCONST(62) = (G_RATE(64))
  RCONST(63) = (G_RATE(65))
  RCONST(64) = (G_RATE(66))
  RCONST(65) = (G_RATE(67))
  RCONST(66) = (G_RATE(68))
  RCONST(67) = (G_RATE(69))
  RCONST(68) = (G_RATE(70))
  RCONST(69) = (G_RATE(71))
  RCONST(70) = (G_RATE(72))
  RCONST(71) = (G_RATE(73))
  RCONST(72) = (G_RATE(74))
  RCONST(73) = (G_RATE(75))
  RCONST(74) = (G_RATE(76))
  RCONST(75) = (G_RATE(77))
  RCONST(76) = (G_RATE(78))
  RCONST(77) = (G_RATE(79))
  RCONST(78) = (G_RATE(80))
  RCONST(79) = (G_RATE(81))
  RCONST(80) = (G_RATE(82))
  RCONST(81) = (G_RATE(83))
  RCONST(82) = (G_RATE(84))
  RCONST(83) = (G_RATE(85))
  RCONST(84) = (G_RATE(86))
  RCONST(85) = (G_RATE(87))
  RCONST(86) = (G_RATE(88))
  RCONST(87) = (G_RATE(89))
  RCONST(88) = (G_RATE(90))
  RCONST(89) = (G_RATE(91))
  RCONST(90) = (G_RATE(92))
  RCONST(91) = (G_RATE(93))
  RCONST(92) = (G_RATE(94))
  RCONST(93) = (G_RATE(95))
  RCONST(94) = (G_RATE(96))
  RCONST(95) = (G_RATE(97))
  RCONST(96) = (G_RATE(98))
  RCONST(97) = (G_RATE(99))
  RCONST(98) = (G_RATE(100))
  RCONST(99) = (G_RATE(101))
  RCONST(100) = (G_RATE(102))
  RCONST(101) = (G_RATE(103))
  RCONST(102) = (G_RATE(104))
  RCONST(103) = (G_RATE(105))
  RCONST(104) = (G_RATE(106))
  RCONST(105) = (G_RATE(107))
  RCONST(106) = (G_RATE(108))
  RCONST(107) = (G_RATE(109))
  RCONST(108) = (G_RATE(110))
  RCONST(109) = (G_RATE(111))
  RCONST(110) = (G_RATE(112))
  RCONST(111) = (G_RATE(113))
  RCONST(112) = (G_RATE(114))

  RETURN
END SUBROUTINE Update_RCONST_day

SUBROUTINE Shuffle_user2kpp_night ( V, nspc )
  IMPLICIT NONE
!     v   input   concentration in user's order
!         output  concentration in order for kpp solver
  integer(kind=4), intent(in) :: nspc
  real(kind=8), intent(inout) :: V(nspc)
! local variables
  real(kind=8) :: V_USER(nspc)
! initialisation
  v_user = v
! shuffle
! variable concentrations
! kpp        adom
  V(19) = V_USER(1)
  V(2) = V_USER(2)
  V(39) = V_USER(3)
  V(40) = V_USER(4)
  V(28) = V_USER(5)
  V(4) = V_USER(6)
  V(15) = V_USER(7)
  V(5) = V_USER(8)
  V(6) = V_USER(9)
  V(9) = V_USER(10)
  V(25) = V_USER(11)
  V(23) = V_USER(12)
  V(10) = V_USER(13)
  V(11) = V_USER(14)
  V(38) = V_USER(15)
  V(26) = V_USER(16)
  V(37) = V_USER(17)
  V(18) = V_USER(18)
  V(7) = V_USER(19)
  V(16) = V_USER(20)
  V(17) = V_USER(21)
  V(3) = V_USER(22)
  V(22) = V_USER(23)
  V(24) = V_USER(24)
  V(36) = V_USER(25)
  V(29) = V_USER(26)
  V(31) = V_USER(27)
  V(14) = V_USER(28)
  V(1) = V_USER(29)
  V(27) = V_USER(30)
  V(30) = V_USER(31)
  V(8) = V_USER(32)
  V(12) = V_USER(33)
  V(32) = V_USER(34)
  V(33) = V_USER(35)
  V(34) = V_USER(36)
  V(35) = V_USER(37)
  V(13) = V_USER(38)
  V(20) = V_USER(39)
  V(21) = V_USER(40)

  RETURN
END SUBROUTINE Shuffle_user2kpp_night

SUBROUTINE Shuffle_kpp2user_night ( V_USER, nspc )
  IMPLICIT NONE
! v_user   input  concentration in order for kpp solver
!          output concentration in user's order
  integer(kind=4), intent(in) :: nspc
  real(kind=8), intent(inout) :: V_user(nspc)
! local variables
  real(kind=8) :: V(nspc)
! initialisation
  v= v_user
! shuffle
!      adom      kpp
  V_USER(1) = V(19)
  V_USER(2) = V(2)
  V_USER(3) = V(39)
  V_USER(4) = V(40)
  V_USER(5) = V(28)
  V_USER(6) = V(4)
  V_USER(7) = V(15)
  V_USER(8) = V(5)
  V_USER(9) = V(6)
  V_USER(10) = V(9)
  V_USER(11) = V(25)
  V_USER(12) = V(23)
  V_USER(13) = V(10)
  V_USER(14) = V(11)
  V_USER(15) = V(38)
  V_USER(16) = V(26)
  V_USER(17) = V(37)
  V_USER(18) = V(18)
  V_USER(19) = V(7)
  V_USER(20) = V(16)
  V_USER(21) = V(17)
  V_USER(22) = V(3)
  V_USER(23) = V(22)
  V_USER(24) = V(24)
  V_USER(25) = V(36)
  V_USER(26) = V(29)
  V_USER(27) = V(31)
  V_USER(28) = V(14)
  V_USER(29) = V(1)
  V_USER(30) = V(27)
  V_USER(31) = V(30)
  V_USER(32) = V(8)
  V_USER(33) = V(12)
  V_USER(34) = V(32)
  V_USER(35) = V(33)
  V_USER(36) = V(34)
  V_USER(37) = V(35)
  V_USER(38) = V(13)
  V_USER(39) = V(20)
  V_USER(40) = V(21)

  RETURN
END SUBROUTINE Shuffle_kpp2user_night

SUBROUTINE Update_RCONST_night(rconst, g_rate, nreact_kpp)
  IMPLICIT NONE
  integer(kind=4), intent (in) :: nreact_kpp
  real(kind=8),    intent (in) :: g_rate(nreac)
  real(kind=8),    intent(out) :: rconst(nreact_kpp)

  RCONST(1) = (G_RATE(2))
  RCONST(2) = (G_RATE(3))
  RCONST(3) = (G_RATE(4))
  RCONST(4) = (G_RATE(5))
  RCONST(5) = (G_RATE(6))
  RCONST(6) = (G_RATE(7))
  RCONST(7) = (G_RATE(8))
  RCONST(8) = (G_RATE(9))
  RCONST(9) = (G_RATE(10))
  RCONST(10) = (G_RATE(11))
  RCONST(11) = (G_RATE(12))
  RCONST(12) = (G_RATE(17))
  RCONST(13) = (G_RATE(18))
  RCONST(14) = (G_RATE(19))
  RCONST(15) = (G_RATE(21))
  RCONST(16) = (G_RATE(22))
  RCONST(17) = (G_RATE(24))
  RCONST(18) = (G_RATE(25))
  RCONST(19) = (G_RATE(26))
  RCONST(20) = (G_RATE(27))
  RCONST(21) = (G_RATE(28))
  RCONST(22) = (G_RATE(29))
  RCONST(23) = (G_RATE(31))
  RCONST(24) = (G_RATE(32))
  RCONST(25) = (G_RATE(33))
  RCONST(26) = (G_RATE(34))
  RCONST(27) = (G_RATE(35)+G_RATE(36))
  RCONST(28) = (G_RATE(38))
  RCONST(29) = (G_RATE(39))
  RCONST(30) = (G_RATE(40))
  RCONST(31) = (G_RATE(41)+G_RATE(42))
  RCONST(32) = (G_RATE(43))
  RCONST(33) = (G_RATE(44))
  RCONST(34) = (G_RATE(45))
  RCONST(35) = (G_RATE(46))
  RCONST(36) = (G_RATE(47))
  RCONST(37) = (G_RATE(51))
  RCONST(38) = (G_RATE(52))
  RCONST(39) = (G_RATE(53))
  RCONST(40) = (G_RATE(54))
  RCONST(41) = (G_RATE(56))
  RCONST(42) = (G_RATE(57))
  RCONST(43) = (G_RATE(58))
  RCONST(44) = (G_RATE(59))
  RCONST(45) = (G_RATE(60))
  RCONST(46) = (G_RATE(61))
  RCONST(47) = (G_RATE(63))
  RCONST(48) = (G_RATE(65))
  RCONST(49) = (G_RATE(66))
  RCONST(50) = (G_RATE(67))
  RCONST(51) = (G_RATE(68))
  RCONST(52) = (G_RATE(69))
  RCONST(53) = (G_RATE(70))
  RCONST(54) = (G_RATE(71))
  RCONST(55) = (G_RATE(72))
  RCONST(56) = (G_RATE(73))
  RCONST(57) = (G_RATE(74))
  RCONST(58) = (G_RATE(75))
  RCONST(59) = (G_RATE(76))
  RCONST(60) = (G_RATE(77))
  RCONST(61) = (G_RATE(78))
  RCONST(62) = (G_RATE(79))
  RCONST(63) = (G_RATE(80))
  RCONST(64) = (G_RATE(81))
  RCONST(65) = (G_RATE(82))
  RCONST(66) = (G_RATE(83))
  RCONST(67) = (G_RATE(84))
  RCONST(68) = (G_RATE(85))
  RCONST(69) = (G_RATE(86))
  RCONST(70) = (G_RATE(87))
  RCONST(71) = (G_RATE(88))
  RCONST(72) = (G_RATE(89))
  RCONST(73) = (G_RATE(90))
  RCONST(74) = (G_RATE(91))
  RCONST(75) = (G_RATE(92))
  RCONST(76) = (G_RATE(93))
  RCONST(77) = (G_RATE(94))
  RCONST(78) = (G_RATE(95))
  RCONST(79) = (G_RATE(96))
  RCONST(80) = (G_RATE(97))
  RCONST(81) = (G_RATE(98))
  RCONST(82) = (G_RATE(99))
  RCONST(83) = (G_RATE(100))
  RCONST(84) = (G_RATE(101))
  RCONST(85) = (G_RATE(102))
  RCONST(86) = (G_RATE(104))
  RCONST(87) = (G_RATE(105))
  RCONST(88) = (G_RATE(106))
  RCONST(89) = (G_RATE(107))
  RCONST(90) = (G_RATE(108))
  RCONST(91) = (G_RATE(109))
  RCONST(92) = (G_RATE(110))
  RCONST(93) = (G_RATE(111))
  RCONST(94) = (G_RATE(112))
  RCONST(95) = (G_RATE(113))
  RCONST(96) = (G_RATE(114))

  RETURN
END SUBROUTINE Update_RCONST_night

end subroutine mach_kppb_adom2_interface
