! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Linear Algebra Data and Routines File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!============================================================================!
!
! GEM-MACH Setup
! Fichier / File   : mach_kpp_adom2_LinearAlgebra.ftn90
! Creation         : Jack Chen (May 2017)
! Modifications    : - utilize the Intel MKL calls WAXPY->DAXPY; WSCAL->DSCAL; WLAMCH->DLAMCH function calls
!
!============================================================================

MODULE mach_kpp_adom2_LinearAlgebra

  USE mach_kpp_adom2_JacobianSP
  USE chm_utils_mod,      ONLY: DP, chm_lun_out
  USE mach_pkg_adom2_mod, ONLY: NVAR, LU_NONZERO

  IMPLICIT NONE

 CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER          :: IER
      COMPLEX(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=dp)    :: b = 0.0_dp
      INTEGER          :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


      INTEGER       :: IER
      REAL(kind=dp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO)
      REAL(kind=dp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER  :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
           X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
           X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER          :: i, j
      COMPLEX(kind=dp) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO

END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER          :: i, j
      COMPLEX(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
           X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
           X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
           XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
           XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
           XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
           XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE adom_Parameters
!  USE adom_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER)
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER)
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO
!
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE adom_Parameters
!  USE adom_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0)
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE adom_Parameters
!  USE adom_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=dp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=dp) :: t, dmax, da, TMP(3)
!      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF
!!      END IF
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=dp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=dp) :: TMP
!
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!
!
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(11) = X(11)-JVS(31)*X(10)
  X(15) = X(15)-JVS(46)*X(10)-JVS(47)*X(11)-JVS(48)*X(12)
  X(16) = X(16)-JVS(59)*X(10)-JVS(60)*X(12)
  X(17) = X(17)-JVS(64)*X(10)-JVS(65)*X(12)-JVS(66)*X(16)
  X(18) = X(18)-JVS(72)*X(7)-JVS(73)*X(16)-JVS(74)*X(17)
  X(20) = X(20)-JVS(91)*X(14)
  X(21) = X(21)-JVS(100)*X(14)-JVS(101)*X(20)
  X(22) = X(22)-JVS(110)*X(13)-JVS(111)*X(16)
  X(25) = X(25)-JVS(129)*X(24)
  X(26) = X(26)-JVS(135)*X(2)-JVS(136)*X(23)-JVS(137)*X(24)-JVS(138)*X(25)
  X(27) = X(27)-JVS(144)*X(5)-JVS(145)*X(8)-JVS(146)*X(22)-JVS(147)*X(23)-JVS(148)*X(26)
  X(28) = X(28)-JVS(159)*X(23)-JVS(160)*X(24)-JVS(161)*X(25)-JVS(162)*X(26)
  X(29) = X(29)-JVS(169)*X(8)-JVS(170)*X(22)-JVS(171)*X(23)-JVS(172)*X(24)-JVS(173)*X(25)-JVS(174)*X(26)-JVS(175)*X(28)
  X(30) = X(30)-JVS(185)*X(7)-JVS(186)*X(16)-JVS(187)*X(17)-JVS(188)*X(18)-JVS(189)*X(23)-JVS(190)*X(24)-JVS(191)*X(25)&
            &-JVS(192)*X(26)-JVS(193)*X(28)
  X(31) = X(31)-JVS(201)*X(5)-JVS(202)*X(8)-JVS(203)*X(10)-JVS(204)*X(12)-JVS(205)*X(16)-JVS(206)*X(19)-JVS(207)*X(23)&
            &-JVS(208)*X(25)-JVS(209)*X(26)-JVS(210)*X(27)-JVS(211)*X(28)-JVS(212)*X(29)-JVS(213)*X(30)
  X(32) = X(32)-JVS(224)*X(5)-JVS(225)*X(8)-JVS(226)*X(10)-JVS(227)*X(12)-JVS(228)*X(16)-JVS(229)*X(19)-JVS(230)*X(22)&
            &-JVS(231)*X(23)-JVS(232)*X(24)-JVS(233)*X(25)-JVS(234)*X(26)-JVS(235)*X(27)-JVS(236)*X(28)-JVS(237)*X(29)&
            &-JVS(238)*X(30)-JVS(239)*X(31)
  X(33) = X(33)-JVS(249)*X(3)-JVS(250)*X(9)-JVS(251)*X(10)-JVS(252)*X(11)-JVS(253)*X(12)-JVS(254)*X(13)-JVS(255)*X(14)&
            &-JVS(256)*X(15)-JVS(257)*X(16)-JVS(258)*X(17)-JVS(259)*X(19)-JVS(260)*X(20)-JVS(261)*X(21)-JVS(262)*X(23)&
            &-JVS(263)*X(24)-JVS(264)*X(25)-JVS(265)*X(26)-JVS(266)*X(28)-JVS(267)*X(29)-JVS(268)*X(30)-JVS(269)*X(31)&
            &-JVS(270)*X(32)
  X(34) = X(34)-JVS(279)*X(5)-JVS(280)*X(8)-JVS(281)*X(14)-JVS(282)*X(20)-JVS(283)*X(21)-JVS(284)*X(22)-JVS(285)*X(23)&
            &-JVS(286)*X(24)-JVS(287)*X(25)-JVS(288)*X(26)-JVS(289)*X(27)-JVS(290)*X(28)-JVS(291)*X(30)-JVS(292)*X(32)&
            &-JVS(293)*X(33)
  X(35) = X(35)-JVS(301)*X(8)-JVS(302)*X(16)-JVS(303)*X(24)-JVS(304)*X(26)-JVS(305)*X(28)-JVS(306)*X(30)-JVS(307)*X(32)&
            &-JVS(308)*X(33)-JVS(309)*X(34)
  X(36) = X(36)-JVS(316)*X(4)-JVS(317)*X(11)-JVS(318)*X(12)-JVS(319)*X(17)-JVS(320)*X(24)-JVS(321)*X(26)-JVS(322)*X(27)&
            &-JVS(323)*X(28)-JVS(324)*X(29)-JVS(325)*X(30)-JVS(326)*X(31)-JVS(327)*X(32)-JVS(328)*X(33)-JVS(329)*X(34)&
            &-JVS(330)*X(35)
  X(37) = X(37)-JVS(336)*X(6)-JVS(337)*X(26)-JVS(338)*X(28)-JVS(339)*X(29)-JVS(340)*X(30)-JVS(341)*X(31)-JVS(342)*X(32)&
            &-JVS(343)*X(33)-JVS(344)*X(34)-JVS(345)*X(35)-JVS(346)*X(36)
  X(38) = X(38)-JVS(351)*X(8)-JVS(352)*X(10)-JVS(353)*X(12)-JVS(354)*X(14)-JVS(355)*X(20)-JVS(356)*X(21)-JVS(357)*X(22)&
            &-JVS(358)*X(23)-JVS(359)*X(24)-JVS(360)*X(25)-JVS(361)*X(26)-JVS(362)*X(27)-JVS(363)*X(28)-JVS(364)*X(29)&
            &-JVS(365)*X(30)-JVS(366)*X(31)-JVS(367)*X(32)-JVS(368)*X(33)-JVS(369)*X(34)-JVS(370)*X(35)-JVS(371)*X(36)&
            &-JVS(372)*X(37)
  X(39) = X(39)-JVS(376)*X(2)-JVS(377)*X(3)-JVS(378)*X(5)-JVS(379)*X(6)-JVS(380)*X(8)-JVS(381)*X(9)-JVS(382)*X(10)&
            &-JVS(383)*X(11)-JVS(384)*X(12)-JVS(385)*X(14)-JVS(386)*X(15)-JVS(387)*X(16)-JVS(388)*X(17)-JVS(389)*X(18)&
            &-JVS(390)*X(19)-JVS(391)*X(20)-JVS(392)*X(21)-JVS(393)*X(22)-JVS(394)*X(23)-JVS(395)*X(24)-JVS(396)*X(25)&
            &-JVS(397)*X(26)-JVS(398)*X(27)-JVS(399)*X(28)-JVS(400)*X(29)-JVS(401)*X(30)-JVS(402)*X(31)-JVS(403)*X(32)&
            &-JVS(404)*X(33)-JVS(405)*X(34)-JVS(406)*X(35)-JVS(407)*X(36)-JVS(408)*X(37)-JVS(409)*X(38)
  X(40) = X(40)-JVS(412)*X(4)-JVS(413)*X(7)-JVS(414)*X(9)-JVS(415)*X(13)-JVS(416)*X(16)-JVS(417)*X(18)-JVS(418)*X(22)&
            &-JVS(419)*X(23)-JVS(420)*X(24)-JVS(421)*X(25)-JVS(422)*X(26)-JVS(423)*X(28)-JVS(424)*X(29)-JVS(425)*X(30)&
            &-JVS(426)*X(31)-JVS(427)*X(32)-JVS(428)*X(33)-JVS(429)*X(34)-JVS(430)*X(35)-JVS(431)*X(36)-JVS(432)*X(37)&
            &-JVS(433)*X(38)-JVS(434)*X(39)
  X(40) = X(40)/JVS(435)
  X(39) = (X(39)-JVS(411)*X(40))/(JVS(410))
  X(38) = (X(38)-JVS(374)*X(39)-JVS(375)*X(40))/(JVS(373))
  X(37) = (X(37)-JVS(348)*X(38)-JVS(349)*X(39)-JVS(350)*X(40))/(JVS(347))
  X(36) = (X(36)-JVS(332)*X(37)-JVS(333)*X(38)-JVS(334)*X(39)-JVS(335)*X(40))/(JVS(331))
  X(35) = (X(35)-JVS(311)*X(36)-JVS(312)*X(37)-JVS(313)*X(38)-JVS(314)*X(39)-JVS(315)*X(40))/(JVS(310))
  X(34) = (X(34)-JVS(295)*X(35)-JVS(296)*X(36)-JVS(297)*X(37)-JVS(298)*X(38)-JVS(299)*X(39)-JVS(300)*X(40))/(JVS(294))
  X(33) = (X(33)-JVS(272)*X(34)-JVS(273)*X(35)-JVS(274)*X(36)-JVS(275)*X(37)-JVS(276)*X(38)-JVS(277)*X(39)-JVS(278)&
            &*X(40))/(JVS(271))
  X(32) = (X(32)-JVS(241)*X(33)-JVS(242)*X(34)-JVS(243)*X(35)-JVS(244)*X(36)-JVS(245)*X(37)-JVS(246)*X(38)-JVS(247)&
            &*X(39)-JVS(248)*X(40))/(JVS(240))
  X(31) = (X(31)-JVS(215)*X(32)-JVS(216)*X(33)-JVS(217)*X(34)-JVS(218)*X(35)-JVS(219)*X(36)-JVS(220)*X(37)-JVS(221)&
            &*X(38)-JVS(222)*X(39)-JVS(223)*X(40))/(JVS(214))
  X(30) = (X(30)-JVS(195)*X(33)-JVS(196)*X(34)-JVS(197)*X(37)-JVS(198)*X(38)-JVS(199)*X(39)-JVS(200)*X(40))/(JVS(194))
  X(29) = (X(29)-JVS(177)*X(30)-JVS(178)*X(32)-JVS(179)*X(33)-JVS(180)*X(35)-JVS(181)*X(36)-JVS(182)*X(37)-JVS(183)&
            &*X(39)-JVS(184)*X(40))/(JVS(176))
  X(28) = (X(28)-JVS(164)*X(30)-JVS(165)*X(33)-JVS(166)*X(37)-JVS(167)*X(39)-JVS(168)*X(40))/(JVS(163))
  X(27) = (X(27)-JVS(150)*X(28)-JVS(151)*X(30)-JVS(152)*X(32)-JVS(153)*X(33)-JVS(154)*X(35)-JVS(155)*X(36)-JVS(156)&
            &*X(37)-JVS(157)*X(39)-JVS(158)*X(40))/(JVS(149))
  X(26) = (X(26)-JVS(140)*X(28)-JVS(141)*X(30)-JVS(142)*X(39)-JVS(143)*X(40))/(JVS(139))
  X(25) = (X(25)-JVS(131)*X(26)-JVS(132)*X(28)-JVS(133)*X(30)-JVS(134)*X(39))/(JVS(130))
  X(24) = (X(24)-JVS(125)*X(26)-JVS(126)*X(28)-JVS(127)*X(30)-JVS(128)*X(39))/(JVS(124))
  X(23) = (X(23)-JVS(120)*X(26)-JVS(121)*X(28)-JVS(122)*X(30)-JVS(123)*X(39))/(JVS(119))
  X(22) = (X(22)-JVS(113)*X(30)-JVS(114)*X(33)-JVS(115)*X(35)-JVS(116)*X(37)-JVS(117)*X(39)-JVS(118)*X(40))/(JVS(112))
  X(21) = (X(21)-JVS(103)*X(23)-JVS(104)*X(24)-JVS(105)*X(25)-JVS(106)*X(28)-JVS(107)*X(34)-JVS(108)*X(38)-JVS(109)&
            &*X(39))/(JVS(102))
  X(20) = (X(20)-JVS(93)*X(21)-JVS(94)*X(23)-JVS(95)*X(25)-JVS(96)*X(28)-JVS(97)*X(34)-JVS(98)*X(38)-JVS(99)*X(39))&
            &/(JVS(92))
  X(19) = (X(19)-JVS(85)*X(29)-JVS(86)*X(31)-JVS(87)*X(33)-JVS(88)*X(35)-JVS(89)*X(36)-JVS(90)*X(39))/(JVS(84))
  X(18) = (X(18)-JVS(76)*X(24)-JVS(77)*X(28)-JVS(78)*X(30)-JVS(79)*X(33)-JVS(80)*X(34)-JVS(81)*X(38)-JVS(82)*X(39)&
            &-JVS(83)*X(40))/(JVS(75))
  X(17) = (X(17)-JVS(68)*X(24)-JVS(69)*X(28)-JVS(70)*X(30)-JVS(71)*X(39))/(JVS(67))
  X(16) = (X(16)-JVS(62)*X(30)-JVS(63)*X(39))/(JVS(61))
  X(15) = (X(15)-JVS(50)*X(17)-JVS(51)*X(23)-JVS(52)*X(25)-JVS(53)*X(26)-JVS(54)*X(28)-JVS(55)*X(30)-JVS(56)*X(34)&
            &-JVS(57)*X(38)-JVS(58)*X(39))/(JVS(49))
  X(14) = (X(14)-JVS(43)*X(20)-JVS(44)*X(21)-JVS(45)*X(39))/(JVS(42))
  X(13) = (X(13)-JVS(38)*X(16)-JVS(39)*X(30)-JVS(40)*X(33)-JVS(41)*X(40))/(JVS(37))
  X(12) = (X(12)-JVS(36)*X(39))/(JVS(35))
  X(11) = (X(11)-JVS(33)*X(12)-JVS(34)*X(39))/(JVS(32))
  X(10) = (X(10)-JVS(30)*X(39))/(JVS(29))
  X(9) = (X(9)-JVS(26)*X(33)-JVS(27)*X(39)-JVS(28)*X(40))/(JVS(25))
  X(8) = (X(8)-JVS(24)*X(39))/(JVS(23))
  X(7) = (X(7)-JVS(21)*X(30)-JVS(22)*X(40))/(JVS(20))
  X(6) = (X(6)-JVS(17)*X(37)-JVS(18)*X(39)-JVS(19)*X(40))/(JVS(16))
  X(5) = (X(5)-JVS(15)*X(39))/(JVS(14))
  X(4) = (X(4)-JVS(12)*X(36)-JVS(13)*X(40))/(JVS(11))
  X(3) = (X(3)-JVS(9)*X(33)-JVS(10)*X(39))/(JVS(8))
  X(2) = (X(2)-JVS(7)*X(28))/(JVS(6))
  X(1) = (X(1)-JVS(2)*X(14)-JVS(3)*X(20)-JVS(4)*X(21)-JVS(5)*X(39))/(JVS(1))

END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(6)
  XX(3) = X(3)/JVS(8)
  XX(4) = X(4)/JVS(11)
  XX(5) = X(5)/JVS(14)
  XX(6) = X(6)/JVS(16)
  XX(7) = X(7)/JVS(20)
  XX(8) = X(8)/JVS(23)
  XX(9) = X(9)/JVS(25)
  XX(10) = X(10)/JVS(29)
  XX(11) = X(11)/JVS(32)
  XX(12) = (X(12)-JVS(33)*XX(11))/(JVS(35))
  XX(13) = X(13)/JVS(37)
  XX(14) = (X(14)-JVS(2)*XX(1))/(JVS(42))
  XX(15) = X(15)/JVS(49)
  XX(16) = (X(16)-JVS(38)*XX(13))/(JVS(61))
  XX(17) = (X(17)-JVS(50)*XX(15))/(JVS(67))
  XX(18) = X(18)/JVS(75)
  XX(19) = X(19)/JVS(84)
  XX(20) = (X(20)-JVS(3)*XX(1)-JVS(43)*XX(14))/(JVS(92))
  XX(21) = (X(21)-JVS(4)*XX(1)-JVS(44)*XX(14)-JVS(93)*XX(20))/(JVS(102))
  XX(22) = X(22)/JVS(112)
  XX(23) = (X(23)-JVS(51)*XX(15)-JVS(94)*XX(20)-JVS(103)*XX(21))/(JVS(119))
  XX(24) = (X(24)-JVS(68)*XX(17)-JVS(76)*XX(18)-JVS(104)*XX(21))/(JVS(124))
  XX(25) = (X(25)-JVS(52)*XX(15)-JVS(95)*XX(20)-JVS(105)*XX(21))/(JVS(130))
  XX(26) = (X(26)-JVS(53)*XX(15)-JVS(120)*XX(23)-JVS(125)*XX(24)-JVS(131)*XX(25))/(JVS(139))
  XX(27) = X(27)/JVS(149)
  XX(28) = (X(28)-JVS(7)*XX(2)-JVS(54)*XX(15)-JVS(69)*XX(17)-JVS(77)*XX(18)-JVS(96)*XX(20)-JVS(106)*XX(21)-JVS(121)&
             &*XX(23)-JVS(126)*XX(24)-JVS(132)*XX(25)-JVS(140)*XX(26)-JVS(150)*XX(27))/(JVS(163))
  XX(29) = (X(29)-JVS(85)*XX(19))/(JVS(176))
  XX(30) = (X(30)-JVS(21)*XX(7)-JVS(39)*XX(13)-JVS(55)*XX(15)-JVS(62)*XX(16)-JVS(70)*XX(17)-JVS(78)*XX(18)-JVS(113)&
             &*XX(22)-JVS(122)*XX(23)-JVS(127)*XX(24)-JVS(133)*XX(25)-JVS(141)*XX(26)-JVS(151)*XX(27)-JVS(164)*XX(28)&
             &-JVS(177)*XX(29))/(JVS(194))
  XX(31) = (X(31)-JVS(86)*XX(19))/(JVS(214))
  XX(32) = (X(32)-JVS(152)*XX(27)-JVS(178)*XX(29)-JVS(215)*XX(31))/(JVS(240))
  XX(33) = (X(33)-JVS(9)*XX(3)-JVS(26)*XX(9)-JVS(40)*XX(13)-JVS(79)*XX(18)-JVS(87)*XX(19)-JVS(114)*XX(22)-JVS(153)&
             &*XX(27)-JVS(165)*XX(28)-JVS(179)*XX(29)-JVS(195)*XX(30)-JVS(216)*XX(31)-JVS(241)*XX(32))/(JVS(271))
  XX(34) = (X(34)-JVS(56)*XX(15)-JVS(80)*XX(18)-JVS(97)*XX(20)-JVS(107)*XX(21)-JVS(196)*XX(30)-JVS(217)*XX(31)-JVS(242)&
             &*XX(32)-JVS(272)*XX(33))/(JVS(294))
  XX(35) = (X(35)-JVS(88)*XX(19)-JVS(115)*XX(22)-JVS(154)*XX(27)-JVS(180)*XX(29)-JVS(218)*XX(31)-JVS(243)*XX(32)&
             &-JVS(273)*XX(33)-JVS(295)*XX(34))/(JVS(310))
  XX(36) = (X(36)-JVS(12)*XX(4)-JVS(89)*XX(19)-JVS(155)*XX(27)-JVS(181)*XX(29)-JVS(219)*XX(31)-JVS(244)*XX(32)-JVS(274)&
             &*XX(33)-JVS(296)*XX(34)-JVS(311)*XX(35))/(JVS(331))
  XX(37) = (X(37)-JVS(17)*XX(6)-JVS(116)*XX(22)-JVS(156)*XX(27)-JVS(166)*XX(28)-JVS(182)*XX(29)-JVS(197)*XX(30)-JVS(220)&
             &*XX(31)-JVS(245)*XX(32)-JVS(275)*XX(33)-JVS(297)*XX(34)-JVS(312)*XX(35)-JVS(332)*XX(36))/(JVS(347))
  XX(38) = (X(38)-JVS(57)*XX(15)-JVS(81)*XX(18)-JVS(98)*XX(20)-JVS(108)*XX(21)-JVS(198)*XX(30)-JVS(221)*XX(31)-JVS(246)&
             &*XX(32)-JVS(276)*XX(33)-JVS(298)*XX(34)-JVS(313)*XX(35)-JVS(333)*XX(36)-JVS(348)*XX(37))/(JVS(373))
  XX(39) = (X(39)-JVS(5)*XX(1)-JVS(10)*XX(3)-JVS(15)*XX(5)-JVS(18)*XX(6)-JVS(24)*XX(8)-JVS(27)*XX(9)-JVS(30)*XX(10)&
             &-JVS(34)*XX(11)-JVS(36)*XX(12)-JVS(45)*XX(14)-JVS(58)*XX(15)-JVS(63)*XX(16)-JVS(71)*XX(17)-JVS(82)*XX(18)&
             &-JVS(90)*XX(19)-JVS(99)*XX(20)-JVS(109)*XX(21)-JVS(117)*XX(22)-JVS(123)*XX(23)-JVS(128)*XX(24)-JVS(134)*XX(25)&
             &-JVS(142)*XX(26)-JVS(157)*XX(27)-JVS(167)*XX(28)-JVS(183)*XX(29)-JVS(199)*XX(30)-JVS(222)*XX(31)-JVS(247)&
             &*XX(32)-JVS(277)*XX(33)-JVS(299)*XX(34)-JVS(314)*XX(35)-JVS(334)*XX(36)-JVS(349)*XX(37)-JVS(374)*XX(38))&
             &/(JVS(410))
  XX(40) = (X(40)-JVS(13)*XX(4)-JVS(19)*XX(6)-JVS(22)*XX(7)-JVS(28)*XX(9)-JVS(41)*XX(13)-JVS(83)*XX(18)-JVS(118)*XX(22)&
             &-JVS(143)*XX(26)-JVS(158)*XX(27)-JVS(168)*XX(28)-JVS(184)*XX(29)-JVS(200)*XX(30)-JVS(223)*XX(31)-JVS(248)&
             &*XX(32)-JVS(278)*XX(33)-JVS(300)*XX(34)-JVS(315)*XX(35)-JVS(335)*XX(36)-JVS(350)*XX(37)-JVS(375)*XX(38)&
             &-JVS(411)*XX(39))/(JVS(435))
  XX(40) = XX(40)
  XX(39) = XX(39)-JVS(434)*XX(40)
  XX(38) = XX(38)-JVS(409)*XX(39)-JVS(433)*XX(40)
  XX(37) = XX(37)-JVS(372)*XX(38)-JVS(408)*XX(39)-JVS(432)*XX(40)
  XX(36) = XX(36)-JVS(346)*XX(37)-JVS(371)*XX(38)-JVS(407)*XX(39)-JVS(431)*XX(40)
  XX(35) = XX(35)-JVS(330)*XX(36)-JVS(345)*XX(37)-JVS(370)*XX(38)-JVS(406)*XX(39)-JVS(430)*XX(40)
  XX(34) = XX(34)-JVS(309)*XX(35)-JVS(329)*XX(36)-JVS(344)*XX(37)-JVS(369)*XX(38)-JVS(405)*XX(39)-JVS(429)*XX(40)
  XX(33) = XX(33)-JVS(293)*XX(34)-JVS(308)*XX(35)-JVS(328)*XX(36)-JVS(343)*XX(37)-JVS(368)*XX(38)-JVS(404)*XX(39)&
             &-JVS(428)*XX(40)
  XX(32) = XX(32)-JVS(270)*XX(33)-JVS(292)*XX(34)-JVS(307)*XX(35)-JVS(327)*XX(36)-JVS(342)*XX(37)-JVS(367)*XX(38)&
             &-JVS(403)*XX(39)-JVS(427)*XX(40)
  XX(31) = XX(31)-JVS(239)*XX(32)-JVS(269)*XX(33)-JVS(326)*XX(36)-JVS(341)*XX(37)-JVS(366)*XX(38)-JVS(402)*XX(39)&
             &-JVS(426)*XX(40)
  XX(30) = XX(30)-JVS(213)*XX(31)-JVS(238)*XX(32)-JVS(268)*XX(33)-JVS(291)*XX(34)-JVS(306)*XX(35)-JVS(325)*XX(36)&
             &-JVS(340)*XX(37)-JVS(365)*XX(38)-JVS(401)*XX(39)-JVS(425)*XX(40)
  XX(29) = XX(29)-JVS(212)*XX(31)-JVS(237)*XX(32)-JVS(267)*XX(33)-JVS(324)*XX(36)-JVS(339)*XX(37)-JVS(364)*XX(38)&
             &-JVS(400)*XX(39)-JVS(424)*XX(40)
  XX(28) = XX(28)-JVS(175)*XX(29)-JVS(193)*XX(30)-JVS(211)*XX(31)-JVS(236)*XX(32)-JVS(266)*XX(33)-JVS(290)*XX(34)&
             &-JVS(305)*XX(35)-JVS(323)*XX(36)-JVS(338)*XX(37)-JVS(363)*XX(38)-JVS(399)*XX(39)-JVS(423)*XX(40)
  XX(27) = XX(27)-JVS(210)*XX(31)-JVS(235)*XX(32)-JVS(289)*XX(34)-JVS(322)*XX(36)-JVS(362)*XX(38)-JVS(398)*XX(39)
  XX(26) = XX(26)-JVS(148)*XX(27)-JVS(162)*XX(28)-JVS(174)*XX(29)-JVS(192)*XX(30)-JVS(209)*XX(31)-JVS(234)*XX(32)&
             &-JVS(265)*XX(33)-JVS(288)*XX(34)-JVS(304)*XX(35)-JVS(321)*XX(36)-JVS(337)*XX(37)-JVS(361)*XX(38)-JVS(397)&
             &*XX(39)-JVS(422)*XX(40)
  XX(25) = XX(25)-JVS(138)*XX(26)-JVS(161)*XX(28)-JVS(173)*XX(29)-JVS(191)*XX(30)-JVS(208)*XX(31)-JVS(233)*XX(32)&
             &-JVS(264)*XX(33)-JVS(287)*XX(34)-JVS(360)*XX(38)-JVS(396)*XX(39)-JVS(421)*XX(40)
  XX(24) = XX(24)-JVS(129)*XX(25)-JVS(137)*XX(26)-JVS(160)*XX(28)-JVS(172)*XX(29)-JVS(190)*XX(30)-JVS(232)*XX(32)&
             &-JVS(263)*XX(33)-JVS(286)*XX(34)-JVS(303)*XX(35)-JVS(320)*XX(36)-JVS(359)*XX(38)-JVS(395)*XX(39)-JVS(420)&
             &*XX(40)
  XX(23) = XX(23)-JVS(136)*XX(26)-JVS(147)*XX(27)-JVS(159)*XX(28)-JVS(171)*XX(29)-JVS(189)*XX(30)-JVS(207)*XX(31)&
             &-JVS(231)*XX(32)-JVS(262)*XX(33)-JVS(285)*XX(34)-JVS(358)*XX(38)-JVS(394)*XX(39)-JVS(419)*XX(40)
  XX(22) = XX(22)-JVS(146)*XX(27)-JVS(170)*XX(29)-JVS(230)*XX(32)-JVS(284)*XX(34)-JVS(357)*XX(38)-JVS(393)*XX(39)&
             &-JVS(418)*XX(40)
  XX(21) = XX(21)-JVS(261)*XX(33)-JVS(283)*XX(34)-JVS(356)*XX(38)-JVS(392)*XX(39)
  XX(20) = XX(20)-JVS(101)*XX(21)-JVS(260)*XX(33)-JVS(282)*XX(34)-JVS(355)*XX(38)-JVS(391)*XX(39)
  XX(19) = XX(19)-JVS(206)*XX(31)-JVS(229)*XX(32)-JVS(259)*XX(33)-JVS(390)*XX(39)
  XX(18) = XX(18)-JVS(188)*XX(30)-JVS(389)*XX(39)-JVS(417)*XX(40)
  XX(17) = XX(17)-JVS(74)*XX(18)-JVS(187)*XX(30)-JVS(258)*XX(33)-JVS(319)*XX(36)-JVS(388)*XX(39)
  XX(16) = XX(16)-JVS(66)*XX(17)-JVS(73)*XX(18)-JVS(111)*XX(22)-JVS(186)*XX(30)-JVS(205)*XX(31)-JVS(228)*XX(32)-JVS(257)&
             &*XX(33)-JVS(302)*XX(35)-JVS(387)*XX(39)-JVS(416)*XX(40)
  XX(15) = XX(15)-JVS(256)*XX(33)-JVS(386)*XX(39)
  XX(14) = XX(14)-JVS(91)*XX(20)-JVS(100)*XX(21)-JVS(255)*XX(33)-JVS(281)*XX(34)-JVS(354)*XX(38)-JVS(385)*XX(39)
  XX(13) = XX(13)-JVS(110)*XX(22)-JVS(254)*XX(33)-JVS(415)*XX(40)
  XX(12) = XX(12)-JVS(48)*XX(15)-JVS(60)*XX(16)-JVS(65)*XX(17)-JVS(204)*XX(31)-JVS(227)*XX(32)-JVS(253)*XX(33)-JVS(318)&
             &*XX(36)-JVS(353)*XX(38)-JVS(384)*XX(39)
  XX(11) = XX(11)-JVS(47)*XX(15)-JVS(252)*XX(33)-JVS(317)*XX(36)-JVS(383)*XX(39)
  XX(10) = XX(10)-JVS(31)*XX(11)-JVS(46)*XX(15)-JVS(59)*XX(16)-JVS(64)*XX(17)-JVS(203)*XX(31)-JVS(226)*XX(32)-JVS(251)&
             &*XX(33)-JVS(352)*XX(38)-JVS(382)*XX(39)
  XX(9) = XX(9)-JVS(250)*XX(33)-JVS(381)*XX(39)-JVS(414)*XX(40)
  XX(8) = XX(8)-JVS(145)*XX(27)-JVS(169)*XX(29)-JVS(202)*XX(31)-JVS(225)*XX(32)-JVS(280)*XX(34)-JVS(301)*XX(35)-JVS(351)&
            &*XX(38)-JVS(380)*XX(39)
  XX(7) = XX(7)-JVS(72)*XX(18)-JVS(185)*XX(30)-JVS(413)*XX(40)
  XX(6) = XX(6)-JVS(336)*XX(37)-JVS(379)*XX(39)
  XX(5) = XX(5)-JVS(144)*XX(27)-JVS(201)*XX(31)-JVS(224)*XX(32)-JVS(279)*XX(34)-JVS(378)*XX(39)
  XX(4) = XX(4)-JVS(316)*XX(36)-JVS(412)*XX(40)
  XX(3) = XX(3)-JVS(249)*XX(33)-JVS(377)*XX(39)
  XX(2) = XX(2)-JVS(135)*XX(26)-JVS(376)*XX(39)
  XX(1) = XX(1)

END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!--------------------------------------------------------------
      SUBROUTINE WGEFA(N,A,Ipvt,info)
!--------------------------------------------------------------
!     WGEFA FACTORS THE MATRIX A (N,N) BY
!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!     LINPACK - LIKE
!--------------------------------------------------------------
!
      INTEGER       :: N,Ipvt(N),info
      REAL(kind=dp) :: A(N,N)
      REAL(kind=dp) :: t, dmax, da
      INTEGER       :: j,k,l
      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0

      external dscal, daxpy

      info = 0

size: IF (n > 1) THEN

col:  DO k = 1, n-1

!        find l = pivot index
!        l = idamax(n-k+1,A(k,k),1) + k - 1
         l = k; dmax = abs(A(k,k))
         DO j = k+1,n
            da = ABS(A(j,k))
            IF (da > dmax) THEN
              l = j; dmax = da
            END IF
         END DO
         Ipvt(k) = l

!        zero pivot implies this column already triangularized
         IF (ABS(A(l,k)) < TINY(ZERO)) THEN
            info = k
            return
         ELSE
            IF (l /= k) THEN
               t = A(l,k); A(l,k) = A(k,k); A(k,k) = t
            END IF
            t = -ONE/A(k,k)
            CALL DSCAL(n-k,t,A(k+1,k),1)
            DO j = k+1, n
               t = A(l,j)
               IF (l /= k) THEN
                  A(l,j) = A(k,j); A(k,j) = t
               END IF
               CALL DAXPY(n-k,t,A(k+1,k),1,A(k+1,j),1)
            END DO
         END IF

       END DO col

      END IF size

      Ipvt(N) = N
      IF (ABS(A(N,N)) == ZERO) info = N

      END SUBROUTINE WGEFA


!--------------------------------------------------------------
      SUBROUTINE WGESL(Trans,N,A,Ipvt,b)
!--------------------------------------------------------------
!     WGESL solves the system
!     a * x = b  or  trans(a) * x = b
!     using the factors computed by WGEFA.
!
!     Trans      = 'N'   to solve  A*x = b ,
!                = 'T'   to solve  transpose(A)*x = b
!     LINPACK - LIKE
!--------------------------------------------------------------

      INTEGER       :: N,Ipvt(N)
      CHARACTER     :: trans
      REAL(kind=dp) :: A(N,N),b(N)
      REAL(kind=dp) :: t
      INTEGER       :: k,kb,l
      REAL(kind=8), external :: ddot ! provided by the MKL library
      external dscal, daxpy


      SELECT CASE (Trans)

      CASE ('n','N')  !  Solve  A * x = b

!        first solve  L*y = b
         IF (n >= 2) THEN
          DO k = 1, n-1
            l = Ipvt(k)
            t = b(l)
            IF (l /= k) THEN
               b(l) = b(k)
               b(k) = t
            END IF
            CALL DAXPY(n-k,t,a(k+1,k),1,b(k+1),1)
          END DO
         END IF
!        now solve  U*x = y
         DO kb = 1, n
            k = n + 1 - kb
            b(k) = b(k)/a(k,k)
            t = -b(k)
            CALL DAXPY(k-1,t,a(1,k),1,b(1),1)
         END DO

      CASE ('t','T')  !  Solve transpose(A) * x = b

!        first solve  trans(U)*y = b
         DO k = 1, n
            t = DDOT(k-1,a(1,k),1,b(1),1)
            b(k) = (b(k) - t)/a(k,k)
         END DO
!        now solve trans(L)*x = y
         IF (n >= 2) THEN
         DO kb = 1, n-1
            k = n - kb
            b(k) = b(k) + DDOT(n-k,a(k+1,k),1,b(k+1),1)
            l = Ipvt(k)
            IF (l /= k) THEN
               t = b(l); b(l) = b(k); b(k) = t
            END IF
         END DO
         END IF

      END SELECT

      END SUBROUTINE WGESL
! End of BLAS_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mach_kpp_adom2_LinearAlgebra

