! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Linear Algebra Data and Routines File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!============================================================================!
!
! GEM-MACH Setup
! Fichier / File   : mach_kpp_saprc07c_LinearAlgebra.ftn90
! Creation         : Jack Chen (Feb. 2018)
!
!============================================================================

MODULE mach_kpp_saprc07c_LinearAlgebra

  USE mach_kpp_saprc07c_JacobianSP
  USE chm_utils_mod,    ONLY: DP, chm_lun_out
  USE mach_pkg_gas_mod, ONLY: NVAR, LU_NONZERO

  IMPLICIT NONE

 CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: IER
      COMPLEX(kind=8) :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=dp)   :: b = 0.0_dp
      INTEGER(kind=4) :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       :: IER
      REAL(kind=dp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO)
      REAL(kind=dp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER  :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

 END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

 END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: i, j
      COMPLEX(kind=8) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

 END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO

 END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: i, j
      COMPLEX(kind=8) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

 END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
          XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
          XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

 END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_Parameters
!  USE saprcCS07Aiepx_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER)
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER)
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO
!
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_Parameters
!  USE saprcCS07Aiepx_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!              X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!              sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0)
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_Parameters
!  USE saprcCS07Aiepx_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!         !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!              X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!        END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!          !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!              X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!        END DO
!      END DO
!
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=dp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=dp) :: t, dmax, da, TMP(3)
!      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF
!!      END IF
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=dp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=dp) :: TMP
!
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!
!
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(9) = X(9)-JVS(72)*X(8)
  X(21) = X(21)-JVS(114)*X(14)-JVS(115)*X(15)
  X(22) = X(22)-JVS(119)*X(14)-JVS(120)*X(15)-JVS(121)*X(20)
  X(23) = X(23)-JVS(127)*X(11)-JVS(128)*X(22)
  X(24) = X(24)-JVS(139)*X(16)-JVS(140)*X(21)
  X(25) = X(25)-JVS(157)*X(14)-JVS(158)*X(15)-JVS(159)*X(21)
  X(27) = X(27)-JVS(169)*X(14)-JVS(170)*X(15)-JVS(171)*X(21)-JVS(172)*X(22)-JVS(173)*X(25)-JVS(174)*X(26)
  X(28) = X(28)-JVS(184)*X(16)-JVS(185)*X(21)-JVS(186)*X(25)
  X(31) = X(31)-JVS(216)*X(16)-JVS(217)*X(17)-JVS(218)*X(21)-JVS(219)*X(25)-JVS(220)*X(26)-JVS(221)*X(29)-JVS(222)*X(30)
  X(33) = X(33)-JVS(246)*X(16)-JVS(247)*X(21)-JVS(248)*X(25)-JVS(249)*X(26)-JVS(250)*X(30)-JVS(251)*X(32)
  X(35) = X(35)-JVS(267)*X(29)-JVS(268)*X(30)-JVS(269)*X(32)-JVS(270)*X(34)
  X(36) = X(36)-JVS(276)*X(30)-JVS(277)*X(32)-JVS(278)*X(34)-JVS(279)*X(35)
  X(37) = X(37)-JVS(287)*X(7)-JVS(288)*X(26)-JVS(289)*X(29)-JVS(290)*X(30)-JVS(291)*X(32)-JVS(292)*X(34)
  X(38) = X(38)-JVS(299)*X(16)-JVS(300)*X(18)-JVS(301)*X(26)-JVS(302)*X(30)-JVS(303)*X(32)-JVS(304)*X(33)-JVS(305)*X(34)&
            &-JVS(306)*X(35)-JVS(307)*X(36)-JVS(308)*X(37)
  X(39) = X(39)-JVS(322)*X(21)-JVS(323)*X(25)-JVS(324)*X(26)-JVS(325)*X(29)-JVS(326)*X(30)-JVS(327)*X(32)-JVS(328)*X(34)&
            &-JVS(329)*X(35)-JVS(330)*X(37)
  X(40) = X(40)-JVS(339)*X(26)-JVS(340)*X(29)-JVS(341)*X(30)-JVS(342)*X(32)-JVS(343)*X(34)-JVS(344)*X(35)-JVS(345)*X(37)&
            &-JVS(346)*X(39)
  X(41) = X(41)-JVS(355)*X(14)-JVS(356)*X(15)-JVS(357)*X(16)-JVS(358)*X(17)-JVS(359)*X(18)-JVS(360)*X(20)-JVS(361)*X(21)&
            &-JVS(362)*X(22)-JVS(363)*X(25)-JVS(364)*X(26)-JVS(365)*X(29)-JVS(366)*X(30)-JVS(367)*X(32)-JVS(368)*X(33)&
            &-JVS(369)*X(34)-JVS(370)*X(35)-JVS(371)*X(36)-JVS(372)*X(37)-JVS(373)*X(38)-JVS(374)*X(39)-JVS(375)*X(40)
  X(42) = X(42)-JVS(386)*X(6)-JVS(387)*X(10)-JVS(388)*X(13)-JVS(389)*X(14)-JVS(390)*X(15)-JVS(391)*X(19)-JVS(392)*X(20)&
            &-JVS(393)*X(21)-JVS(394)*X(22)-JVS(395)*X(24)-JVS(396)*X(25)-JVS(397)*X(26)-JVS(398)*X(27)-JVS(399)*X(29)&
            &-JVS(400)*X(30)-JVS(401)*X(31)-JVS(402)*X(32)-JVS(403)*X(33)-JVS(404)*X(34)-JVS(405)*X(35)-JVS(406)*X(36)&
            &-JVS(407)*X(37)-JVS(408)*X(38)-JVS(409)*X(39)-JVS(410)*X(40)-JVS(411)*X(41)
  X(43) = X(43)-JVS(421)*X(14)-JVS(422)*X(15)-JVS(423)*X(16)-JVS(424)*X(21)-JVS(425)*X(25)-JVS(426)*X(29)-JVS(427)*X(30)&
            &-JVS(428)*X(32)-JVS(429)*X(34)-JVS(430)*X(35)-JVS(431)*X(36)-JVS(432)*X(37)-JVS(433)*X(39)-JVS(434)*X(40)&
            &-JVS(435)*X(41)-JVS(436)*X(42)
  X(44) = X(44)-JVS(445)*X(16)-JVS(446)*X(17)-JVS(447)*X(21)-JVS(448)*X(25)-JVS(449)*X(27)-JVS(450)*X(32)-JVS(451)*X(34)&
            &-JVS(452)*X(35)-JVS(453)*X(37)-JVS(454)*X(38)-JVS(455)*X(39)-JVS(456)*X(40)-JVS(457)*X(41)-JVS(458)*X(42)&
            &-JVS(459)*X(43)
  X(45) = X(45)-JVS(467)*X(11)-JVS(468)*X(12)-JVS(469)*X(17)-JVS(470)*X(18)-JVS(471)*X(19)-JVS(472)*X(20)-JVS(473)*X(22)&
            &-JVS(474)*X(23)-JVS(475)*X(27)-JVS(476)*X(28)-JVS(477)*X(29)-JVS(478)*X(30)-JVS(479)*X(31)-JVS(480)*X(32)&
            &-JVS(481)*X(33)-JVS(482)*X(34)-JVS(483)*X(35)-JVS(484)*X(36)-JVS(485)*X(37)-JVS(486)*X(38)-JVS(487)*X(39)&
            &-JVS(488)*X(40)-JVS(489)*X(41)-JVS(490)*X(42)-JVS(491)*X(43)-JVS(492)*X(44)
  X(46) = X(46)-JVS(499)*X(12)-JVS(500)*X(28)-JVS(501)*X(29)-JVS(502)*X(30)-JVS(503)*X(32)-JVS(504)*X(34)-JVS(505)*X(35)&
            &-JVS(506)*X(36)-JVS(507)*X(37)-JVS(508)*X(39)-JVS(509)*X(40)-JVS(510)*X(41)-JVS(511)*X(42)-JVS(512)*X(43)&
            &-JVS(513)*X(44)-JVS(514)*X(45)
  X(47) = X(47)-JVS(520)*X(11)-JVS(521)*X(17)-JVS(522)*X(18)-JVS(523)*X(19)-JVS(524)*X(22)-JVS(525)*X(23)-JVS(526)*X(26)&
            &-JVS(527)*X(27)-JVS(528)*X(28)-JVS(529)*X(29)-JVS(530)*X(30)-JVS(531)*X(31)-JVS(532)*X(32)-JVS(533)*X(33)&
            &-JVS(534)*X(34)-JVS(535)*X(35)-JVS(536)*X(36)-JVS(537)*X(37)-JVS(538)*X(38)-JVS(539)*X(39)-JVS(540)*X(40)&
            &-JVS(541)*X(41)-JVS(542)*X(42)-JVS(543)*X(43)-JVS(544)*X(44)-JVS(545)*X(45)-JVS(546)*X(46)
  X(48) = X(48)-JVS(551)*X(14)-JVS(552)*X(15)-JVS(553)*X(16)-JVS(554)*X(21)-JVS(555)*X(25)-JVS(556)*X(29)-JVS(557)*X(30)&
            &-JVS(558)*X(32)-JVS(559)*X(34)-JVS(560)*X(35)-JVS(561)*X(36)-JVS(562)*X(37)-JVS(563)*X(39)-JVS(564)*X(40)&
            &-JVS(565)*X(41)-JVS(566)*X(42)-JVS(567)*X(43)-JVS(568)*X(44)-JVS(569)*X(45)-JVS(570)*X(46)-JVS(571)*X(47)
  X(49) = X(49)-JVS(575)*X(6)-JVS(576)*X(7)-JVS(577)*X(10)-JVS(578)*X(12)-JVS(579)*X(13)-JVS(580)*X(14)-JVS(581)*X(15)&
            &-JVS(582)*X(16)-JVS(583)*X(19)-JVS(584)*X(21)-JVS(585)*X(22)-JVS(586)*X(23)-JVS(587)*X(24)-JVS(588)*X(25)&
            &-JVS(589)*X(26)-JVS(590)*X(27)-JVS(591)*X(29)-JVS(592)*X(30)-JVS(593)*X(31)-JVS(594)*X(32)-JVS(595)*X(33)&
            &-JVS(596)*X(34)-JVS(597)*X(35)-JVS(598)*X(36)-JVS(599)*X(37)-JVS(600)*X(38)-JVS(601)*X(39)-JVS(602)*X(40)&
            &-JVS(603)*X(41)-JVS(604)*X(42)-JVS(605)*X(43)-JVS(606)*X(44)-JVS(607)*X(45)-JVS(608)*X(46)-JVS(609)*X(47)&
            &-JVS(610)*X(48)
  X(50) = X(50)-JVS(613)*X(18)-JVS(614)*X(21)-JVS(615)*X(25)-JVS(616)*X(29)-JVS(617)*X(32)-JVS(618)*X(33)-JVS(619)*X(34)&
            &-JVS(620)*X(35)-JVS(621)*X(36)-JVS(622)*X(37)-JVS(623)*X(39)-JVS(624)*X(40)-JVS(625)*X(41)-JVS(626)*X(42)&
            &-JVS(627)*X(43)-JVS(628)*X(44)-JVS(629)*X(45)-JVS(630)*X(46)-JVS(631)*X(47)-JVS(632)*X(48)-JVS(633)*X(49)
  X(50) = X(50)/JVS(634)
  X(49) = (X(49)-JVS(612)*X(50))/(JVS(611))
  X(48) = (X(48)-JVS(573)*X(49)-JVS(574)*X(50))/(JVS(572))
  X(47) = (X(47)-JVS(548)*X(48)-JVS(549)*X(49)-JVS(550)*X(50))/(JVS(547))
  X(46) = (X(46)-JVS(516)*X(47)-JVS(517)*X(48)-JVS(518)*X(49)-JVS(519)*X(50))/(JVS(515))
  X(45) = (X(45)-JVS(494)*X(46)-JVS(495)*X(47)-JVS(496)*X(48)-JVS(497)*X(49)-JVS(498)*X(50))/(JVS(493))
  X(44) = (X(44)-JVS(461)*X(45)-JVS(462)*X(46)-JVS(463)*X(47)-JVS(464)*X(48)-JVS(465)*X(49)-JVS(466)*X(50))/(JVS(460))
  X(43) = (X(43)-JVS(438)*X(44)-JVS(439)*X(45)-JVS(440)*X(46)-JVS(441)*X(47)-JVS(442)*X(48)-JVS(443)*X(49)-JVS(444)&
            &*X(50))/(JVS(437))
  X(42) = (X(42)-JVS(413)*X(43)-JVS(414)*X(44)-JVS(415)*X(45)-JVS(416)*X(46)-JVS(417)*X(47)-JVS(418)*X(48)-JVS(419)&
            &*X(49)-JVS(420)*X(50))/(JVS(412))
  X(41) = (X(41)-JVS(377)*X(42)-JVS(378)*X(43)-JVS(379)*X(44)-JVS(380)*X(45)-JVS(381)*X(46)-JVS(382)*X(47)-JVS(383)&
            &*X(48)-JVS(384)*X(49)-JVS(385)*X(50))/(JVS(376))
  X(40) = (X(40)-JVS(348)*X(42)-JVS(349)*X(44)-JVS(350)*X(45)-JVS(351)*X(46)-JVS(352)*X(47)-JVS(353)*X(49)-JVS(354)&
            &*X(50))/(JVS(347))
  X(39) = (X(39)-JVS(332)*X(42)-JVS(333)*X(44)-JVS(334)*X(45)-JVS(335)*X(46)-JVS(336)*X(47)-JVS(337)*X(49)-JVS(338)&
            &*X(50))/(JVS(331))
  X(38) = (X(38)-JVS(310)*X(39)-JVS(311)*X(40)-JVS(312)*X(41)-JVS(313)*X(42)-JVS(314)*X(43)-JVS(315)*X(44)-JVS(316)&
            &*X(45)-JVS(317)*X(46)-JVS(318)*X(47)-JVS(319)*X(48)-JVS(320)*X(49)-JVS(321)*X(50))/(JVS(309))
  X(37) = (X(37)-JVS(294)*X(39)-JVS(295)*X(45)-JVS(296)*X(46)-JVS(297)*X(47)-JVS(298)*X(49))/(JVS(293))
  X(36) = (X(36)-JVS(281)*X(37)-JVS(282)*X(39)-JVS(283)*X(43)-JVS(284)*X(46)-JVS(285)*X(47)-JVS(286)*X(49))/(JVS(280))
  X(35) = (X(35)-JVS(272)*X(37)-JVS(273)*X(39)-JVS(274)*X(47)-JVS(275)*X(49))/(JVS(271))
  X(34) = (X(34)-JVS(263)*X(37)-JVS(264)*X(39)-JVS(265)*X(47)-JVS(266)*X(49))/(JVS(262))
  X(33) = (X(33)-JVS(253)*X(34)-JVS(254)*X(35)-JVS(255)*X(36)-JVS(256)*X(37)-JVS(257)*X(39)-JVS(258)*X(40)-JVS(259)&
            &*X(47)-JVS(260)*X(48)-JVS(261)*X(49))/(JVS(252))
  X(32) = (X(32)-JVS(242)*X(37)-JVS(243)*X(39)-JVS(244)*X(47)-JVS(245)*X(49))/(JVS(241))
  X(31) = (X(31)-JVS(224)*X(32)-JVS(225)*X(34)-JVS(226)*X(35)-JVS(227)*X(36)-JVS(228)*X(37)-JVS(229)*X(38)-JVS(230)&
            &*X(39)-JVS(231)*X(40)-JVS(232)*X(41)-JVS(233)*X(43)-JVS(234)*X(44)-JVS(235)*X(45)-JVS(236)*X(46)-JVS(237)*X(47)&
            &-JVS(238)*X(48)-JVS(239)*X(49)-JVS(240)*X(50))/(JVS(223))
  X(30) = (X(30)-JVS(212)*X(37)-JVS(213)*X(39)-JVS(214)*X(47)-JVS(215)*X(49))/(JVS(211))
  X(29) = (X(29)-JVS(207)*X(37)-JVS(208)*X(39)-JVS(209)*X(47)-JVS(210)*X(49))/(JVS(206))
  X(28) = (X(28)-JVS(188)*X(29)-JVS(189)*X(30)-JVS(190)*X(32)-JVS(191)*X(34)-JVS(192)*X(35)-JVS(193)*X(36)-JVS(194)&
            &*X(37)-JVS(195)*X(39)-JVS(196)*X(40)-JVS(197)*X(41)-JVS(198)*X(42)-JVS(199)*X(43)-JVS(200)*X(44)-JVS(201)*X(46)&
            &-JVS(202)*X(47)-JVS(203)*X(48)-JVS(204)*X(49)-JVS(205)*X(50))/(JVS(187))
  X(27) = (X(27)-JVS(176)*X(32)-JVS(177)*X(35)-JVS(178)*X(37)-JVS(179)*X(39)-JVS(180)*X(42)-JVS(181)*X(45)-JVS(182)&
            &*X(47)-JVS(183)*X(49))/(JVS(175))
  X(26) = (X(26)-JVS(165)*X(37)-JVS(166)*X(39)-JVS(167)*X(47)-JVS(168)*X(49))/(JVS(164))
  X(25) = (X(25)-JVS(161)*X(35)-JVS(162)*X(39)-JVS(163)*X(49))/(JVS(160))
  X(24) = (X(24)-JVS(142)*X(25)-JVS(143)*X(26)-JVS(144)*X(27)-JVS(145)*X(29)-JVS(146)*X(30)-JVS(147)*X(31)-JVS(148)&
            &*X(32)-JVS(149)*X(33)-JVS(150)*X(34)-JVS(151)*X(35)-JVS(152)*X(37)-JVS(153)*X(38)-JVS(154)*X(39)-JVS(155)*X(47)&
            &-JVS(156)*X(49))/(JVS(141))
  X(23) = (X(23)-JVS(130)*X(27)-JVS(131)*X(31)-JVS(132)*X(33)-JVS(133)*X(35)-JVS(134)*X(38)-JVS(135)*X(42)-JVS(136)&
            &*X(45)-JVS(137)*X(47)-JVS(138)*X(49))/(JVS(129))
  X(22) = (X(22)-JVS(123)*X(42)-JVS(124)*X(45)-JVS(125)*X(47)-JVS(126)*X(49))/(JVS(122))
  X(21) = (X(21)-JVS(117)*X(39)-JVS(118)*X(49))/(JVS(116))
  X(20) = (X(20)-JVS(109)*X(22)-JVS(110)*X(42)-JVS(111)*X(45)-JVS(112)*X(47)-JVS(113)*X(49))/(JVS(108))
  X(19) = (X(19)-JVS(105)*X(42)-JVS(106)*X(45)-JVS(107)*X(49))/(JVS(104))
  X(18) = (X(18)-JVS(102)*X(45)-JVS(103)*X(50))/(JVS(101))
  X(17) = (X(17)-JVS(99)*X(44)-JVS(100)*X(45))/(JVS(98))
  X(16) = (X(16)-JVS(97)*X(49))/(JVS(96))
  X(15) = (X(15)-JVS(95)*X(49))/(JVS(94))
  X(14) = (X(14)-JVS(93)*X(49))/(JVS(92))
  X(13) = (X(13)-JVS(88)*X(41)-JVS(89)*X(42)-JVS(90)*X(43)-JVS(91)*X(49))/(JVS(87))
  X(12) = (X(12)-JVS(85)*X(46)-JVS(86)*X(49))/(JVS(84))
  X(11) = (X(11)-JVS(82)*X(45)-JVS(83)*X(47))/(JVS(81))
  X(10) = (X(10)-JVS(79)*X(42)-JVS(80)*X(49))/(JVS(78))
  X(9) = (X(9)-JVS(74)*X(29)-JVS(75)*X(42)-JVS(76)*X(46)-JVS(77)*X(49))/(JVS(73))
  X(8) = (X(8)-JVS(69)*X(9)-JVS(70)*X(42)-JVS(71)*X(49))/(JVS(68))
  X(7) = (X(7)-JVS(67)*X(39))/(JVS(66))
  X(6) = (X(6)-JVS(65)*X(49))/(JVS(64))
  X(5) = (X(5)-JVS(40)*X(14)-JVS(41)*X(15)-JVS(42)*X(16)-JVS(43)*X(20)-JVS(44)*X(21)-JVS(45)*X(22)-JVS(46)*X(25)-JVS(47)&
           &*X(26)-JVS(48)*X(29)-JVS(49)*X(30)-JVS(50)*X(32)-JVS(51)*X(34)-JVS(52)*X(35)-JVS(53)*X(36)-JVS(54)*X(37)-JVS(55)&
           &*X(39)-JVS(56)*X(40)-JVS(57)*X(42)-JVS(58)*X(44)-JVS(59)*X(45)-JVS(60)*X(47)-JVS(61)*X(48)-JVS(62)*X(49)-JVS(63)&
           &*X(50))/(JVS(39))
  X(4) = (X(4)-JVS(28)*X(20)-JVS(29)*X(26)-JVS(30)*X(29)-JVS(31)*X(30)-JVS(32)*X(32)-JVS(33)*X(34)-JVS(34)*X(35)-JVS(35)&
           &*X(36)-JVS(36)*X(45)-JVS(37)*X(47)-JVS(38)*X(49))/(JVS(27))
  X(3) = (X(3)-JVS(8)*X(17)-JVS(9)*X(18)-JVS(10)*X(21)-JVS(11)*X(24)-JVS(12)*X(25)-JVS(13)*X(26)-JVS(14)*X(29)-JVS(15)&
           &*X(30)-JVS(16)*X(32)-JVS(17)*X(34)-JVS(18)*X(35)-JVS(19)*X(39)-JVS(20)*X(41)-JVS(21)*X(43)-JVS(22)*X(44)-JVS(23)&
           &*X(46)-JVS(24)*X(47)-JVS(25)*X(49)-JVS(26)*X(50))/(JVS(7))
  X(2) = (X(2)-JVS(5)*X(6)-JVS(6)*X(49))/(JVS(4))
  X(1) = (X(1)-JVS(2)*X(8)-JVS(3)*X(49))/(JVS(1))

 END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(4)
  XX(3) = X(3)/JVS(7)
  XX(4) = X(4)/JVS(27)
  XX(5) = X(5)/JVS(39)
  XX(6) = (X(6)-JVS(5)*XX(2))/(JVS(64))
  XX(7) = X(7)/JVS(66)
  XX(8) = (X(8)-JVS(2)*XX(1))/(JVS(68))
  XX(9) = (X(9)-JVS(69)*XX(8))/(JVS(73))
  XX(10) = X(10)/JVS(78)
  XX(11) = X(11)/JVS(81)
  XX(12) = X(12)/JVS(84)
  XX(13) = X(13)/JVS(87)
  XX(14) = (X(14)-JVS(40)*XX(5))/(JVS(92))
  XX(15) = (X(15)-JVS(41)*XX(5))/(JVS(94))
  XX(16) = (X(16)-JVS(42)*XX(5))/(JVS(96))
  XX(17) = (X(17)-JVS(8)*XX(3))/(JVS(98))
  XX(18) = (X(18)-JVS(9)*XX(3))/(JVS(101))
  XX(19) = X(19)/JVS(104)
  XX(20) = (X(20)-JVS(28)*XX(4)-JVS(43)*XX(5))/(JVS(108))
  XX(21) = (X(21)-JVS(10)*XX(3)-JVS(44)*XX(5))/(JVS(116))
  XX(22) = (X(22)-JVS(45)*XX(5)-JVS(109)*XX(20))/(JVS(122))
  XX(23) = X(23)/JVS(129)
  XX(24) = (X(24)-JVS(11)*XX(3))/(JVS(141))
  XX(25) = (X(25)-JVS(12)*XX(3)-JVS(46)*XX(5)-JVS(142)*XX(24))/(JVS(160))
  XX(26) = (X(26)-JVS(13)*XX(3)-JVS(29)*XX(4)-JVS(47)*XX(5)-JVS(143)*XX(24))/(JVS(164))
  XX(27) = (X(27)-JVS(130)*XX(23)-JVS(144)*XX(24))/(JVS(175))
  XX(28) = X(28)/JVS(187)
  XX(29) = (X(29)-JVS(14)*XX(3)-JVS(30)*XX(4)-JVS(48)*XX(5)-JVS(74)*XX(9)-JVS(145)*XX(24)-JVS(188)*XX(28))/(JVS(206))
  XX(30) = (X(30)-JVS(15)*XX(3)-JVS(31)*XX(4)-JVS(49)*XX(5)-JVS(146)*XX(24)-JVS(189)*XX(28))/(JVS(211))
  XX(31) = (X(31)-JVS(131)*XX(23)-JVS(147)*XX(24))/(JVS(223))
  XX(32) = (X(32)-JVS(16)*XX(3)-JVS(32)*XX(4)-JVS(50)*XX(5)-JVS(148)*XX(24)-JVS(176)*XX(27)-JVS(190)*XX(28)-JVS(224)&
             &*XX(31))/(JVS(241))
  XX(33) = (X(33)-JVS(132)*XX(23)-JVS(149)*XX(24))/(JVS(252))
  XX(34) = (X(34)-JVS(17)*XX(3)-JVS(33)*XX(4)-JVS(51)*XX(5)-JVS(150)*XX(24)-JVS(191)*XX(28)-JVS(225)*XX(31)-JVS(253)&
             &*XX(33))/(JVS(262))
  XX(35) = (X(35)-JVS(18)*XX(3)-JVS(34)*XX(4)-JVS(52)*XX(5)-JVS(133)*XX(23)-JVS(151)*XX(24)-JVS(161)*XX(25)-JVS(177)&
             &*XX(27)-JVS(192)*XX(28)-JVS(226)*XX(31)-JVS(254)*XX(33))/(JVS(271))
  XX(36) = (X(36)-JVS(35)*XX(4)-JVS(53)*XX(5)-JVS(193)*XX(28)-JVS(227)*XX(31)-JVS(255)*XX(33))/(JVS(280))
  XX(37) = (X(37)-JVS(54)*XX(5)-JVS(152)*XX(24)-JVS(165)*XX(26)-JVS(178)*XX(27)-JVS(194)*XX(28)-JVS(207)*XX(29)-JVS(212)&
             &*XX(30)-JVS(228)*XX(31)-JVS(242)*XX(32)-JVS(256)*XX(33)-JVS(263)*XX(34)-JVS(272)*XX(35)-JVS(281)*XX(36))&
             &/(JVS(293))
  XX(38) = (X(38)-JVS(134)*XX(23)-JVS(153)*XX(24)-JVS(229)*XX(31))/(JVS(309))
  XX(39) = (X(39)-JVS(19)*XX(3)-JVS(55)*XX(5)-JVS(67)*XX(7)-JVS(117)*XX(21)-JVS(154)*XX(24)-JVS(162)*XX(25)-JVS(166)&
             &*XX(26)-JVS(179)*XX(27)-JVS(195)*XX(28)-JVS(208)*XX(29)-JVS(213)*XX(30)-JVS(230)*XX(31)-JVS(243)*XX(32)&
             &-JVS(257)*XX(33)-JVS(264)*XX(34)-JVS(273)*XX(35)-JVS(282)*XX(36)-JVS(294)*XX(37)-JVS(310)*XX(38))/(JVS(331))
  XX(40) = (X(40)-JVS(56)*XX(5)-JVS(196)*XX(28)-JVS(231)*XX(31)-JVS(258)*XX(33)-JVS(311)*XX(38))/(JVS(347))
  XX(41) = (X(41)-JVS(20)*XX(3)-JVS(88)*XX(13)-JVS(197)*XX(28)-JVS(232)*XX(31)-JVS(312)*XX(38))/(JVS(376))
  XX(42) = (X(42)-JVS(57)*XX(5)-JVS(70)*XX(8)-JVS(75)*XX(9)-JVS(79)*XX(10)-JVS(89)*XX(13)-JVS(105)*XX(19)-JVS(110)&
             &*XX(20)-JVS(123)*XX(22)-JVS(135)*XX(23)-JVS(180)*XX(27)-JVS(198)*XX(28)-JVS(313)*XX(38)-JVS(332)*XX(39)&
             &-JVS(348)*XX(40)-JVS(377)*XX(41))/(JVS(412))
  XX(43) = (X(43)-JVS(21)*XX(3)-JVS(90)*XX(13)-JVS(199)*XX(28)-JVS(233)*XX(31)-JVS(283)*XX(36)-JVS(314)*XX(38)-JVS(378)&
             &*XX(41)-JVS(413)*XX(42))/(JVS(437))
  XX(44) = (X(44)-JVS(22)*XX(3)-JVS(58)*XX(5)-JVS(99)*XX(17)-JVS(200)*XX(28)-JVS(234)*XX(31)-JVS(315)*XX(38)-JVS(333)&
             &*XX(39)-JVS(349)*XX(40)-JVS(379)*XX(41)-JVS(414)*XX(42)-JVS(438)*XX(43))/(JVS(460))
  XX(45) = (X(45)-JVS(36)*XX(4)-JVS(59)*XX(5)-JVS(82)*XX(11)-JVS(100)*XX(17)-JVS(102)*XX(18)-JVS(106)*XX(19)-JVS(111)&
             &*XX(20)-JVS(124)*XX(22)-JVS(136)*XX(23)-JVS(181)*XX(27)-JVS(235)*XX(31)-JVS(295)*XX(37)-JVS(316)*XX(38)&
             &-JVS(334)*XX(39)-JVS(350)*XX(40)-JVS(380)*XX(41)-JVS(415)*XX(42)-JVS(439)*XX(43)-JVS(461)*XX(44))/(JVS(493))
  XX(46) = (X(46)-JVS(23)*XX(3)-JVS(76)*XX(9)-JVS(85)*XX(12)-JVS(201)*XX(28)-JVS(236)*XX(31)-JVS(284)*XX(36)-JVS(296)&
             &*XX(37)-JVS(317)*XX(38)-JVS(335)*XX(39)-JVS(351)*XX(40)-JVS(381)*XX(41)-JVS(416)*XX(42)-JVS(440)*XX(43)&
             &-JVS(462)*XX(44)-JVS(494)*XX(45))/(JVS(515))
  XX(47) = (X(47)-JVS(24)*XX(3)-JVS(37)*XX(4)-JVS(60)*XX(5)-JVS(83)*XX(11)-JVS(112)*XX(20)-JVS(125)*XX(22)-JVS(137)&
             &*XX(23)-JVS(155)*XX(24)-JVS(167)*XX(26)-JVS(182)*XX(27)-JVS(202)*XX(28)-JVS(209)*XX(29)-JVS(214)*XX(30)&
             &-JVS(237)*XX(31)-JVS(244)*XX(32)-JVS(259)*XX(33)-JVS(265)*XX(34)-JVS(274)*XX(35)-JVS(285)*XX(36)-JVS(297)&
             &*XX(37)-JVS(318)*XX(38)-JVS(336)*XX(39)-JVS(352)*XX(40)-JVS(382)*XX(41)-JVS(417)*XX(42)-JVS(441)*XX(43)&
             &-JVS(463)*XX(44)-JVS(495)*XX(45)-JVS(516)*XX(46))/(JVS(547))
  XX(48) = (X(48)-JVS(61)*XX(5)-JVS(203)*XX(28)-JVS(238)*XX(31)-JVS(260)*XX(33)-JVS(319)*XX(38)-JVS(383)*XX(41)-JVS(418)&
             &*XX(42)-JVS(442)*XX(43)-JVS(464)*XX(44)-JVS(496)*XX(45)-JVS(517)*XX(46)-JVS(548)*XX(47))/(JVS(572))
  XX(49) = (X(49)-JVS(3)*XX(1)-JVS(6)*XX(2)-JVS(25)*XX(3)-JVS(38)*XX(4)-JVS(62)*XX(5)-JVS(65)*XX(6)-JVS(71)*XX(8)&
             &-JVS(77)*XX(9)-JVS(80)*XX(10)-JVS(86)*XX(12)-JVS(91)*XX(13)-JVS(93)*XX(14)-JVS(95)*XX(15)-JVS(97)*XX(16)&
             &-JVS(107)*XX(19)-JVS(113)*XX(20)-JVS(118)*XX(21)-JVS(126)*XX(22)-JVS(138)*XX(23)-JVS(156)*XX(24)-JVS(163)&
             &*XX(25)-JVS(168)*XX(26)-JVS(183)*XX(27)-JVS(204)*XX(28)-JVS(210)*XX(29)-JVS(215)*XX(30)-JVS(239)*XX(31)&
             &-JVS(245)*XX(32)-JVS(261)*XX(33)-JVS(266)*XX(34)-JVS(275)*XX(35)-JVS(286)*XX(36)-JVS(298)*XX(37)-JVS(320)&
             &*XX(38)-JVS(337)*XX(39)-JVS(353)*XX(40)-JVS(384)*XX(41)-JVS(419)*XX(42)-JVS(443)*XX(43)-JVS(465)*XX(44)&
             &-JVS(497)*XX(45)-JVS(518)*XX(46)-JVS(549)*XX(47)-JVS(573)*XX(48))/(JVS(611))
  XX(50) = (X(50)-JVS(26)*XX(3)-JVS(63)*XX(5)-JVS(103)*XX(18)-JVS(205)*XX(28)-JVS(240)*XX(31)-JVS(321)*XX(38)-JVS(338)&
             &*XX(39)-JVS(354)*XX(40)-JVS(385)*XX(41)-JVS(420)*XX(42)-JVS(444)*XX(43)-JVS(466)*XX(44)-JVS(498)*XX(45)&
             &-JVS(519)*XX(46)-JVS(550)*XX(47)-JVS(574)*XX(48)-JVS(612)*XX(49))/(JVS(634))
  XX(50) = XX(50)
  XX(49) = XX(49)-JVS(633)*XX(50)
  XX(48) = XX(48)-JVS(610)*XX(49)-JVS(632)*XX(50)
  XX(47) = XX(47)-JVS(571)*XX(48)-JVS(609)*XX(49)-JVS(631)*XX(50)
  XX(46) = XX(46)-JVS(546)*XX(47)-JVS(570)*XX(48)-JVS(608)*XX(49)-JVS(630)*XX(50)
  XX(45) = XX(45)-JVS(514)*XX(46)-JVS(545)*XX(47)-JVS(569)*XX(48)-JVS(607)*XX(49)-JVS(629)*XX(50)
  XX(44) = XX(44)-JVS(492)*XX(45)-JVS(513)*XX(46)-JVS(544)*XX(47)-JVS(568)*XX(48)-JVS(606)*XX(49)-JVS(628)*XX(50)
  XX(43) = XX(43)-JVS(459)*XX(44)-JVS(491)*XX(45)-JVS(512)*XX(46)-JVS(543)*XX(47)-JVS(567)*XX(48)-JVS(605)*XX(49)&
             &-JVS(627)*XX(50)
  XX(42) = XX(42)-JVS(436)*XX(43)-JVS(458)*XX(44)-JVS(490)*XX(45)-JVS(511)*XX(46)-JVS(542)*XX(47)-JVS(566)*XX(48)&
             &-JVS(604)*XX(49)-JVS(626)*XX(50)
  XX(41) = XX(41)-JVS(411)*XX(42)-JVS(435)*XX(43)-JVS(457)*XX(44)-JVS(489)*XX(45)-JVS(510)*XX(46)-JVS(541)*XX(47)&
             &-JVS(565)*XX(48)-JVS(603)*XX(49)-JVS(625)*XX(50)
  XX(40) = XX(40)-JVS(375)*XX(41)-JVS(410)*XX(42)-JVS(434)*XX(43)-JVS(456)*XX(44)-JVS(488)*XX(45)-JVS(509)*XX(46)&
             &-JVS(540)*XX(47)-JVS(564)*XX(48)-JVS(602)*XX(49)-JVS(624)*XX(50)
  XX(39) = XX(39)-JVS(346)*XX(40)-JVS(374)*XX(41)-JVS(409)*XX(42)-JVS(433)*XX(43)-JVS(455)*XX(44)-JVS(487)*XX(45)&
             &-JVS(508)*XX(46)-JVS(539)*XX(47)-JVS(563)*XX(48)-JVS(601)*XX(49)-JVS(623)*XX(50)
  XX(38) = XX(38)-JVS(373)*XX(41)-JVS(408)*XX(42)-JVS(454)*XX(44)-JVS(486)*XX(45)-JVS(538)*XX(47)-JVS(600)*XX(49)
  XX(37) = XX(37)-JVS(308)*XX(38)-JVS(330)*XX(39)-JVS(345)*XX(40)-JVS(372)*XX(41)-JVS(407)*XX(42)-JVS(432)*XX(43)&
             &-JVS(453)*XX(44)-JVS(485)*XX(45)-JVS(507)*XX(46)-JVS(537)*XX(47)-JVS(562)*XX(48)-JVS(599)*XX(49)-JVS(622)&
             &*XX(50)
  XX(36) = XX(36)-JVS(307)*XX(38)-JVS(371)*XX(41)-JVS(406)*XX(42)-JVS(431)*XX(43)-JVS(484)*XX(45)-JVS(506)*XX(46)&
             &-JVS(536)*XX(47)-JVS(561)*XX(48)-JVS(598)*XX(49)-JVS(621)*XX(50)
  XX(35) = XX(35)-JVS(279)*XX(36)-JVS(306)*XX(38)-JVS(329)*XX(39)-JVS(344)*XX(40)-JVS(370)*XX(41)-JVS(405)*XX(42)&
             &-JVS(430)*XX(43)-JVS(452)*XX(44)-JVS(483)*XX(45)-JVS(505)*XX(46)-JVS(535)*XX(47)-JVS(560)*XX(48)-JVS(597)&
             &*XX(49)-JVS(620)*XX(50)
  XX(34) = XX(34)-JVS(270)*XX(35)-JVS(278)*XX(36)-JVS(292)*XX(37)-JVS(305)*XX(38)-JVS(328)*XX(39)-JVS(343)*XX(40)&
             &-JVS(369)*XX(41)-JVS(404)*XX(42)-JVS(429)*XX(43)-JVS(451)*XX(44)-JVS(482)*XX(45)-JVS(504)*XX(46)-JVS(534)&
             &*XX(47)-JVS(559)*XX(48)-JVS(596)*XX(49)-JVS(619)*XX(50)
  XX(33) = XX(33)-JVS(304)*XX(38)-JVS(368)*XX(41)-JVS(403)*XX(42)-JVS(481)*XX(45)-JVS(533)*XX(47)-JVS(595)*XX(49)&
             &-JVS(618)*XX(50)
  XX(32) = XX(32)-JVS(251)*XX(33)-JVS(269)*XX(35)-JVS(277)*XX(36)-JVS(291)*XX(37)-JVS(303)*XX(38)-JVS(327)*XX(39)&
             &-JVS(342)*XX(40)-JVS(367)*XX(41)-JVS(402)*XX(42)-JVS(428)*XX(43)-JVS(450)*XX(44)-JVS(480)*XX(45)-JVS(503)&
             &*XX(46)-JVS(532)*XX(47)-JVS(558)*XX(48)-JVS(594)*XX(49)-JVS(617)*XX(50)
  XX(31) = XX(31)-JVS(401)*XX(42)-JVS(479)*XX(45)-JVS(531)*XX(47)-JVS(593)*XX(49)
  XX(30) = XX(30)-JVS(222)*XX(31)-JVS(250)*XX(33)-JVS(268)*XX(35)-JVS(276)*XX(36)-JVS(290)*XX(37)-JVS(302)*XX(38)&
             &-JVS(326)*XX(39)-JVS(341)*XX(40)-JVS(366)*XX(41)-JVS(400)*XX(42)-JVS(427)*XX(43)-JVS(478)*XX(45)-JVS(502)&
             &*XX(46)-JVS(530)*XX(47)-JVS(557)*XX(48)-JVS(592)*XX(49)
  XX(29) = XX(29)-JVS(221)*XX(31)-JVS(267)*XX(35)-JVS(289)*XX(37)-JVS(325)*XX(39)-JVS(340)*XX(40)-JVS(365)*XX(41)&
             &-JVS(399)*XX(42)-JVS(426)*XX(43)-JVS(477)*XX(45)-JVS(501)*XX(46)-JVS(529)*XX(47)-JVS(556)*XX(48)-JVS(591)&
             &*XX(49)-JVS(616)*XX(50)
  XX(28) = XX(28)-JVS(476)*XX(45)-JVS(500)*XX(46)-JVS(528)*XX(47)
  XX(27) = XX(27)-JVS(398)*XX(42)-JVS(449)*XX(44)-JVS(475)*XX(45)-JVS(527)*XX(47)-JVS(590)*XX(49)
  XX(26) = XX(26)-JVS(174)*XX(27)-JVS(220)*XX(31)-JVS(249)*XX(33)-JVS(288)*XX(37)-JVS(301)*XX(38)-JVS(324)*XX(39)&
             &-JVS(339)*XX(40)-JVS(364)*XX(41)-JVS(397)*XX(42)-JVS(526)*XX(47)-JVS(589)*XX(49)
  XX(25) = XX(25)-JVS(173)*XX(27)-JVS(186)*XX(28)-JVS(219)*XX(31)-JVS(248)*XX(33)-JVS(323)*XX(39)-JVS(363)*XX(41)&
             &-JVS(396)*XX(42)-JVS(425)*XX(43)-JVS(448)*XX(44)-JVS(555)*XX(48)-JVS(588)*XX(49)-JVS(615)*XX(50)
  XX(24) = XX(24)-JVS(395)*XX(42)-JVS(587)*XX(49)
  XX(23) = XX(23)-JVS(474)*XX(45)-JVS(525)*XX(47)-JVS(586)*XX(49)
  XX(22) = XX(22)-JVS(128)*XX(23)-JVS(172)*XX(27)-JVS(362)*XX(41)-JVS(394)*XX(42)-JVS(473)*XX(45)-JVS(524)*XX(47)&
             &-JVS(585)*XX(49)
  XX(21) = XX(21)-JVS(140)*XX(24)-JVS(159)*XX(25)-JVS(171)*XX(27)-JVS(185)*XX(28)-JVS(218)*XX(31)-JVS(247)*XX(33)&
             &-JVS(322)*XX(39)-JVS(361)*XX(41)-JVS(393)*XX(42)-JVS(424)*XX(43)-JVS(447)*XX(44)-JVS(554)*XX(48)-JVS(584)&
             &*XX(49)-JVS(614)*XX(50)
  XX(20) = XX(20)-JVS(121)*XX(22)-JVS(360)*XX(41)-JVS(392)*XX(42)-JVS(472)*XX(45)
  XX(19) = XX(19)-JVS(391)*XX(42)-JVS(471)*XX(45)-JVS(523)*XX(47)-JVS(583)*XX(49)
  XX(18) = XX(18)-JVS(300)*XX(38)-JVS(359)*XX(41)-JVS(470)*XX(45)-JVS(522)*XX(47)-JVS(613)*XX(50)
  XX(17) = XX(17)-JVS(217)*XX(31)-JVS(358)*XX(41)-JVS(446)*XX(44)-JVS(469)*XX(45)-JVS(521)*XX(47)
  XX(16) = XX(16)-JVS(139)*XX(24)-JVS(184)*XX(28)-JVS(216)*XX(31)-JVS(246)*XX(33)-JVS(299)*XX(38)-JVS(357)*XX(41)&
             &-JVS(423)*XX(43)-JVS(445)*XX(44)-JVS(553)*XX(48)-JVS(582)*XX(49)
  XX(15) = XX(15)-JVS(115)*XX(21)-JVS(120)*XX(22)-JVS(158)*XX(25)-JVS(170)*XX(27)-JVS(356)*XX(41)-JVS(390)*XX(42)&
             &-JVS(422)*XX(43)-JVS(552)*XX(48)-JVS(581)*XX(49)
  XX(14) = XX(14)-JVS(114)*XX(21)-JVS(119)*XX(22)-JVS(157)*XX(25)-JVS(169)*XX(27)-JVS(355)*XX(41)-JVS(389)*XX(42)&
             &-JVS(421)*XX(43)-JVS(551)*XX(48)-JVS(580)*XX(49)
  XX(13) = XX(13)-JVS(388)*XX(42)-JVS(579)*XX(49)
  XX(12) = XX(12)-JVS(468)*XX(45)-JVS(499)*XX(46)-JVS(578)*XX(49)
  XX(11) = XX(11)-JVS(127)*XX(23)-JVS(467)*XX(45)-JVS(520)*XX(47)
  XX(10) = XX(10)-JVS(387)*XX(42)-JVS(577)*XX(49)
  XX(9) = XX(9)
  XX(8) = XX(8)-JVS(72)*XX(9)
  XX(7) = XX(7)-JVS(287)*XX(37)-JVS(576)*XX(49)
  XX(6) = XX(6)-JVS(386)*XX(42)-JVS(575)*XX(49)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)

 END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!--------------------------------------------------------------
      SUBROUTINE WGEFA(N,A,Ipvt,info)
!--------------------------------------------------------------
!     WGEFA FACTORS THE MATRIX A (N,N) BY
!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!     LINPACK - LIKE
!--------------------------------------------------------------
!
      INTEGER       :: N,Ipvt(N),info
      REAL(kind=dp) :: A(N,N)
      REAL(kind=dp) :: t, dmax, da
      INTEGER       :: j,k,l
      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0

      external dscal, daxpy
      info = 0

size: IF (n > 1) THEN

col:  DO k = 1, n-1

!        find l = pivot index
!        l = idamax(n-k+1,A(k,k),1) + k - 1
         l = k; dmax = abs(A(k,k))
         DO j = k+1,n
            da = ABS(A(j,k))
            IF (da > dmax) THEN
              l = j; dmax = da
            END IF
         END DO
         Ipvt(k) = l

!        zero pivot implies this column already triangularized
         IF (ABS(A(l,k)) < TINY(ZERO)) THEN
            info = k
            return
         ELSE
            IF (l /= k) THEN
               t = A(l,k); A(l,k) = A(k,k); A(k,k) = t
            END IF
            t = -ONE/A(k,k)
            CALL DSCAL(n-k,t,A(k+1,k),1)
            DO j = k+1, n
               t = A(l,j)
               IF (l /= k) THEN
                  A(l,j) = A(k,j); A(k,j) = t
               END IF
               CALL DAXPY(n-k,t,A(k+1,k),1,A(k+1,j),1)
            END DO
         END IF

       END DO col

      END IF size

      Ipvt(N) = N
      IF (ABS(A(N,N)) == ZERO) info = N

      END SUBROUTINE WGEFA


!--------------------------------------------------------------
      SUBROUTINE WGESL(Trans,N,A,Ipvt,b)
!--------------------------------------------------------------
!     WGESL solves the system
!     a * x = b  or  trans(a) * x = b
!     using the factors computed by WGEFA.
!
!     Trans      = 'N'   to solve  A*x = b ,
!                = 'T'   to solve  transpose(A)*x = b
!     LINPACK - LIKE
!--------------------------------------------------------------

      INTEGER       :: N,Ipvt(N)
      CHARACTER     :: trans
      REAL(kind=dp) :: A(N,N),b(N)
      REAL(kind=dp) :: t
      INTEGER       :: k,kb,l
      REAL(kind=8), external :: ddot ! provided by the MKL library
      external dscal, daxpy
      SELECT CASE (Trans)

      CASE ('n','N')  !  Solve  A * x = b

!        first solve  L*y = b
         IF (n >= 2) THEN
          DO k = 1, n-1
            l = Ipvt(k)
            t = b(l)
            IF (l /= k) THEN
               b(l) = b(k)
               b(k) = t
            END IF
            CALL DAXPY(n-k,t,a(k+1,k),1,b(k+1),1)
          END DO
         END IF
!        now solve  U*x = y
         DO kb = 1, n
            k = n + 1 - kb
            b(k) = b(k)/a(k,k)
            t = -b(k)
            CALL DAXPY(k-1,t,a(1,k),1,b(1),1)
         END DO

      CASE ('t','T')  !  Solve transpose(A) * x = b

!        first solve  trans(U)*y = b
         DO k = 1, n
            t = DDOT(k-1,a(1,k),1,b(1),1)
            b(k) = (b(k) - t)/a(k,k)
         END DO
!        now solve trans(L)*x = y
         IF (n >= 2) THEN
         DO kb = 1, n-1
            k = n - kb
            b(k) = b(k) + DDOT(n-k,a(k+1,k),1,b(k+1),1)
            l = Ipvt(k)
            IF (l /= k) THEN
               t = b(l); b(l) = b(k); b(k) = t
            END IF
         END DO
         END IF

      END SELECT

      END SUBROUTINE WGESL
! End of BLAS_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mach_kpp_saprc07c_LinearAlgebra

