! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! The ODE Function of Chemical Model File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : mach_kpp_adom2_Function.f90
! Time                 : Wed Feb 17 16:49:33 2021
! Working directory    : /fs/homeu1/eccc/aq/arqi/ket001/GEM-MACH/kpp/jac001/mach_kpp_adom2
! Equation file        : mach_kpp_adom2.def
! Output root filename : mach_kpp_adom2
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Modified for incorporate into GEMMACH - rename module
! changed "A(NREACT)" declaration from in module to local in subroutine


MODULE mach_kpp_adom2_Function

  USE mach_pkg_adom2_mod, ONLY: NVAR, NFIX, NREACT, NREACT_KPP, NPRCF ! see note below
  USE chm_utils_mod,      ONLY: DP
  IMPLICIT NONE

 CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local), with Stoichiometric coefficients
!      Vdot      - Time derivative of variable species concentrations
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local), including the Stoichiometric coefficients
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

! BCS - Stoichiometric coefficients (local)
  REAL(kind=dp) :: BCS(NPRCF)

  BCS(1:NPRCF) = RCT(NREACT_KPP+1 : NREACT)

! Computation of equation rates
  A(1) = RCT(1)*V(40)
  A(2) = RCT(2)*V(26)*F(1)*F(2)
  A(3) = RCT(3)*V(26)*V(40)
  A(4) = RCT(4)*V(26)*V(40)
  A(5) = RCT(5)*V(28)*V(37)
  A(6) = RCT(6)*V(28)*V(40)
  A(7) = RCT(7)*V(30)*V(37)
  A(8) = RCT(8)*V(37)*V(37)*F(2)
  A(9) = RCT(9)*V(30)*V(40)
  A(10) = RCT(10)*V(7)
  A(11) = 1e-21*V(7)*F(3)
  A(12) = RCT(12)*V(30)*V(40)
  A(13) = RCT(13)*V(30)
  A(14) = RCT(14)*V(30)
  A(15) = RCT(15)*V(28)
  A(16) = RCT(16)*V(28)
  A(17) = 2.2e-10*V(2)*F(3)
  A(18) = 2.9e-11*V(2)*F(1)
  A(19) = RCT(19)*V(37)*V(39)
  A(20) = RCT(20)*V(6)
  A(21) = 1e-24*V(40)*F(3)
  A(22) = RCT(22)*V(39)*V(40)
  A(23) = RCT(23)*V(18)
  A(24) = RCT(24)*V(18)*V(39)
  A(25) = 2.4e-13*V(15)*V(39)
  A(26) = RCT(26)*V(28)*V(39)
  A(27) = RCT(27)*V(33)*V(37)
  A(28) = RCT(28)*V(33)*V(40)
  A(29) = RCT(29)*V(9)
  A(30) = RCT(30)*V(9)
  A(31) = RCT(31)*V(9)*V(39)
  A(32) = RCT(32)*V(28)*V(33)
  A(33) = RCT(33)*V(33)*V(33)
  A(34) = RCT(34)*V(33)*V(33)*F(1)
  A(35) = RCT(35)*V(33)*V(33)*F(3)
  A(36) = RCT(36)*V(3)
  A(37) = RCT(37)*V(3)*V(39)
  A(38) = RCT(38)*V(30)*V(33)
  A(39) = RCT(39)*V(30)*V(33)*F(1)
  A(40) = RCT(40)*V(30)*V(33)*F(3)
  A(41) = RCT(41)*V(14)*V(39)
  A(42) = RCT(42)*V(32)*V(37)
  A(43) = RCT(43)*V(32)*V(33)
  A(44) = 1e-15*V(32)*V(32)
  A(45) = 3e-12*V(32)*V(36)
  A(46) = RCT(46)*V(19)
  A(47) = RCT(47)*V(38)
  A(48) = RCT(48)*V(38)
  A(49) = RCT(49)*V(38)*V(39)
  A(50) = RCT(50)*V(30)*V(38)
  A(51) = RCT(51)*V(33)*V(38)
  A(52) = RCT(52)*V(34)*V(39)
  A(53) = RCT(53)*V(34)
  A(54) = RCT(54)*V(30)*V(34)
  A(55) = RCT(55)*V(36)*V(37)
  A(56) = RCT(56)*V(36)*V(40)
  A(57) = RCT(57)*V(33)*V(36)
  A(58) = 5.3e-12*V(36)*V(36)
  A(59) = RCT(59)*V(4)
  A(60) = RCT(60)*V(27)
  A(61) = RCT(61)*V(27)*V(39)
  A(62) = RCT(62)*V(17)
  A(63) = 1.7e-11*V(17)*V(39)
  A(64) = RCT(64)*V(17)*V(30)
  A(65) = RCT(65)*V(39)*F(4)
  A(66) = RCT(66)*V(39)*F(5)
  A(67) = RCT(67)*V(5)*V(39)
  A(68) = RCT(68)*V(8)*V(39)
  A(69) = RCT(69)*V(22)*V(39)
  A(70) = RCT(70)*V(35)*V(37)
  A(71) = RCT(71)*V(33)*V(35)
  A(72) = 1e-15*V(32)*V(35)
  A(73) = 3e-12*V(35)*V(36)
  A(74) = RCT(74)*V(29)*V(37)
  A(75) = RCT(75)*V(29)*V(33)
  A(76) = 1e-15*V(29)*V(32)
  A(77) = 3e-12*V(29)*V(36)
  A(78) = RCT(78)*V(31)*V(37)
  A(79) = RCT(79)*V(31)*V(33)
  A(80) = 1e-13*V(31)*V(32)
  A(81) = 3e-12*V(31)*V(36)
  A(82) = RCT(82)*V(25)*V(39)
  A(83) = RCT(83)*V(25)*V(28)
  A(84) = RCT(84)*V(25)*V(26)
  A(85) = RCT(85)*V(25)*V(30)
  A(86) = RCT(86)*V(23)*V(39)
  A(87) = RCT(87)*V(23)*V(28)
  A(88) = RCT(88)*V(23)*V(26)
  A(89) = RCT(89)*V(23)*V(30)
  A(90) = 1e-13*V(14)*V(20)
  A(91) = 1e-13*V(14)*V(21)
  A(92) = 2.3e-17*V(20)*F(3)
  A(93) = 2.3e-17*V(21)*F(3)
  A(94) = 2.5e-14*V(20)*V(38)
  A(95) = 2.5e-14*V(21)*V(38)
  A(96) = 2.5e-14*V(20)*V(34)
  A(97) = 2.5e-14*V(21)*V(34)
  A(98) = RCT(98)*V(10)*V(39)
  A(99) = RCT(99)*V(12)*V(39)
  A(100) = 3e-11*V(11)*V(39)
  A(101) = RCT(101)*V(11)
  A(102) = 4e-11*V(16)*V(39)
  A(103) = 2.2e-11*V(16)*V(30)
  A(104) = 1.5e-11*V(13)*V(40)
  A(105) = RCT(105)*V(13)*V(33)
  A(106) = 0.001*V(13)
  A(107) = RCT(107)*V(24)*V(39)
  A(108) = RCT(108)*V(24)*V(28)
  A(109) = 1.8e-11*V(24)*V(26)
  A(110) = 3.2e-13*V(24)*V(30)
  A(111) = RCT(111)*V(33)*V(39)
  A(112) = RCT(112)*V(19)*V(39)

! Aggregate function
  Vdot(1) = A(41)+A(90)+A(91)
  Vdot(2) = A(16)-A(17)-A(18)
  Vdot(3) = A(33)+A(34)+A(35)-A(36)-A(37)
  Vdot(4) = A(56)-A(59)
  Vdot(5) = -A(67)
  Vdot(6) = A(19)-A(20)+A(21)
  Vdot(7) = A(9)-A(10)-A(11)
  Vdot(8) = -A(68)
  Vdot(9) = A(28)-A(29)-A(30)-A(31)
  Vdot(10) = -A(98)
  Vdot(11) = 0.4*A(98)+BCS(22)*A(99)-A(100)-A(101)
  Vdot(12) = -A(99)
  Vdot(13) = A(103)-A(104)-A(105)-A(106)
  Vdot(14) = -A(41)-A(90)-A(91)
  Vdot(15) = -A(25)+A(47)+A(48)+A(49)+A(50)+A(53)+A(62)+A(63)+A(64)+0.42*A(83)+A(84)+BCS(15)*A(87)+BCS(16)*A(88)+0.11&
               &*A(98)+BCS(24)*A(99)+A(101)
  Vdot(16) = 0.16*A(98)+0.17*A(99)-0.92*A(102)-0.5*A(103)
  Vdot(17) = -A(62)-A(63)-A(64)+0.13*A(98)+BCS(23)*A(99)+0.2*A(102)+0.27*A(107)+0.2*A(108)
  Vdot(18) = 2*A(11)+A(21)+A(22)-A(23)-A(24)+A(38)+A(39)+A(40)+A(50)+A(54)+A(64)+A(103)
  Vdot(19) = -A(46)+A(57)+A(71)+A(75)+A(79)-A(112)
  Vdot(20) = 0.4*A(83)+BCS(25)*A(87)-A(90)-A(92)-A(94)-A(96)
  Vdot(21) = BCS(26)*A(87)-A(91)-A(93)-A(95)-A(97)+0.2*A(108)
  Vdot(22) = -A(69)+A(70)+A(104)
  Vdot(23) = -A(86)-A(87)-A(88)-A(89)
  Vdot(24) = -A(107)-A(108)-A(109)-A(110)
  Vdot(25) = -A(82)-A(83)-A(84)-A(85)+A(107)+0.5*A(108)+A(109)
  Vdot(26) = A(1)-A(2)-A(3)-A(4)+A(14)+A(15)+A(18)-A(84)-A(88)-A(109)
  Vdot(27) = -A(60)-A(61)+0.5*A(67)+BCS(3)*A(68)+0.14*A(69)+A(71)+A(72)+A(73)+BCS(17)*A(88)
  Vdot(28) = A(2)-A(5)-A(6)-A(15)-A(16)-A(26)-A(32)-A(83)-A(87)-A(108)
  Vdot(29) = BCS(6)*A(68)+1.39*A(69)-A(74)-A(75)-A(76)-A(77)+A(85)+A(89)+0.9*A(107)+0.5*A(109)+A(110)
  Vdot(30) = A(4)+A(6)-A(7)-A(9)+A(10)-A(12)-A(13)-A(14)+A(24)-A(38)-A(39)-A(40)-A(50)-A(54)-A(64)-A(85)-A(89)-A(103)&
               &-A(110)
  Vdot(31) = A(51)+A(53)+A(55)+A(60)+1.5*A(61)+A(65)+A(66)+A(67)+BCS(5)*A(68)-A(78)-A(79)-A(80)-A(81)+A(82)+A(84)+A(86)&
               &+BCS(12)*A(87)+BCS(21)*A(88)+0.84*A(98)+0.83*A(99)+0.85*A(102)+0.5*A(112)
  Vdot(32) = -A(42)-A(43)-2*A(44)-A(45)+A(51)+A(53)+A(55)+A(60)+1.5*A(61)+A(65)+A(66)+A(67)+BCS(7)*A(68)+1.39*A(69)&
               &+A(82)+A(84)+A(85)+A(86)+BCS(12)*A(87)+BCS(21)*A(88)+A(89)+0.84*A(98)+0.83*A(99)+A(102)+A(107)+0.5*A(109)&
               &+A(110)+0.5*A(112)
  Vdot(33) = A(25)+A(26)-A(27)-A(28)+A(29)+A(30)-A(32)-2*A(33)-2*A(34)-2*A(35)+A(37)-A(38)-A(39)-A(40)+A(41)+A(46)+2&
               &*A(47)+A(49)+A(50)-A(51)+A(53)-A(57)+2*A(58)+A(62)-A(71)+0.5*A(72)+A(73)-A(75)+A(77)+A(78)-A(79)+0.5*A(80)&
               &+A(81)+0.12*A(83)+A(84)+BCS(13)*A(87)+BCS(2)*A(88)+0.16*A(98)+0.17*A(99)+A(101)-A(105)+0.7*A(107)+0.4*A(108)&
               &+0.6*A(109)-A(111)
  Vdot(34) = -A(52)-A(53)-A(54)+A(60)+0.5*A(61)+A(66)+0.3*A(67)+BCS(2)*A(68)+1.52*A(69)+0.22*A(82)+BCS(9)*A(86)+BCS(11)&
               &*A(87)+BCS(19)*A(88)+BCS(9)*A(89)+A(91)-A(96)-A(97)+0.2*A(107)+0.4*A(108)+A(109)+A(110)
  Vdot(35) = BCS(4)*A(68)-A(70)-A(71)-A(72)-A(73)+0.15*A(102)+0.1*A(107)
  Vdot(36) = A(52)+A(54)-A(55)-A(56)-A(57)-2*A(58)+A(59)+A(60)+A(61)+A(62)+A(63)+A(64)-A(73)-A(77)-A(81)+A(100)+A(101)&
               &+0.2*A(107)
  Vdot(37) = A(1)+A(3)-A(5)-A(7)-2*A(8)+A(12)+A(13)-A(19)+A(20)-A(27)-A(55)-A(70)-A(74)-A(78)
  Vdot(38) = -A(47)-A(48)-A(49)-A(50)-A(51)+A(53)+A(55)+A(57)+2*A(58)+0.5*A(61)+A(65)+BCS(1)*A(68)+0.16*A(69)+A(73)&
               &+A(77)+A(81)+1.56*A(82)+A(83)+A(84)+2*A(85)+BCS(8)*A(86)+BCS(1)*A(87)+BCS(18)*A(88)+BCS(8)*A(89)+A(90)-A(94)&
               &-A(95)+0.11*A(98)+BCS(24)*A(99)+A(107)+A(108)+A(110)
  Vdot(39) = 2*A(17)-A(19)+A(20)-A(22)+A(23)-A(24)-A(25)-A(26)+A(27)-A(31)+A(32)+2*A(36)-A(37)-A(41)+A(46)-A(49)-A(52)&
               &-A(61)-A(63)-A(65)-A(66)-A(67)-A(68)-A(69)-A(82)-A(86)+BCS(14)*A(87)-A(98)-A(99)-A(100)-A(102)-A(107)+0.1&
               &*A(108)-A(111)-0.5*A(112)
  Vdot(40) = -A(1)-A(3)-A(4)+A(5)-A(6)+2*A(7)+2*A(8)-A(9)+A(10)+A(14)-2*A(21)-A(22)+A(23)+A(27)-A(28)+A(29)+A(30)+A(31)&
               &+A(55)-A(56)+A(59)+A(69)+A(74)+A(78)+A(85)+A(89)-A(104)+A(110)

END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mach_kpp_adom2_Function

