! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! The Reaction Rates File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!

! SAPRC07CS.eqn - modified from condensed SAPRC07c with isop, UTLS rx. {141-158}
! {1,1} NO2 + hv = NO + O3P : (7.23e-1/60.0)*SUN;
! {2,2} O3P + O2 + M = O3 + M : ARR(5.68e-34,0.0e0,-2.60e0,TEMP);
! {3,3} O3P + O3 = 2O2 : ARR(8.00e-12,2.058e3,0.0,TEMP);
! {4,4} O3P + NO = NO2 : FALL2(9.0e-32,0.0,-1.50,3.0e-11,0.0,0.0,0.6,1.0,TEMP);
! {5,5} O3P + NO2 = NO + O2 : ARR(5.50e-12,-1.862e2,0.0,TEMP);
! {6,6} O3P + NO2 = NO3 : FALL2(2.5e-31,0.0,-1.8,2.2e-11,0.0,-0.7,0.6,1.0,TEMP);
! {7,7} O3 + NO = NO2 + O2 : ARR(3.0e-12,1.5e3,0.0,TEMP);
! {8,8} O3 + NO2 = NO3 +O2 : ARR(1.40e-13,2.471e3,0.0,TEMP);
! {9,9} NO + NO3 = 2NO2 : ARR(1.8e-11,-1.107e2,0.0,TEMP);
! {10,10} NO + NO + O2 = 2NO2 : ARR(3.3e-39,-5.284e2,0.0,TEMP);
! {11,11} NO2 + NO3 = N2O5 : FALL2(3.6e-30,0.0,-4.1,1.9e-12,0.0,0.2,0.35,1.33,TEMP);
! {12,12} N2O5 = NO2 + NO3 : FALL2(1.3e-3,1.1e4,-3.5,9.7e+14,1.108e4,0.1,0.35,1.33,TEMP);
! {13,13} N2O5 + H2O = 2HNO3 : 2.5e-22;
! {14,14} N2O5 + H2O + H2O = 2HNO3 + H2O : 1.8e-39;
! {15,15} NO2 + NO3 = NO + NO2 + O2: ARR(4.5e-14,1.258e3,0.0,TEMP);
! {16,16} NO3 + hv = NO +O2 : (1.91/60.0)*SUN;
! {17,17} NO3 + hv = NO2 + O3P : (1.54e+1/60.0)*SUN;
! {18,18} O3 + hv = O1D + O2 : (3.06e-3/60.0)*SUN;
! {19,19} O3 + hv = O3P + O2 : (3.66e-2/60.0)*SUN;
! {20,20} O1D + H2O = 2OH : ARR(1.63e-10,-6.039e1,0.0,TEMP);
! {21,21} O1D + M = O3P + M : ARR(2.38e-11,-9.561e1,0.0,TEMP);
! {22,22} OH + NO = HONO : FALL2(7.0e-31,0.0,-2.6,3.6e-11,0.0,-0.1,0.6,1.0,TEMP);
! {23,23} HONO + hv = OH + NO : (1.14e-1/60.0)*SUN;
! {24,24} OH + HONO = NO2 + H2O : ARR(2.5e-12,-2.617e2,0.0,TEMP);
! {25,25} OH + NO2 = HNO3 : FALL2(1.8e-30, 0.0,-3.0,2.8e-11,0.0,0.0,0.6,1.0,TEMP);
! {26,26} OH + NO3 = HO2 + NO2 : 2.00e-11;
! {27,27} OH + HNO3 = NO3 + H2O : EP4(2.4e-14,-4.58e2,0.0,2.7e-17,-2.2e3,0.0,6.5e-34,-1.33e3,-4.37,TEMP);
! {28,28} HNO3 + hv = OH + NO2 : (5.40e-5/60.0)*SUN;
! {29,29} OH + CO = HO2 +CO2 : EP3(1.44e-13,0.0,3.43e-33,0.0,TEMP);
! {30,30} OH + O3 = HO2 + O2 : ARR(1.7e-12,9.41e2,0.0,TEMP);
! {31,31} HO2 + NO = OH + NO2 : ARR(3.6e-12,-2.717e2,0.0,TEMP);
! {32,32} HO2 + NO2 = HNO4 : FALL2(2.0e-31,0.0,-3.4,2.9e-12,0.0,-1.1,0.6,1.0,TEMP);
! {33,33} HNO4 = HO2 + NO2 : FALL2(3.72e-05,1.065e4,-2.4,5.42e+15,1.117e4,-2.3,0.6,1.0,TEMP);
! {34,34} HNO4 + hv = 0.61HO2 + 0.61NO2 + 0.39OH + 0.39NO3 : (5.42e-4/60.0)*SUN;
! {35,35} HNO4 + OH = NO2 +H2O + O2 : ARR(1.3e-12,-3.824e2,0.0,TEMP);
! {36,36} HO2 + O3 = OH + 2O2 : ARR(2.03e-16,-6.944e2,4.57,TEMP);
! {37,37} HO2 + HO2 = H2O2 + O2 : EP3(2.2e-13,-5.99e2,1.9e-33,-9.81e2,TEMP);
! {38,38} HO2 + HO2 + H2O = H2O2 + O2 + H2O : EP3(3.08e-34,-2.80e3,2.66e-54,-3.18e3,TEMP);
! {39,39} NO3 + HO2 = 0.8OH + 0.8NO2 + O2 + 0.2HNO3 : 4.0e-12;
! {40,40} NO3 + NO3 = 2NO2 + O2 : ARR(8.5e-13,2.451e3,0.0,TEMP);
! {41,41} H2O2 + hv = 2OH : (5.64e-4/60.0)*SUN;
! {42,42} H2O2 + OH = HO2 + H2O : 1.8e-12;
! {43,43} OH + HO2 = H2O + O2 : ARR(4.8e-11,-2.516e2,0.0,TEMP);
! {44,44} OH + SO2 = HO2 + H2SO4 : FALL2(3.3e-31,0.0,-4.3,1.6e-12,0.0,0.0,0.6,1.0,TEMP);
! {45,45} OH + H2 = HO2 + H2O : ARR(7.7e-12,2.098e3,0.0,TEMP);
! {46,BR07} RO2R + NO = NO2 + HO2 : ARR(2.6e-12,-3.824e2,0.0,TEMP);
! {47,BR08} RO2R + HO2 = XOOH + O2 : ARR(3.8e-13,-9.008e2,0.0,TEMP);
! {48,BR09} RO2R + NO3 = NO2 + HO2 + O2 : 2.30e-12;
! {49,BR11} RO2R + RO2R = HO2 : 3.50e-14;
! {50,BR12} RO2N + NO = RNO3 : ARR(2.6e-12,-3.824e2,0.0,TEMP);
! {51,BR13} RO2N + HO2 = XOOH + PROD2 : ARR(3.8e-13,-9.008e2,0.0,TEMP);
! {52,BR14} RO2N + NO3 = NO2 + HO2 + PROD2 + O2 : 2.30e-12;
! {53,BR16} RO2N + RO2R = HO2 + PROD2 + O2 : 3.50e-14;
! {54,BR17} RO2N + RO2N = HO2 + 2PROD2 + O2 : 3.50e-14;
! {55,BR18} MECO3 + NO2 = PAN : FALL2(2.7e-28,0.0,-7.1,1.21e-11,0.0,-0.9,0.3,1.41,TEMP);
! {56,BR19} PAN = MECO3 + NO2 : FALL2(4.9e-3,1.21e4,0.0,4.0e16,1.36e4,0.0,0.3,1.41,TEMP);
! {57,BR20} PAN + hv = 0.6MECO3 + 0.6NO2 + 0.4RO2R + 0.4HCHO + 0.4CO2 + 0.4NO3 : (6.12e-5/60.0)*SUN;
! {58,BR21} MECO3 + NO = RO2R + HCHO + NO2 + CO2 : ARR(7.5e-12,-2.919e2,0.0,TEMP);
! {59,BR22} MECO3 + HO2 = 0.243ALK3 + 0.086CCHO + 0.7O2 + 0.3O3 + 0.856XC : ARR(5.2e-13,-9.813e2,0.0,TEMP);
! {60,BR23} MECO3 + NO3 = RO2R + HCHO + CO2 + NO2 + O2 : 2.30e-12;
! {61,BR25} MECO3 + RO2R = HCHO + RO2R + CO2 : ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {62,BR26} MECO3 + RO2N = RO2R + HCHO + CO2 + HO2 + PROD2 : ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {63,BR27} MECO3 + MECO3 = 2RO2R + 2HCHO + 2CO2 + O2 : ARR(2.90e-12,-4.982e2,0.0,TEMP);
! {64,BR28} RCO3 + NO2 = PAN2 : ARR(1.21e-11,0.0,-1.07,TEMP);
! {65,BR29} PAN2 = RCO3 + NO2 : ARR(8.3e+16,1.394e4,0.0,TEMP);
! {66,BR30} PAN2 + hv = 0.6RCO3 + 0.6NO2 + 0.4RO2R + 0.4CCHO + 0.4CO2 + 0.4NO3 : (6.12e-5/60.0)*SUN;
! {67,BR31} RCO3 + NO = NO2 + CCHO + RO2R + CO2 : ARR(6.7e-12,-3.422e2,0.0,TEMP);
! {68,BR32} RCO3 + HO2 = 0.526ALK3 + 0.19CCHO + 0.75O2 + 0.25O3 + 0.516XC : ARR(5.2e-13,-9.813e2,0.0,TEMP);
! {69,BR33} RCO3 + NO3 = NO2 + CCHO + RO2R + CO2 + O2 : 2.30e-12;
! {70,BR35} RCO3 + RO2R = CO2 + RO2R + CCHO :   ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {71,BR36} RCO3 + RO2N = RO2R + CCHO + CO2 + HO2 + PROD2 : ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {72,BR37} RCO3 + MECO3 = 2CO2 + HCHO + CCHO + 2RO2R + O2 : ARR(2.9e-12,-4.982e2,0.0,TEMP);
! {73,BR38} RCO3 + RCO3 = 2CCHO + 2RO2R + 2CO2 : ARR(2.9e-12,-4.982e2,0.0,TEMP);
! {74,BR66} BZO + NO2 = 0.5CRES + 2.5XC + XN : ARR(2.3e-11,-1.51e2,0.0,TEMP);
! {75,BR67} BZO + HO2 = CRES - XC : ARR(3.8e-13,-9.008e2,0.0,TEMP);
! {76,BR68} BZO = CRES + RO2R - XC : 1.00e-03;
! {77,BR69} R2O2 + NO = NO2 : ARR(2.6e-12,-3.824e2,0.0,TEMP);
! {78,BR70} R2O2 + HO2 = HO2 : ARR(3.8e-13,-9.008e2,0.0,TEMP);
! {79,BR71} R2O2 + NO3 = NO2 : 2.30e-12;
! {80,BR73} R2O2 + RO2R = RO2R : 3.50e-14;
! {81,BR74} R2O2 + RO2N = RO2N : 3.50e-14;
! {82,BR75} R2O2 + R2O2 = DUM : 3.50e-14;
! {83,BR76} R2O2 + MECO3 = MECO3 : ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {84,BR77} R2O2 + RCO3 = RCO3 : ARR(4.4e-13,-1.072e3,0.0,TEMP);
! {85,BP01} HCHO + hv = 2HO2 + CO : (2.76e-3/60.0)*SUN;
! {86,BP02} HCHO + hv = CO + H2 : (3.12e-3/60.0)*SUN;
! {87,BP03} HCHO + OH = HO2 + CO + H2O : ARR(5.4e-12,-1.359e2,0.0,TEMP);
! {88,BP07} HCHO + NO3 = HNO3 + HO2 + CO : ARR(2.0e-12,2.431e3,0.0,TEMP);
! {89,BP08} CCHO + OH = MECO3 : ARR(4.4e-12,-3.674e2,0.0,TEMP);
! {90,BP09} CCHO + hv = HO2 + RO2R + CO + HCHO : (4.16e-4/60.0)*SUN;
! {91,BP10} CCHO + NO3 = HNO3 + MECO3 : ARR(1.4e-12,1.862e3,0.0,TEMP);
! {92,BP11} RCHO + OH = 0.035RO2R + 0.965RCO3 + 0.035CO+ 0.035CCHO : ARR(5.1e-12,-4.026e2,0.0,TEMP);
! {93,BP12} RCHO + hv = CCHO + RO2R + CO + HO2 : (1.403e-3/60.0)*SUN;
! {94,BP13} RCHO + NO3 = HNO3 + RCO3 : ARR(1.4e-12,1.6e3,0.0,TEMP);
! {95,BP24} XOOH + OH = OH : 2.5e-11;
! {96,BP25} XOOH + hv = HO2 + OH : (3.94e-4/60.0)*SUN;
! {97,BP34} MGLY + hv = HO2 + CO + MECO3 : (1.56e-2/60.0)*SUN;
! {98,BP35} MGLY + OH = CO + MECO3 : 1.50e-11;
! {99,BP36} MGLY + NO3 = HNO3 + CO + MECO3 : ARR(1.4e-12,1.897e3,0.0,TEMP);
! {100,BP38} CRES + OH = 0.2BZO + 0.8RO2R + 0.25MGLY + 5.05XC : ARR(1.7e-12,-9.511e2,0.0,TEMP);
! {101,BP39} CRES + NO3 = HNO3 + BZO + XC : 1.4e-11;
! {102,BP46} AFG1 + OH = 0.521RO2R + 0.201MECO3 + 0.217RCO3 + 0.06RO2N + 0.202R2O2 + 0.334CO + 0.407RCHO + 0.048PROD2 + 0.329MGLY + 0.002AFG1 + 0.747XC : 7.4e-11;
! {103,BP47} AFG1 + O3 = 0.522HO2 + 0.826OH + 0.652RCO3 + 0.652R2O2 + 0.522CO + 0.174CO2 + 0.652HCHO + 0.819MGLY + 0.007AFG1 - 0.796XC : 9.66e-18;
! {104,BP48} AFG1 + hv = 1.023HO2 + 0.173RO2R + 0.305MECO3 + 0.5RCO3 + 0.695CO + 0.173HCHO + 0.418MGLY + 0.003AFG1 + 0.753XC : (3.87e-1/60.0)*SUN;
! {105,BP49} AFG2 + OH = 0.521RO2R + 0.201MECO3 + 0.217RCO3 + 0.06RO2N + 0.202R2O2 + 0.334CO + 0.407RCHO + 0.048PROD2 + 0.329MGLY + 0.002AFG1 + 0.747XC : 7.4e-11;
! {106,BP50} AFG2 + O3 = 0.522HO2 + 0.826OH + 0.652RCO3 + 0.652R2O2 + 0.522CO + 0.174CO2 + 0.652HCHO + 0.819MGLY + 0.007AFG1 - 0.796XC : 9.66e-18;
! {107,BP51} AFG2 + hv = PROD2 - XC : (3.87e-1/60.0)*SUN;
! {108,BP64} IPRD + OH = 0.496RO2R + 0.238MECO3 + 0.241RCO3 + 0.025RO2N + 0.238R2O2 + 0.238CO + 0.149HCHO + 0.051CCHO + 0.243RCHO + 0.192PROD2 + 0.23MGLY + 0.001AFG1 + 0.586XC : 6.19e-11;
! {109,BP65} IPRD + O3 = 0.211HO2 + 0.025RO2R + 0.219OH + 0.053RCO3 + 0.028R2O2 + 0.483CO + 0.13CO2 + 0.119HCHO + 0.05CCHO + 0.033PROD2 + 0.095ALK3 + 0.863MGLY + 0.842XC : 4.18e-18;
! {110,BP66} IPRD + NO3 = 0.792RO2R + 0.158RCO3 + 0.05RO2N + 0.158HNO3 + 0.57CO + 0.222HCHO + 0.213RCHO + 0.008MGLY + 0.559RNO3 + 0.283XN - 0.583XC : 1.00e-13;
! {111,BP67} IPRD + hv = 0.655HO2 + 0.141RO2R + 0.084OH + 0.354MECO3 + 0.343RCO3 + 0.084R2O2 + 0.867CO + 0.429HCHO + 0.184CCHO + 0.246PROD2 + 0.123XC : (1.97e-4/60.0)*SUN;
! {112,BP68} PROD2 + OH = 0.472HO2 + 0.379RO2R + 0.029MECO3 + 0.071RO2N + 0.049RCO3 + 0.094R2O2 + 0.213HCHO + 0.084CCHO + 0.545RCHO + 0.378PROD2 + 1.085XC : 1.55e-11;
! {113,BP69} PROD2 + hv = 0.913RO2R + 0.4MECO3 + 0.6RCO3 + 0.087RO2N + 0.677R2O2 + 0.303HCHO + 0.163CCHO + 0.78RCHO - 0.091XC : (4.69e-6/60.0)*SUN;
! {114,BP70} RNO3 + OH = 0.332NO2 + 0.189HO2 + 0.305RO2R + 0.175RO2N + 0.671R2O2+ 0.011HCHO + 0.429CCHO + 0.037RCHO + 0.106PROD2 + 0.494RNO3 + 0.174XN + 0.37XC : 7.20e-12;
! {115,BP71} RNO3 + hv = 0.344HO2 + 0.554RO2R + NO2 + 0.102RO2N + 0.167R2O2+ 0.135HCHO + 0.444CCHO + 0.137RCHO + 0.528PROD2 + 0.786XC : (2.35e-4/60.0)*SUN;
! {116,BE01} CH4 + OH = RO2R + HCHO : ARR(1.85e-12,1.691e3,0.0,TEMP);
! {117,BE02} ETHENE + OH = RO2R + 1.61HCHO + 0.195CCHO : FALL2(1.0e-28,0.0,-4.5,8.8e-12,0.0,-0.85,0.6,1.0,TEMP);
! {118,BE03} ETHENE + O3 = 0.16HO2 + 0.16OH + 0.51CO + 0.12CO2 + HCHO + 0.018ALK3 + 0.298XC : ARR(9.14e-15,2.582e3,0.0,TEMP);
! {119,BE04} ETHENE + NO3 = RO2R + RCHO + XN - XC : ARR(3.3e-12,2.878e3,2.0,TEMP);
! {120,BE05} ETHENE + O3P = 0.8HO2 + 0.8RO2R + 0.788CO + 0.788HCHO + 0.1CCHO + 0.007MGLY + 0.203XC : ARR(1.07e-11,8.001e2,0.0,TEMP);
! {121,BE06} ISOPRENE + OH = 0.907RO2R + 0.093RO2N + 0.079R2O2 + 0.624HCHO + 0.907IPRD - 0.717XC + yIOH : ARR(2.54e-11,-4.076e2,0.0,TEMP);
! {122,BE07} ISOPRENE + O3 = 0.066HO2 + 0.266OH + 0.192RCO3 + 0.008RO2N + 0.192R2O2 + 0.275CO + 0.122CO2 + 0.592HCHO + 0.1PROD2 + 0.01ALK3 + 0.7IPRD - 0.753XC : ARR(7.86e-15,1.912e3,0.0,TEMP);
! {123,BE08} ISOPRENE + NO3 = 0.187NO2 + 0.749RO2R + 0.064RO2N + 0.187R2O2 + 0.936IPRD + 0.813XN - 0.064XC : ARR(3.03e-12,4.479e2,0.0,TEMP);
! {124,BE09} ISOPRENE + O3P = 0.25RO2R + 0.24RCO3 + 0.01RO2N + 0.24R2O2 + 0.49HCHO + 0.75PROD2 - 0.77XC : 3.5e-11;
! {125,BL03} ALK3 + OH = 0.931RO2R + 0.07RO2N + 0.558R2O2 + 0.262HCHO + 0.445CCHO + 0.122RCHO + 0.141PROD2 + 1.216XC : ARR(1.51e-12,-1.258e2,0.0,TEMP);
! {126,BL04} ALK4 + OH = 0.766RO2R + 0.007MECO3 + 0.227RO2N + 0.943R2O2 + 0.001CO + 0.039HCHO + 0.31CCHO + 0.226RCHO + 0.303PROD2 + 0.468XC : 6.16e-12;
! {127,Bl06} OLE1 + OH = 0.905RO2R + 0.095RO2N + 0.234R2O2 + 0.701HCHO + 0.301CCHO + 0.47RCHO + 0.119PROD2 + 0.04IPRD + 0.803XC : ARR(6.18e-12,-5.032e2,0.0,TEMP);
! {128,BL07} OLE1 + O3 = 0.116HO2 + 0.144RO2R + 0.193OH + 0.004RO2N + 0.023R2O2 + 0.368CO + 0.125CO2 + 0.604HCHO + 0.177CCHO + 0.384RCHO + 0.191PROD2 + 0.073ALK3 + 0.935XC : ARR(3.15e-15,1.701e3,0.0,TEMP);
! {129,BL08} OLE1 + NO3 = 0.824RO2R + 0.176RO2N + 0.488R2O2 + 0.009CCHO + 0.002RCHO + 0.002PROD2 + 0.546RNO3 + 0.454XN + 0.632XC : ARR(4.73e-13,1.047e3,0.0,TEMP);
! {130,BL09} OLE1 + O3P = 0.45RCHO + 0.274PROD2 + 2.006XC : ARR(1.49e-11,3.271e2,0.0,TEMP);
! {131,BL10} OLE2 + OH = 0.914RO2R + 0.086RO2N + 0.052R2O2 + 0.209HCHO + 0.788CCHO + 0.481RCHO + 0.06PROD2 + 0.066IPRD + 0.566XC : ARR(1.26e-11,-4.881e2,0.0,TEMP);
! {132,BL11} OLE2 + O3 = 0.093HO2 + 0.329RO2R + 0.423OH + 0.147MECO3 + 0.008RCO3 + 0.003RO2N + 0.161R2O2 + 0.297CO + 0.162CO2 + 0.55HCHO + 0.542CCHO + 0.333RCHO + 0.057PROD2 + 0.133ALK3 + 0.049IPRD + 0.453XC : ARR(8.14e-15,1.253e3,0.0,TEMP);
! {133,BL12} OLE2 + NO3 = 0.456RO2R + 0.409NO2 + 0.136RO2N + 0.762R2O2 + 0.107HCHO + 0.546CCHO + 0.154RCHO + 0.009PROD2 + 0.033IPRD + 0.322RNO3 + 0.269XN + 0.372XC : ARR(2.2e-13,-3.824e2,0.0,TEMP);
! {134,BL13} OLE2 + O3P = 0.014HO2 + 0.007RO2R + 0.007RCO3 + 0.001RO2N + 0.006R2O2 + 0.006CO + 0.074RCHO + 0.464PROD2 + 0.006IPRD + 1.931XC : ARR(1.43e-11,-1.107e2,0.0,TEMP);
! {135,BL14} ARO1 + OH = 0.166HO2 + 0.482RO2R + 0.284OH + 0.068RO2N + 0.077PROD2 + 0.47MGLY + 0.166CRES + 0.167AFG1 + 0.454AFG2 + 0.453XC : 6.15e-12;
! {136,BL15} ARO2 + OH = 0.108HO2 + 0.58RO2R + 0.202OH + 0.11RO2N + 0.035PROD2 + 0.709MGLY + 0.108CRES + 0.219AFG1 + 0.469AFG2 + 1.807XC : 2.57e-11;
! {137,BL16} TERP + OH = 0.759RO2R + 0.042RCO3 + 0.2RO2N + 0.388R2O2 + 0.001CO + 0.264HCHO + 0.533RCHO + 0.259PROD2 + 0.029MGLY + 0.003IPRD + 5.154XC : ARR(1.87e-11,-4.328e2,0.0,TEMP);
! {138,BL17} TERP + O3 = 0.052HO2 + 0.067RO2R + 0.585OH + 0.126MECO3 + 0.149RCO3 + 0.203RO2N + 0.808R2O2 + 0.185CO + 0.045CO2 + 0.229HCHO + 0.008CCHO + 0.22RCHO + 0.422PROD2 + 0.028ALK3 + 0.083MGLY + 0.002IPRD + 4.045XC : ARR(9.57e-16,7.85e2,0.0,TEMP);
! {139BL18} TERP + NO3 = 0.421NO2 + 0.162RO2R + 0.019RCO3 + 0.397RO2N + 1.347R2O2 + 0.01CO + 0.017HCHO + 0.001CCHO + 0.509RCHO + 0.012PROD2 + 0.001MGLY + 0.006IPRD + 0.163RNO3 + 0.416XN + 4.922XC : ARR(1.28e-12,-4.881e2,0.0,TEMP);
! {140,BL19} TERP + O3P = 0.147RCHO + 0.853PROD2 + 4.441XC : 3.71e-11;
! // add Isoprene rx, changed "{121,BE06} ISOP + OH
! {141,IS01} yIOH + NO = NO : ARR(2.60e-12, -380.0, 0.0, TEMP) ;
! {142,ISO2} yIOH + HO2 = HO2 + IOOH : ARR(3.80e-13, -900.0, 0.0, TEMP) ;
! {143,ISO3} IOOH + OH = OH + IEPX : ARR(1.90E-11, -390.0, 0.0, TEMP) ;
! {144,ISO4} IOOH + OH = 0.387 yIOH + OH : ARR(4.75E-12, -200.0, 0.0, TEMP) ;
! {145,ISO5} IOOH = DUM : (1.0/60.0)*SUN ;
! {146,ISO6} IEPX + OH = OH + DUM : ARR(5.78E-11, 400.0, 0.0, TEMP) ;
! // add Rx for Strato
! {147,STJ01} NO + hv = O1D + N :                  (1.00/60.0)*SUN;
! {148,STJ02} N2O + hv = N2 + O1D :                (2.7E-13/60.0)*SUN;
! {149,STJ03} N2O5 + hv = NO2 + NO3 :              (1.00/60.0)*SUN;
! {150,STJ04} N2O5 + hv = NO + O3P + NO3 :         (1.00/60.0)*SUN;
! {151,STJ05} O2 + hv = O3P :                      (1.00/60.0)*SUN;
! {152,STJ06} CH4 + hv = 2HO2 + CO + H2 {+ 2H}:    (1.00/60.0)*SUN;
! {153,STR01} N + NO = N2 + O3P :                  ARR2(2.10E-11, 100.0, TEMP);
! {154,STR02} N + O2 = NO + O3P :                  ARR2(1.50E-11, -3600.0, TEMP);
! {155,STR03} N + NO2 = N2O + O3P :                ARR2(5.80E-12, 220.0, TEMP);
! {156,STR04} O1D + O3 = 1.5 O2 + O3P :            1.20E-10 ;
! {157,STR05} O1D + N2O = 2.0 NO :                 ARR2(7.25E-11, 20.0, TEMP);
! {158,STR06} O1D + N2O = N2 + O2 :                ARR2(4.63E-11, 20.0, TEMP);
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!============================================================================!
!
! GEM-MACH Setup
! Fichier / File   : mach_kpp_saprc07_rates.ftn90
! Creation         : Diane Pendlebury (Feb. 2018) and Jack Chen (Feb. 2017)
!
!============================================================================
!
!!if_on
subroutine mach_kpp_saprc07_rates(rconst_out, ksoa, kNO_r2o2, kHO2_r2o2, tp, &
                                  conv, gni, gnk)
  use mach_pkg_gas_mod,   only: nreact, nvsoa
!!if_off
  use mach_pkg_saprc_mod, only: nreact_saprc07
  use chm_nml_mod,        only: nk_start, chm_soa_s
  implicit none

!!if_on
  integer(kind=4), intent(in) :: gni, gnk
  real(kind=8), intent(out)   :: rconst_out(gni*gnk, nreact)
  real(kind=8), intent(out)   :: ksoa      (3, nvsoa, gni, gnk)
  real(kind=8), intent(out)   :: kNO_r2o2  (gni, gnk)
  real(kind=8), intent(out)   :: kHO2_r2o2 (gni, gnk)
  real(kind=4), intent(in )   :: tp        (gni, gnk) ! Deg. Kelvin
  real(kind=8), intent(in )   :: conv      (gni*gnk)  ! concentration of air in molecules/cm3
!!if_off
!
  integer(kind=4) :: i, k, nn
  real(kind=8)    :: RCONST(gni*gnk, nreact_saprc07)
  real(kind=8)    :: cfactor, temp

! INITIALIZE
  RCONST(:,:) = 0.0D0

  nn = (nk_start - 1) * gni
  do k = nk_start, gnk
     do i = 1, gni
      nn = nn + 1
      temp = dble(tp(i, k))
      cfactor = conv(nn)

    ! RCONST(nn, 1   ) = ! Photolysis J    ((7.23e-1/60.0)*SUN)
      RCONST(nn, 2   ) = (ARR(6.00d-34,0.0d0,-2.40d0,TEMP))
      RCONST(nn, 3   ) = (ARR2(8.00d-12,-2.06d3,TEMP))
      RCONST(nn, 4   ) = (FALL2(9.0e-32,0.0,-1.50,3.0e-11,0.0,0.0,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 5   ) = (ARR2(5.10d-12,2.1d2,TEMP))
      RCONST(nn, 6   ) = (FALL2(2.5e-31,0.0,-1.8,2.2e-11,0.0,-0.7,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 7   ) = (ARR2(3.0d-12,-1.5d3,TEMP))
      RCONST(nn, 8   ) = (ARR2(1.20d-13,-2.45d3,TEMP))
      RCONST(nn, 9   ) = (ARR2(1.8d-11,1.70d2,TEMP))
      RCONST(nn, 10  ) = (ARR2(3.3d-39,5.284d2,TEMP))
      RCONST(nn, 11  ) = (FALL2(2.0e-30,0.0,-4.4,1.4e-12,0.0,-0.7,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 12  ) = (FALL2(7.4e-4,1.1e4,-4.4,5.185e+14,1.1e4,-0.7,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 13  ) = 2.5d-22 ! constant rate coefficient
      RCONST(nn, 14  ) = 1.8d-39 ! constant rate coefficient
      RCONST(nn, 15  ) = (ARR2(4.5d-14,-1.26d3,TEMP))
    ! RCONST(nn, 16  ) = ! Photolysis J ((1.91/60.0)*SUN)
    ! RCONST(nn, 17  ) = ! Photolysis J ((1.54e+1/60.0)*SUN)
    ! RCONST(nn, 18  ) = ! Photolysis J ((3.06e-3/60.0)*SUN)
    ! RCONST(nn, 19  ) = ! Photolysis J ((3.66e-2/60.0)*SUN)
      RCONST(nn, 20  ) = (ARR2(1.63d-10,6.039d1,TEMP))
      RCONST(nn, 21  ) = (ARR2(2.38d-11,9.561d1,TEMP))
      RCONST(nn, 22  ) = (FALL2(7.0e-31,0.0,-2.6,3.6e-11,0.0,-0.1,0.6,1.0,TEMP,CFACTOR))
    ! RCONST(nn, 23  ) = ! Photolysis J ((1.14e-1/60.0)*SUN)
      RCONST(nn, 24  ) = (ARR2(1.8d-11,-3.90d2,TEMP))
      RCONST(nn, 25  ) = (FALL2(1.8e-30,0.0,-3.0,2.8e-11,0.0,0.0,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 26  ) = 2.2d-11 ! constant rate coefficient
      RCONST(nn, 27  ) = (EP4(2.4e-14,-4.6e2,0.0,2.7e-17,-2.199e3,0.0,6.5e-34,-1.335e3,0.0,TEMP,CFACTOR))
    ! RCONST(nn, 28  ) = ! Photolysis J ((5.40e-5/60.0)*SUN)
      RCONST(nn, 29  ) = (EP3(1.57d-13,0.d0,3.54d-33,0.0d0,TEMP,CFACTOR))
      RCONST(nn, 30  ) = (ARR2(1.7d-12,-9.40d2,TEMP))
      RCONST(nn, 31  ) = (ARR2(3.5d-12,2.50d2,TEMP))
      RCONST(nn, 32  ) = (FALL2(1.8e-31,0.0,-3.2,4.7e-12,0.0,-1.4,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 33  ) = (FALL2(8.57e-05,1.09e4,-3.2,2.24e+15,1.09e4,-1.4,0.6,1.0,TEMP,CFACTOR))
    ! RCONST(nn, 34  ) = ! Photolysis J ((5.42e-4/60.0)*SUN)
      RCONST(nn, 35  ) = (ARR2(1.3d-12,3.80d2,TEMP))
      RCONST(nn, 36  ) = (ARR2(1.4d-14,-4.90d2,TEMP))
      RCONST(nn, 37  ) = (EP3(1.5d-12,-1.9d1,1.7d-33,-1.0d3,TEMP,CFACTOR))
      RCONST(nn, 38  ) = (EP3(2.1d-33,-2.22d3,2.38d-54,-3.2d3,TEMP,CFACTOR))
      RCONST(nn, 39  ) = 4.0d-12 ! constant rate coefficient
      RCONST(nn, 40  ) = (ARR2(8.5d-13,-2.451d3,TEMP))
    ! RCONST(nn, 41  ) = ! Photolysis J ((5.64e-4/60.0)*SUN)
      RCONST(nn, 42  ) = 1.8d-12 ! constant rate coefficient
      RCONST(nn, 43  ) = (ARR2(4.8d-11,2.6d2,TEMP))
      RCONST(nn, 44  ) = (FALL2(3.3e-31,0.0,-4.3,1.6e-12,0.0,0.0,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 45  ) = (ARR2(2.8d-12,-1.8d3,TEMP))
      RCONST(nn, 46  ) = (ARR2(2.6d-12,3.824d2,TEMP))
      RCONST(nn, 47  ) = (ARR2(3.8d-13,9.008d2,TEMP))
      RCONST(nn, 48  ) = 2.3d-12 ! constant rate coefficient
      RCONST(nn, 49  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 50  ) = (ARR2(2.6d-12,3.824d2,TEMP))
      RCONST(nn, 51  ) = (ARR2(3.8d-13,9.008d2,TEMP))
      RCONST(nn, 52  ) = 2.3d-12 ! constant rate coefficient
      RCONST(nn, 53  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 54  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 55  ) = (FALL2(2.7e-28,0.0,-7.1,1.21e-11,0.0,-0.9,0.3,1.41,TEMP,CFACTOR))
      RCONST(nn, 56  ) = (FALL2(4.9e-3,1.21e4,0.0,4.0e16,1.36e4,0.0,0.3,1.41,TEMP,CFACTOR))
    ! RCONST(nn, 57  ) = ! Photolysis J ((6.12e-5/60.0)*SUN)
      RCONST(nn, 58  ) = (ARR2(7.5d-12,2.919d2,TEMP))
      RCONST(nn, 59  ) = (ARR2(5.2d-13,9.813d2,TEMP))
      RCONST(nn, 60  ) = 2.3d-12 ! constant rate coefficient
      RCONST(nn, 61  ) = (ARR2(4.4d-13,1.072d3,TEMP))
      RCONST(nn, 62  ) = (ARR2(4.4d-13,1.072d3,TEMP))
      RCONST(nn, 63  ) = (ARR2(2.90d-12,4.982d2,TEMP))
      RCONST(nn, 64  ) = (ARR(1.21d-11,0.d0,-1.07d0,TEMP))
      RCONST(nn, 65  ) = (ARR2(8.3d+16,-1.394d4,TEMP))
    ! RCONST(nn, 66  ) = ! Photolysis J ((6.12e-5/60.0)*SUN)
      RCONST(nn, 67  ) = (ARR2(6.7d-12,3.422d2,TEMP))
      RCONST(nn, 68  ) = (ARR2(5.2d-13,9.813d2,TEMP))
      RCONST(nn, 69  ) = 2.3d-12 ! constant rate coefficient
      RCONST(nn, 70  ) = (ARR2(4.4d-13,1.072d3,TEMP))
      RCONST(nn, 71  ) = (ARR2(4.4d-13,1.072d3,TEMP))
      RCONST(nn, 72  ) = (ARR2(2.9d-12,4.982d2,TEMP))
      RCONST(nn, 73  ) = (ARR2(2.9d-12,4.982d2,TEMP))
      RCONST(nn, 74  ) = (ARR2(2.3d-11,1.51d2,TEMP))
      RCONST(nn, 75  ) = (ARR2(3.8d-13,9.008d2,TEMP))
      RCONST(nn, 76  ) = 0.001d0 ! constant rate coefficient
      RCONST(nn, 77  ) = (ARR2(2.6d-12,3.824d2,TEMP))
      RCONST(nn, 78  ) = (ARR2(3.8d-13,9.008d2,TEMP))
      RCONST(nn, 79  ) = 2.3d-12 ! constant rate coefficient
      RCONST(nn, 80  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 81  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 82  ) = 3.5d-14 ! constant rate coefficient
      RCONST(nn, 83  ) = (ARR2(4.4d-13,1.072d3,TEMP))
      RCONST(nn, 84  ) = (ARR2(4.4d-13,1.072d3,TEMP))
    ! RCONST(nn, 85  ) = ! Photolysis J ((2.76e-3/60.0)*SUN)
    ! RCONST(nn, 86  ) = ! Photolysis J ((3.12e-3/60.0)*SUN)
      RCONST(nn, 87  ) = (ARR2(5.4d-12,1.359d2,TEMP))
      RCONST(nn, 88  ) = (ARR2(2.0d-12,-2.431d3,TEMP))
      RCONST(nn, 89  ) = (ARR2(4.4d-12,3.674d2,TEMP))
    ! RCONST(nn, 90  ) = ! Photolysis J ((4.16e-4/60.0)*SUN)
      RCONST(nn, 91  ) = (ARR2(1.4d-12,-1.862d3,TEMP))
      RCONST(nn, 92  ) = (ARR2(5.1d-12,4.026d2,TEMP))
    ! RCONST(nn, 93  ) = ! Photolysis J ((1.403e-3/60.0)*SUN)
      RCONST(nn, 94  ) = (ARR2(1.4d-12,-1.6d3,TEMP))
      RCONST(nn, 95  ) = 2.5d-11 ! constant rate coefficient
    ! RCONST(nn, 96  ) = ! Photolysis J ((3.94e-4/60.0)*SUN)
    ! RCONST(nn, 97  ) = ! Photolysis J ((1.56e-2/60.0)*SUN)
      RCONST(nn, 98  ) = 1.5d-11 ! constant rate coefficient
      RCONST(nn, 99  ) = (ARR2(1.4d-12,-1.897d3,TEMP))
      RCONST(nn, 100 ) = (ARR2(1.7d-12,9.511d2,TEMP))
      RCONST(nn, 101 ) = 1.4d-11 ! constant rate coefficient
      RCONST(nn, 102 ) = 7.4d-11 ! constant rate coefficient
      RCONST(nn, 103 ) = 9.66d-18 ! constant rate coefficient
    ! RCONST(nn, 104 ) = ! Photolysis J ((3.87e-1/60.0)*SUN)
      RCONST(nn, 105 ) = 7.4d-11 ! constant rate coefficient
      RCONST(nn, 106 ) = 9.66d-18 ! constant rate coefficient
    ! RCONST(nn, 107 ) = ! Photolysis J ((3.87e-1/60.0)*SUN)
      RCONST(nn, 108 ) = 6.19d-11 ! constant rate coefficient
      RCONST(nn, 109 ) = 4.18d-18 ! constant rate coefficient
      RCONST(nn, 110 ) = 1.0d-13 ! constant rate coefficient
    ! RCONST(nn, 111 ) = ! Photolysis J ((1.97e-4/60.0)*SUN)
      RCONST(nn, 112 ) = 1.55d-11 ! constant rate coefficient
    ! RCONST(nn, 113 ) = ! Photolysis J ((4.69e-6/60.0)*SUN)
      RCONST(nn, 114 ) = 7.2d-12 ! constant rate coefficient
    ! RCONST(nn, 115 ) = ! Photolysis J ((2.35e-4/60.0)*SUN)
      RCONST(nn, 116 ) = (ARR2(1.85d-12,-1.691d3,TEMP))
      RCONST(nn, 117 ) = (FALL2(1.0e-28,0.0,-4.5,8.8e-12,0.0,-0.85,0.6,1.0,TEMP,CFACTOR))
      RCONST(nn, 118 ) = (ARR2(9.14d-15,-2.582d3,TEMP))
      RCONST(nn, 119 ) = (ARR(3.3d-12,2.878d3,2.0d0,TEMP))
      RCONST(nn, 120 ) = (ARR2(1.07d-11,-8.001d2,TEMP))
      RCONST(nn, 121 ) = (ARR2(2.54d-11,4.076d2,TEMP))
      RCONST(nn, 122 ) = (ARR2(7.86d-15,-1.912d3,TEMP))
      RCONST(nn, 123 ) = (ARR2(3.03d-12,-4.479d2,TEMP))
      RCONST(nn, 124 ) = 3.5d-11 ! constant rate coefficient
      RCONST(nn, 125 ) = (ARR2(1.51d-12,1.258d2,TEMP))
      RCONST(nn, 126 ) = 6.16d-12 ! constant rate coefficient
      RCONST(nn, 127 ) = (ARR2(6.18d-12,5.032d2,TEMP))
      RCONST(nn, 128 ) = (ARR2(3.15d-15,-1.701d3,TEMP))
      RCONST(nn, 129 ) = (ARR2(4.73d-13,-1.047d3,TEMP))
      RCONST(nn, 130 ) = (ARR2(1.49d-11,-3.271d2,TEMP))
      RCONST(nn, 131 ) = (ARR2(1.26d-11,4.881d2,TEMP))
      RCONST(nn, 132 ) = (ARR2(8.14d-15,-1.253d3,TEMP))
      RCONST(nn, 133 ) = (ARR2(2.2d-13,3.824d2,TEMP))
      RCONST(nn, 134 ) = (ARR2(1.43d-11,1.107d2,TEMP))
      RCONST(nn, 135 ) = 6.15d-12 ! constant rate coefficient
      RCONST(nn, 136 ) = 2.57d-11 ! constant rate coefficient
      RCONST(nn, 137 ) = (ARR2(1.87d-11,4.328d2,TEMP))
      RCONST(nn, 138 ) = (ARR2(9.57d-16,-7.85d2,TEMP))
      RCONST(nn, 139 ) = (ARR2(1.28d-12,4.881d2,TEMP))
      RCONST(nn, 140 ) = 3.71d-11 ! constant rate coefficient
      RCONST(nn, 141 ) = (ARR2(2.60d-12,380.0d0,TEMP))
      RCONST(nn, 142 ) = (ARR2(3.80d-13,900.0d0,TEMP))
      RCONST(nn, 143 ) = (ARR2(1.90d-11,390.0d0,TEMP))
      RCONST(nn, 144 ) = (ARR2(4.75d-12,200.0d0,TEMP))
    ! RCONST(nn, 145 ) = ! Photolysis J ((1.0/60.0)*SUN)
      RCONST(nn, 146 ) = (ARR2(5.78d-11,-400.0d0,TEMP))
    ! RCONST(nn, 147 ) = ! Photolysis J ((1.00/60.0)*SUN)
    ! RCONST(nn, 148 ) = ! Photolysis J ((2.7E-13/60.0)*SUN)
    ! RCONST(nn, 149 ) = ! Photolysis J ((1.00/60.0)*SUN)
    ! RCONST(nn, 150 ) = ! Photolysis J ((1.00/60.0)*SUN)
    ! RCONST(nn, 151 ) = ! Photolysis J ((1.00/60.0)*SUN)
    ! RCONST(nn, 152 ) = ! Photolysis J ((1.00/60.0)*SUN)
      RCONST(nn, 153 ) = (ARR2(2.10d-11,100.0d0,TEMP))
      RCONST(nn, 154 ) = (ARR2(1.50d-11,-3600.0d0,TEMP))
      RCONST(nn, 155 ) = (ARR2(5.80d-12,220.0d0,TEMP))
      RCONST(nn, 156 ) = 1.2d-10 ! constant rate coefficient
      RCONST(nn, 157 ) = (ARR2(7.25d-11,20.0d0,TEMP))
      RCONST(nn, 158 ) = (ARR2(4.63d-11,20.0d0,TEMP))

     end do
  end do
!END constant rate coefficients

  rconst_out(:, 1:nreact) = RCONST(:, 1:nreact)

  ! Evaluate the rate constants for Odum SOA scheme
  if (chm_soa_s(1:4) == 'ODUM') then
     call mach_soa_saprc07_rates(ksoa, kNO_r2o2, kHO2_r2o2, rconst_out, tp, &
                                 gni, gnk)
  else
     ksoa = 0.0
     kNO_r2o2  = 0.0
     kHO2_r2o2 = 0.0
  end if

  return

  contains

   subroutine mach_soa_saprc07_rates(ksoa, kNO_r2o2, kHO2_r2o2, rconst, tplus, &
                                     gni, gnk)
      use mach_soa_odum_mod, only: i_kOH, i_kO3, i_kNO3,                    &
                                   soa_alk4, soa_alk5, soa_ole1, soa_ole2,  &
                                   soa_aro1, soa_aro2, soa_isop, soa_apin,  &
                                   soa_bpin, soa_limo, soa_benz, soa_sesq
      integer(kind=4), intent(in)  :: gni, gnk
      real(kind=4),    intent(in)  :: tplus    (gni, gnk)
      real(kind=8),    intent(in)  :: rconst   (gni*gnk, nreact)
      real(kind=8),    intent(out) :: kNO_r2o2 (gni, gnk)
      real(kind=8),    intent(out) :: kHO2_r2o2(gni, gnk)
      real(kind=8),    intent(out) :: ksoa     (3, nvsoa, gni, gnk)

      real(kind=8) :: tt

      nn = (nk_start - 1) * gni
      do k = nk_start, gnk
         do i = 1, gni
            tt = dble(tplus(i, k))
            nn = nn + 1
            ksoa(i_kOH,  soa_alk4, i, k) = rconst(nn, 126) ! {126} ALK4 + OH = : 6.16e-12;
            ksoa(i_kO3,  soa_alk4, i, k) = 0.0d0
            ksoa(i_kNO3, soa_alk4, i, k) = 0.0d0
            ksoa(i_kOH,  soa_alk5, i, k) = ksoa(i_kOH,  soa_alk4, i, k) ! same as soa_alk4
            ksoa(i_kO3,  soa_alk5, i, k) = ksoa(i_kO3,  soa_alk4, i, k)
            ksoa(i_kNO3, soa_alk5, i, k) = ksoa(i_kNO3, soa_alk4, i, k)
            ksoa(i_kOH,  soa_ole1, i, k) = rconst(nn, 127) ! {127} OLE1 + OH = : ARR(6.18e-12,-5.032e2,0.0);
            ksoa(i_kO3,  soa_ole1, i, k) = rconst(nn, 128) ! {128} OLE1 + O3 = : ARR(3.15e-15,1.701e3,0.0);
            ksoa(i_kNO3, soa_ole1, i, k) = rconst(nn, 129) ! {129} OLE1 + NO3 =: ARR(4.73e-13,1.047e3,0.0);
            ksoa(i_kOH,  soa_ole2, i, k) = rconst(nn, 131) ! {131} OLE2 + OH = : ARR(1.26e-11,-4.881e2,0.0);
            ksoa(i_kO3,  soa_ole2, i, k) = rconst(nn, 132) ! {132} OLE2 + O3 = : ARR(8.14e-15,1.253e3,0.0);
            ksoa(i_kNO3, soa_ole2, i, k) = rconst(nn, 133) ! {133} OLE2 + NO3 =: ARR(2.2e-13,-3.824e2,0.0);
            ksoa(i_kOH,  soa_aro1, i, k) = rconst(nn, 135) ! {135} ARO1 + OH = :    6.15e-12;
            ksoa(i_kO3,  soa_aro1, i, k) = 0.0d0
            ksoa(i_kNO3, soa_aro1, i, k) = 0.0d0
            ksoa(i_kOH,  soa_aro2, i, k) = rconst(nn, 136) ! {136} ARO2 + OH = :    2.57e-11;
            ksoa(i_kO3,  soa_aro2, i, k) = 0.0d0
            ksoa(i_kNO3, soa_aro2, i, k) = 0.0d0
            ksoa(i_kOH,  soa_isop, i, k) = rconst(nn, 121) ! {121} ISOP + OH = : ARR(2.54e-11,-4.076e2,0.0);
            ksoa(i_kO3,  soa_isop, i, k) = rconst(nn, 122) ! {122} ISOP + O3 = : ARR(7.86e-15,1.912e3,0.0);
            ksoa(i_kNO3, soa_isop, i, k) = rconst(nn, 123) ! {123} ISOP + NO3 =: ARR(3.03e-12,4.479e2,0.0);
            ksoa(i_kOH,  soa_apin, i, k) = rconst(nn, 137) ! {137} TERP + OH = : ARR(1.87e-11,-4.328e2,0.0);
            ksoa(i_kO3,  soa_apin, i, k) = rconst(nn, 138) ! {138} TERP + O3 = : ARR(9.57e-16,7.85e2,0.0);
            ksoa(i_kNO3, soa_apin, i, k) = rconst(nn, 139) ! {139} TERP + NO3 = : ARR(1.28e-12,-4.881e2,0.0);
            ksoa(i_kOH,  soa_bpin, i, k) = ksoa(i_kOH,  soa_apin, i, k) ! same as terp
            ksoa(i_kO3,  soa_bpin, i, k) = ksoa(i_kO3,  soa_apin, i, k)
            ksoa(i_kNO3, soa_bpin, i, k) = ksoa(i_kNO3, soa_apin, i, k)
            ksoa(i_kOH,  soa_limo, i, k) = ksoa(i_kOH,  soa_apin, i, k) ! same as terp
            ksoa(i_kO3,  soa_limo, i, k) = ksoa(i_kO3,  soa_apin, i, k)
            ksoa(i_kNO3, soa_limo, i, k) = ksoa(i_kNO3, soa_apin, i, k)
            ksoa(i_kOH,  soa_benz, i, k) = ARR2(2.33d-12,-193.0d0, tt) ! from mach_kpp_saprc11_rates.ftn90
            ksoa(i_kO3,  soa_benz, i, k) = 0.0d0
            ksoa(i_kNO3, soa_benz, i, k) = 0.0d0
            ksoa(i_kOH,  soa_sesq, i, k) = ARR2(1.87d-11,435.0d0, tt) ! from mach_kpp_saprc11_rates.ftn90
            ksoa(i_kO3,  soa_sesq, i, k) = ARR2(9.57d-16,-785.0d0, tt)! mach_kpp_saprc11_rates.ftn90
            ksoa(i_kNO3, soa_sesq, i, k) = ARR2(1.28d-12,490.0d0, tt) ! mach_kpp_saprc11_rates.ftn90
            kNO_r2o2(i, k)  = rconst(nn, 77)  ! {77}  R2O2 + NO = NO2 : ARR(2.6e-12,-3.824e2,0.0);
            kHO2_r2o2(i, k) = rconst(nn, 78)  ! {78}  R2O2 + HO2 = HO2 : ARR(3.8e-13,-9.008e2,0.0);
         end do
      end do

      return
   end subroutine mach_soa_saprc07_rates

   REAL(kind=8) FUNCTION ARR(A0, B0, C0, TEMP)
     REAL(kind=8) :: TEMP
     REAL(kind=8) :: A0, B0, C0
      ARR =  A0 * EXP(-B0 / TEMP) * (TEMP / 300.0d0)**C0
   END FUNCTION ARR

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=8) FUNCTION ARR2(A0, B0, TEMP)
      REAL(kind=8) :: TEMP
      REAL(kind=8) :: A0, B0
      ARR2 =  A0 * EXP( B0 / TEMP)
   END FUNCTION ARR2

   REAL(kind=8) FUNCTION EP3(A1, C1, A2, C2, TEMP, CFACTOR)
      REAL(kind=8) :: TEMP, CFACTOR
      REAL(kind=8) :: A1, C1, A2, C2, K1, K2
      K1 = A1 * EXP(-C1 / TEMP)
      K2 = A2 * EXP(-C2 / TEMP)
      EP3 = K1 + K2 * 1.0D6 * CFACTOR
   END FUNCTION EP3

   REAL(kind=8) FUNCTION EP4(A0, B0, C0, A2, B2, C2, A3, B3, C3, TEMP, CFACTOR)
      REAL(kind=4) :: A0, B0, C0, A2, B2, C2, A3, B3, C3
      REAL(kind=8) :: TEMP, CFACTOR
      REAL(kind=8) :: K0, K2, K3
      K0 = DBLE(A0) * EXP(-DBLE(B0) / TEMP) * (TEMP / 300.0d0)**DBLE(C0)
      K2 = DBLE(A2) * EXP(-DBLE(B2) / TEMP) * (TEMP / 300.0d0)**DBLE(C2)
      K3 = DBLE(A3) * EXP(-DBLE(B3) / TEMP) * (TEMP / 300.0d0)**DBLE(C3)
      K3 = K3 * 1.0D6 * CFACTOR
      EP4 = K0 + K3 / (1.0d0 + K3 / K2)
   END FUNCTION EP4

   REAL(kind=8) FUNCTION FALL2(A0, B0, E0, A1, B1, E1, CF, CN, TEMP, CFACTOR)
      REAL(kind=4) :: A0, B0, E0, A1, B1, E1, CF, CN
      REAL(kind=8) :: TEMP, CFACTOR
      REAL(kind=8) :: K0, K1
      K0 = DBLE(A0) * EXP(-DBLE(B0) / TEMP) * (TEMP / 300.0d0)**DBLE(E0)
      K1 = DBLE(A1) * EXP(-DBLE(B1) / TEMP) * (TEMP / 300.0d0)**DBLE(E1)
      K0 = K0 * 1.0D6 * CFACTOR
      K1 = K0 / K1
      FALL2 = (K0 / (1.0d0 + K1))*   &
              DBLE(CF)**(1.0d0 / (1.0d0 + ((LOG10(K1)) / DBLE(CN))**2))
   END FUNCTION FALL2

end subroutine mach_kpp_saprc07_rates

