!---------------------------------- LICENCE BEGIN -------------------------------
! GEM-MACH - Atmospheric chemistry library for the GEM numerical atmospheric model
! Copyright (C) 2007-2013 - Air Quality Research Division &
!                           National Prediction Operations division
!                           Environnement Canada
! This library is free software; you can redistribute it and/or
! modify it under the terms of the GNU Lesser General Public
! License as published by the Free Software Foundation; either
! version 2.1 of the License, or (at your option) any later version.
!
! This library is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
! Lesser General Public License for more details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with this library; if not, write to the Free Software
! Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
!---------------------------------- LICENCE END ---------------------------------

!============================================================================!
!         Environnement Canada         |        Environment Canada           !
!                                      |                                     !
! - Service meteorologique du Canada   | - Meteorological Service of Canada  !
! - Direction generale des sciences    | - Science and Technology Branch     !
!   et de la technologie               |                                     !
!============================================================================!
!                            http://www.ec.gc.ca                             !
!============================================================================!
!
! Projet/Project : GEM-MACH
! Fichier/File   : mach_kppb_adom2night_rodas3.ftn90
! Creation       : K. Toyota, J. Chen, C. Stroud & M. Russell, Dec 2017 for GEM-MACH
!
! Description    : "KPPb" version of RODAS-3 solver for ADOM-II gas-phase chemistry
!                  for nighttime without the photolysis reactions
!
! Extra info     : This file contains additional subroutines, namely:
!                  - Fun_night (calculate the net tendencies for concentrations of chemical species)
!                  - Jac_SP_night (calculate the values of non-zero Jacobian elements)
!                  - ros_PrepareMatrix_night (calculate I/(H*ros_gamma)-Jac)
!                  - KppDecomp_night (perform the LU factorization of I/(H*ros_gamma)-Jac)
!                  - KppSolve_night (solve the matrix inversion problem, y=A^{-1}*b)
!
! Adapted from   : Rosenbrock-rodas3 subroutine(s) generated by KPP v2.2.3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!  By default the code employs the KPP sparse linear algebra routines     !
!                                                                         !
!    (C)  Adrian Sandu, August 2004                                       !
!    Virginia Polytechnic Institute and State University                  !
!    Contact: sandu@cs.vt.edu                                             !
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  !                               !
!    This implementation is part of KPP - the Kinetic PreProcessor        !
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!
! Arguments:  IN
!               delt     -> chm. timestep interval (min)
!               fix      -> Fixed concentrations of gaseous species (CH4, C2H6, H2O, O2 & M) 
!               rconst   -> Reaction rate coefficients
!               bgs      -> Reaction product stochiometric coefficients
!               AbsTol   -> Absolute tolerance for solution convergence used by the solver
!               RelTol   -> Relative tolerance for solution convergence used by the solver
!
!             INOUT
!               Y       -> Concentrations of gaseous species (ppmv)
!               H       -> Initial guess for solver timestep interval (min) at the entry &
!                          exit of this subroutine; within the core of the subroutine, H means
!                          the actual time step interval used for the numerical integration
!             OUT
!               IERR    -> Error code 
!
!============================================================================
!
!!if_on
SUBROUTINE mach_kppb_adom2night_rodas3 (N, Y, nfix, fix, nreact, rconst, nprcf, bgs, &
                     delt, H, RelTol, AbsTol, IERR)
!!if_off
   IMPLICIT NONE
!!if_on
  integer(kind=4), intent(in) :: N, nfix, nreact, nprcf
   REAL(kind=8), INTENT(IN) ::  fix(nfix)
   REAL(kind=4), INTENT(IN) ::  delt
   REAL(kind=8), INTENT(IN) ::  rconst(nreact), bgs(nprcf)
   REAL(kind=8), INTENT(IN) ::  AbsTol(N), RelTol(N)
   INTEGER(kind=4), INTENT(OUT) :: IERR
   REAL(kind=8), INTENT(INOUT) :: H, Y(N)
!!if_off
!~~~~ rodas3 parameters
   INTEGER(kind=4), parameter ::  ros_S=4
   REAL(kind=8), parameter :: ros_ELO = 3.0d0
   REAL(kind=8), parameter, dimension(6) :: ros_A = &
            (/ 0.0d0, 2.0d0, 0.0d0, 2.0d0, 0.0d0, 1.0d0/)
   REAL(kind=8), parameter, dimension(6) :: ros_C = &
            (/ 4.0d0, 1.0d0,-1.0d0, 1.0d0,-1.0d0,-(8.0d0/3.0d0)/)
   REAL(kind=8), parameter :: ros_Gamma = 0.5d0
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 428 
!~~~~ local variables
   integer(kind=4) :: nstp
   REAL(kind=8) :: T, Tstart,Tend, Hmin, Hmax
   REAL(kind=8) :: Roundoff
   REAL(kind=8) :: Ynew(N), Fcn0(N), Fcn(N)
   REAL(kind=8) :: K(N*ros_S)
   REAL(kind=8) :: Jac0(LU_NONZERO), Ghimj(LU_NONZERO)
   REAL(kind=8) :: Hnew, HC, Fac, Hexit
   REAL(kind=8) :: Err, Yerr(N)
   INTEGER(kind=4) :: ioffset, j, istage
   LOGICAL :: RejectLastH, RejectMoreH, Singular
!~~~>  Local parameters
   INTEGER(kind=4), parameter :: Max_no_steps=200000
   REAL(kind=8), PARAMETER :: ZERO = 0.0d0, ONE  = 1.0d0
   REAL(kind=8), parameter :: FacMin=0.2d0, FacMax=6.0d0, &
                              FacRej=0.1d0, FacSafe=0.9d0
   REAL(kind=8), PARAMETER :: DeltaMin = 1.6666667d-7

!   write(0,*) 'in rodas3: rconst=', rconst
!   write(0,*) 'in rodas3: bgs=', bgs
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~>  Initial preparations
   Roundoff = epsilon(ONE)
   nstp = 0
   Tstart = ZERO
   Tend = Tstart + dble(delt)
   T = Tstart
   Hexit = ZERO
   Hmin = ZERO
   Hmax = dble(delt)
   IF (H <= 10.0d0*Roundoff) H = DeltaMin
   RejectLastH=.FALSE.
   RejectMoreH=.FALSE.
!~~~> Time loop begins below
TimeLoop: DO WHILE ( (T-Tend)+Roundoff <= ZERO )
   IF ( Nstp > Max_no_steps ) THEN
      IERR=-6
      RETURN
   END IF
   IF ( ((T+0.1d0*H) == T).OR.(H <= Roundoff) ) THEN
      IERR=-7
      RETURN
   END IF
!~~~>  Limit H if necessary to avoid going beyond Tend
   Hexit = H
   H = MIN(H,Tend-T)
!~~~>   Compute the function at current time
   CALL Fun_night( Y, FIX, RCONST, BGS, Fcn0, n, nfix, nreact, nprcf )
!~~~>   Compute the Jacobian at current time
   CALL Jac_SP_night( Y, FIX, RCONST, BGS, Jac0, n, nfix, nreact, nprcf, LU_NONZERO )
!~~~>  Repeat step calculation until current step accepted
UntilAccepted: DO
    CALL ros_PrepareMatrix_night(H,ros_Gamma,Jac0,Ghimj,Singular)
   IF (Singular) THEN
       IERR=-8
       RETURN
   END IF
!~~~>   Compute the stages
Stage: DO istage = 1, ros_S

       ioffset = N*(istage-1)

       IF ( istage == 1 ) THEN
         Fcn(1:N) = Fcn0(1:N)

       ELSEIF ( istage == 3 ) THEN
         !MR-legacy: do j=1,N
         !MR-legacy:  Ynew(j) = Y(j) + ros_A(2)*K(j)
         !MR-legacy: enddo
         Ynew(1:N) = Y(1:N) + ros_A(2)*K(1:N)
         CALL Fun_night( Ynew, FIX, RCONST, BGS, Fcn, n, nfix, nreact, nprcf )
       ELSEIF ( istage == 4 ) THEN
         !MR-legacy: do j=1,N
         !MR-legacy:   Ynew(j) = Y(j) + ros_A(4)*K(j) + ros_A(6)*K(2*N+j)
         !MR-legacy: enddo
         Ynew(1:N) = Y(1:N) + ros_A(4)*K(1:N) + ros_A(6)*K(2*N+1:3*N)
         CALL Fun_night( Ynew, FIX, RCONST, BGS, Fcn, n, nfix, nreact, nprcf )
       END IF
       K(ioffset+1:ioffset+N)=Fcn(1:N)
       DO j = 1, istage-1
         HC = ros_C((istage-1)*(istage-2)/2+j)/H
         !MR-legacy: do i=1,N
         !MR-legacy:   K(ioffset+i) = K(ioffset+i) + HC*K(N*(j-1)+i)
         !MR-legacy: end do
         K(ioffset+1:ioffset+N) = K(ioffset+1:ioffset+N) + HC*K(N*(j-1)+1:N*j+1)
       END DO
       CALL KppSolve_night( Ghimj, K(ioffset+1),N,LU_NONZERO)
   END DO Stage
!~~~>  Compute the new solution
   Ynew(1:N) = Y(1:N)
   !MR-legacy: DO j=1,N
   !MR-legacy:   Ynew(j) = Ynew(j) + 2.0d0*K(j) + K(2*N+j) + K(3*N+j)
   !MR-legacy: END DO
   Ynew(1:N) = Ynew(1:N) + 2.0d0*K(1:N) + K(2*N+1:3*N) + K(3*N+1:4*N)
!~~~>  Compute the error estimation
   Yerr(1:N) = K(3*N+1:4*N)
   Err = ros_ErrorNorm ( Y, Ynew, Yerr, AbsTol, RelTol )
!~~~> New step size is bounded by FacMin <= Hnew/H <= FacMax
   Fac  = MIN(FacMax,MAX(FacMin,FacSafe/Err**(ONE/ros_ELO)))
   Hnew = H*Fac
!~~~>  Check the error magnitude and adjust step size
   Nstp = Nstp + 1
   IF ( (Err <= ONE).OR.(H <= Hmin) ) THEN
      Y(1:N) = Ynew(1:N)
      T = T + H
      Hnew = MAX(Hmin,MIN(Hnew,Hmax))
      IF (RejectLastH) THEN
         Hnew = MIN(Hnew,H)
      END IF
      RejectLastH = .FALSE.
      RejectMoreH = .FALSE.
      H = Hnew
      EXIT UntilAccepted
   ELSE
      IF (RejectMoreH) THEN
         Hnew = H*FacRej
      END IF
      RejectMoreH = RejectLastH
      RejectLastH = .TRUE.
      H = Hnew
   END IF
   END DO UntilAccepted
   END DO TimeLoop
!~~~> Succesful exit
   IERR = 1
   H = Hexit

  RETURN

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Contains ! Subroutines internal to rodas3_night
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun_night ( V, F, RCT, BGS, Vdot, nvar, nfix, nreact, nprcf )
  IMPLICIT NONE
  integer(kind=4), intent(in) :: nvar, nfix, nreact, nprcf
  real(kind=8), intent(in) :: rct(nreact)
  real(kind=8), intent(in) :: BGS(nprcf)
  real(kind=8), intent(in) :: v(nvar), f(nfix)
  real(kind=8), intent(out) :: vdot(nvar)
! Local variables                                                 
  real(kind=8) :: A(NREACT)

! Computation of equation rates
  A(1) = RCT(1)*V(27)*F(4)*F(5)
  A(2) = RCT(2)*V(27)*V(40)
  A(3) = RCT(3)*V(27)*V(40)
  A(4) = RCT(4)*V(28)*V(39)
  A(5) = RCT(5)*V(28)*V(40)
  A(6) = RCT(6)*V(30)*V(39)
  A(7) = RCT(7)*V(39)*V(39)*F(4)
  A(8) = RCT(8)*V(30)*V(40)
  A(9) = RCT(9)*V(8)
  A(10) = RCT(10)*V(8)*F(3)
  A(11) = RCT(11)*V(30)*V(40)
  A(12) = RCT(12)*V(1)*F(3)
  A(13) = RCT(13)*V(1)*F(5)
  A(14) = RCT(14)*V(32)*V(39)
  A(15) = RCT(15)*V(40)*F(3)
  A(16) = RCT(16)*V(32)*V(40)
  A(17) = RCT(17)*V(15)*V(32)
  A(18) = RCT(18)*V(14)*V(32)
  A(19) = RCT(19)*V(28)*V(32)
  A(20) = RCT(20)*V(36)*V(39)
  A(21) = RCT(21)*V(36)*V(40)
  A(22) = RCT(22)*V(12)
  A(23) = RCT(23)*V(12)*V(32)
  A(24) = RCT(24)*V(28)*V(36)
  A(25) = RCT(25)*V(36)*V(36)
  A(26) = RCT(26)*V(36)*V(36)*F(5)
  A(27) = RCT(27)*V(36)*V(36)*F(3)
  A(28) = RCT(28)*V(4)*V(32)
  A(29) = RCT(29)*V(30)*V(36)
  A(30) = RCT(30)*V(30)*V(36)*F(5)
  A(31) = RCT(31)*V(30)*V(36)*F(3)
  A(32) = RCT(32)*V(19)*V(32)
  A(33) = RCT(33)*V(29)*V(39)
  A(34) = RCT(34)*V(29)*V(36)
  A(35) = RCT(35)*V(29)*V(29)
  A(36) = RCT(36)*V(29)*V(31)
  A(37) = RCT(37)*V(32)*V(38)
  A(38) = RCT(38)*V(30)*V(38)
  A(39) = RCT(39)*V(36)*V(38)
  A(40) = RCT(40)*V(26)*V(32)
  A(41) = RCT(41)*V(26)*V(30)
  A(42) = RCT(42)*V(31)*V(39)
  A(43) = RCT(43)*V(31)*V(40)
  A(44) = RCT(44)*V(31)*V(36)
  A(45) = RCT(45)*V(31)*V(31)
  A(46) = RCT(46)*V(5)
  A(47) = RCT(47)*V(32)*V(37)
  A(48) = RCT(48)*V(18)*V(32)
  A(49) = RCT(49)*V(18)*V(30)
  A(50) = RCT(50)*V(32)*F(1)
  A(51) = RCT(51)*V(32)*F(2)
  A(52) = RCT(52)*V(6)*V(32)
  A(53) = RCT(53)*V(9)*V(32)
  A(54) = RCT(54)*V(22)*V(32)
  A(55) = RCT(55)*V(35)*V(39)
  A(56) = RCT(56)*V(35)*V(36)
  A(57) = RCT(57)*V(29)*V(35)
  A(58) = RCT(58)*V(31)*V(35)
  A(59) = RCT(59)*V(34)*V(39)
  A(60) = RCT(60)*V(34)*V(36)
  A(61) = RCT(61)*V(29)*V(34)
  A(62) = RCT(62)*V(31)*V(34)
  A(63) = RCT(63)*V(33)*V(39)
  A(64) = RCT(64)*V(33)*V(36)
  A(65) = RCT(65)*V(29)*V(33)
  A(66) = RCT(66)*V(31)*V(33)
  A(67) = RCT(67)*V(25)*V(32)
  A(68) = RCT(68)*V(25)*V(28)
  A(69) = RCT(69)*V(25)*V(27)
  A(70) = RCT(70)*V(25)*V(30)
  A(71) = RCT(71)*V(23)*V(32)
  A(72) = RCT(72)*V(23)*V(28)
  A(73) = RCT(73)*V(23)*V(27)
  A(74) = RCT(74)*V(23)*V(30)
  A(75) = RCT(75)*V(19)*V(20)
  A(76) = RCT(76)*V(19)*V(21)
  A(77) = RCT(77)*V(20)*F(3)
  A(78) = RCT(78)*V(21)*F(3)
  A(79) = RCT(79)*V(20)*V(38)
  A(80) = RCT(80)*V(21)*V(38)
  A(81) = RCT(81)*V(20)*V(26)
  A(82) = RCT(82)*V(21)*V(26)
  A(83) = RCT(83)*V(10)*V(32)
  A(84) = RCT(84)*V(11)*V(32)
  A(85) = RCT(85)*V(7)*V(32)
  A(86) = RCT(86)*V(17)*V(32)
  A(87) = RCT(87)*V(17)*V(30)
  A(88) = RCT(88)*V(13)*V(40)
  A(89) = RCT(89)*V(13)*V(36)
  A(90) = RCT(90)*V(13)
  A(91) = RCT(91)*V(24)*V(32)
  A(92) = RCT(92)*V(24)*V(28)
  A(93) = RCT(93)*V(24)*V(27)
  A(94) = RCT(94)*V(24)*V(30)
  A(95) = RCT(95)*V(32)*V(36)
  A(96) = RCT(96)*V(16)*V(32)

! Aggregate function
  Vdot(1) = -A(12)-A(13)
  Vdot(2) = A(32)+A(75)+A(76)
  Vdot(3) = A(14)+A(15)
  Vdot(4) = A(25)+A(26)+A(27)-A(28)
  Vdot(5) = A(43)-A(46)
  Vdot(6) = -A(52)
  Vdot(7) = 0.4*A(83)+BGS(22)*A(84)-A(85)
  Vdot(8) = A(8)-A(9)-A(10)
  Vdot(9) = -A(53)
  Vdot(10) = -A(83)
  Vdot(11) = -A(84)
  Vdot(12) = A(21)-A(22)-A(23)
  Vdot(13) = A(87)-A(88)-A(89)-A(90)
  Vdot(14) = -A(18)+A(37)+A(38)+A(48)+A(49)+0.42*A(68)+A(69)+BGS(15)*A(72)+BGS(16)*A(73)+0.11*A(83)+BGS(24)*A(84)
  Vdot(15) = 2*A(10)+A(15)+A(16)-A(17)+A(29)+A(30)+A(31)+A(38)+A(41)+A(49)+A(87)
  Vdot(16) = A(44)+A(56)+A(60)+A(64)-A(96)
  Vdot(17) = 0.16*A(83)+0.17*A(84)-0.92*A(86)-0.5*A(87)
  Vdot(18) = -A(48)-A(49)+0.13*A(83)+BGS(23)*A(84)+0.2*A(86)+0.27*A(91)+0.2*A(92)
  Vdot(19) = -A(32)-A(75)-A(76)
  Vdot(20) = 0.4*A(68)+BGS(25)*A(72)-A(75)-A(77)-A(79)-A(81)
  Vdot(21) = BGS(26)*A(72)-A(76)-A(78)-A(80)-A(82)+0.2*A(92)
  Vdot(22) = -A(54)+A(55)+A(88)
  Vdot(23) = -A(71)-A(72)-A(73)-A(74)
  Vdot(24) = -A(91)-A(92)-A(93)-A(94)
  Vdot(25) = -A(67)-A(68)-A(69)-A(70)+A(91)+0.5*A(92)+A(93)
  Vdot(26) = -A(40)-A(41)+0.5*A(47)+A(51)+0.3*A(52)+BGS(2)*A(53)+1.52*A(54)+0.22*A(67)+BGS(9)*A(71)+BGS(11)*A(72)&
               &+BGS(19)*A(73)+BGS(9)*A(74)+A(76)-A(81)-A(82)+0.2*A(91)+0.4*A(92)+A(93)+A(94)
  Vdot(27) = -A(1)-A(2)-A(3)+A(13)-A(69)-A(73)-A(93)
  Vdot(28) = A(1)-A(4)-A(5)-A(19)-A(24)-A(68)-A(72)-A(92)
  Vdot(29) = -A(33)-A(34)-2*A(35)-A(36)+A(39)+A(42)+1.5*A(47)+A(50)+A(51)+A(52)+BGS(7)*A(53)+1.39*A(54)+A(67)+A(69)&
               &+A(70)+A(71)+BGS(12)*A(72)+BGS(21)*A(73)+A(74)+0.84*A(83)+0.83*A(84)+A(86)+A(91)+0.5*A(93)+A(94)+0.5*A(96)
  Vdot(30) = A(3)+A(5)-A(6)-A(8)+A(9)-A(11)+A(17)-A(29)-A(30)-A(31)-A(38)-A(41)-A(49)-A(70)-A(74)-A(87)-A(94)
  Vdot(31) = A(40)+A(41)-A(42)-A(43)-A(44)-2*A(45)+A(46)+A(47)+A(48)+A(49)-A(58)-A(62)-A(66)+A(85)+0.2*A(91)
  Vdot(32) = 2*A(12)-A(14)-A(16)-A(17)-A(18)-A(19)+A(20)-A(23)+A(24)-A(28)-A(32)-A(37)-A(40)-A(47)-A(48)-A(50)-A(51)&
               &-A(52)-A(53)-A(54)-A(67)-A(71)+BGS(14)*A(72)-A(83)-A(84)-A(85)-A(86)-A(91)+0.1*A(92)-A(95)-0.5*A(96)
  Vdot(33) = A(39)+A(42)+1.5*A(47)+A(50)+A(51)+A(52)+BGS(5)*A(53)-A(63)-A(64)-A(65)-A(66)+A(67)+A(69)+A(71)+BGS(12)&
               &*A(72)+BGS(21)*A(73)+0.84*A(83)+0.83*A(84)+0.85*A(86)+0.5*A(96)
  Vdot(34) = BGS(6)*A(53)+1.39*A(54)-A(59)-A(60)-A(61)-A(62)+A(70)+A(74)+0.9*A(91)+0.5*A(93)+A(94)
  Vdot(35) = BGS(4)*A(53)-A(55)-A(56)-A(57)-A(58)+0.15*A(86)+0.1*A(91)
  Vdot(36) = A(18)+A(19)-A(20)-A(21)+A(22)-A(24)-2*A(25)-2*A(26)-2*A(27)+A(28)-A(29)-A(30)-A(31)+A(32)+A(37)+A(38)-A(39)&
               &-A(44)+2*A(45)-A(56)+0.5*A(57)+A(58)-A(60)+A(62)+A(63)-A(64)+0.5*A(65)+A(66)+0.12*A(68)+A(69)+BGS(13)*A(72)&
               &+BGS(2)*A(73)+0.16*A(83)+0.17*A(84)-A(89)+0.7*A(91)+0.4*A(92)+0.6*A(93)-A(95)
  Vdot(37) = -A(47)+0.5*A(52)+BGS(3)*A(53)+0.14*A(54)+A(56)+A(57)+A(58)+BGS(17)*A(73)
  Vdot(38) = -A(37)-A(38)-A(39)+A(42)+A(44)+2*A(45)+0.5*A(47)+A(50)+BGS(1)*A(53)+0.16*A(54)+A(58)+A(62)+A(66)+1.56*A(67)&
               &+A(68)+A(69)+2*A(70)+BGS(8)*A(71)+BGS(1)*A(72)+BGS(18)*A(73)+BGS(8)*A(74)+A(75)-A(79)-A(80)+0.11*A(83)&
               &+BGS(24)*A(84)+A(91)+A(92)+A(94)
  Vdot(39) = A(2)-A(4)-A(6)-2*A(7)+A(11)-A(14)-A(20)-A(42)-A(55)-A(59)-A(63)
  Vdot(40) = -A(2)-A(3)+A(4)-A(5)+2*A(6)+2*A(7)-A(8)+A(9)-2*A(15)-A(16)+A(20)-A(21)+A(22)+A(23)+A(42)-A(43)+A(46)+A(54)&
               &+A(59)+A(63)+A(70)+A(74)-A(88)+A(94)

  RETURN
END SUBROUTINE Fun_night

SUBROUTINE Jac_SP_night ( V, F, RCT, BGS, JVS, NVAR, NFIX, NREACT, nprcf, LU_NONZERO )
  IMPLICIT NONE
  integer(kind=4), intent(in) :: NVAR, NFIX, NREACT, nprcf, LU_NONZERO
! V - Concentrations of variable species (local)
  REAL(kind=8), intent(in) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=8), intent(in) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=8), intent(in) :: RCT(NREACT)
! BGS - Fractional product yields for some reactions (local)
  REAL(kind=8), intent(in) :: BGS(nprcf)
! JVS - sparse Jacobian of variables
  REAL(kind=8), intent(out) :: JVS(LU_NONZERO)
! Local variables
! B - Temporary array
  REAL(kind=8) :: B(188)

! B(1) = dA(1)/dV(27)
  B(1) = RCT(1)*F(4)*F(5)
! B(4) = dA(2)/dV(27)
  B(4) = RCT(2)*V(40)
! B(5) = dA(2)/dV(40)
  B(5) = RCT(2)*V(27)
! B(6) = dA(3)/dV(27)
  B(6) = RCT(3)*V(40)
! B(7) = dA(3)/dV(40)
  B(7) = RCT(3)*V(27)
! B(8) = dA(4)/dV(28)
  B(8) = RCT(4)*V(39)
! B(9) = dA(4)/dV(39)
  B(9) = RCT(4)*V(28)
! B(10) = dA(5)/dV(28)
  B(10) = RCT(5)*V(40)
! B(11) = dA(5)/dV(40)
  B(11) = RCT(5)*V(28)
! B(12) = dA(6)/dV(30)
  B(12) = RCT(6)*V(39)
! B(13) = dA(6)/dV(39)
  B(13) = RCT(6)*V(30)
! B(14) = dA(7)/dV(39)
  B(14) = RCT(7)*2*V(39)*F(4)
! B(16) = dA(8)/dV(30)
  B(16) = RCT(8)*V(40)
! B(17) = dA(8)/dV(40)
  B(17) = RCT(8)*V(30)
! B(18) = dA(9)/dV(8)
  B(18) = RCT(9)
! B(19) = dA(10)/dV(8)
  B(19) = RCT(10)*F(3)
! B(21) = dA(11)/dV(30)
  B(21) = RCT(11)*V(40)
! B(22) = dA(11)/dV(40)
  B(22) = RCT(11)*V(30)
! B(23) = dA(12)/dV(1)
  B(23) = RCT(12)*F(3)
! B(25) = dA(13)/dV(1)
  B(25) = RCT(13)*F(5)
! B(27) = dA(14)/dV(32)
  B(27) = RCT(14)*V(39)
! B(28) = dA(14)/dV(39)
  B(28) = RCT(14)*V(32)
! B(29) = dA(15)/dV(40)
  B(29) = RCT(15)*F(3)
! B(31) = dA(16)/dV(32)
  B(31) = RCT(16)*V(40)
! B(32) = dA(16)/dV(40)
  B(32) = RCT(16)*V(32)
! B(33) = dA(17)/dV(15)
  B(33) = RCT(17)*V(32)
! B(34) = dA(17)/dV(32)
  B(34) = RCT(17)*V(15)
! B(35) = dA(18)/dV(14)
  B(35) = RCT(18)*V(32)
! B(36) = dA(18)/dV(32)
  B(36) = RCT(18)*V(14)
! B(37) = dA(19)/dV(28)
  B(37) = RCT(19)*V(32)
! B(38) = dA(19)/dV(32)
  B(38) = RCT(19)*V(28)
! B(39) = dA(20)/dV(36)
  B(39) = RCT(20)*V(39)
! B(40) = dA(20)/dV(39)
  B(40) = RCT(20)*V(36)
! B(41) = dA(21)/dV(36)
  B(41) = RCT(21)*V(40)
! B(42) = dA(21)/dV(40)
  B(42) = RCT(21)*V(36)
! B(43) = dA(22)/dV(12)
  B(43) = RCT(22)
! B(44) = dA(23)/dV(12)
  B(44) = RCT(23)*V(32)
! B(45) = dA(23)/dV(32)
  B(45) = RCT(23)*V(12)
! B(46) = dA(24)/dV(28)
  B(46) = RCT(24)*V(36)
! B(47) = dA(24)/dV(36)
  B(47) = RCT(24)*V(28)
! B(48) = dA(25)/dV(36)
  B(48) = RCT(25)*2*V(36)
! B(49) = dA(26)/dV(36)
  B(49) = RCT(26)*2*V(36)*F(5)
! B(51) = dA(27)/dV(36)
  B(51) = RCT(27)*2*V(36)*F(3)
! B(53) = dA(28)/dV(4)
  B(53) = RCT(28)*V(32)
! B(54) = dA(28)/dV(32)
  B(54) = RCT(28)*V(4)
! B(55) = dA(29)/dV(30)
  B(55) = RCT(29)*V(36)
! B(56) = dA(29)/dV(36)
  B(56) = RCT(29)*V(30)
! B(57) = dA(30)/dV(30)
  B(57) = RCT(30)*V(36)*F(5)
! B(58) = dA(30)/dV(36)
  B(58) = RCT(30)*V(30)*F(5)
! B(60) = dA(31)/dV(30)
  B(60) = RCT(31)*V(36)*F(3)
! B(61) = dA(31)/dV(36)
  B(61) = RCT(31)*V(30)*F(3)
! B(63) = dA(32)/dV(19)
  B(63) = RCT(32)*V(32)
! B(64) = dA(32)/dV(32)
  B(64) = RCT(32)*V(19)
! B(65) = dA(33)/dV(29)
  B(65) = RCT(33)*V(39)
! B(66) = dA(33)/dV(39)
  B(66) = RCT(33)*V(29)
! B(67) = dA(34)/dV(29)
  B(67) = RCT(34)*V(36)
! B(68) = dA(34)/dV(36)
  B(68) = RCT(34)*V(29)
! B(69) = dA(35)/dV(29)
  B(69) = RCT(35)*2*V(29)
! B(70) = dA(36)/dV(29)
  B(70) = RCT(36)*V(31)
! B(71) = dA(36)/dV(31)
  B(71) = RCT(36)*V(29)
! B(72) = dA(37)/dV(32)
  B(72) = RCT(37)*V(38)
! B(73) = dA(37)/dV(38)
  B(73) = RCT(37)*V(32)
! B(74) = dA(38)/dV(30)
  B(74) = RCT(38)*V(38)
! B(75) = dA(38)/dV(38)
  B(75) = RCT(38)*V(30)
! B(76) = dA(39)/dV(36)
  B(76) = RCT(39)*V(38)
! B(77) = dA(39)/dV(38)
  B(77) = RCT(39)*V(36)
! B(78) = dA(40)/dV(26)
  B(78) = RCT(40)*V(32)
! B(79) = dA(40)/dV(32)
  B(79) = RCT(40)*V(26)
! B(80) = dA(41)/dV(26)
  B(80) = RCT(41)*V(30)
! B(81) = dA(41)/dV(30)
  B(81) = RCT(41)*V(26)
! B(82) = dA(42)/dV(31)
  B(82) = RCT(42)*V(39)
! B(83) = dA(42)/dV(39)
  B(83) = RCT(42)*V(31)
! B(84) = dA(43)/dV(31)
  B(84) = RCT(43)*V(40)
! B(85) = dA(43)/dV(40)
  B(85) = RCT(43)*V(31)
! B(86) = dA(44)/dV(31)
  B(86) = RCT(44)*V(36)
! B(87) = dA(44)/dV(36)
  B(87) = RCT(44)*V(31)
! B(88) = dA(45)/dV(31)
  B(88) = RCT(45)*2*V(31)
! B(89) = dA(46)/dV(5)
  B(89) = RCT(46)
! B(90) = dA(47)/dV(32)
  B(90) = RCT(47)*V(37)
! B(91) = dA(47)/dV(37)
  B(91) = RCT(47)*V(32)
! B(92) = dA(48)/dV(18)
  B(92) = RCT(48)*V(32)
! B(93) = dA(48)/dV(32)
  B(93) = RCT(48)*V(18)
! B(94) = dA(49)/dV(18)
  B(94) = RCT(49)*V(30)
! B(95) = dA(49)/dV(30)
  B(95) = RCT(49)*V(18)
! B(96) = dA(50)/dV(32)
  B(96) = RCT(50)*F(1)
! B(98) = dA(51)/dV(32)
  B(98) = RCT(51)*F(2)
! B(100) = dA(52)/dV(6)
  B(100) = RCT(52)*V(32)
! B(101) = dA(52)/dV(32)
  B(101) = RCT(52)*V(6)
! B(102) = dA(53)/dV(9)
  B(102) = RCT(53)*V(32)
! B(103) = dA(53)/dV(32)
  B(103) = RCT(53)*V(9)
! B(104) = dA(54)/dV(22)
  B(104) = RCT(54)*V(32)
! B(105) = dA(54)/dV(32)
  B(105) = RCT(54)*V(22)
! B(106) = dA(55)/dV(35)
  B(106) = RCT(55)*V(39)
! B(107) = dA(55)/dV(39)
  B(107) = RCT(55)*V(35)
! B(108) = dA(56)/dV(35)
  B(108) = RCT(56)*V(36)
! B(109) = dA(56)/dV(36)
  B(109) = RCT(56)*V(35)
! B(110) = dA(57)/dV(29)
  B(110) = RCT(57)*V(35)
! B(111) = dA(57)/dV(35)
  B(111) = RCT(57)*V(29)
! B(112) = dA(58)/dV(31)
  B(112) = RCT(58)*V(35)
! B(113) = dA(58)/dV(35)
  B(113) = RCT(58)*V(31)
! B(114) = dA(59)/dV(34)
  B(114) = RCT(59)*V(39)
! B(115) = dA(59)/dV(39)
  B(115) = RCT(59)*V(34)
! B(116) = dA(60)/dV(34)
  B(116) = RCT(60)*V(36)
! B(117) = dA(60)/dV(36)
  B(117) = RCT(60)*V(34)
! B(118) = dA(61)/dV(29)
  B(118) = RCT(61)*V(34)
! B(119) = dA(61)/dV(34)
  B(119) = RCT(61)*V(29)
! B(120) = dA(62)/dV(31)
  B(120) = RCT(62)*V(34)
! B(121) = dA(62)/dV(34)
  B(121) = RCT(62)*V(31)
! B(122) = dA(63)/dV(33)
  B(122) = RCT(63)*V(39)
! B(123) = dA(63)/dV(39)
  B(123) = RCT(63)*V(33)
! B(124) = dA(64)/dV(33)
  B(124) = RCT(64)*V(36)
! B(125) = dA(64)/dV(36)
  B(125) = RCT(64)*V(33)
! B(126) = dA(65)/dV(29)
  B(126) = RCT(65)*V(33)
! B(127) = dA(65)/dV(33)
  B(127) = RCT(65)*V(29)
! B(128) = dA(66)/dV(31)
  B(128) = RCT(66)*V(33)
! B(129) = dA(66)/dV(33)
  B(129) = RCT(66)*V(31)
! B(130) = dA(67)/dV(25)
  B(130) = RCT(67)*V(32)
! B(131) = dA(67)/dV(32)
  B(131) = RCT(67)*V(25)
! B(132) = dA(68)/dV(25)
  B(132) = RCT(68)*V(28)
! B(133) = dA(68)/dV(28)
  B(133) = RCT(68)*V(25)
! B(134) = dA(69)/dV(25)
  B(134) = RCT(69)*V(27)
! B(135) = dA(69)/dV(27)
  B(135) = RCT(69)*V(25)
! B(136) = dA(70)/dV(25)
  B(136) = RCT(70)*V(30)
! B(137) = dA(70)/dV(30)
  B(137) = RCT(70)*V(25)
! B(138) = dA(71)/dV(23)
  B(138) = RCT(71)*V(32)
! B(139) = dA(71)/dV(32)
  B(139) = RCT(71)*V(23)
! B(140) = dA(72)/dV(23)
  B(140) = RCT(72)*V(28)
! B(141) = dA(72)/dV(28)
  B(141) = RCT(72)*V(23)
! B(142) = dA(73)/dV(23)
  B(142) = RCT(73)*V(27)
! B(143) = dA(73)/dV(27)
  B(143) = RCT(73)*V(23)
! B(144) = dA(74)/dV(23)
  B(144) = RCT(74)*V(30)
! B(145) = dA(74)/dV(30)
  B(145) = RCT(74)*V(23)
! B(146) = dA(75)/dV(19)
  B(146) = RCT(75)*V(20)
! B(147) = dA(75)/dV(20)
  B(147) = RCT(75)*V(19)
! B(148) = dA(76)/dV(19)
  B(148) = RCT(76)*V(21)
! B(149) = dA(76)/dV(21)
  B(149) = RCT(76)*V(19)
! B(150) = dA(77)/dV(20)
  B(150) = RCT(77)*F(3)
! B(152) = dA(78)/dV(21)
  B(152) = RCT(78)*F(3)
! B(154) = dA(79)/dV(20)
  B(154) = RCT(79)*V(38)
! B(155) = dA(79)/dV(38)
  B(155) = RCT(79)*V(20)
! B(156) = dA(80)/dV(21)
  B(156) = RCT(80)*V(38)
! B(157) = dA(80)/dV(38)
  B(157) = RCT(80)*V(21)
! B(158) = dA(81)/dV(20)
  B(158) = RCT(81)*V(26)
! B(159) = dA(81)/dV(26)
  B(159) = RCT(81)*V(20)
! B(160) = dA(82)/dV(21)
  B(160) = RCT(82)*V(26)
! B(161) = dA(82)/dV(26)
  B(161) = RCT(82)*V(21)
! B(162) = dA(83)/dV(10)
  B(162) = RCT(83)*V(32)
! B(163) = dA(83)/dV(32)
  B(163) = RCT(83)*V(10)
! B(164) = dA(84)/dV(11)
  B(164) = RCT(84)*V(32)
! B(165) = dA(84)/dV(32)
  B(165) = RCT(84)*V(11)
! B(166) = dA(85)/dV(7)
  B(166) = RCT(85)*V(32)
! B(167) = dA(85)/dV(32)
  B(167) = RCT(85)*V(7)
! B(168) = dA(86)/dV(17)
  B(168) = RCT(86)*V(32)
! B(169) = dA(86)/dV(32)
  B(169) = RCT(86)*V(17)
! B(170) = dA(87)/dV(17)
  B(170) = RCT(87)*V(30)
! B(171) = dA(87)/dV(30)
  B(171) = RCT(87)*V(17)
! B(172) = dA(88)/dV(13)
  B(172) = RCT(88)*V(40)
! B(173) = dA(88)/dV(40)
  B(173) = RCT(88)*V(13)
! B(174) = dA(89)/dV(13)
  B(174) = RCT(89)*V(36)
! B(175) = dA(89)/dV(36)
  B(175) = RCT(89)*V(13)
! B(176) = dA(90)/dV(13)
  B(176) = RCT(90)
! B(177) = dA(91)/dV(24)
  B(177) = RCT(91)*V(32)
! B(178) = dA(91)/dV(32)
  B(178) = RCT(91)*V(24)
! B(179) = dA(92)/dV(24)
  B(179) = RCT(92)*V(28)
! B(180) = dA(92)/dV(28)
  B(180) = RCT(92)*V(24)
! B(181) = dA(93)/dV(24)
  B(181) = RCT(93)*V(27)
! B(182) = dA(93)/dV(27)
  B(182) = RCT(93)*V(24)
! B(183) = dA(94)/dV(24)
  B(183) = RCT(94)*V(30)
! B(184) = dA(94)/dV(30)
  B(184) = RCT(94)*V(24)
! B(185) = dA(95)/dV(32)
  B(185) = RCT(95)*V(36)
! B(186) = dA(95)/dV(36)
  B(186) = RCT(95)*V(32)
! B(187) = dA(96)/dV(16)
  B(187) = RCT(96)*V(32)
! B(188) = dA(96)/dV(32)
  B(188) = RCT(96)*V(16)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = -B(23)-B(25)
! JVS(2) = Jac_FULL(2,2)
  JVS(2) = 0
! JVS(3) = Jac_FULL(2,19)
  JVS(3) = B(63)+B(146)+B(148)
! JVS(4) = Jac_FULL(2,20)
  JVS(4) = B(147)
! JVS(5) = Jac_FULL(2,21)
  JVS(5) = B(149)
! JVS(6) = Jac_FULL(2,32)
  JVS(6) = B(64)
! JVS(7) = Jac_FULL(3,3)
  JVS(7) = 0
! JVS(8) = Jac_FULL(3,32)
  JVS(8) = B(27)
! JVS(9) = Jac_FULL(3,39)
  JVS(9) = B(28)
! JVS(10) = Jac_FULL(3,40)
  JVS(10) = B(29)
! JVS(11) = Jac_FULL(4,4)
  JVS(11) = -B(53)
! JVS(12) = Jac_FULL(4,32)
  JVS(12) = -B(54)
! JVS(13) = Jac_FULL(4,36)
  JVS(13) = B(48)+B(49)+B(51)
! JVS(14) = Jac_FULL(5,5)
  JVS(14) = -B(89)
! JVS(15) = Jac_FULL(5,31)
  JVS(15) = B(84)
! JVS(16) = Jac_FULL(5,40)
  JVS(16) = B(85)
! JVS(17) = Jac_FULL(6,6)
  JVS(17) = -B(100)
! JVS(18) = Jac_FULL(6,32)
  JVS(18) = -B(101)
! JVS(19) = Jac_FULL(7,7)
  JVS(19) = -B(166)
! JVS(20) = Jac_FULL(7,10)
  JVS(20) = 0.4*B(162)
! JVS(21) = Jac_FULL(7,11)
  JVS(21) = BGS(22)*B(164)
! JVS(22) = Jac_FULL(7,32)
  JVS(22) = 0.4*B(163)+BGS(22)*B(165)-B(167)
! JVS(23) = Jac_FULL(8,8)
  JVS(23) = -B(18)-B(19)
! JVS(24) = Jac_FULL(8,30)
  JVS(24) = B(16)
! JVS(25) = Jac_FULL(8,40)
  JVS(25) = B(17)
! JVS(26) = Jac_FULL(9,9)
  JVS(26) = -B(102)
! JVS(27) = Jac_FULL(9,32)
  JVS(27) = -B(103)
! JVS(28) = Jac_FULL(10,10)
  JVS(28) = -B(162)
! JVS(29) = Jac_FULL(10,32)
  JVS(29) = -B(163)
! JVS(30) = Jac_FULL(11,11)
  JVS(30) = -B(164)
! JVS(31) = Jac_FULL(11,32)
  JVS(31) = -B(165)
! JVS(32) = Jac_FULL(12,12)
  JVS(32) = -B(43)-B(44)
! JVS(33) = Jac_FULL(12,32)
  JVS(33) = -B(45)
! JVS(34) = Jac_FULL(12,36)
  JVS(34) = B(41)
! JVS(35) = Jac_FULL(12,40)
  JVS(35) = B(42)
! JVS(36) = Jac_FULL(13,13)
  JVS(36) = -B(172)-B(174)-B(176)
! JVS(37) = Jac_FULL(13,17)
  JVS(37) = B(170)
! JVS(38) = Jac_FULL(13,30)
  JVS(38) = B(171)
! JVS(39) = Jac_FULL(13,36)
  JVS(39) = -B(175)
! JVS(40) = Jac_FULL(13,40)
  JVS(40) = -B(173)
! JVS(41) = Jac_FULL(14,10)
  JVS(41) = 0.11*B(162)
! JVS(42) = Jac_FULL(14,11)
  JVS(42) = BGS(24)*B(164)
! JVS(43) = Jac_FULL(14,14)
  JVS(43) = -B(35)
! JVS(44) = Jac_FULL(14,18)
  JVS(44) = B(92)+B(94)
! JVS(45) = Jac_FULL(14,23)
  JVS(45) = BGS(15)*B(140)+BGS(16)*B(142)
! JVS(46) = Jac_FULL(14,25)
  JVS(46) = 0.42*B(132)+B(134)
! JVS(47) = Jac_FULL(14,27)
  JVS(47) = B(135)+BGS(16)*B(143)
! JVS(48) = Jac_FULL(14,28)
  JVS(48) = 0.42*B(133)+BGS(15)*B(141)
! JVS(49) = Jac_FULL(14,30)
  JVS(49) = B(74)+B(95)
! JVS(50) = Jac_FULL(14,32)
  JVS(50) = -B(36)+B(72)+B(93)+0.11*B(163)+BGS(24)*B(165)
! JVS(51) = Jac_FULL(14,38)
  JVS(51) = B(73)+B(75)
! JVS(52) = Jac_FULL(15,8)
  JVS(52) = 2*B(19)
! JVS(53) = Jac_FULL(15,15)
  JVS(53) = -B(33)
! JVS(54) = Jac_FULL(15,17)
  JVS(54) = B(170)
! JVS(55) = Jac_FULL(15,18)
  JVS(55) = B(94)
! JVS(56) = Jac_FULL(15,26)
  JVS(56) = B(80)
! JVS(57) = Jac_FULL(15,30)
  JVS(57) = B(55)+B(57)+B(60)+B(74)+B(81)+B(95)+B(171)
! JVS(58) = Jac_FULL(15,32)
  JVS(58) = B(31)-B(34)
! JVS(59) = Jac_FULL(15,36)
  JVS(59) = B(56)+B(58)+B(61)
! JVS(60) = Jac_FULL(15,38)
  JVS(60) = B(75)
! JVS(61) = Jac_FULL(15,40)
  JVS(61) = B(29)+B(32)
! JVS(62) = Jac_FULL(16,16)
  JVS(62) = -B(187)
! JVS(63) = Jac_FULL(16,31)
  JVS(63) = B(86)
! JVS(64) = Jac_FULL(16,32)
  JVS(64) = -B(188)
! JVS(65) = Jac_FULL(16,33)
  JVS(65) = B(124)
! JVS(66) = Jac_FULL(16,34)
  JVS(66) = B(116)
! JVS(67) = Jac_FULL(16,35)
  JVS(67) = B(108)
! JVS(68) = Jac_FULL(16,36)
  JVS(68) = B(87)+B(109)+B(117)+B(125)
! JVS(69) = Jac_FULL(17,10)
  JVS(69) = 0.16*B(162)
! JVS(70) = Jac_FULL(17,11)
  JVS(70) = 0.17*B(164)
! JVS(71) = Jac_FULL(17,17)
  JVS(71) = -0.92*B(168)-0.5*B(170)
! JVS(72) = Jac_FULL(17,30)
  JVS(72) = -0.5*B(171)
! JVS(73) = Jac_FULL(17,32)
  JVS(73) = 0.16*B(163)+0.17*B(165)-0.92*B(169)
! JVS(74) = Jac_FULL(18,10)
  JVS(74) = 0.13*B(162)
! JVS(75) = Jac_FULL(18,11)
  JVS(75) = BGS(23)*B(164)
! JVS(76) = Jac_FULL(18,17)
  JVS(76) = 0.2*B(168)
! JVS(77) = Jac_FULL(18,18)
  JVS(77) = -B(92)-B(94)
! JVS(78) = Jac_FULL(18,24)
  JVS(78) = 0.27*B(177)+0.2*B(179)
! JVS(79) = Jac_FULL(18,28)
  JVS(79) = 0.2*B(180)
! JVS(80) = Jac_FULL(18,30)
  JVS(80) = -B(95)
! JVS(81) = Jac_FULL(18,32)
  JVS(81) = -B(93)+0.13*B(163)+BGS(23)*B(165)+0.2*B(169)+0.27*B(178)
! JVS(82) = Jac_FULL(19,19)
  JVS(82) = -B(63)-B(146)-B(148)
! JVS(83) = Jac_FULL(19,20)
  JVS(83) = -B(147)
! JVS(84) = Jac_FULL(19,21)
  JVS(84) = -B(149)
! JVS(85) = Jac_FULL(19,32)
  JVS(85) = -B(64)
! JVS(86) = Jac_FULL(20,19)
  JVS(86) = -B(146)
! JVS(87) = Jac_FULL(20,20)
  JVS(87) = -B(147)-B(150)-B(154)-B(158)
! JVS(88) = Jac_FULL(20,21)
  JVS(88) = 0
! JVS(89) = Jac_FULL(20,23)
  JVS(89) = BGS(25)*B(140)
! JVS(90) = Jac_FULL(20,25)
  JVS(90) = 0.4*B(132)
! JVS(91) = Jac_FULL(20,26)
  JVS(91) = -B(159)
! JVS(92) = Jac_FULL(20,28)
  JVS(92) = 0.4*B(133)+BGS(25)*B(141)
! JVS(93) = Jac_FULL(20,32)
  JVS(93) = 0
! JVS(94) = Jac_FULL(20,38)
  JVS(94) = -B(155)
! JVS(95) = Jac_FULL(21,19)
  JVS(95) = -B(148)
! JVS(96) = Jac_FULL(21,20)
  JVS(96) = 0
! JVS(97) = Jac_FULL(21,21)
  JVS(97) = -B(149)-B(152)-B(156)-B(160)
! JVS(98) = Jac_FULL(21,23)
  JVS(98) = BGS(26)*B(140)
! JVS(99) = Jac_FULL(21,24)
  JVS(99) = 0.2*B(179)
! JVS(100) = Jac_FULL(21,25)
  JVS(100) = 0
! JVS(101) = Jac_FULL(21,26)
  JVS(101) = -B(161)
! JVS(102) = Jac_FULL(21,28)
  JVS(102) = BGS(26)*B(141)+0.2*B(180)
! JVS(103) = Jac_FULL(21,32)
  JVS(103) = 0
! JVS(104) = Jac_FULL(21,38)
  JVS(104) = -B(157)
! JVS(105) = Jac_FULL(22,13)
  JVS(105) = B(172)
! JVS(106) = Jac_FULL(22,17)
  JVS(106) = 0
! JVS(107) = Jac_FULL(22,22)
  JVS(107) = -B(104)
! JVS(108) = Jac_FULL(22,30)
  JVS(108) = 0
! JVS(109) = Jac_FULL(22,32)
  JVS(109) = -B(105)
! JVS(110) = Jac_FULL(22,35)
  JVS(110) = B(106)
! JVS(111) = Jac_FULL(22,36)
  JVS(111) = 0
! JVS(112) = Jac_FULL(22,39)
  JVS(112) = B(107)
! JVS(113) = Jac_FULL(22,40)
  JVS(113) = B(173)
! JVS(114) = Jac_FULL(23,23)
  JVS(114) = -B(138)-B(140)-B(142)-B(144)
! JVS(115) = Jac_FULL(23,27)
  JVS(115) = -B(143)
! JVS(116) = Jac_FULL(23,28)
  JVS(116) = -B(141)
! JVS(117) = Jac_FULL(23,30)
  JVS(117) = -B(145)
! JVS(118) = Jac_FULL(23,32)
  JVS(118) = -B(139)
! JVS(119) = Jac_FULL(24,24)
  JVS(119) = -B(177)-B(179)-B(181)-B(183)
! JVS(120) = Jac_FULL(24,27)
  JVS(120) = -B(182)
! JVS(121) = Jac_FULL(24,28)
  JVS(121) = -B(180)
! JVS(122) = Jac_FULL(24,30)
  JVS(122) = -B(184)
! JVS(123) = Jac_FULL(24,32)
  JVS(123) = -B(178)
! JVS(124) = Jac_FULL(25,24)
  JVS(124) = B(177)+0.5*B(179)+B(181)
! JVS(125) = Jac_FULL(25,25)
  JVS(125) = -B(130)-B(132)-B(134)-B(136)
! JVS(126) = Jac_FULL(25,27)
  JVS(126) = -B(135)+B(182)
! JVS(127) = Jac_FULL(25,28)
  JVS(127) = -B(133)+0.5*B(180)
! JVS(128) = Jac_FULL(25,30)
  JVS(128) = -B(137)
! JVS(129) = Jac_FULL(25,32)
  JVS(129) = -B(131)+B(178)
! JVS(130) = Jac_FULL(26,6)
  JVS(130) = 0.3*B(100)
! JVS(131) = Jac_FULL(26,9)
  JVS(131) = BGS(2)*B(102)
! JVS(132) = Jac_FULL(26,19)
  JVS(132) = B(148)
! JVS(133) = Jac_FULL(26,20)
  JVS(133) = -B(158)
! JVS(134) = Jac_FULL(26,21)
  JVS(134) = B(149)-B(160)
! JVS(135) = Jac_FULL(26,22)
  JVS(135) = 1.52*B(104)
! JVS(136) = Jac_FULL(26,23)
  JVS(136) = BGS(9)*B(138)+BGS(11)*B(140)+BGS(19)*B(142)+BGS(9)*B(144)
! JVS(137) = Jac_FULL(26,24)
  JVS(137) = 0.2*B(177)+0.4*B(179)+B(181)+B(183)
! JVS(138) = Jac_FULL(26,25)
  JVS(138) = 0.22*B(130)
! JVS(139) = Jac_FULL(26,26)
  JVS(139) = -B(78)-B(80)-B(159)-B(161)
! JVS(140) = Jac_FULL(26,27)
  JVS(140) = BGS(19)*B(143)+B(182)
! JVS(141) = Jac_FULL(26,28)
  JVS(141) = BGS(11)*B(141)+0.4*B(180)
! JVS(142) = Jac_FULL(26,30)
  JVS(142) = -B(81)+BGS(9)*B(145)+B(184)
! JVS(143) = Jac_FULL(26,32)
  JVS(143) = -B(79)+0.5*B(90)+B(98)+0.3*B(101)+BGS(2)*B(103)+1.52*B(105)+0.22*B(131)+BGS(9)*B(139)+0.2*B(178)
! JVS(144) = Jac_FULL(26,35)
  JVS(144) = 0
! JVS(145) = Jac_FULL(26,36)
  JVS(145) = 0
! JVS(146) = Jac_FULL(26,37)
  JVS(146) = 0.5*B(91)
! JVS(147) = Jac_FULL(26,38)
  JVS(147) = 0
! JVS(148) = Jac_FULL(26,39)
  JVS(148) = 0
! JVS(149) = Jac_FULL(26,40)
  JVS(149) = 0
! JVS(150) = Jac_FULL(27,1)
  JVS(150) = B(25)
! JVS(151) = Jac_FULL(27,23)
  JVS(151) = -B(142)
! JVS(152) = Jac_FULL(27,24)
  JVS(152) = -B(181)
! JVS(153) = Jac_FULL(27,25)
  JVS(153) = -B(134)
! JVS(154) = Jac_FULL(27,27)
  JVS(154) = -B(1)-B(4)-B(6)-B(135)-B(143)-B(182)
! JVS(155) = Jac_FULL(27,28)
  JVS(155) = 0
! JVS(156) = Jac_FULL(27,30)
  JVS(156) = 0
! JVS(157) = Jac_FULL(27,32)
  JVS(157) = 0
! JVS(158) = Jac_FULL(27,40)
  JVS(158) = -B(5)-B(7)
! JVS(159) = Jac_FULL(28,23)
  JVS(159) = -B(140)
! JVS(160) = Jac_FULL(28,24)
  JVS(160) = -B(179)
! JVS(161) = Jac_FULL(28,25)
  JVS(161) = -B(132)
! JVS(162) = Jac_FULL(28,27)
  JVS(162) = B(1)
! JVS(163) = Jac_FULL(28,28)
  JVS(163) = -B(8)-B(10)-B(37)-B(46)-B(133)-B(141)-B(180)
! JVS(164) = Jac_FULL(28,30)
  JVS(164) = 0
! JVS(165) = Jac_FULL(28,32)
  JVS(165) = -B(38)
! JVS(166) = Jac_FULL(28,36)
  JVS(166) = -B(47)
! JVS(167) = Jac_FULL(28,39)
  JVS(167) = -B(9)
! JVS(168) = Jac_FULL(28,40)
  JVS(168) = -B(11)
! JVS(169) = Jac_FULL(29,6)
  JVS(169) = B(100)
! JVS(170) = Jac_FULL(29,9)
  JVS(170) = BGS(7)*B(102)
! JVS(171) = Jac_FULL(29,10)
  JVS(171) = 0.84*B(162)
! JVS(172) = Jac_FULL(29,11)
  JVS(172) = 0.83*B(164)
! JVS(173) = Jac_FULL(29,16)
  JVS(173) = 0.5*B(187)
! JVS(174) = Jac_FULL(29,17)
  JVS(174) = B(168)
! JVS(175) = Jac_FULL(29,22)
  JVS(175) = 1.39*B(104)
! JVS(176) = Jac_FULL(29,23)
  JVS(176) = B(138)+BGS(12)*B(140)+BGS(21)*B(142)+B(144)
! JVS(177) = Jac_FULL(29,24)
  JVS(177) = B(177)+0.5*B(181)+B(183)
! JVS(178) = Jac_FULL(29,25)
  JVS(178) = B(130)+B(134)+B(136)
! JVS(179) = Jac_FULL(29,27)
  JVS(179) = B(135)+BGS(21)*B(143)+0.5*B(182)
! JVS(180) = Jac_FULL(29,28)
  JVS(180) = BGS(12)*B(141)
! JVS(181) = Jac_FULL(29,29)
  JVS(181) = -B(65)-B(67)-2*B(69)-B(70)
! JVS(182) = Jac_FULL(29,30)
  JVS(182) = B(137)+B(145)+B(184)
! JVS(183) = Jac_FULL(29,31)
  JVS(183) = -B(71)+B(82)
! JVS(184) = Jac_FULL(29,32)
  JVS(184) = 1.5*B(90)+B(96)+B(98)+B(101)+BGS(7)*B(103)+1.39*B(105)+B(131)+B(139)+0.84*B(163)+0.83*B(165)+B(169)+B(178)&
               &+0.5*B(188)
! JVS(185) = Jac_FULL(29,33)
  JVS(185) = 0
! JVS(186) = Jac_FULL(29,34)
  JVS(186) = 0
! JVS(187) = Jac_FULL(29,35)
  JVS(187) = 0
! JVS(188) = Jac_FULL(29,36)
  JVS(188) = -B(68)+B(76)
! JVS(189) = Jac_FULL(29,37)
  JVS(189) = 1.5*B(91)
! JVS(190) = Jac_FULL(29,38)
  JVS(190) = B(77)
! JVS(191) = Jac_FULL(29,39)
  JVS(191) = -B(66)+B(83)
! JVS(192) = Jac_FULL(29,40)
  JVS(192) = 0
! JVS(193) = Jac_FULL(30,8)
  JVS(193) = B(18)
! JVS(194) = Jac_FULL(30,15)
  JVS(194) = B(33)
! JVS(195) = Jac_FULL(30,17)
  JVS(195) = -B(170)
! JVS(196) = Jac_FULL(30,18)
  JVS(196) = -B(94)
! JVS(197) = Jac_FULL(30,23)
  JVS(197) = -B(144)
! JVS(198) = Jac_FULL(30,24)
  JVS(198) = -B(183)
! JVS(199) = Jac_FULL(30,25)
  JVS(199) = -B(136)
! JVS(200) = Jac_FULL(30,26)
  JVS(200) = -B(80)
! JVS(201) = Jac_FULL(30,27)
  JVS(201) = B(6)
! JVS(202) = Jac_FULL(30,28)
  JVS(202) = B(10)
! JVS(203) = Jac_FULL(30,30)
  JVS(203) = -B(12)-B(16)-B(21)-B(55)-B(57)-B(60)-B(74)-B(81)-B(95)-B(137)-B(145)-B(171)-B(184)
! JVS(204) = Jac_FULL(30,32)
  JVS(204) = B(34)
! JVS(205) = Jac_FULL(30,35)
  JVS(205) = 0
! JVS(206) = Jac_FULL(30,36)
  JVS(206) = -B(56)-B(58)-B(61)
! JVS(207) = Jac_FULL(30,37)
  JVS(207) = 0
! JVS(208) = Jac_FULL(30,38)
  JVS(208) = -B(75)
! JVS(209) = Jac_FULL(30,39)
  JVS(209) = -B(13)
! JVS(210) = Jac_FULL(30,40)
  JVS(210) = B(7)+B(11)-B(17)-B(22)
! JVS(211) = Jac_FULL(31,5)
  JVS(211) = B(89)
! JVS(212) = Jac_FULL(31,7)
  JVS(212) = B(166)
! JVS(213) = Jac_FULL(31,10)
  JVS(213) = 0
! JVS(214) = Jac_FULL(31,11)
  JVS(214) = 0
! JVS(215) = Jac_FULL(31,18)
  JVS(215) = B(92)+B(94)
! JVS(216) = Jac_FULL(31,24)
  JVS(216) = 0.2*B(177)
! JVS(217) = Jac_FULL(31,26)
  JVS(217) = B(78)+B(80)
! JVS(218) = Jac_FULL(31,27)
  JVS(218) = 0
! JVS(219) = Jac_FULL(31,28)
  JVS(219) = 0
! JVS(220) = Jac_FULL(31,30)
  JVS(220) = B(81)+B(95)
! JVS(221) = Jac_FULL(31,31)
  JVS(221) = -B(82)-B(84)-B(86)-2*B(88)-B(112)-B(120)-B(128)
! JVS(222) = Jac_FULL(31,32)
  JVS(222) = B(79)+B(90)+B(93)+B(167)+0.2*B(178)
! JVS(223) = Jac_FULL(31,33)
  JVS(223) = -B(129)
! JVS(224) = Jac_FULL(31,34)
  JVS(224) = -B(121)
! JVS(225) = Jac_FULL(31,35)
  JVS(225) = -B(113)
! JVS(226) = Jac_FULL(31,36)
  JVS(226) = -B(87)
! JVS(227) = Jac_FULL(31,37)
  JVS(227) = B(91)
! JVS(228) = Jac_FULL(31,38)
  JVS(228) = 0
! JVS(229) = Jac_FULL(31,39)
  JVS(229) = -B(83)
! JVS(230) = Jac_FULL(31,40)
  JVS(230) = -B(85)
! JVS(231) = Jac_FULL(32,1)
  JVS(231) = 2*B(23)
! JVS(232) = Jac_FULL(32,4)
  JVS(232) = -B(53)
! JVS(233) = Jac_FULL(32,6)
  JVS(233) = -B(100)
! JVS(234) = Jac_FULL(32,7)
  JVS(234) = -B(166)
! JVS(235) = Jac_FULL(32,9)
  JVS(235) = -B(102)
! JVS(236) = Jac_FULL(32,10)
  JVS(236) = -B(162)
! JVS(237) = Jac_FULL(32,11)
  JVS(237) = -B(164)
! JVS(238) = Jac_FULL(32,12)
  JVS(238) = -B(44)
! JVS(239) = Jac_FULL(32,14)
  JVS(239) = -B(35)
! JVS(240) = Jac_FULL(32,15)
  JVS(240) = -B(33)
! JVS(241) = Jac_FULL(32,16)
  JVS(241) = -0.5*B(187)
! JVS(242) = Jac_FULL(32,17)
  JVS(242) = -B(168)
! JVS(243) = Jac_FULL(32,18)
  JVS(243) = -B(92)
! JVS(244) = Jac_FULL(32,19)
  JVS(244) = -B(63)
! JVS(245) = Jac_FULL(32,20)
  JVS(245) = 0
! JVS(246) = Jac_FULL(32,21)
  JVS(246) = 0
! JVS(247) = Jac_FULL(32,22)
  JVS(247) = -B(104)
! JVS(248) = Jac_FULL(32,23)
  JVS(248) = -B(138)+BGS(14)*B(140)
! JVS(249) = Jac_FULL(32,24)
  JVS(249) = -B(177)+0.1*B(179)
! JVS(250) = Jac_FULL(32,25)
  JVS(250) = -B(130)
! JVS(251) = Jac_FULL(32,26)
  JVS(251) = -B(78)
! JVS(252) = Jac_FULL(32,27)
  JVS(252) = 0
! JVS(253) = Jac_FULL(32,28)
  JVS(253) = -B(37)+B(46)+BGS(14)*B(141)+0.1*B(180)
! JVS(254) = Jac_FULL(32,30)
  JVS(254) = 0
! JVS(255) = Jac_FULL(32,31)
  JVS(255) = 0
! JVS(256) = Jac_FULL(32,32)
  JVS(256) = -B(27)-B(31)-B(34)-B(36)-B(38)-B(45)-B(54)-B(64)-B(72)-B(79)-B(90)-B(93)-B(96)-B(98)-B(101)-B(103)-B(105)&
               &-B(131)-B(139)-B(163)-B(165)-B(167)-B(169)-B(178)-B(185)-0.5*B(188)
! JVS(257) = Jac_FULL(32,33)
  JVS(257) = 0
! JVS(258) = Jac_FULL(32,34)
  JVS(258) = 0
! JVS(259) = Jac_FULL(32,35)
  JVS(259) = 0
! JVS(260) = Jac_FULL(32,36)
  JVS(260) = B(39)+B(47)-B(186)
! JVS(261) = Jac_FULL(32,37)
  JVS(261) = -B(91)
! JVS(262) = Jac_FULL(32,38)
  JVS(262) = -B(73)
! JVS(263) = Jac_FULL(32,39)
  JVS(263) = -B(28)+B(40)
! JVS(264) = Jac_FULL(32,40)
  JVS(264) = -B(32)
! JVS(265) = Jac_FULL(33,6)
  JVS(265) = B(100)
! JVS(266) = Jac_FULL(33,9)
  JVS(266) = BGS(5)*B(102)
! JVS(267) = Jac_FULL(33,10)
  JVS(267) = 0.84*B(162)
! JVS(268) = Jac_FULL(33,11)
  JVS(268) = 0.83*B(164)
! JVS(269) = Jac_FULL(33,16)
  JVS(269) = 0.5*B(187)
! JVS(270) = Jac_FULL(33,17)
  JVS(270) = 0.85*B(168)
! JVS(271) = Jac_FULL(33,23)
  JVS(271) = B(138)+BGS(12)*B(140)+BGS(21)*B(142)
! JVS(272) = Jac_FULL(33,25)
  JVS(272) = B(130)+B(134)
! JVS(273) = Jac_FULL(33,27)
  JVS(273) = B(135)+BGS(21)*B(143)
! JVS(274) = Jac_FULL(33,28)
  JVS(274) = BGS(12)*B(141)
! JVS(275) = Jac_FULL(33,29)
  JVS(275) = -B(126)
! JVS(276) = Jac_FULL(33,30)
  JVS(276) = 0
! JVS(277) = Jac_FULL(33,31)
  JVS(277) = B(82)-B(128)
! JVS(278) = Jac_FULL(33,32)
  JVS(278) = 1.5*B(90)+B(96)+B(98)+B(101)+BGS(5)*B(103)+B(131)+B(139)+0.84*B(163)+0.83*B(165)+0.85*B(169)+0.5*B(188)
! JVS(279) = Jac_FULL(33,33)
  JVS(279) = -B(122)-B(124)-B(127)-B(129)
! JVS(280) = Jac_FULL(33,34)
  JVS(280) = 0
! JVS(281) = Jac_FULL(33,35)
  JVS(281) = 0
! JVS(282) = Jac_FULL(33,36)
  JVS(282) = B(76)-B(125)
! JVS(283) = Jac_FULL(33,37)
  JVS(283) = 1.5*B(91)
! JVS(284) = Jac_FULL(33,38)
  JVS(284) = B(77)
! JVS(285) = Jac_FULL(33,39)
  JVS(285) = B(83)-B(123)
! JVS(286) = Jac_FULL(33,40)
  JVS(286) = 0
! JVS(287) = Jac_FULL(34,9)
  JVS(287) = BGS(6)*B(102)
! JVS(288) = Jac_FULL(34,22)
  JVS(288) = 1.39*B(104)
! JVS(289) = Jac_FULL(34,23)
  JVS(289) = B(144)
! JVS(290) = Jac_FULL(34,24)
  JVS(290) = 0.9*B(177)+0.5*B(181)+B(183)
! JVS(291) = Jac_FULL(34,25)
  JVS(291) = B(136)
! JVS(292) = Jac_FULL(34,27)
  JVS(292) = 0.5*B(182)
! JVS(293) = Jac_FULL(34,28)
  JVS(293) = 0
! JVS(294) = Jac_FULL(34,29)
  JVS(294) = -B(118)
! JVS(295) = Jac_FULL(34,30)
  JVS(295) = B(137)+B(145)+B(184)
! JVS(296) = Jac_FULL(34,31)
  JVS(296) = -B(120)
! JVS(297) = Jac_FULL(34,32)
  JVS(297) = BGS(6)*B(103)+1.39*B(105)+0.9*B(178)
! JVS(298) = Jac_FULL(34,33)
  JVS(298) = 0
! JVS(299) = Jac_FULL(34,34)
  JVS(299) = -B(114)-B(116)-B(119)-B(121)
! JVS(300) = Jac_FULL(34,35)
  JVS(300) = 0
! JVS(301) = Jac_FULL(34,36)
  JVS(301) = -B(117)
! JVS(302) = Jac_FULL(34,37)
  JVS(302) = 0
! JVS(303) = Jac_FULL(34,38)
  JVS(303) = 0
! JVS(304) = Jac_FULL(34,39)
  JVS(304) = -B(115)
! JVS(305) = Jac_FULL(34,40)
  JVS(305) = 0
! JVS(306) = Jac_FULL(35,9)
  JVS(306) = BGS(4)*B(102)
! JVS(307) = Jac_FULL(35,17)
  JVS(307) = 0.15*B(168)
! JVS(308) = Jac_FULL(35,24)
  JVS(308) = 0.1*B(177)
! JVS(309) = Jac_FULL(35,27)
  JVS(309) = 0
! JVS(310) = Jac_FULL(35,28)
  JVS(310) = 0
! JVS(311) = Jac_FULL(35,29)
  JVS(311) = -B(110)
! JVS(312) = Jac_FULL(35,30)
  JVS(312) = 0
! JVS(313) = Jac_FULL(35,31)
  JVS(313) = -B(112)
! JVS(314) = Jac_FULL(35,32)
  JVS(314) = BGS(4)*B(103)+0.15*B(169)+0.1*B(178)
! JVS(315) = Jac_FULL(35,33)
  JVS(315) = 0
! JVS(316) = Jac_FULL(35,34)
  JVS(316) = 0
! JVS(317) = Jac_FULL(35,35)
  JVS(317) = -B(106)-B(108)-B(111)-B(113)
! JVS(318) = Jac_FULL(35,36)
  JVS(318) = -B(109)
! JVS(319) = Jac_FULL(35,37)
  JVS(319) = 0
! JVS(320) = Jac_FULL(35,38)
  JVS(320) = 0
! JVS(321) = Jac_FULL(35,39)
  JVS(321) = -B(107)
! JVS(322) = Jac_FULL(35,40)
  JVS(322) = 0
! JVS(323) = Jac_FULL(36,4)
  JVS(323) = B(53)
! JVS(324) = Jac_FULL(36,10)
  JVS(324) = 0.16*B(162)
! JVS(325) = Jac_FULL(36,11)
  JVS(325) = 0.17*B(164)
! JVS(326) = Jac_FULL(36,12)
  JVS(326) = B(43)
! JVS(327) = Jac_FULL(36,13)
  JVS(327) = -B(174)
! JVS(328) = Jac_FULL(36,14)
  JVS(328) = B(35)
! JVS(329) = Jac_FULL(36,17)
  JVS(329) = 0
! JVS(330) = Jac_FULL(36,18)
  JVS(330) = 0
! JVS(331) = Jac_FULL(36,19)
  JVS(331) = B(63)
! JVS(332) = Jac_FULL(36,20)
  JVS(332) = 0
! JVS(333) = Jac_FULL(36,21)
  JVS(333) = 0
! JVS(334) = Jac_FULL(36,23)
  JVS(334) = BGS(13)*B(140)+BGS(2)*B(142)
! JVS(335) = Jac_FULL(36,24)
  JVS(335) = 0.7*B(177)+0.4*B(179)+0.6*B(181)
! JVS(336) = Jac_FULL(36,25)
  JVS(336) = 0.12*B(132)+B(134)
! JVS(337) = Jac_FULL(36,26)
  JVS(337) = 0
! JVS(338) = Jac_FULL(36,27)
  JVS(338) = B(135)+BGS(2)*B(143)+0.6*B(182)
! JVS(339) = Jac_FULL(36,28)
  JVS(339) = B(37)-B(46)+0.12*B(133)+BGS(13)*B(141)+0.4*B(180)
! JVS(340) = Jac_FULL(36,29)
  JVS(340) = 0.5*B(110)+0.5*B(126)
! JVS(341) = Jac_FULL(36,30)
  JVS(341) = -B(55)-B(57)-B(60)+B(74)
! JVS(342) = Jac_FULL(36,31)
  JVS(342) = -B(86)+2*B(88)+B(112)+B(120)+B(128)
! JVS(343) = Jac_FULL(36,32)
  JVS(343) = B(36)+B(38)+B(54)+B(64)+B(72)+0.16*B(163)+0.17*B(165)+0.7*B(178)-B(185)
! JVS(344) = Jac_FULL(36,33)
  JVS(344) = B(122)-B(124)+0.5*B(127)+B(129)
! JVS(345) = Jac_FULL(36,34)
  JVS(345) = -B(116)+B(121)
! JVS(346) = Jac_FULL(36,35)
  JVS(346) = -B(108)+0.5*B(111)+B(113)
! JVS(347) = Jac_FULL(36,36)
  JVS(347) = -B(39)-B(41)-B(47)-2*B(48)-2*B(49)-2*B(51)-B(56)-B(58)-B(61)-B(76)-B(87)-B(109)-B(117)-B(125)-B(175)-B(186)
! JVS(348) = Jac_FULL(36,37)
  JVS(348) = 0
! JVS(349) = Jac_FULL(36,38)
  JVS(349) = B(73)+B(75)-B(77)
! JVS(350) = Jac_FULL(36,39)
  JVS(350) = -B(40)+B(123)
! JVS(351) = Jac_FULL(36,40)
  JVS(351) = -B(42)
! JVS(352) = Jac_FULL(37,6)
  JVS(352) = 0.5*B(100)
! JVS(353) = Jac_FULL(37,9)
  JVS(353) = BGS(3)*B(102)
! JVS(354) = Jac_FULL(37,22)
  JVS(354) = 0.14*B(104)
! JVS(355) = Jac_FULL(37,23)
  JVS(355) = BGS(17)*B(142)
! JVS(356) = Jac_FULL(37,27)
  JVS(356) = BGS(17)*B(143)
! JVS(357) = Jac_FULL(37,28)
  JVS(357) = 0
! JVS(358) = Jac_FULL(37,29)
  JVS(358) = B(110)
! JVS(359) = Jac_FULL(37,30)
  JVS(359) = 0
! JVS(360) = Jac_FULL(37,31)
  JVS(360) = B(112)
! JVS(361) = Jac_FULL(37,32)
  JVS(361) = -B(90)+0.5*B(101)+BGS(3)*B(103)+0.14*B(105)
! JVS(362) = Jac_FULL(37,33)
  JVS(362) = 0
! JVS(363) = Jac_FULL(37,34)
  JVS(363) = 0
! JVS(364) = Jac_FULL(37,35)
  JVS(364) = B(108)+B(111)+B(113)
! JVS(365) = Jac_FULL(37,36)
  JVS(365) = B(109)
! JVS(366) = Jac_FULL(37,37)
  JVS(366) = -B(91)
! JVS(367) = Jac_FULL(37,38)
  JVS(367) = 0
! JVS(368) = Jac_FULL(37,39)
  JVS(368) = 0
! JVS(369) = Jac_FULL(37,40)
  JVS(369) = 0
! JVS(370) = Jac_FULL(38,9)
  JVS(370) = BGS(1)*B(102)
! JVS(371) = Jac_FULL(38,10)
  JVS(371) = 0.11*B(162)
! JVS(372) = Jac_FULL(38,11)
  JVS(372) = BGS(24)*B(164)
! JVS(373) = Jac_FULL(38,19)
  JVS(373) = B(146)
! JVS(374) = Jac_FULL(38,20)
  JVS(374) = B(147)-B(154)
! JVS(375) = Jac_FULL(38,21)
  JVS(375) = -B(156)
! JVS(376) = Jac_FULL(38,22)
  JVS(376) = 0.16*B(104)
! JVS(377) = Jac_FULL(38,23)
  JVS(377) = BGS(8)*B(138)+BGS(1)*B(140)+BGS(18)*B(142)+BGS(8)*B(144)
! JVS(378) = Jac_FULL(38,24)
  JVS(378) = B(177)+B(179)+B(183)
! JVS(379) = Jac_FULL(38,25)
  JVS(379) = 1.56*B(130)+B(132)+B(134)+2*B(136)
! JVS(380) = Jac_FULL(38,26)
  JVS(380) = 0
! JVS(381) = Jac_FULL(38,27)
  JVS(381) = B(135)+BGS(18)*B(143)
! JVS(382) = Jac_FULL(38,28)
  JVS(382) = B(133)+BGS(1)*B(141)+B(180)
! JVS(383) = Jac_FULL(38,30)
  JVS(383) = -B(74)+2*B(137)+BGS(8)*B(145)+B(184)
! JVS(384) = Jac_FULL(38,31)
  JVS(384) = B(82)+B(86)+2*B(88)+B(112)+B(120)+B(128)
! JVS(385) = Jac_FULL(38,32)
  JVS(385) = -B(72)+0.5*B(90)+B(96)+BGS(1)*B(103)+0.16*B(105)+1.56*B(131)+BGS(8)*B(139)+0.11*B(163)+BGS(24)*B(165)&
               &+B(178)
! JVS(386) = Jac_FULL(38,33)
  JVS(386) = B(129)
! JVS(387) = Jac_FULL(38,34)
  JVS(387) = B(121)
! JVS(388) = Jac_FULL(38,35)
  JVS(388) = B(113)
! JVS(389) = Jac_FULL(38,36)
  JVS(389) = -B(76)+B(87)
! JVS(390) = Jac_FULL(38,37)
  JVS(390) = 0.5*B(91)
! JVS(391) = Jac_FULL(38,38)
  JVS(391) = -B(73)-B(75)-B(77)-B(155)-B(157)
! JVS(392) = Jac_FULL(38,39)
  JVS(392) = B(83)
! JVS(393) = Jac_FULL(38,40)
  JVS(393) = 0
! JVS(394) = Jac_FULL(39,27)
  JVS(394) = B(4)
! JVS(395) = Jac_FULL(39,28)
  JVS(395) = -B(8)
! JVS(396) = Jac_FULL(39,30)
  JVS(396) = -B(12)+B(21)
! JVS(397) = Jac_FULL(39,31)
  JVS(397) = -B(82)
! JVS(398) = Jac_FULL(39,32)
  JVS(398) = -B(27)
! JVS(399) = Jac_FULL(39,33)
  JVS(399) = -B(122)
! JVS(400) = Jac_FULL(39,34)
  JVS(400) = -B(114)
! JVS(401) = Jac_FULL(39,35)
  JVS(401) = -B(106)
! JVS(402) = Jac_FULL(39,36)
  JVS(402) = -B(39)
! JVS(403) = Jac_FULL(39,37)
  JVS(403) = 0
! JVS(404) = Jac_FULL(39,38)
  JVS(404) = 0
! JVS(405) = Jac_FULL(39,39)
  JVS(405) = -B(9)-B(13)-2*B(14)-B(28)-B(40)-B(83)-B(107)-B(115)-B(123)
! JVS(406) = Jac_FULL(39,40)
  JVS(406) = B(5)+B(22)
! JVS(407) = Jac_FULL(40,5)
  JVS(407) = B(89)
! JVS(408) = Jac_FULL(40,8)
  JVS(408) = B(18)
! JVS(409) = Jac_FULL(40,12)
  JVS(409) = B(43)+B(44)
! JVS(410) = Jac_FULL(40,13)
  JVS(410) = -B(172)
! JVS(411) = Jac_FULL(40,17)
  JVS(411) = 0
! JVS(412) = Jac_FULL(40,22)
  JVS(412) = B(104)
! JVS(413) = Jac_FULL(40,23)
  JVS(413) = B(144)
! JVS(414) = Jac_FULL(40,24)
  JVS(414) = B(183)
! JVS(415) = Jac_FULL(40,25)
  JVS(415) = B(136)
! JVS(416) = Jac_FULL(40,27)
  JVS(416) = -B(4)-B(6)
! JVS(417) = Jac_FULL(40,28)
  JVS(417) = B(8)-B(10)
! JVS(418) = Jac_FULL(40,30)
  JVS(418) = 2*B(12)-B(16)+B(137)+B(145)+B(184)
! JVS(419) = Jac_FULL(40,31)
  JVS(419) = B(82)-B(84)
! JVS(420) = Jac_FULL(40,32)
  JVS(420) = -B(31)+B(45)+B(105)
! JVS(421) = Jac_FULL(40,33)
  JVS(421) = B(122)
! JVS(422) = Jac_FULL(40,34)
  JVS(422) = B(114)
! JVS(423) = Jac_FULL(40,35)
  JVS(423) = 0
! JVS(424) = Jac_FULL(40,36)
  JVS(424) = B(39)-B(41)
! JVS(425) = Jac_FULL(40,37)
  JVS(425) = 0
! JVS(426) = Jac_FULL(40,38)
  JVS(426) = 0
! JVS(427) = Jac_FULL(40,39)
  JVS(427) = B(9)+2*B(13)+2*B(14)+B(40)+B(83)+B(115)+B(123)
! JVS(428) = Jac_FULL(40,40)
  JVS(428) = -B(5)-B(7)-B(11)-B(17)-2*B(29)-B(32)-B(42)-B(85)-B(173)
      
  RETURN
END SUBROUTINE Jac_SP_night

SUBROUTINE ros_PrepareMatrix_night ( H, gam, &
             Jac0, Ghimj, Singular )
! --- --- --- --- --- --- --- --- --- --- --- --- ---
!  Prepares the LHS matrix for stage calculations
!  1.  Construct Ghimj = 1/(H*ham) - Jac0
!      "(Gamma H) Inverse Minus Jacobian"
!  2.  Repeat LU decomposition of Ghimj until successful.
!       -half the step size if LU decomposition fails and retry
!       -exit after 5 consecutive fails
! --- --- --- --- --- --- --- --- --- --- --- --- ---
   IMPLICIT NONE
!~~~> Input arguments
   real(kind=8), INTENT(IN) ::  Jac0(LU_NONZERO)
   real(kind=8), INTENT(IN) ::  gam
!~~~> Output arguments
   real(kind=8), INTENT(OUT) :: Ghimj(LU_NONZERO)
   LOGICAL, INTENT(OUT) ::  Singular
!~~~> Inout arguments
   real(kind=8), INTENT(INOUT) :: H
!~~~> Local variables
   INTEGER(KIND=4)  :: i, ising, Nconsecutive
   real(kind=8) :: ghinv
   real(kind=8), PARAMETER :: ONE  = 1.0d0, HALF = 0.5d0
! Sparse Jacobian Data

  INTEGER, PARAMETER, DIMENSION(41) :: LU_DIAG = (/ &
       1,  2,  7, 11, 14, 17, 19, 23, 26, 28, 30, 32, &
      36, 43, 53, 62, 71, 77, 82, 87, 97,107,114,119, &
     125,139,154,163,181,203,221,256,279,299,317,347, &
     366,391,405,428,429 /)

   Nconsecutive = 0
   Singular = .TRUE.
   DO WHILE (Singular)
!~~~>    Construct Ghimj = 1/(H*gam) - Jac0
     Ghimj = -ONE*Jac0
     ghinv = ONE/(H*gam)
     DO i=1,N
       Ghimj(LU_DIAG(i)) = Ghimj(LU_DIAG(i))+ghinv
     END DO
!~~~>    Compute LU decomposition
     CALL KppDecomp_night ( Ghimj, ising, N, LU_NONZERO )
     IF (ising == 0) THEN
!~~~>    If successful done
        Singular = .FALSE.
     ELSE
!~~~>    If unsuccessful half the step size; if 5 consecutive fails then return
        Nconsecutive = Nconsecutive+1
        Singular = .TRUE.
        PRINT*,'Warning: LU Decomposition returned ising = ',ising
        IF (Nconsecutive <= 5) THEN
           H = H*HALF
        ELSE
           RETURN
        END IF
      END IF
   END DO

  RETURN
END SUBROUTINE ros_PrepareMatrix_night

SUBROUTINE KppDecomp_night( JVS, IER, NVAR, LU_NONZERO )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      implicit none
      integer(kind=4), intent(in) :: NVAR, LU_NONZERO
      INTEGER(kind=4), intent(out)  :: IER
      real(kind=8), intent(inout) :: JVS(LU_NONZERO)
!local variables
      real(kind=8) :: W(NVAR), a
      INTEGER(kind=4)  :: k, kk, j, jj
! Sparse Jacobian Data

  INTEGER, PARAMETER, DIMENSION(360) :: LU_ICOL_0 = (/ &
       1,  2, 19, 20, 21, 32,  3, 32, 39, 40,  4, 32, &
      36,  5, 31, 40,  6, 32,  7, 10, 11, 32,  8, 30, &
      40,  9, 32, 10, 32, 11, 32, 12, 32, 36, 40, 13, &
      17, 30, 36, 40, 10, 11, 14, 18, 23, 25, 27, 28, &
      30, 32, 38,  8, 15, 17, 18, 26, 30, 32, 36, 38, &
      40, 16, 31, 32, 33, 34, 35, 36, 10, 11, 17, 30, &
      32, 10, 11, 17, 18, 24, 28, 30, 32, 19, 20, 21, &
      32, 19, 20, 21, 23, 25, 26, 28, 32, 38, 19, 20, &
      21, 23, 24, 25, 26, 28, 32, 38, 13, 17, 22, 30, &
      32, 35, 36, 39, 40, 23, 27, 28, 30, 32, 24, 27, &
      28, 30, 32, 24, 25, 27, 28, 30, 32,  6,  9, 19, &
      20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 32, 35, &
      36, 37, 38, 39, 40,  1, 23, 24, 25, 27, 28, 30, &
      32, 40, 23, 24, 25, 27, 28, 30, 32, 36, 39, 40, &
       6,  9, 10, 11, 16, 17, 22, 23, 24, 25, 27, 28, &
      29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, &
       8, 15, 17, 18, 23, 24, 25, 26, 27, 28, 30, 32, &
      35, 36, 37, 38, 39, 40,  5,  7, 10, 11, 18, 24, &
      26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, &
      39, 40,  1,  4,  6,  7,  9, 10, 11, 12, 14, 15, &
      16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, &
      28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, &
       6,  9, 10, 11, 16, 17, 23, 25, 27, 28, 29, 30, &
      31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  9, 22, &
      23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, &
      36, 37, 38, 39, 40,  9, 17, 24, 27, 28, 29, 30, &
      31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  4, 10, &
      11, 12, 13, 14, 17, 18, 19, 20, 21, 23, 24, 25, &
      26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, &
      38, 39, 40,  6,  9, 22, 23, 27, 28, 29, 30, 31 /)
  INTEGER, PARAMETER, DIMENSION(68) :: LU_ICOL_1 = (/ &
      32, 33, 34, 35, 36, 37, 38, 39, 40,  9, 10, 11, &
      19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, &
      32, 33, 34, 35, 36, 37, 38, 39, 40, 27, 28, 30, &
      31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  5,  8, &
      12, 13, 17, 22, 23, 24, 25, 27, 28, 30, 31, 32, &
      33, 34, 35, 36, 37, 38, 39, 40 /)
  INTEGER, PARAMETER, DIMENSION(428) :: LU_ICOL = (/&
    LU_ICOL_0, LU_ICOL_1 /)

  INTEGER, PARAMETER, DIMENSION(41) :: LU_CROW = (/ &
       1,  2,  7, 11, 14, 17, 19, 23, 26, 28, 30, 32, &
      36, 41, 52, 62, 69, 74, 82, 86, 95,105,114,119, &
     124,130,150,159,169,193,211,231,265,287,306,323, &
     352,370,394,407,429 /)

  INTEGER, PARAMETER, DIMENSION(41) :: LU_DIAG = (/ &
       1,  2,  7, 11, 14, 17, 19, 23, 26, 28, 30, 32, &
      36, 43, 53, 62, 71, 77, 82, 87, 97,107,114,119, &
     125,139,154,163,181,203,221,256,279,299,317,347, &
     366,391,405,428,429 /)


      a = 0.
      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

  RETURN
END SUBROUTINE KppDecomp_night

SUBROUTINE KppSolve_night ( JVS, X, NVAR, LU_NONZERO )
  implicit none
  integer(kind=4), intent(in) :: nvar, LU_NONZERO
! JVS - sparse Jacobian of variables
  real(kind=8), intent(in) :: JVS(LU_NONZERO)
! X - Vector for variables
  real(kind=8), intent(inout):: X(NVAR)

  X(14) = X(14)-JVS(41)*X(10)-JVS(42)*X(11)
  X(15) = X(15)-JVS(52)*X(8)
  X(17) = X(17)-JVS(69)*X(10)-JVS(70)*X(11)
  X(18) = X(18)-JVS(74)*X(10)-JVS(75)*X(11)-JVS(76)*X(17)
  X(20) = X(20)-JVS(86)*X(19)
  X(21) = X(21)-JVS(95)*X(19)-JVS(96)*X(20)
  X(22) = X(22)-JVS(105)*X(13)-JVS(106)*X(17)
  X(25) = X(25)-JVS(124)*X(24)
  X(26) = X(26)-JVS(130)*X(6)-JVS(131)*X(9)-JVS(132)*X(19)-JVS(133)*X(20)-JVS(134)*X(21)-JVS(135)*X(22)-JVS(136)*X(23)&
            &-JVS(137)*X(24)-JVS(138)*X(25)
  X(27) = X(27)-JVS(150)*X(1)-JVS(151)*X(23)-JVS(152)*X(24)-JVS(153)*X(25)
  X(28) = X(28)-JVS(159)*X(23)-JVS(160)*X(24)-JVS(161)*X(25)-JVS(162)*X(27)
  X(29) = X(29)-JVS(169)*X(6)-JVS(170)*X(9)-JVS(171)*X(10)-JVS(172)*X(11)-JVS(173)*X(16)-JVS(174)*X(17)-JVS(175)*X(22)&
            &-JVS(176)*X(23)-JVS(177)*X(24)-JVS(178)*X(25)-JVS(179)*X(27)-JVS(180)*X(28)
  X(30) = X(30)-JVS(193)*X(8)-JVS(194)*X(15)-JVS(195)*X(17)-JVS(196)*X(18)-JVS(197)*X(23)-JVS(198)*X(24)-JVS(199)*X(25)&
            &-JVS(200)*X(26)-JVS(201)*X(27)-JVS(202)*X(28)
  X(31) = X(31)-JVS(211)*X(5)-JVS(212)*X(7)-JVS(213)*X(10)-JVS(214)*X(11)-JVS(215)*X(18)-JVS(216)*X(24)-JVS(217)*X(26)&
            &-JVS(218)*X(27)-JVS(219)*X(28)-JVS(220)*X(30)
  X(32) = X(32)-JVS(231)*X(1)-JVS(232)*X(4)-JVS(233)*X(6)-JVS(234)*X(7)-JVS(235)*X(9)-JVS(236)*X(10)-JVS(237)*X(11)&
            &-JVS(238)*X(12)-JVS(239)*X(14)-JVS(240)*X(15)-JVS(241)*X(16)-JVS(242)*X(17)-JVS(243)*X(18)-JVS(244)*X(19)&
            &-JVS(245)*X(20)-JVS(246)*X(21)-JVS(247)*X(22)-JVS(248)*X(23)-JVS(249)*X(24)-JVS(250)*X(25)-JVS(251)*X(26)&
            &-JVS(252)*X(27)-JVS(253)*X(28)-JVS(254)*X(30)-JVS(255)*X(31)
  X(33) = X(33)-JVS(265)*X(6)-JVS(266)*X(9)-JVS(267)*X(10)-JVS(268)*X(11)-JVS(269)*X(16)-JVS(270)*X(17)-JVS(271)*X(23)&
            &-JVS(272)*X(25)-JVS(273)*X(27)-JVS(274)*X(28)-JVS(275)*X(29)-JVS(276)*X(30)-JVS(277)*X(31)-JVS(278)*X(32)
  X(34) = X(34)-JVS(287)*X(9)-JVS(288)*X(22)-JVS(289)*X(23)-JVS(290)*X(24)-JVS(291)*X(25)-JVS(292)*X(27)-JVS(293)*X(28)&
            &-JVS(294)*X(29)-JVS(295)*X(30)-JVS(296)*X(31)-JVS(297)*X(32)-JVS(298)*X(33)
  X(35) = X(35)-JVS(306)*X(9)-JVS(307)*X(17)-JVS(308)*X(24)-JVS(309)*X(27)-JVS(310)*X(28)-JVS(311)*X(29)-JVS(312)*X(30)&
            &-JVS(313)*X(31)-JVS(314)*X(32)-JVS(315)*X(33)-JVS(316)*X(34)
  X(36) = X(36)-JVS(323)*X(4)-JVS(324)*X(10)-JVS(325)*X(11)-JVS(326)*X(12)-JVS(327)*X(13)-JVS(328)*X(14)-JVS(329)*X(17)&
            &-JVS(330)*X(18)-JVS(331)*X(19)-JVS(332)*X(20)-JVS(333)*X(21)-JVS(334)*X(23)-JVS(335)*X(24)-JVS(336)*X(25)&
            &-JVS(337)*X(26)-JVS(338)*X(27)-JVS(339)*X(28)-JVS(340)*X(29)-JVS(341)*X(30)-JVS(342)*X(31)-JVS(343)*X(32)&
            &-JVS(344)*X(33)-JVS(345)*X(34)-JVS(346)*X(35)
  X(37) = X(37)-JVS(352)*X(6)-JVS(353)*X(9)-JVS(354)*X(22)-JVS(355)*X(23)-JVS(356)*X(27)-JVS(357)*X(28)-JVS(358)*X(29)&
            &-JVS(359)*X(30)-JVS(360)*X(31)-JVS(361)*X(32)-JVS(362)*X(33)-JVS(363)*X(34)-JVS(364)*X(35)-JVS(365)*X(36)
  X(38) = X(38)-JVS(370)*X(9)-JVS(371)*X(10)-JVS(372)*X(11)-JVS(373)*X(19)-JVS(374)*X(20)-JVS(375)*X(21)-JVS(376)*X(22)&
            &-JVS(377)*X(23)-JVS(378)*X(24)-JVS(379)*X(25)-JVS(380)*X(26)-JVS(381)*X(27)-JVS(382)*X(28)-JVS(383)*X(30)&
            &-JVS(384)*X(31)-JVS(385)*X(32)-JVS(386)*X(33)-JVS(387)*X(34)-JVS(388)*X(35)-JVS(389)*X(36)-JVS(390)*X(37)
  X(39) = X(39)-JVS(394)*X(27)-JVS(395)*X(28)-JVS(396)*X(30)-JVS(397)*X(31)-JVS(398)*X(32)-JVS(399)*X(33)-JVS(400)*X(34)&
            &-JVS(401)*X(35)-JVS(402)*X(36)-JVS(403)*X(37)-JVS(404)*X(38)
  X(40) = X(40)-JVS(407)*X(5)-JVS(408)*X(8)-JVS(409)*X(12)-JVS(410)*X(13)-JVS(411)*X(17)-JVS(412)*X(22)-JVS(413)*X(23)&
            &-JVS(414)*X(24)-JVS(415)*X(25)-JVS(416)*X(27)-JVS(417)*X(28)-JVS(418)*X(30)-JVS(419)*X(31)-JVS(420)*X(32)&
            &-JVS(421)*X(33)-JVS(422)*X(34)-JVS(423)*X(35)-JVS(424)*X(36)-JVS(425)*X(37)-JVS(426)*X(38)-JVS(427)*X(39)
  X(40) = X(40)/JVS(428)
  X(39) = (X(39)-JVS(406)*X(40))/(JVS(405))
  X(38) = (X(38)-JVS(392)*X(39)-JVS(393)*X(40))/(JVS(391))
  X(37) = (X(37)-JVS(367)*X(38)-JVS(368)*X(39)-JVS(369)*X(40))/(JVS(366))
  X(36) = (X(36)-JVS(348)*X(37)-JVS(349)*X(38)-JVS(350)*X(39)-JVS(351)*X(40))/(JVS(347))
  X(35) = (X(35)-JVS(318)*X(36)-JVS(319)*X(37)-JVS(320)*X(38)-JVS(321)*X(39)-JVS(322)*X(40))/(JVS(317))
  X(34) = (X(34)-JVS(300)*X(35)-JVS(301)*X(36)-JVS(302)*X(37)-JVS(303)*X(38)-JVS(304)*X(39)-JVS(305)*X(40))/(JVS(299))
  X(33) = (X(33)-JVS(280)*X(34)-JVS(281)*X(35)-JVS(282)*X(36)-JVS(283)*X(37)-JVS(284)*X(38)-JVS(285)*X(39)-JVS(286)&
            &*X(40))/(JVS(279))
  X(32) = (X(32)-JVS(257)*X(33)-JVS(258)*X(34)-JVS(259)*X(35)-JVS(260)*X(36)-JVS(261)*X(37)-JVS(262)*X(38)-JVS(263)&
            &*X(39)-JVS(264)*X(40))/(JVS(256))
  X(31) = (X(31)-JVS(222)*X(32)-JVS(223)*X(33)-JVS(224)*X(34)-JVS(225)*X(35)-JVS(226)*X(36)-JVS(227)*X(37)-JVS(228)&
            &*X(38)-JVS(229)*X(39)-JVS(230)*X(40))/(JVS(221))
  X(30) = (X(30)-JVS(204)*X(32)-JVS(205)*X(35)-JVS(206)*X(36)-JVS(207)*X(37)-JVS(208)*X(38)-JVS(209)*X(39)-JVS(210)&
            &*X(40))/(JVS(203))
  X(29) = (X(29)-JVS(182)*X(30)-JVS(183)*X(31)-JVS(184)*X(32)-JVS(185)*X(33)-JVS(186)*X(34)-JVS(187)*X(35)-JVS(188)&
            &*X(36)-JVS(189)*X(37)-JVS(190)*X(38)-JVS(191)*X(39)-JVS(192)*X(40))/(JVS(181))
  X(28) = (X(28)-JVS(164)*X(30)-JVS(165)*X(32)-JVS(166)*X(36)-JVS(167)*X(39)-JVS(168)*X(40))/(JVS(163))
  X(27) = (X(27)-JVS(155)*X(28)-JVS(156)*X(30)-JVS(157)*X(32)-JVS(158)*X(40))/(JVS(154))
  X(26) = (X(26)-JVS(140)*X(27)-JVS(141)*X(28)-JVS(142)*X(30)-JVS(143)*X(32)-JVS(144)*X(35)-JVS(145)*X(36)-JVS(146)&
            &*X(37)-JVS(147)*X(38)-JVS(148)*X(39)-JVS(149)*X(40))/(JVS(139))
  X(25) = (X(25)-JVS(126)*X(27)-JVS(127)*X(28)-JVS(128)*X(30)-JVS(129)*X(32))/(JVS(125))
  X(24) = (X(24)-JVS(120)*X(27)-JVS(121)*X(28)-JVS(122)*X(30)-JVS(123)*X(32))/(JVS(119))
  X(23) = (X(23)-JVS(115)*X(27)-JVS(116)*X(28)-JVS(117)*X(30)-JVS(118)*X(32))/(JVS(114))
  X(22) = (X(22)-JVS(108)*X(30)-JVS(109)*X(32)-JVS(110)*X(35)-JVS(111)*X(36)-JVS(112)*X(39)-JVS(113)*X(40))/(JVS(107))
  X(21) = (X(21)-JVS(98)*X(23)-JVS(99)*X(24)-JVS(100)*X(25)-JVS(101)*X(26)-JVS(102)*X(28)-JVS(103)*X(32)-JVS(104)*X(38))&
            &/(JVS(97))
  X(20) = (X(20)-JVS(88)*X(21)-JVS(89)*X(23)-JVS(90)*X(25)-JVS(91)*X(26)-JVS(92)*X(28)-JVS(93)*X(32)-JVS(94)*X(38))&
            &/(JVS(87))
  X(19) = (X(19)-JVS(83)*X(20)-JVS(84)*X(21)-JVS(85)*X(32))/(JVS(82))
  X(18) = (X(18)-JVS(78)*X(24)-JVS(79)*X(28)-JVS(80)*X(30)-JVS(81)*X(32))/(JVS(77))
  X(17) = (X(17)-JVS(72)*X(30)-JVS(73)*X(32))/(JVS(71))
  X(16) = (X(16)-JVS(63)*X(31)-JVS(64)*X(32)-JVS(65)*X(33)-JVS(66)*X(34)-JVS(67)*X(35)-JVS(68)*X(36))/(JVS(62))
  X(15) = (X(15)-JVS(54)*X(17)-JVS(55)*X(18)-JVS(56)*X(26)-JVS(57)*X(30)-JVS(58)*X(32)-JVS(59)*X(36)-JVS(60)*X(38)&
            &-JVS(61)*X(40))/(JVS(53))
  X(14) = (X(14)-JVS(44)*X(18)-JVS(45)*X(23)-JVS(46)*X(25)-JVS(47)*X(27)-JVS(48)*X(28)-JVS(49)*X(30)-JVS(50)*X(32)&
            &-JVS(51)*X(38))/(JVS(43))
  X(13) = (X(13)-JVS(37)*X(17)-JVS(38)*X(30)-JVS(39)*X(36)-JVS(40)*X(40))/(JVS(36))
  X(12) = (X(12)-JVS(33)*X(32)-JVS(34)*X(36)-JVS(35)*X(40))/(JVS(32))
  X(11) = (X(11)-JVS(31)*X(32))/(JVS(30))
  X(10) = (X(10)-JVS(29)*X(32))/(JVS(28))
  X(9) = (X(9)-JVS(27)*X(32))/(JVS(26))
  X(8) = (X(8)-JVS(24)*X(30)-JVS(25)*X(40))/(JVS(23))
  X(7) = (X(7)-JVS(20)*X(10)-JVS(21)*X(11)-JVS(22)*X(32))/(JVS(19))
  X(6) = (X(6)-JVS(18)*X(32))/(JVS(17))
  X(5) = (X(5)-JVS(15)*X(31)-JVS(16)*X(40))/(JVS(14))
  X(4) = (X(4)-JVS(12)*X(32)-JVS(13)*X(36))/(JVS(11))
  X(3) = (X(3)-JVS(8)*X(32)-JVS(9)*X(39)-JVS(10)*X(40))/(JVS(7))
  X(2) = (X(2)-JVS(3)*X(19)-JVS(4)*X(20)-JVS(5)*X(21)-JVS(6)*X(32))/(JVS(2))
  X(1) = X(1)/JVS(1)
      
  RETURN
END SUBROUTINE KppSolve_night

  real(kind=8) FUNCTION ros_ErrorNorm ( Y, Ynew, Yerr, &
                               AbsTol, RelTol )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~> Computes the "scaled norm" of the error vector Yerr
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   IMPLICIT NONE
! Input arguments
   real(kind=8), INTENT(IN) :: Y(N), Ynew(N), &
          Yerr(N), AbsTol(N), RelTol(N)
! Local variables
   real(kind=8) :: Err, Scale, Ymax
   INTEGER(KIND=4)  :: i
   real(kind=8), PARAMETER :: ZERO = 0.0d0
   Err = ZERO
   DO i=1,N
     Ymax = MAX(ABS(Y(i)),ABS(Ynew(i)))
     Scale = AbsTol(i)+RelTol(i)*Ymax
     Err = Err+(Yerr(i)/Scale)**2
   END DO
   Err  = SQRT(Err/N)
   ros_ErrorNorm = MAX(Err,1.0d-10)
  END FUNCTION ros_ErrorNorm

END SUBROUTINE mach_kppb_adom2night_rodas3
