! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Linear Algebra Data and Routines File
!
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!============================================================================!
!
! GEM-MACH Setup
! Fichier / File   : mach_kpp_saprc07cs_LinearAlgebra.ftn90
! Creation         : Jack Chen (Feb. 2017)
! Modifications    : code adapted from KPP
!  - updated module name
!  - add debug flag and change print statements to write (chm_lun_out, *)
!  - utilize the Intel MKL calls WAXPY->DAXPY; WSCAL->DSCAL;
!
!============================================================================

MODULE mach_kpp_saprc07cs_LinearAlgebra

  USE mach_kpp_saprc07cs_JacobianSP
  USE chm_utils_mod,    ONLY: DP, chm_lun_out
  USE mach_pkg_gas_mod, ONLY: NVAR, LU_NONZERO

  IMPLICIT NONE

 CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: IER
      COMPLEX(kind=8) :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=dp)   :: b = 0.0_dp
      INTEGER(kind=4) :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       :: IER
      REAL(kind=dp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO)
      REAL(kind=dp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

 END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER  :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

 END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

 END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: i, j
      COMPLEX(kind=8) :: JVS(LU_NONZERO), X(NVAR), rsum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j))
         END DO
      END DO

      DO i=NVAR,1,-1
        rsum = X(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          rsum = rsum - JVS(j)*X(LU_ICOL(j))
        END DO
        X(i) = rsum/JVS(LU_DIAG(i))
      END DO

 END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO

 END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER(kind=4) :: i, j
      COMPLEX(kind=8) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
        END DO
      END DO

 END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
          XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
          XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

      DO i=NVAR, 1, -1
        ! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
          XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
          XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
        END DO
      END DO

 END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_strato_Parameters
!  USE saprcCS07Aiepx_strato_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER)
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER)
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO
!
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_strato_Parameters
!  USE saprcCS07Aiepx_strato_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!              X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!              sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0)
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprcCS07Aiepx_strato_Parameters
!  USE saprcCS07Aiepx_strato_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!         !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!              X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!        END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!          !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!              X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!        END DO
!      END DO
!
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=dp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=dp) :: t, dmax, da, TMP(3)
!      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF
!!      END IF
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF
!!
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=dp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=dp) :: TMP
!
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!
!
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(8) = X(8)-JVS(70)*X(7)
  X(21) = X(21)-JVS(113)*X(11)-JVS(114)*X(13)
  X(23) = X(23)-JVS(125)*X(14)-JVS(126)*X(15)
  X(24) = X(24)-JVS(130)*X(14)-JVS(131)*X(15)-JVS(132)*X(22)
  X(25) = X(25)-JVS(138)*X(19)-JVS(139)*X(24)
  X(26) = X(26)-JVS(150)*X(16)-JVS(151)*X(23)
  X(27) = X(27)-JVS(168)*X(14)-JVS(169)*X(15)-JVS(170)*X(23)
  X(29) = X(29)-JVS(180)*X(14)-JVS(181)*X(15)-JVS(182)*X(23)-JVS(183)*X(24)-JVS(184)*X(27)-JVS(185)*X(28)
  X(30) = X(30)-JVS(195)*X(16)-JVS(196)*X(23)-JVS(197)*X(27)
  X(33) = X(33)-JVS(227)*X(16)-JVS(228)*X(17)-JVS(229)*X(23)-JVS(230)*X(27)-JVS(231)*X(28)-JVS(232)*X(31)-JVS(233)*X(32)
  X(35) = X(35)-JVS(257)*X(16)-JVS(258)*X(23)-JVS(259)*X(27)-JVS(260)*X(28)-JVS(261)*X(32)-JVS(262)*X(34)
  X(37) = X(37)-JVS(278)*X(31)-JVS(279)*X(32)-JVS(280)*X(34)-JVS(281)*X(36)
  X(38) = X(38)-JVS(287)*X(32)-JVS(288)*X(34)-JVS(289)*X(36)-JVS(290)*X(37)
  X(39) = X(39)-JVS(298)*X(13)-JVS(299)*X(19)-JVS(300)*X(21)-JVS(301)*X(28)-JVS(302)*X(31)-JVS(303)*X(32)-JVS(304)*X(34)&
            &-JVS(305)*X(36)
  X(40) = X(40)-JVS(312)*X(16)-JVS(313)*X(18)-JVS(314)*X(28)-JVS(315)*X(32)-JVS(316)*X(34)-JVS(317)*X(35)-JVS(318)*X(36)&
            &-JVS(319)*X(37)-JVS(320)*X(38)-JVS(321)*X(39)
  X(41) = X(41)-JVS(335)*X(21)-JVS(336)*X(23)-JVS(337)*X(27)-JVS(338)*X(28)-JVS(339)*X(31)-JVS(340)*X(32)-JVS(341)*X(34)&
            &-JVS(342)*X(36)-JVS(343)*X(37)-JVS(344)*X(39)
  X(42) = X(42)-JVS(353)*X(28)-JVS(354)*X(31)-JVS(355)*X(32)-JVS(356)*X(34)-JVS(357)*X(36)-JVS(358)*X(37)-JVS(359)*X(39)&
            &-JVS(360)*X(41)
  X(43) = X(43)-JVS(369)*X(14)-JVS(370)*X(15)-JVS(371)*X(16)-JVS(372)*X(17)-JVS(373)*X(18)-JVS(374)*X(22)-JVS(375)*X(23)&
            &-JVS(376)*X(24)-JVS(377)*X(27)-JVS(378)*X(28)-JVS(379)*X(31)-JVS(380)*X(32)-JVS(381)*X(34)-JVS(382)*X(35)&
            &-JVS(383)*X(36)-JVS(384)*X(37)-JVS(385)*X(38)-JVS(386)*X(39)-JVS(387)*X(40)-JVS(388)*X(41)-JVS(389)*X(42)
  X(44) = X(44)-JVS(400)*X(6)-JVS(401)*X(9)-JVS(402)*X(12)-JVS(403)*X(14)-JVS(404)*X(15)-JVS(405)*X(20)-JVS(406)*X(22)&
            &-JVS(407)*X(23)-JVS(408)*X(24)-JVS(409)*X(26)-JVS(410)*X(27)-JVS(411)*X(28)-JVS(412)*X(29)-JVS(413)*X(31)&
            &-JVS(414)*X(32)-JVS(415)*X(33)-JVS(416)*X(34)-JVS(417)*X(35)-JVS(418)*X(36)-JVS(419)*X(37)-JVS(420)*X(38)&
            &-JVS(421)*X(39)-JVS(422)*X(40)-JVS(423)*X(41)-JVS(424)*X(42)-JVS(425)*X(43)
  X(45) = X(45)-JVS(435)*X(14)-JVS(436)*X(15)-JVS(437)*X(16)-JVS(438)*X(23)-JVS(439)*X(27)-JVS(440)*X(31)-JVS(441)*X(32)&
            &-JVS(442)*X(34)-JVS(443)*X(36)-JVS(444)*X(37)-JVS(445)*X(38)-JVS(446)*X(39)-JVS(447)*X(41)-JVS(448)*X(42)&
            &-JVS(449)*X(43)-JVS(450)*X(44)
  X(46) = X(46)-JVS(459)*X(16)-JVS(460)*X(17)-JVS(461)*X(23)-JVS(462)*X(27)-JVS(463)*X(29)-JVS(464)*X(34)-JVS(465)*X(36)&
            &-JVS(466)*X(37)-JVS(467)*X(39)-JVS(468)*X(40)-JVS(469)*X(41)-JVS(470)*X(42)-JVS(471)*X(43)-JVS(472)*X(44)&
            &-JVS(473)*X(45)
  X(47) = X(47)-JVS(481)*X(6)-JVS(482)*X(9)-JVS(483)*X(10)-JVS(484)*X(12)-JVS(485)*X(14)-JVS(486)*X(15)-JVS(487)*X(16)&
            &-JVS(488)*X(20)-JVS(489)*X(21)-JVS(490)*X(23)-JVS(491)*X(24)-JVS(492)*X(25)-JVS(493)*X(26)-JVS(494)*X(27)&
            &-JVS(495)*X(28)-JVS(496)*X(29)-JVS(497)*X(31)-JVS(498)*X(32)-JVS(499)*X(33)-JVS(500)*X(34)-JVS(501)*X(35)&
            &-JVS(502)*X(36)-JVS(503)*X(37)-JVS(504)*X(38)-JVS(505)*X(39)-JVS(506)*X(40)-JVS(507)*X(41)-JVS(508)*X(42)&
            &-JVS(509)*X(43)-JVS(510)*X(44)-JVS(511)*X(45)-JVS(512)*X(46)
  X(48) = X(48)-JVS(519)*X(17)-JVS(520)*X(18)-JVS(521)*X(19)-JVS(522)*X(20)-JVS(523)*X(24)-JVS(524)*X(25)-JVS(525)*X(28)&
            &-JVS(526)*X(29)-JVS(527)*X(30)-JVS(528)*X(31)-JVS(529)*X(32)-JVS(530)*X(33)-JVS(531)*X(34)-JVS(532)*X(35)&
            &-JVS(533)*X(36)-JVS(534)*X(37)-JVS(535)*X(38)-JVS(536)*X(39)-JVS(537)*X(40)-JVS(538)*X(41)-JVS(539)*X(42)&
            &-JVS(540)*X(43)-JVS(541)*X(44)-JVS(542)*X(45)-JVS(543)*X(46)-JVS(544)*X(47)
  X(49) = X(49)-JVS(550)*X(14)-JVS(551)*X(15)-JVS(552)*X(16)-JVS(553)*X(23)-JVS(554)*X(27)-JVS(555)*X(31)-JVS(556)*X(32)&
            &-JVS(557)*X(34)-JVS(558)*X(36)-JVS(559)*X(37)-JVS(560)*X(38)-JVS(561)*X(39)-JVS(562)*X(41)-JVS(563)*X(42)&
            &-JVS(564)*X(43)-JVS(565)*X(44)-JVS(566)*X(45)-JVS(567)*X(46)-JVS(568)*X(47)-JVS(569)*X(48)
  X(50) = X(50)-JVS(574)*X(10)-JVS(575)*X(11)-JVS(576)*X(13)-JVS(577)*X(19)-JVS(578)*X(21)-JVS(579)*X(30)-JVS(580)*X(31)&
            &-JVS(581)*X(32)-JVS(582)*X(34)-JVS(583)*X(36)-JVS(584)*X(37)-JVS(585)*X(38)-JVS(586)*X(39)-JVS(587)*X(41)&
            &-JVS(588)*X(42)-JVS(589)*X(43)-JVS(590)*X(44)-JVS(591)*X(45)-JVS(592)*X(46)-JVS(593)*X(47)-JVS(594)*X(48)&
            &-JVS(595)*X(49)
  X(51) = X(51)-JVS(599)*X(10)-JVS(600)*X(13)-JVS(601)*X(17)-JVS(602)*X(18)-JVS(603)*X(19)-JVS(604)*X(20)-JVS(605)*X(22)&
            &-JVS(606)*X(24)-JVS(607)*X(25)-JVS(608)*X(29)-JVS(609)*X(30)-JVS(610)*X(31)-JVS(611)*X(32)-JVS(612)*X(33)&
            &-JVS(613)*X(34)-JVS(614)*X(35)-JVS(615)*X(36)-JVS(616)*X(37)-JVS(617)*X(38)-JVS(618)*X(39)-JVS(619)*X(40)&
            &-JVS(620)*X(41)-JVS(621)*X(42)-JVS(622)*X(43)-JVS(623)*X(44)-JVS(624)*X(45)-JVS(625)*X(46)-JVS(626)*X(47)&
            &-JVS(627)*X(48)-JVS(628)*X(49)-JVS(629)*X(50)
  X(52) = X(52)-JVS(632)*X(18)-JVS(633)*X(23)-JVS(634)*X(27)-JVS(635)*X(31)-JVS(636)*X(34)-JVS(637)*X(35)-JVS(638)*X(36)&
            &-JVS(639)*X(37)-JVS(640)*X(38)-JVS(641)*X(39)-JVS(642)*X(41)-JVS(643)*X(42)-JVS(644)*X(43)-JVS(645)*X(44)&
            &-JVS(646)*X(45)-JVS(647)*X(46)-JVS(648)*X(47)-JVS(649)*X(48)-JVS(650)*X(49)-JVS(651)*X(50)-JVS(652)*X(51)
  X(52) = X(52)/JVS(653)
  X(51) = (X(51)-JVS(631)*X(52))/(JVS(630))
  X(50) = (X(50)-JVS(597)*X(51)-JVS(598)*X(52))/(JVS(596))
  X(49) = (X(49)-JVS(571)*X(50)-JVS(572)*X(51)-JVS(573)*X(52))/(JVS(570))
  X(48) = (X(48)-JVS(546)*X(49)-JVS(547)*X(50)-JVS(548)*X(51)-JVS(549)*X(52))/(JVS(545))
  X(47) = (X(47)-JVS(514)*X(48)-JVS(515)*X(49)-JVS(516)*X(50)-JVS(517)*X(51)-JVS(518)*X(52))/(JVS(513))
  X(46) = (X(46)-JVS(475)*X(47)-JVS(476)*X(48)-JVS(477)*X(49)-JVS(478)*X(50)-JVS(479)*X(51)-JVS(480)*X(52))/(JVS(474))
  X(45) = (X(45)-JVS(452)*X(46)-JVS(453)*X(47)-JVS(454)*X(48)-JVS(455)*X(49)-JVS(456)*X(50)-JVS(457)*X(51)-JVS(458)&
            &*X(52))/(JVS(451))
  X(44) = (X(44)-JVS(427)*X(45)-JVS(428)*X(46)-JVS(429)*X(47)-JVS(430)*X(48)-JVS(431)*X(49)-JVS(432)*X(50)-JVS(433)&
            &*X(51)-JVS(434)*X(52))/(JVS(426))
  X(43) = (X(43)-JVS(391)*X(44)-JVS(392)*X(45)-JVS(393)*X(46)-JVS(394)*X(47)-JVS(395)*X(48)-JVS(396)*X(49)-JVS(397)&
            &*X(50)-JVS(398)*X(51)-JVS(399)*X(52))/(JVS(390))
  X(42) = (X(42)-JVS(362)*X(44)-JVS(363)*X(46)-JVS(364)*X(47)-JVS(365)*X(48)-JVS(366)*X(50)-JVS(367)*X(51)-JVS(368)&
            &*X(52))/(JVS(361))
  X(41) = (X(41)-JVS(346)*X(44)-JVS(347)*X(46)-JVS(348)*X(47)-JVS(349)*X(48)-JVS(350)*X(50)-JVS(351)*X(51)-JVS(352)&
            &*X(52))/(JVS(345))
  X(40) = (X(40)-JVS(323)*X(41)-JVS(324)*X(42)-JVS(325)*X(43)-JVS(326)*X(44)-JVS(327)*X(45)-JVS(328)*X(46)-JVS(329)&
            &*X(47)-JVS(330)*X(48)-JVS(331)*X(49)-JVS(332)*X(50)-JVS(333)*X(51)-JVS(334)*X(52))/(JVS(322))
  X(39) = (X(39)-JVS(307)*X(41)-JVS(308)*X(47)-JVS(309)*X(48)-JVS(310)*X(50)-JVS(311)*X(51))/(JVS(306))
  X(38) = (X(38)-JVS(292)*X(39)-JVS(293)*X(41)-JVS(294)*X(45)-JVS(295)*X(47)-JVS(296)*X(48)-JVS(297)*X(50))/(JVS(291))
  X(37) = (X(37)-JVS(283)*X(39)-JVS(284)*X(41)-JVS(285)*X(47)-JVS(286)*X(48))/(JVS(282))
  X(36) = (X(36)-JVS(274)*X(39)-JVS(275)*X(41)-JVS(276)*X(47)-JVS(277)*X(48))/(JVS(273))
  X(35) = (X(35)-JVS(264)*X(36)-JVS(265)*X(37)-JVS(266)*X(38)-JVS(267)*X(39)-JVS(268)*X(41)-JVS(269)*X(42)-JVS(270)&
            &*X(47)-JVS(271)*X(48)-JVS(272)*X(49))/(JVS(263))
  X(34) = (X(34)-JVS(253)*X(39)-JVS(254)*X(41)-JVS(255)*X(47)-JVS(256)*X(48))/(JVS(252))
  X(33) = (X(33)-JVS(235)*X(34)-JVS(236)*X(36)-JVS(237)*X(37)-JVS(238)*X(38)-JVS(239)*X(39)-JVS(240)*X(40)-JVS(241)&
            &*X(41)-JVS(242)*X(42)-JVS(243)*X(43)-JVS(244)*X(45)-JVS(245)*X(46)-JVS(246)*X(47)-JVS(247)*X(48)-JVS(248)*X(49)&
            &-JVS(249)*X(50)-JVS(250)*X(51)-JVS(251)*X(52))/(JVS(234))
  X(32) = (X(32)-JVS(223)*X(39)-JVS(224)*X(41)-JVS(225)*X(47)-JVS(226)*X(48))/(JVS(222))
  X(31) = (X(31)-JVS(218)*X(39)-JVS(219)*X(41)-JVS(220)*X(47)-JVS(221)*X(48))/(JVS(217))
  X(30) = (X(30)-JVS(199)*X(31)-JVS(200)*X(32)-JVS(201)*X(34)-JVS(202)*X(36)-JVS(203)*X(37)-JVS(204)*X(38)-JVS(205)&
            &*X(39)-JVS(206)*X(41)-JVS(207)*X(42)-JVS(208)*X(43)-JVS(209)*X(44)-JVS(210)*X(45)-JVS(211)*X(46)-JVS(212)*X(47)&
            &-JVS(213)*X(48)-JVS(214)*X(49)-JVS(215)*X(50)-JVS(216)*X(52))/(JVS(198))
  X(29) = (X(29)-JVS(187)*X(34)-JVS(188)*X(37)-JVS(189)*X(39)-JVS(190)*X(41)-JVS(191)*X(44)-JVS(192)*X(47)-JVS(193)&
            &*X(48)-JVS(194)*X(51))/(JVS(186))
  X(28) = (X(28)-JVS(176)*X(39)-JVS(177)*X(41)-JVS(178)*X(47)-JVS(179)*X(48))/(JVS(175))
  X(27) = (X(27)-JVS(172)*X(37)-JVS(173)*X(41)-JVS(174)*X(47))/(JVS(171))
  X(26) = (X(26)-JVS(153)*X(27)-JVS(154)*X(28)-JVS(155)*X(29)-JVS(156)*X(31)-JVS(157)*X(32)-JVS(158)*X(33)-JVS(159)&
            &*X(34)-JVS(160)*X(35)-JVS(161)*X(36)-JVS(162)*X(37)-JVS(163)*X(39)-JVS(164)*X(40)-JVS(165)*X(41)-JVS(166)*X(47)&
            &-JVS(167)*X(48))/(JVS(152))
  X(25) = (X(25)-JVS(141)*X(29)-JVS(142)*X(33)-JVS(143)*X(35)-JVS(144)*X(37)-JVS(145)*X(40)-JVS(146)*X(44)-JVS(147)&
            &*X(47)-JVS(148)*X(48)-JVS(149)*X(51))/(JVS(140))
  X(24) = (X(24)-JVS(134)*X(44)-JVS(135)*X(47)-JVS(136)*X(48)-JVS(137)*X(51))/(JVS(133))
  X(23) = (X(23)-JVS(128)*X(41)-JVS(129)*X(47))/(JVS(127))
  X(22) = (X(22)-JVS(120)*X(24)-JVS(121)*X(44)-JVS(122)*X(47)-JVS(123)*X(48)-JVS(124)*X(51))/(JVS(119))
  X(21) = (X(21)-JVS(116)*X(41)-JVS(117)*X(50)-JVS(118)*X(51))/(JVS(115))
  X(20) = (X(20)-JVS(110)*X(44)-JVS(111)*X(47)-JVS(112)*X(51))/(JVS(109))
  X(19) = (X(19)-JVS(107)*X(48)-JVS(108)*X(51))/(JVS(106))
  X(18) = (X(18)-JVS(104)*X(51)-JVS(105)*X(52))/(JVS(103))
  X(17) = (X(17)-JVS(101)*X(46)-JVS(102)*X(51))/(JVS(100))
  X(16) = (X(16)-JVS(99)*X(47))/(JVS(98))
  X(15) = (X(15)-JVS(97)*X(47))/(JVS(96))
  X(14) = (X(14)-JVS(95)*X(47))/(JVS(94))
  X(13) = (X(13)-JVS(92)*X(50)-JVS(93)*X(51))/(JVS(91))
  X(12) = (X(12)-JVS(87)*X(43)-JVS(88)*X(44)-JVS(89)*X(45)-JVS(90)*X(47))/(JVS(86))
  X(11) = (X(11)-JVS(83)*X(13)-JVS(84)*X(21)-JVS(85)*X(51))/(JVS(82))
  X(10) = (X(10)-JVS(80)*X(47)-JVS(81)*X(50))/(JVS(79))
  X(9) = (X(9)-JVS(77)*X(44)-JVS(78)*X(47))/(JVS(76))
  X(8) = (X(8)-JVS(72)*X(31)-JVS(73)*X(44)-JVS(74)*X(47)-JVS(75)*X(50))/(JVS(71))
  X(7) = (X(7)-JVS(67)*X(8)-JVS(68)*X(44)-JVS(69)*X(47))/(JVS(66))
  X(6) = (X(6)-JVS(65)*X(47))/(JVS(64))
  X(5) = (X(5)-JVS(40)*X(14)-JVS(41)*X(15)-JVS(42)*X(16)-JVS(43)*X(22)-JVS(44)*X(23)-JVS(45)*X(24)-JVS(46)*X(27)-JVS(47)&
           &*X(28)-JVS(48)*X(31)-JVS(49)*X(32)-JVS(50)*X(34)-JVS(51)*X(36)-JVS(52)*X(37)-JVS(53)*X(38)-JVS(54)*X(39)-JVS(55)&
           &*X(41)-JVS(56)*X(42)-JVS(57)*X(44)-JVS(58)*X(46)-JVS(59)*X(47)-JVS(60)*X(48)-JVS(61)*X(49)-JVS(62)*X(51)-JVS(63)&
           &*X(52))/(JVS(39))
  X(4) = (X(4)-JVS(28)*X(22)-JVS(29)*X(28)-JVS(30)*X(31)-JVS(31)*X(32)-JVS(32)*X(34)-JVS(33)*X(36)-JVS(34)*X(37)-JVS(35)&
           &*X(38)-JVS(36)*X(47)-JVS(37)*X(48)-JVS(38)*X(51))/(JVS(27))
  X(3) = (X(3)-JVS(8)*X(17)-JVS(9)*X(18)-JVS(10)*X(23)-JVS(11)*X(26)-JVS(12)*X(27)-JVS(13)*X(28)-JVS(14)*X(31)-JVS(15)&
           &*X(32)-JVS(16)*X(34)-JVS(17)*X(36)-JVS(18)*X(37)-JVS(19)*X(41)-JVS(20)*X(43)-JVS(21)*X(45)-JVS(22)*X(46)-JVS(23)&
           &*X(47)-JVS(24)*X(48)-JVS(25)*X(50)-JVS(26)*X(52))/(JVS(7))
  X(2) = (X(2)-JVS(5)*X(6)-JVS(6)*X(47))/(JVS(4))
  X(1) = (X(1)-JVS(2)*X(7)-JVS(3)*X(47))/(JVS(1))

 END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(4)
  XX(3) = X(3)/JVS(7)
  XX(4) = X(4)/JVS(27)
  XX(5) = X(5)/JVS(39)
  XX(6) = (X(6)-JVS(5)*XX(2))/(JVS(64))
  XX(7) = (X(7)-JVS(2)*XX(1))/(JVS(66))
  XX(8) = (X(8)-JVS(67)*XX(7))/(JVS(71))
  XX(9) = X(9)/JVS(76)
  XX(10) = X(10)/JVS(79)
  XX(11) = X(11)/JVS(82)
  XX(12) = X(12)/JVS(86)
  XX(13) = (X(13)-JVS(83)*XX(11))/(JVS(91))
  XX(14) = (X(14)-JVS(40)*XX(5))/(JVS(94))
  XX(15) = (X(15)-JVS(41)*XX(5))/(JVS(96))
  XX(16) = (X(16)-JVS(42)*XX(5))/(JVS(98))
  XX(17) = (X(17)-JVS(8)*XX(3))/(JVS(100))
  XX(18) = (X(18)-JVS(9)*XX(3))/(JVS(103))
  XX(19) = X(19)/JVS(106)
  XX(20) = X(20)/JVS(109)
  XX(21) = (X(21)-JVS(84)*XX(11))/(JVS(115))
  XX(22) = (X(22)-JVS(28)*XX(4)-JVS(43)*XX(5))/(JVS(119))
  XX(23) = (X(23)-JVS(10)*XX(3)-JVS(44)*XX(5))/(JVS(127))
  XX(24) = (X(24)-JVS(45)*XX(5)-JVS(120)*XX(22))/(JVS(133))
  XX(25) = X(25)/JVS(140)
  XX(26) = (X(26)-JVS(11)*XX(3))/(JVS(152))
  XX(27) = (X(27)-JVS(12)*XX(3)-JVS(46)*XX(5)-JVS(153)*XX(26))/(JVS(171))
  XX(28) = (X(28)-JVS(13)*XX(3)-JVS(29)*XX(4)-JVS(47)*XX(5)-JVS(154)*XX(26))/(JVS(175))
  XX(29) = (X(29)-JVS(141)*XX(25)-JVS(155)*XX(26))/(JVS(186))
  XX(30) = X(30)/JVS(198)
  XX(31) = (X(31)-JVS(14)*XX(3)-JVS(30)*XX(4)-JVS(48)*XX(5)-JVS(72)*XX(8)-JVS(156)*XX(26)-JVS(199)*XX(30))/(JVS(217))
  XX(32) = (X(32)-JVS(15)*XX(3)-JVS(31)*XX(4)-JVS(49)*XX(5)-JVS(157)*XX(26)-JVS(200)*XX(30))/(JVS(222))
  XX(33) = (X(33)-JVS(142)*XX(25)-JVS(158)*XX(26))/(JVS(234))
  XX(34) = (X(34)-JVS(16)*XX(3)-JVS(32)*XX(4)-JVS(50)*XX(5)-JVS(159)*XX(26)-JVS(187)*XX(29)-JVS(201)*XX(30)-JVS(235)&
             &*XX(33))/(JVS(252))
  XX(35) = (X(35)-JVS(143)*XX(25)-JVS(160)*XX(26))/(JVS(263))
  XX(36) = (X(36)-JVS(17)*XX(3)-JVS(33)*XX(4)-JVS(51)*XX(5)-JVS(161)*XX(26)-JVS(202)*XX(30)-JVS(236)*XX(33)-JVS(264)&
             &*XX(35))/(JVS(273))
  XX(37) = (X(37)-JVS(18)*XX(3)-JVS(34)*XX(4)-JVS(52)*XX(5)-JVS(144)*XX(25)-JVS(162)*XX(26)-JVS(172)*XX(27)-JVS(188)&
             &*XX(29)-JVS(203)*XX(30)-JVS(237)*XX(33)-JVS(265)*XX(35))/(JVS(282))
  XX(38) = (X(38)-JVS(35)*XX(4)-JVS(53)*XX(5)-JVS(204)*XX(30)-JVS(238)*XX(33)-JVS(266)*XX(35))/(JVS(291))
  XX(39) = (X(39)-JVS(54)*XX(5)-JVS(163)*XX(26)-JVS(176)*XX(28)-JVS(189)*XX(29)-JVS(205)*XX(30)-JVS(218)*XX(31)-JVS(223)&
             &*XX(32)-JVS(239)*XX(33)-JVS(253)*XX(34)-JVS(267)*XX(35)-JVS(274)*XX(36)-JVS(283)*XX(37)-JVS(292)*XX(38))&
             &/(JVS(306))
  XX(40) = (X(40)-JVS(145)*XX(25)-JVS(164)*XX(26)-JVS(240)*XX(33))/(JVS(322))
  XX(41) = (X(41)-JVS(19)*XX(3)-JVS(55)*XX(5)-JVS(116)*XX(21)-JVS(128)*XX(23)-JVS(165)*XX(26)-JVS(173)*XX(27)-JVS(177)&
             &*XX(28)-JVS(190)*XX(29)-JVS(206)*XX(30)-JVS(219)*XX(31)-JVS(224)*XX(32)-JVS(241)*XX(33)-JVS(254)*XX(34)&
             &-JVS(268)*XX(35)-JVS(275)*XX(36)-JVS(284)*XX(37)-JVS(293)*XX(38)-JVS(307)*XX(39)-JVS(323)*XX(40))/(JVS(345))
  XX(42) = (X(42)-JVS(56)*XX(5)-JVS(207)*XX(30)-JVS(242)*XX(33)-JVS(269)*XX(35)-JVS(324)*XX(40))/(JVS(361))
  XX(43) = (X(43)-JVS(20)*XX(3)-JVS(87)*XX(12)-JVS(208)*XX(30)-JVS(243)*XX(33)-JVS(325)*XX(40))/(JVS(390))
  XX(44) = (X(44)-JVS(57)*XX(5)-JVS(68)*XX(7)-JVS(73)*XX(8)-JVS(77)*XX(9)-JVS(88)*XX(12)-JVS(110)*XX(20)-JVS(121)*XX(22)&
             &-JVS(134)*XX(24)-JVS(146)*XX(25)-JVS(191)*XX(29)-JVS(209)*XX(30)-JVS(326)*XX(40)-JVS(346)*XX(41)-JVS(362)&
             &*XX(42)-JVS(391)*XX(43))/(JVS(426))
  XX(45) = (X(45)-JVS(21)*XX(3)-JVS(89)*XX(12)-JVS(210)*XX(30)-JVS(244)*XX(33)-JVS(294)*XX(38)-JVS(327)*XX(40)-JVS(392)&
             &*XX(43)-JVS(427)*XX(44))/(JVS(451))
  XX(46) = (X(46)-JVS(22)*XX(3)-JVS(58)*XX(5)-JVS(101)*XX(17)-JVS(211)*XX(30)-JVS(245)*XX(33)-JVS(328)*XX(40)-JVS(347)&
             &*XX(41)-JVS(363)*XX(42)-JVS(393)*XX(43)-JVS(428)*XX(44)-JVS(452)*XX(45))/(JVS(474))
  XX(47) = (X(47)-JVS(3)*XX(1)-JVS(6)*XX(2)-JVS(23)*XX(3)-JVS(36)*XX(4)-JVS(59)*XX(5)-JVS(65)*XX(6)-JVS(69)*XX(7)&
             &-JVS(74)*XX(8)-JVS(78)*XX(9)-JVS(80)*XX(10)-JVS(90)*XX(12)-JVS(95)*XX(14)-JVS(97)*XX(15)-JVS(99)*XX(16)&
             &-JVS(111)*XX(20)-JVS(122)*XX(22)-JVS(129)*XX(23)-JVS(135)*XX(24)-JVS(147)*XX(25)-JVS(166)*XX(26)-JVS(174)&
             &*XX(27)-JVS(178)*XX(28)-JVS(192)*XX(29)-JVS(212)*XX(30)-JVS(220)*XX(31)-JVS(225)*XX(32)-JVS(246)*XX(33)&
             &-JVS(255)*XX(34)-JVS(270)*XX(35)-JVS(276)*XX(36)-JVS(285)*XX(37)-JVS(295)*XX(38)-JVS(308)*XX(39)-JVS(329)&
             &*XX(40)-JVS(348)*XX(41)-JVS(364)*XX(42)-JVS(394)*XX(43)-JVS(429)*XX(44)-JVS(453)*XX(45)-JVS(475)*XX(46))&
             &/(JVS(513))
  XX(48) = (X(48)-JVS(24)*XX(3)-JVS(37)*XX(4)-JVS(60)*XX(5)-JVS(107)*XX(19)-JVS(123)*XX(22)-JVS(136)*XX(24)-JVS(148)&
             &*XX(25)-JVS(167)*XX(26)-JVS(179)*XX(28)-JVS(193)*XX(29)-JVS(213)*XX(30)-JVS(221)*XX(31)-JVS(226)*XX(32)&
             &-JVS(247)*XX(33)-JVS(256)*XX(34)-JVS(271)*XX(35)-JVS(277)*XX(36)-JVS(286)*XX(37)-JVS(296)*XX(38)-JVS(309)&
             &*XX(39)-JVS(330)*XX(40)-JVS(349)*XX(41)-JVS(365)*XX(42)-JVS(395)*XX(43)-JVS(430)*XX(44)-JVS(454)*XX(45)&
             &-JVS(476)*XX(46)-JVS(514)*XX(47))/(JVS(545))
  XX(49) = (X(49)-JVS(61)*XX(5)-JVS(214)*XX(30)-JVS(248)*XX(33)-JVS(272)*XX(35)-JVS(331)*XX(40)-JVS(396)*XX(43)-JVS(431)&
             &*XX(44)-JVS(455)*XX(45)-JVS(477)*XX(46)-JVS(515)*XX(47)-JVS(546)*XX(48))/(JVS(570))
  XX(50) = (X(50)-JVS(25)*XX(3)-JVS(75)*XX(8)-JVS(81)*XX(10)-JVS(92)*XX(13)-JVS(117)*XX(21)-JVS(215)*XX(30)-JVS(249)&
             &*XX(33)-JVS(297)*XX(38)-JVS(310)*XX(39)-JVS(332)*XX(40)-JVS(350)*XX(41)-JVS(366)*XX(42)-JVS(397)*XX(43)&
             &-JVS(432)*XX(44)-JVS(456)*XX(45)-JVS(478)*XX(46)-JVS(516)*XX(47)-JVS(547)*XX(48)-JVS(571)*XX(49))/(JVS(596))
  XX(51) = (X(51)-JVS(38)*XX(4)-JVS(62)*XX(5)-JVS(85)*XX(11)-JVS(93)*XX(13)-JVS(102)*XX(17)-JVS(104)*XX(18)-JVS(108)&
             &*XX(19)-JVS(112)*XX(20)-JVS(118)*XX(21)-JVS(124)*XX(22)-JVS(137)*XX(24)-JVS(149)*XX(25)-JVS(194)*XX(29)&
             &-JVS(250)*XX(33)-JVS(311)*XX(39)-JVS(333)*XX(40)-JVS(351)*XX(41)-JVS(367)*XX(42)-JVS(398)*XX(43)-JVS(433)&
             &*XX(44)-JVS(457)*XX(45)-JVS(479)*XX(46)-JVS(517)*XX(47)-JVS(548)*XX(48)-JVS(572)*XX(49)-JVS(597)*XX(50))&
             &/(JVS(630))
  XX(52) = (X(52)-JVS(26)*XX(3)-JVS(63)*XX(5)-JVS(105)*XX(18)-JVS(216)*XX(30)-JVS(251)*XX(33)-JVS(334)*XX(40)-JVS(352)&
             &*XX(41)-JVS(368)*XX(42)-JVS(399)*XX(43)-JVS(434)*XX(44)-JVS(458)*XX(45)-JVS(480)*XX(46)-JVS(518)*XX(47)&
             &-JVS(549)*XX(48)-JVS(573)*XX(49)-JVS(598)*XX(50)-JVS(631)*XX(51))/(JVS(653))
  XX(52) = XX(52)
  XX(51) = XX(51)-JVS(652)*XX(52)
  XX(50) = XX(50)-JVS(629)*XX(51)-JVS(651)*XX(52)
  XX(49) = XX(49)-JVS(595)*XX(50)-JVS(628)*XX(51)-JVS(650)*XX(52)
  XX(48) = XX(48)-JVS(569)*XX(49)-JVS(594)*XX(50)-JVS(627)*XX(51)-JVS(649)*XX(52)
  XX(47) = XX(47)-JVS(544)*XX(48)-JVS(568)*XX(49)-JVS(593)*XX(50)-JVS(626)*XX(51)-JVS(648)*XX(52)
  XX(46) = XX(46)-JVS(512)*XX(47)-JVS(543)*XX(48)-JVS(567)*XX(49)-JVS(592)*XX(50)-JVS(625)*XX(51)-JVS(647)*XX(52)
  XX(45) = XX(45)-JVS(473)*XX(46)-JVS(511)*XX(47)-JVS(542)*XX(48)-JVS(566)*XX(49)-JVS(591)*XX(50)-JVS(624)*XX(51)&
             &-JVS(646)*XX(52)
  XX(44) = XX(44)-JVS(450)*XX(45)-JVS(472)*XX(46)-JVS(510)*XX(47)-JVS(541)*XX(48)-JVS(565)*XX(49)-JVS(590)*XX(50)&
             &-JVS(623)*XX(51)-JVS(645)*XX(52)
  XX(43) = XX(43)-JVS(425)*XX(44)-JVS(449)*XX(45)-JVS(471)*XX(46)-JVS(509)*XX(47)-JVS(540)*XX(48)-JVS(564)*XX(49)&
             &-JVS(589)*XX(50)-JVS(622)*XX(51)-JVS(644)*XX(52)
  XX(42) = XX(42)-JVS(389)*XX(43)-JVS(424)*XX(44)-JVS(448)*XX(45)-JVS(470)*XX(46)-JVS(508)*XX(47)-JVS(539)*XX(48)&
             &-JVS(563)*XX(49)-JVS(588)*XX(50)-JVS(621)*XX(51)-JVS(643)*XX(52)
  XX(41) = XX(41)-JVS(360)*XX(42)-JVS(388)*XX(43)-JVS(423)*XX(44)-JVS(447)*XX(45)-JVS(469)*XX(46)-JVS(507)*XX(47)&
             &-JVS(538)*XX(48)-JVS(562)*XX(49)-JVS(587)*XX(50)-JVS(620)*XX(51)-JVS(642)*XX(52)
  XX(40) = XX(40)-JVS(387)*XX(43)-JVS(422)*XX(44)-JVS(468)*XX(46)-JVS(506)*XX(47)-JVS(537)*XX(48)-JVS(619)*XX(51)
  XX(39) = XX(39)-JVS(321)*XX(40)-JVS(344)*XX(41)-JVS(359)*XX(42)-JVS(386)*XX(43)-JVS(421)*XX(44)-JVS(446)*XX(45)&
             &-JVS(467)*XX(46)-JVS(505)*XX(47)-JVS(536)*XX(48)-JVS(561)*XX(49)-JVS(586)*XX(50)-JVS(618)*XX(51)-JVS(641)&
             &*XX(52)
  XX(38) = XX(38)-JVS(320)*XX(40)-JVS(385)*XX(43)-JVS(420)*XX(44)-JVS(445)*XX(45)-JVS(504)*XX(47)-JVS(535)*XX(48)&
             &-JVS(560)*XX(49)-JVS(585)*XX(50)-JVS(617)*XX(51)-JVS(640)*XX(52)
  XX(37) = XX(37)-JVS(290)*XX(38)-JVS(319)*XX(40)-JVS(343)*XX(41)-JVS(358)*XX(42)-JVS(384)*XX(43)-JVS(419)*XX(44)&
             &-JVS(444)*XX(45)-JVS(466)*XX(46)-JVS(503)*XX(47)-JVS(534)*XX(48)-JVS(559)*XX(49)-JVS(584)*XX(50)-JVS(616)&
             &*XX(51)-JVS(639)*XX(52)
  XX(36) = XX(36)-JVS(281)*XX(37)-JVS(289)*XX(38)-JVS(305)*XX(39)-JVS(318)*XX(40)-JVS(342)*XX(41)-JVS(357)*XX(42)&
             &-JVS(383)*XX(43)-JVS(418)*XX(44)-JVS(443)*XX(45)-JVS(465)*XX(46)-JVS(502)*XX(47)-JVS(533)*XX(48)-JVS(558)&
             &*XX(49)-JVS(583)*XX(50)-JVS(615)*XX(51)-JVS(638)*XX(52)
  XX(35) = XX(35)-JVS(317)*XX(40)-JVS(382)*XX(43)-JVS(417)*XX(44)-JVS(501)*XX(47)-JVS(532)*XX(48)-JVS(614)*XX(51)&
             &-JVS(637)*XX(52)
  XX(34) = XX(34)-JVS(262)*XX(35)-JVS(280)*XX(37)-JVS(288)*XX(38)-JVS(304)*XX(39)-JVS(316)*XX(40)-JVS(341)*XX(41)&
             &-JVS(356)*XX(42)-JVS(381)*XX(43)-JVS(416)*XX(44)-JVS(442)*XX(45)-JVS(464)*XX(46)-JVS(500)*XX(47)-JVS(531)&
             &*XX(48)-JVS(557)*XX(49)-JVS(582)*XX(50)-JVS(613)*XX(51)-JVS(636)*XX(52)
  XX(33) = XX(33)-JVS(415)*XX(44)-JVS(499)*XX(47)-JVS(530)*XX(48)-JVS(612)*XX(51)
  XX(32) = XX(32)-JVS(233)*XX(33)-JVS(261)*XX(35)-JVS(279)*XX(37)-JVS(287)*XX(38)-JVS(303)*XX(39)-JVS(315)*XX(40)&
             &-JVS(340)*XX(41)-JVS(355)*XX(42)-JVS(380)*XX(43)-JVS(414)*XX(44)-JVS(441)*XX(45)-JVS(498)*XX(47)-JVS(529)&
             &*XX(48)-JVS(556)*XX(49)-JVS(581)*XX(50)-JVS(611)*XX(51)
  XX(31) = XX(31)-JVS(232)*XX(33)-JVS(278)*XX(37)-JVS(302)*XX(39)-JVS(339)*XX(41)-JVS(354)*XX(42)-JVS(379)*XX(43)&
             &-JVS(413)*XX(44)-JVS(440)*XX(45)-JVS(497)*XX(47)-JVS(528)*XX(48)-JVS(555)*XX(49)-JVS(580)*XX(50)-JVS(610)&
             &*XX(51)-JVS(635)*XX(52)
  XX(30) = XX(30)-JVS(527)*XX(48)-JVS(579)*XX(50)-JVS(609)*XX(51)
  XX(29) = XX(29)-JVS(412)*XX(44)-JVS(463)*XX(46)-JVS(496)*XX(47)-JVS(526)*XX(48)-JVS(608)*XX(51)
  XX(28) = XX(28)-JVS(185)*XX(29)-JVS(231)*XX(33)-JVS(260)*XX(35)-JVS(301)*XX(39)-JVS(314)*XX(40)-JVS(338)*XX(41)&
             &-JVS(353)*XX(42)-JVS(378)*XX(43)-JVS(411)*XX(44)-JVS(495)*XX(47)-JVS(525)*XX(48)
  XX(27) = XX(27)-JVS(184)*XX(29)-JVS(197)*XX(30)-JVS(230)*XX(33)-JVS(259)*XX(35)-JVS(337)*XX(41)-JVS(377)*XX(43)&
             &-JVS(410)*XX(44)-JVS(439)*XX(45)-JVS(462)*XX(46)-JVS(494)*XX(47)-JVS(554)*XX(49)-JVS(634)*XX(52)
  XX(26) = XX(26)-JVS(409)*XX(44)-JVS(493)*XX(47)
  XX(25) = XX(25)-JVS(492)*XX(47)-JVS(524)*XX(48)-JVS(607)*XX(51)
  XX(24) = XX(24)-JVS(139)*XX(25)-JVS(183)*XX(29)-JVS(376)*XX(43)-JVS(408)*XX(44)-JVS(491)*XX(47)-JVS(523)*XX(48)&
             &-JVS(606)*XX(51)
  XX(23) = XX(23)-JVS(151)*XX(26)-JVS(170)*XX(27)-JVS(182)*XX(29)-JVS(196)*XX(30)-JVS(229)*XX(33)-JVS(258)*XX(35)&
             &-JVS(336)*XX(41)-JVS(375)*XX(43)-JVS(407)*XX(44)-JVS(438)*XX(45)-JVS(461)*XX(46)-JVS(490)*XX(47)-JVS(553)&
             &*XX(49)-JVS(633)*XX(52)
  XX(22) = XX(22)-JVS(132)*XX(24)-JVS(374)*XX(43)-JVS(406)*XX(44)-JVS(605)*XX(51)
  XX(21) = XX(21)-JVS(300)*XX(39)-JVS(335)*XX(41)-JVS(489)*XX(47)-JVS(578)*XX(50)
  XX(20) = XX(20)-JVS(405)*XX(44)-JVS(488)*XX(47)-JVS(522)*XX(48)-JVS(604)*XX(51)
  XX(19) = XX(19)-JVS(138)*XX(25)-JVS(299)*XX(39)-JVS(521)*XX(48)-JVS(577)*XX(50)-JVS(603)*XX(51)
  XX(18) = XX(18)-JVS(313)*XX(40)-JVS(373)*XX(43)-JVS(520)*XX(48)-JVS(602)*XX(51)-JVS(632)*XX(52)
  XX(17) = XX(17)-JVS(228)*XX(33)-JVS(372)*XX(43)-JVS(460)*XX(46)-JVS(519)*XX(48)-JVS(601)*XX(51)
  XX(16) = XX(16)-JVS(150)*XX(26)-JVS(195)*XX(30)-JVS(227)*XX(33)-JVS(257)*XX(35)-JVS(312)*XX(40)-JVS(371)*XX(43)&
             &-JVS(437)*XX(45)-JVS(459)*XX(46)-JVS(487)*XX(47)-JVS(552)*XX(49)
  XX(15) = XX(15)-JVS(126)*XX(23)-JVS(131)*XX(24)-JVS(169)*XX(27)-JVS(181)*XX(29)-JVS(370)*XX(43)-JVS(404)*XX(44)&
             &-JVS(436)*XX(45)-JVS(486)*XX(47)-JVS(551)*XX(49)
  XX(14) = XX(14)-JVS(125)*XX(23)-JVS(130)*XX(24)-JVS(168)*XX(27)-JVS(180)*XX(29)-JVS(369)*XX(43)-JVS(403)*XX(44)&
             &-JVS(435)*XX(45)-JVS(485)*XX(47)-JVS(550)*XX(49)
  XX(13) = XX(13)-JVS(114)*XX(21)-JVS(298)*XX(39)-JVS(576)*XX(50)-JVS(600)*XX(51)
  XX(12) = XX(12)-JVS(402)*XX(44)-JVS(484)*XX(47)
  XX(11) = XX(11)-JVS(113)*XX(21)-JVS(575)*XX(50)
  XX(10) = XX(10)-JVS(483)*XX(47)-JVS(574)*XX(50)-JVS(599)*XX(51)
  XX(9) = XX(9)-JVS(401)*XX(44)-JVS(482)*XX(47)
  XX(8) = XX(8)
  XX(7) = XX(7)-JVS(70)*XX(8)
  XX(6) = XX(6)-JVS(400)*XX(44)-JVS(481)*XX(47)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)

 END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!--------------------------------------------------------------
      SUBROUTINE WGEFA(N,A,Ipvt,info)
!--------------------------------------------------------------
!     WGEFA FACTORS THE MATRIX A (N,N) BY
!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!     LINPACK - LIKE
!--------------------------------------------------------------
!
      INTEGER       :: N,Ipvt(N),info
      REAL(kind=dp) :: A(N,N)
      REAL(kind=dp) :: t, dmax, da
      INTEGER       :: j,k,l
      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
      external dscal, daxpy
      info = 0

size: IF (n > 1) THEN

col:  DO k = 1, n-1

!        find l = pivot index
!        l = idamax(n-k+1,A(k,k),1) + k - 1
         l = k; dmax = abs(A(k,k))
         DO j = k+1,n
            da = ABS(A(j,k))
            IF (da > dmax) THEN
              l = j; dmax = da
            END IF
         END DO
         Ipvt(k) = l

!        zero pivot implies this column already triangularized
         IF (ABS(A(l,k)) < TINY(ZERO)) THEN
            info = k
            return
         ELSE
            IF (l /= k) THEN
               t = A(l,k); A(l,k) = A(k,k); A(k,k) = t
            END IF
            t = -ONE/A(k,k)
            CALL DSCAL(n-k,t,A(k+1,k),1)
            DO j = k+1, n
               t = A(l,j)
               IF (l /= k) THEN
                  A(l,j) = A(k,j); A(k,j) = t
               END IF
               CALL DAXPY(n-k,t,A(k+1,k),1,A(k+1,j),1)
            END DO
         END IF

       END DO col

      END IF size

      Ipvt(N) = N
      IF (ABS(A(N,N)) == ZERO) info = N

      END SUBROUTINE WGEFA


!--------------------------------------------------------------
      SUBROUTINE WGESL(Trans,N,A,Ipvt,b)
!--------------------------------------------------------------
!     WGESL solves the system
!     a * x = b  or  trans(a) * x = b
!     using the factors computed by WGEFA.
!
!     Trans      = 'N'   to solve  A*x = b ,
!                = 'T'   to solve  transpose(A)*x = b
!     LINPACK - LIKE
!--------------------------------------------------------------

      INTEGER       :: N,Ipvt(N)
      CHARACTER     :: trans
      REAL(kind=dp) :: A(N,N),b(N)
      REAL(kind=dp) :: t
      INTEGER       :: k,kb,l
      REAL(kind=8), external :: ddot ! provided by the MKL library
      external dscal, daxpy
      SELECT CASE (Trans)

      CASE ('n','N')  !  Solve  A * x = b

!        first solve  L*y = b
         IF (n >= 2) THEN
          DO k = 1, n-1
            l = Ipvt(k)
            t = b(l)
            IF (l /= k) THEN
               b(l) = b(k)
               b(k) = t
            END IF
            CALL DAXPY(n-k,t,a(k+1,k),1,b(k+1),1)
          END DO
         END IF
!        now solve  U*x = y
         DO kb = 1, n
            k = n + 1 - kb
            b(k) = b(k)/a(k,k)
            t = -b(k)
            CALL DAXPY(k-1,t,a(1,k),1,b(1),1)
         END DO

      CASE ('t','T')  !  Solve transpose(A) * x = b

!        first solve  trans(U)*y = b
         DO k = 1, n
            t = DDOT(k-1,a(1,k),1,b(1),1)
            b(k) = (b(k) - t)/a(k,k)
         END DO
!        now solve trans(L)*x = y
         IF (n >= 2) THEN
         DO kb = 1, n-1
            k = n - kb
            b(k) = b(k) + DDOT(n-k,a(k+1,k),1,b(k+1),1)
            l = Ipvt(k)
            IF (l /= k) THEN
               t = b(l); b(l) = b(k); b(k) = t
            END IF
         END DO
         END IF

      END SELECT

      END SUBROUTINE WGESL
! End of BLAS_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mach_kpp_saprc07cs_LinearAlgebra

