!---------------------------------- LICENCE BEGIN -------------------------------
! GEM-MACH - Atmospheric chemistry library for the GEM numerical atmospheric model
! Copyright (C) 2007-2013 - Air Quality Research Division &
!                           National Prediction Operations division
!                           Environnement Canada
! This library is free software; you can redistribute it and/or
! modify it under the terms of the GNU Lesser General Public
! License as published by the Free Software Foundation; either
! version 2.1 of the License, or (at your option) any later version.
!
! This library is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
! Lesser General Public License for more details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with this library; if not, write to the Free Software
! Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
!---------------------------------- LICENCE END ---------------------------------

!============================================================================!
!         Environnement Canada         |        Environment Canada           !
!                                      |                                     !
! - Service meteorologique du Canada   | - Meteorological Service of Canada  !
! - Direction generale des sciences    | - Science and Technology Branch     !
!   et de la technologie               |                                     !
!============================================================================!
!                            http://www.ec.gc.ca                             !
!============================================================================!
!
! Projet/Project : GEM-MACH
! Fichier/File   : mach_kppb_adom2day_rodas3.ftn90
! Creation       : K. Toyota, J. Chen, C. Stroud & M. Russell, Dec 2017 for GEM-MACH
!
! Description    : "KPPb" version of RODAS-3 solver for ADOM-II gas-phase chemistry
!
! Extra info     : This file contains additional subroutines, namely:
!                  - Fun_day (calculate the net tendencies for concentrations of chemical species)
!                  - Jac_SP_day (calculate the values of non-zero Jacobian elements)
!                  - ros_PrepareMatrix_day (calculate I/(H*ros_gamma)-Jac)
!                  - KppDecomp_day (perform the LU factorization of I/(H*ros_gamma)-Jac)
!                  - KppSolve_day (solve the matrix inversion problem, y=A^{-1}*b)
!
! Adapted from   : Rosenbrock-rodas3 subroutine(s) generated by KPP v2.2.3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!  By default the code employs the KPP sparse linear algebra routines     !
!                                                                         !
!    (C)  Adrian Sandu, August 2004                                       !
!    Virginia Polytechnic Institute and State University                  !
!    Contact: sandu@cs.vt.edu                                             !
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  !                               !
!    This implementation is part of KPP - the Kinetic PreProcessor        !
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!
! Arguments:  IN
!               delt     -> chm. timestep interval (min)
!               fix      -> Fixed concentrations of gaseous species (CH4, C2H6, H2O, O2 & M)
!               rconst   -> Reaction rate coefficients
!               bgs      -> Reaction product stochiometric coefficients
!               AbsTol   -> Absolute tolerance for solution convergence used by the solver
!               RelTol   -> Relative tolerance for solution convergence used by the solver
!
!             INOUT
!               Y       -> Concentrations of gaseous species (ppmv)
!               H       -> Initial guess for solver timestep interval (min) at the entry &
!                          exit of this subroutine; within the core of the subroutine, H means
!                          the actual time step interval used for the numerical integration
!             OUT
!               IERR    -> Error code
!
!============================================================================
!
!!if_on
SUBROUTINE mach_kppb_adom2day_rodas3(N, Y, nfix, fix, nreact, rconst, nprcf, bgs, &
                     delt, H, RelTol, AbsTol, IERR)
!!if_off
   IMPLICIT NONE
!!if_on
   integer(kind=4), intent(in) :: N, nfix, nreact, nprcf
   REAL(kind=8), INTENT(IN) ::  fix(nfix)
   REAL(kind=4), INTENT(IN) ::  delt
   REAL(kind=8), INTENT(IN) ::  rconst(nreact), bgs(nprcf)
   REAL(kind=8), INTENT(IN) ::  AbsTol(N), RelTol(N)
   INTEGER(kind=4), INTENT(OUT) :: IERR
   REAL(kind=8), INTENT(INOUT) :: H, Y(N)
!!if_off
!~~~~ rodas3 parameters
   INTEGER(kind=4), parameter ::  ros_S=4
   REAL(kind=8), parameter :: ros_ELO = 3.0d0
   REAL(kind=8), parameter, dimension(6) :: ros_A = &
            (/ 0.0d0, 2.0d0, 0.0d0, 2.0d0, 0.0d0, 1.0d0/)
   REAL(kind=8), parameter, dimension(6) :: ros_C = &
            (/ 4.0d0, 1.0d0,-1.0d0, 1.0d0,-1.0d0,-(8.0d0/3.0d0)/)
   REAL(kind=8), parameter :: ros_Gamma = 0.5d0
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 432
!~~~~ local variables
   integer(kind=4) :: nstp
   REAL(kind=8) :: T, Tstart,Tend, Hmin, Hmax
   REAL(kind=8) :: Roundoff
   REAL(kind=8) :: Ynew(N), Fcn0(N), Fcn(N)
   REAL(kind=8) :: K(N*ros_S)
   REAL(kind=8) :: Jac0(LU_NONZERO), Ghimj(LU_NONZERO)
   REAL(kind=8) :: Hnew, HC, Fac, Hexit
   REAL(kind=8) :: Err, Yerr(N)
   INTEGER(kind=4) :: ioffset, j, istage
   LOGICAL :: RejectLastH, RejectMoreH, Singular
!~~~>  Local parameters
   INTEGER(kind=4), parameter :: Max_no_steps=200000
   REAL(kind=8), PARAMETER :: ZERO = 0.0d0, ONE  = 1.0d0
   REAL(kind=8), parameter :: FacMin=0.2d0, FacMax=6.0d0, &
                              FacRej=0.1d0, FacSafe=0.9d0
   REAL(kind=8), PARAMETER :: DeltaMin = 1.6666667d-7

   EXTERNAL DSCAL, DAXPY

!   write(0,*) 'in rodas3: rconst=', rconst
!   write(0,*) 'in rodas3: bgs=', bgs
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~>  Initial preparations
   Roundoff = epsilon(ONE)
   nstp = 0
   Tstart = ZERO
   Tend = Tstart + dble(delt)
   T = Tstart
   Hexit = ZERO
   Hmin = ZERO
   Hmax = dble(delt)
   IF (H <= 10.0d0*Roundoff) H = DeltaMin
   RejectLastH=.FALSE.
   RejectMoreH=.FALSE.
!~~~> Time loop begins below
TimeLoop: DO WHILE ( (T-Tend)+Roundoff <= ZERO )
   IF ( Nstp > Max_no_steps ) THEN
      IERR=-6
      RETURN
   END IF
   IF ( ((T+0.1d0*H) == T).OR.(H <= Roundoff) ) THEN
      IERR=-7
      RETURN
   END IF
!~~~>  Limit H if necessary to avoid going beyond Tend
   Hexit = H
   H = MIN(H,Tend-T)
!~~~>   Compute the function at current time
   CALL Fun_day( Y, FIX, RCONST, BGS, Fcn0, n, nfix, nreact, nprcf )
!~~~>   Compute the Jacobian at current time
   CALL Jac_SP_day( Y, FIX, RCONST, BGS, Jac0, n, nfix, nreact, nprcf, LU_NONZERO )
!~~~>  Repeat step calculation until current step accepted
UntilAccepted: DO
    CALL ros_PrepareMatrix_day(H,ros_Gamma,Jac0,Ghimj,Singular)
   IF (Singular) THEN
       IERR=-8
       RETURN
   END IF
!~~~>   Compute the stages
Stage: DO istage = 1, ros_S

       ioffset = N*(istage-1)

       IF ( istage == 1 ) THEN
         Fcn(1:N) = Fcn0(1:N)

       ELSEIF ( istage == 3 ) THEN
         do j = 1, N
           Ynew(j) = Y(j) + ros_A(2)*K(j)
         enddo
         CALL Fun_day( Ynew, FIX, RCONST, BGS, Fcn, n, nfix, nreact, nprcf )
       ELSEIF ( istage == 4 ) THEN
         do j=1,N
            Ynew(j) = Y(j) + ros_A(4)*K(j) + ros_A(6)*K(2*N+j)
         enddo
         CALL Fun_day( Ynew, FIX, RCONST, BGS, Fcn, n, nfix, nreact, nprcf )
       END IF
       K(ioffset+1:ioffset+N)=Fcn(1:N)
       DO j = 1, istage-1
         HC = ros_C((istage-1)*(istage-2)/2+j)/H
!         do i = 1, N
!            K(ioffset+i) = K(ioffset+i) + HC*K(N*(j-1)+i)
!         end do
         CALL DAXPY(N,HC,K(N*(j-1)+1),1,K(ioffset+1),1)
       END DO
       CALL KppSolve_day( Ghimj, K(ioffset+1),N,LU_NONZERO)
   END DO Stage
!~~~>  Compute the new solution and the error estimation
   DO j = 1, N
      Ynew(j) = Y(j) + 2.0d0*K(j) + K(2*N+j) + K(3*N+j)
      Yerr(j) = K(3*N+j)
   END DO
   Err = ros_ErrorNorm ( Y, Ynew, Yerr, AbsTol, RelTol )
!~~~> New step size is bounded by FacMin <= Hnew/H <= FacMax
   Fac  = MIN(FacMax,MAX(FacMin,FacSafe/Err**(ONE/ros_ELO)))
   Hnew = H*Fac
!~~~>  Check the error magnitude and adjust step size
   Nstp = Nstp + 1
   IF ( (Err <= ONE).OR.(H <= Hmin) ) THEN
      Y(1:N) = Ynew(1:N)
      T = T + H
      Hnew = MAX(Hmin,MIN(Hnew,Hmax))
      IF (RejectLastH) THEN
         Hnew = MIN(Hnew,H)
      END IF
      RejectLastH = .FALSE.
      RejectMoreH = .FALSE.
      H = Hnew
      EXIT UntilAccepted
   ELSE
      IF (RejectMoreH) THEN
         Hnew = H*FacRej
      END IF
      RejectMoreH = RejectLastH
      RejectLastH = .TRUE.
      H = Hnew
   END IF
   END DO UntilAccepted
   END DO TimeLoop
!~~~> Succesful exit
   IERR = 1
   H = Hexit

  RETURN

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Contains ! Subroutines internal to rodas3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun_day ( V, F, RCT, BGS, Vdot, nvar, nfix, nreact, nprcf )
  IMPLICIT NONE
  integer(kind=4), intent(in) :: nvar, nfix, nreact, nprcf
  real(kind=8), intent(in) :: rct(nreact)
  real(kind=8), intent(in) :: BGS(nprcf)
  real(kind=8), intent(in) :: v(nvar), f(nfix)
  real(kind=8), intent(out) :: vdot(nvar)
! Local variables
  real(kind=8) :: A(NREACT)

! Computation of equation rates
  A(1) = RCT(1)*V(32)
  A(2) = RCT(2)*V(26)*F(4)*F(5)
  A(3) = RCT(3)*V(26)*V(32)
  A(4) = RCT(4)*V(26)*V(32)
  A(5) = RCT(5)*V(28)*V(34)
  A(6) = RCT(6)*V(28)*V(32)
  A(7) = RCT(7)*V(30)*V(34)
  A(8) = RCT(8)*V(34)*V(34)*F(4)
  A(9) = RCT(9)*V(30)*V(32)
  A(10) = RCT(10)*V(7)
  A(11) = RCT(11)*V(7)*F(3)
  A(12) = RCT(12)*V(30)*V(32)
  A(13) = RCT(13)*V(30)
  A(14) = RCT(14)*V(30)
  A(15) = RCT(15)*V(28)
  A(16) = RCT(16)*V(28)
  A(17) = RCT(17)*V(2)*F(3)
  A(18) = RCT(18)*V(2)*F(5)
  A(19) = RCT(19)*V(33)*V(34)
  A(20) = RCT(20)*V(6)
  A(21) = RCT(21)*V(32)*F(3)
  A(22) = RCT(22)*V(32)*V(33)
  A(23) = RCT(23)*V(20)
  A(24) = RCT(24)*V(20)*V(33)
  A(25) = RCT(25)*V(14)*V(33)
  A(26) = RCT(26)*V(28)*V(33)
  A(27) = RCT(27)*V(34)*V(37)
  A(28) = RCT(28)*V(32)*V(37)
  A(29) = RCT(29)*V(12)
  A(30) = RCT(30)*V(12)
  A(31) = RCT(31)*V(12)*V(33)
  A(32) = RCT(32)*V(28)*V(37)
  A(33) = RCT(33)*V(37)*V(37)
  A(34) = RCT(34)*V(37)*V(37)*F(5)
  A(35) = RCT(35)*V(37)*V(37)*F(3)
  A(36) = RCT(36)*V(3)
  A(37) = RCT(37)*V(3)*V(33)
  A(38) = RCT(38)*V(30)*V(37)
  A(39) = RCT(39)*V(30)*V(37)*F(5)
  A(40) = RCT(40)*V(30)*V(37)*F(3)
  A(41) = RCT(41)*V(21)*V(33)
  A(42) = RCT(42)*V(34)*V(40)
  A(43) = RCT(43)*V(37)*V(40)
  A(44) = RCT(44)*V(40)*V(40)
  A(45) = RCT(45)*V(35)*V(40)
  A(46) = RCT(46)*V(19)
  A(47) = RCT(47)*V(39)
  A(48) = RCT(48)*V(39)
  A(49) = RCT(49)*V(33)*V(39)
  A(50) = RCT(50)*V(30)*V(39)
  A(51) = RCT(51)*V(37)*V(39)
  A(52) = RCT(52)*V(33)*V(38)
  A(53) = RCT(53)*V(38)
  A(54) = RCT(54)*V(30)*V(38)
  A(55) = RCT(55)*V(34)*V(35)
  A(56) = RCT(56)*V(32)*V(35)
  A(57) = RCT(57)*V(35)*V(37)
  A(58) = RCT(58)*V(35)*V(35)
  A(59) = RCT(59)*V(4)
  A(60) = RCT(60)*V(27)
  A(61) = RCT(61)*V(27)*V(33)
  A(62) = RCT(62)*V(18)
  A(63) = RCT(63)*V(18)*V(33)
  A(64) = RCT(64)*V(18)*V(30)
  A(65) = RCT(65)*V(33)*F(1)
  A(66) = RCT(66)*V(33)*F(2)
  A(67) = RCT(67)*V(5)*V(33)
  A(68) = RCT(68)*V(8)*V(33)
  A(69) = RCT(69)*V(22)*V(33)
  A(70) = RCT(70)*V(34)*V(36)
  A(71) = RCT(71)*V(36)*V(37)
  A(72) = RCT(72)*V(36)*V(40)
  A(73) = RCT(73)*V(35)*V(36)
  A(74) = RCT(74)*V(29)*V(34)
  A(75) = RCT(75)*V(29)*V(37)
  A(76) = RCT(76)*V(29)*V(40)
  A(77) = RCT(77)*V(29)*V(35)
  A(78) = RCT(78)*V(31)*V(34)
  A(79) = RCT(79)*V(31)*V(37)
  A(80) = RCT(80)*V(31)*V(40)
  A(81) = RCT(81)*V(31)*V(35)
  A(82) = RCT(82)*V(25)*V(33)
  A(83) = RCT(83)*V(25)*V(28)
  A(84) = RCT(84)*V(25)*V(26)
  A(85) = RCT(85)*V(25)*V(30)
  A(86) = RCT(86)*V(23)*V(33)
  A(87) = RCT(87)*V(23)*V(28)
  A(88) = RCT(88)*V(23)*V(26)
  A(89) = RCT(89)*V(23)*V(30)
  A(90) = RCT(90)*V(15)*V(21)
  A(91) = RCT(91)*V(16)*V(21)
  A(92) = RCT(92)*V(15)*F(3)
  A(93) = RCT(93)*V(16)*F(3)
  A(94) = RCT(94)*V(15)*V(39)
  A(95) = RCT(95)*V(16)*V(39)
  A(96) = RCT(96)*V(15)*V(38)
  A(97) = RCT(97)*V(16)*V(38)
  A(98) = RCT(98)*V(9)*V(33)
  A(99) = RCT(99)*V(11)*V(33)
  A(100) = RCT(100)*V(10)*V(33)
  A(101) = RCT(101)*V(10)
  A(102) = RCT(102)*V(17)*V(33)
  A(103) = RCT(103)*V(17)*V(30)
  A(104) = RCT(104)*V(13)*V(32)
  A(105) = RCT(105)*V(13)*V(37)
  A(106) = RCT(106)*V(13)
  A(107) = RCT(107)*V(24)*V(33)
  A(108) = RCT(108)*V(24)*V(28)
  A(109) = RCT(109)*V(24)*V(26)
  A(110) = RCT(110)*V(24)*V(30)
  A(111) = RCT(111)*V(33)*V(37)
  A(112) = RCT(112)*V(19)*V(33)

! Aggregate function
  Vdot(1) = A(41)+A(90)+A(91)
  Vdot(2) = A(16)-A(17)-A(18)
  Vdot(3) = A(33)+A(34)+A(35)-A(36)-A(37)
  Vdot(4) = A(56)-A(59)
  Vdot(5) = -A(67)
  Vdot(6) = A(19)-A(20)+A(21)
  Vdot(7) = A(9)-A(10)-A(11)
  Vdot(8) = -A(68)
  Vdot(9) = -A(98)
  Vdot(10) = 0.4*A(98)+BGS(22)*A(99)-A(100)-A(101)
  Vdot(11) = -A(99)
  Vdot(12) = A(28)-A(29)-A(30)-A(31)
  Vdot(13) = A(103)-A(104)-A(105)-A(106)
  Vdot(14) = -A(25)+A(47)+A(48)+A(49)+A(50)+A(53)+A(62)+A(63)+A(64)+0.42*A(83)+A(84)+BGS(15)*A(87)+BGS(16)*A(88)+0.11&
               &*A(98)+BGS(24)*A(99)+A(101)
  Vdot(15) = 0.4*A(83)+BGS(25)*A(87)-A(90)-A(92)-A(94)-A(96)
  Vdot(16) = BGS(26)*A(87)-A(91)-A(93)-A(95)-A(97)+0.2*A(108)
  Vdot(17) = 0.16*A(98)+0.17*A(99)-0.92*A(102)-0.5*A(103)
  Vdot(18) = -A(62)-A(63)-A(64)+0.13*A(98)+BGS(23)*A(99)+0.2*A(102)+0.27*A(107)+0.2*A(108)
  Vdot(19) = -A(46)+A(57)+A(71)+A(75)+A(79)-A(112)
  Vdot(20) = 2*A(11)+A(21)+A(22)-A(23)-A(24)+A(38)+A(39)+A(40)+A(50)+A(54)+A(64)+A(103)
  Vdot(21) = -A(41)-A(90)-A(91)
  Vdot(22) = -A(69)+A(70)+A(104)
  Vdot(23) = -A(86)-A(87)-A(88)-A(89)
  Vdot(24) = -A(107)-A(108)-A(109)-A(110)
  Vdot(25) = -A(82)-A(83)-A(84)-A(85)+A(107)+0.5*A(108)+A(109)
  Vdot(26) = A(1)-A(2)-A(3)-A(4)+A(14)+A(15)+A(18)-A(84)-A(88)-A(109)
  Vdot(27) = -A(60)-A(61)+0.5*A(67)+BGS(3)*A(68)+0.14*A(69)+A(71)+A(72)+A(73)+BGS(17)*A(88)
  Vdot(28) = A(2)-A(5)-A(6)-A(15)-A(16)-A(26)-A(32)-A(83)-A(87)-A(108)
  Vdot(29) = BGS(6)*A(68)+1.39*A(69)-A(74)-A(75)-A(76)-A(77)+A(85)+A(89)+0.9*A(107)+0.5*A(109)+A(110)
  Vdot(30) = A(4)+A(6)-A(7)-A(9)+A(10)-A(12)-A(13)-A(14)+A(24)-A(38)-A(39)-A(40)-A(50)-A(54)-A(64)-A(85)-A(89)-A(103)&
               &-A(110)
  Vdot(31) = A(51)+A(53)+A(55)+A(60)+1.5*A(61)+A(65)+A(66)+A(67)+BGS(5)*A(68)-A(78)-A(79)-A(80)-A(81)+A(82)+A(84)+A(86)&
               &+BGS(12)*A(87)+BGS(21)*A(88)+0.84*A(98)+0.83*A(99)+0.85*A(102)+0.5*A(112)
  Vdot(32) = -A(1)-A(3)-A(4)+A(5)-A(6)+2*A(7)+2*A(8)-A(9)+A(10)+A(14)-2*A(21)-A(22)+A(23)+A(27)-A(28)+A(29)+A(30)+A(31)&
               &+A(55)-A(56)+A(59)+A(69)+A(74)+A(78)+A(85)+A(89)-A(104)+A(110)
  Vdot(33) = 2*A(17)-A(19)+A(20)-A(22)+A(23)-A(24)-A(25)-A(26)+A(27)-A(31)+A(32)+2*A(36)-A(37)-A(41)+A(46)-A(49)-A(52)&
               &-A(61)-A(63)-A(65)-A(66)-A(67)-A(68)-A(69)-A(82)-A(86)+BGS(14)*A(87)-A(98)-A(99)-A(100)-A(102)-A(107)+0.1&
               &*A(108)-A(111)-0.5*A(112)
  Vdot(34) = A(1)+A(3)-A(5)-A(7)-2*A(8)+A(12)+A(13)-A(19)+A(20)-A(27)-A(55)-A(70)-A(74)-A(78)
  Vdot(35) = A(52)+A(54)-A(55)-A(56)-A(57)-2*A(58)+A(59)+A(60)+A(61)+A(62)+A(63)+A(64)-A(73)-A(77)-A(81)+A(100)+A(101)&
               &+0.2*A(107)
  Vdot(36) = BGS(4)*A(68)-A(70)-A(71)-A(72)-A(73)+0.15*A(102)+0.1*A(107)
  Vdot(37) = A(25)+A(26)-A(27)-A(28)+A(29)+A(30)-A(32)-2*A(33)-2*A(34)-2*A(35)+A(37)-A(38)-A(39)-A(40)+A(41)+A(46)+2&
               &*A(47)+A(49)+A(50)-A(51)+A(53)-A(57)+2*A(58)+A(62)-A(71)+0.5*A(72)+A(73)-A(75)+A(77)+A(78)-A(79)+0.5*A(80)&
               &+A(81)+0.12*A(83)+A(84)+BGS(13)*A(87)+BGS(2)*A(88)+0.16*A(98)+0.17*A(99)+A(101)-A(105)+0.7*A(107)+0.4*A(108)&
               &+0.6*A(109)-A(111)
  Vdot(38) = -A(52)-A(53)-A(54)+A(60)+0.5*A(61)+A(66)+0.3*A(67)+BGS(2)*A(68)+1.52*A(69)+0.22*A(82)+BGS(9)*A(86)+BGS(11)&
               &*A(87)+BGS(19)*A(88)+BGS(9)*A(89)+A(91)-A(96)-A(97)+0.2*A(107)+0.4*A(108)+A(109)+A(110)
  Vdot(39) = -A(47)-A(48)-A(49)-A(50)-A(51)+A(53)+A(55)+A(57)+2*A(58)+0.5*A(61)+A(65)+BGS(1)*A(68)+0.16*A(69)+A(73)&
               &+A(77)+A(81)+1.56*A(82)+A(83)+A(84)+2*A(85)+BGS(8)*A(86)+BGS(1)*A(87)+BGS(18)*A(88)+BGS(8)*A(89)+A(90)-A(94)&
               &-A(95)+0.11*A(98)+BGS(24)*A(99)+A(107)+A(108)+A(110)
  Vdot(40) = -A(42)-A(43)-2*A(44)-A(45)+A(51)+A(53)+A(55)+A(60)+1.5*A(61)+A(65)+A(66)+A(67)+BGS(7)*A(68)+1.39*A(69)&
               &+A(82)+A(84)+A(85)+A(86)+BGS(12)*A(87)+BGS(21)*A(88)+A(89)+0.84*A(98)+0.83*A(99)+A(102)+A(107)+0.5*A(109)&
               &+A(110)+0.5*A(112)

  RETURN
END SUBROUTINE Fun_day

SUBROUTINE Jac_SP_day ( V, F, RCT, BGS, JVS, NVAR, NFIX, NREACT, nprcf, LU_NONZERO )
  IMPLICIT NONE
  integer(kind=4), intent(in) :: NVAR, NFIX, NREACT, nprcf, LU_NONZERO
! V - Concentrations of variable species (local)
  REAL(kind=8), intent(in) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=8), intent(in) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=8), intent(in) :: RCT(NREACT)
! BGS - Fractional product yields for some reactions (local)
  REAL(kind=8), intent(in) :: BGS(nprcf)
! JVS - sparse Jacobian of variables
  REAL(kind=8), intent(out) :: JVS(LU_NONZERO)
! Local variables
! B - Temporary array
  REAL(kind=8) :: B(204)

! B(1) = dA(1)/dV(32)
  B(1) = RCT(1)
! B(2) = dA(2)/dV(26)
  B(2) = RCT(2)*F(4)*F(5)
! B(5) = dA(3)/dV(26)
  B(5) = RCT(3)*V(32)
! B(6) = dA(3)/dV(32)
  B(6) = RCT(3)*V(26)
! B(7) = dA(4)/dV(26)
  B(7) = RCT(4)*V(32)
! B(8) = dA(4)/dV(32)
  B(8) = RCT(4)*V(26)
! B(9) = dA(5)/dV(28)
  B(9) = RCT(5)*V(34)
! B(10) = dA(5)/dV(34)
  B(10) = RCT(5)*V(28)
! B(11) = dA(6)/dV(28)
  B(11) = RCT(6)*V(32)
! B(12) = dA(6)/dV(32)
  B(12) = RCT(6)*V(28)
! B(13) = dA(7)/dV(30)
  B(13) = RCT(7)*V(34)
! B(14) = dA(7)/dV(34)
  B(14) = RCT(7)*V(30)
! B(15) = dA(8)/dV(34)
  B(15) = RCT(8)*2*V(34)*F(4)
! B(17) = dA(9)/dV(30)
  B(17) = RCT(9)*V(32)
! B(18) = dA(9)/dV(32)
  B(18) = RCT(9)*V(30)
! B(19) = dA(10)/dV(7)
  B(19) = RCT(10)
! B(20) = dA(11)/dV(7)
  B(20) = RCT(11)*F(3)
! B(22) = dA(12)/dV(30)
  B(22) = RCT(12)*V(32)
! B(23) = dA(12)/dV(32)
  B(23) = RCT(12)*V(30)
! B(24) = dA(13)/dV(30)
  B(24) = RCT(13)
! B(25) = dA(14)/dV(30)
  B(25) = RCT(14)
! B(26) = dA(15)/dV(28)
  B(26) = RCT(15)
! B(27) = dA(16)/dV(28)
  B(27) = RCT(16)
! B(28) = dA(17)/dV(2)
  B(28) = RCT(17)*F(3)
! B(30) = dA(18)/dV(2)
  B(30) = RCT(18)*F(5)
! B(32) = dA(19)/dV(33)
  B(32) = RCT(19)*V(34)
! B(33) = dA(19)/dV(34)
  B(33) = RCT(19)*V(33)
! B(34) = dA(20)/dV(6)
  B(34) = RCT(20)
! B(35) = dA(21)/dV(32)
  B(35) = RCT(21)*F(3)
! B(37) = dA(22)/dV(32)
  B(37) = RCT(22)*V(33)
! B(38) = dA(22)/dV(33)
  B(38) = RCT(22)*V(32)
! B(39) = dA(23)/dV(20)
  B(39) = RCT(23)
! B(40) = dA(24)/dV(20)
  B(40) = RCT(24)*V(33)
! B(41) = dA(24)/dV(33)
  B(41) = RCT(24)*V(20)
! B(42) = dA(25)/dV(14)
  B(42) = RCT(25)*V(33)
! B(43) = dA(25)/dV(33)
  B(43) = RCT(25)*V(14)
! B(44) = dA(26)/dV(28)
  B(44) = RCT(26)*V(33)
! B(45) = dA(26)/dV(33)
  B(45) = RCT(26)*V(28)
! B(46) = dA(27)/dV(34)
  B(46) = RCT(27)*V(37)
! B(47) = dA(27)/dV(37)
  B(47) = RCT(27)*V(34)
! B(48) = dA(28)/dV(32)
  B(48) = RCT(28)*V(37)
! B(49) = dA(28)/dV(37)
  B(49) = RCT(28)*V(32)
! B(50) = dA(29)/dV(12)
  B(50) = RCT(29)
! B(51) = dA(30)/dV(12)
  B(51) = RCT(30)
! B(52) = dA(31)/dV(12)
  B(52) = RCT(31)*V(33)
! B(53) = dA(31)/dV(33)
  B(53) = RCT(31)*V(12)
! B(54) = dA(32)/dV(28)
  B(54) = RCT(32)*V(37)
! B(55) = dA(32)/dV(37)
  B(55) = RCT(32)*V(28)
! B(56) = dA(33)/dV(37)
  B(56) = RCT(33)*2*V(37)
! B(57) = dA(34)/dV(37)
  B(57) = RCT(34)*2*V(37)*F(5)
! B(59) = dA(35)/dV(37)
  B(59) = RCT(35)*2*V(37)*F(3)
! B(61) = dA(36)/dV(3)
  B(61) = RCT(36)
! B(62) = dA(37)/dV(3)
  B(62) = RCT(37)*V(33)
! B(63) = dA(37)/dV(33)
  B(63) = RCT(37)*V(3)
! B(64) = dA(38)/dV(30)
  B(64) = RCT(38)*V(37)
! B(65) = dA(38)/dV(37)
  B(65) = RCT(38)*V(30)
! B(66) = dA(39)/dV(30)
  B(66) = RCT(39)*V(37)*F(5)
! B(67) = dA(39)/dV(37)
  B(67) = RCT(39)*V(30)*F(5)
! B(69) = dA(40)/dV(30)
  B(69) = RCT(40)*V(37)*F(3)
! B(70) = dA(40)/dV(37)
  B(70) = RCT(40)*V(30)*F(3)
! B(72) = dA(41)/dV(21)
  B(72) = RCT(41)*V(33)
! B(73) = dA(41)/dV(33)
  B(73) = RCT(41)*V(21)
! B(74) = dA(42)/dV(34)
  B(74) = RCT(42)*V(40)
! B(75) = dA(42)/dV(40)
  B(75) = RCT(42)*V(34)
! B(76) = dA(43)/dV(37)
  B(76) = RCT(43)*V(40)
! B(77) = dA(43)/dV(40)
  B(77) = RCT(43)*V(37)
! B(78) = dA(44)/dV(40)
  B(78) = RCT(44)*2*V(40)
! B(79) = dA(45)/dV(35)
  B(79) = RCT(45)*V(40)
! B(80) = dA(45)/dV(40)
  B(80) = RCT(45)*V(35)
! B(81) = dA(46)/dV(19)
  B(81) = RCT(46)
! B(82) = dA(47)/dV(39)
  B(82) = RCT(47)
! B(83) = dA(48)/dV(39)
  B(83) = RCT(48)
! B(84) = dA(49)/dV(33)
  B(84) = RCT(49)*V(39)
! B(85) = dA(49)/dV(39)
  B(85) = RCT(49)*V(33)
! B(86) = dA(50)/dV(30)
  B(86) = RCT(50)*V(39)
! B(87) = dA(50)/dV(39)
  B(87) = RCT(50)*V(30)
! B(88) = dA(51)/dV(37)
  B(88) = RCT(51)*V(39)
! B(89) = dA(51)/dV(39)
  B(89) = RCT(51)*V(37)
! B(90) = dA(52)/dV(33)
  B(90) = RCT(52)*V(38)
! B(91) = dA(52)/dV(38)
  B(91) = RCT(52)*V(33)
! B(92) = dA(53)/dV(38)
  B(92) = RCT(53)
! B(93) = dA(54)/dV(30)
  B(93) = RCT(54)*V(38)
! B(94) = dA(54)/dV(38)
  B(94) = RCT(54)*V(30)
! B(95) = dA(55)/dV(34)
  B(95) = RCT(55)*V(35)
! B(96) = dA(55)/dV(35)
  B(96) = RCT(55)*V(34)
! B(97) = dA(56)/dV(32)
  B(97) = RCT(56)*V(35)
! B(98) = dA(56)/dV(35)
  B(98) = RCT(56)*V(32)
! B(99) = dA(57)/dV(35)
  B(99) = RCT(57)*V(37)
! B(100) = dA(57)/dV(37)
  B(100) = RCT(57)*V(35)
! B(101) = dA(58)/dV(35)
  B(101) = RCT(58)*2*V(35)
! B(102) = dA(59)/dV(4)
  B(102) = RCT(59)
! B(103) = dA(60)/dV(27)
  B(103) = RCT(60)
! B(104) = dA(61)/dV(27)
  B(104) = RCT(61)*V(33)
! B(105) = dA(61)/dV(33)
  B(105) = RCT(61)*V(27)
! B(106) = dA(62)/dV(18)
  B(106) = RCT(62)
! B(107) = dA(63)/dV(18)
  B(107) = RCT(63)*V(33)
! B(108) = dA(63)/dV(33)
  B(108) = RCT(63)*V(18)
! B(109) = dA(64)/dV(18)
  B(109) = RCT(64)*V(30)
! B(110) = dA(64)/dV(30)
  B(110) = RCT(64)*V(18)
! B(111) = dA(65)/dV(33)
  B(111) = RCT(65)*F(1)
! B(113) = dA(66)/dV(33)
  B(113) = RCT(66)*F(2)
! B(115) = dA(67)/dV(5)
  B(115) = RCT(67)*V(33)
! B(116) = dA(67)/dV(33)
  B(116) = RCT(67)*V(5)
! B(117) = dA(68)/dV(8)
  B(117) = RCT(68)*V(33)
! B(118) = dA(68)/dV(33)
  B(118) = RCT(68)*V(8)
! B(119) = dA(69)/dV(22)
  B(119) = RCT(69)*V(33)
! B(120) = dA(69)/dV(33)
  B(120) = RCT(69)*V(22)
! B(121) = dA(70)/dV(34)
  B(121) = RCT(70)*V(36)
! B(122) = dA(70)/dV(36)
  B(122) = RCT(70)*V(34)
! B(123) = dA(71)/dV(36)
  B(123) = RCT(71)*V(37)
! B(124) = dA(71)/dV(37)
  B(124) = RCT(71)*V(36)
! B(125) = dA(72)/dV(36)
  B(125) = RCT(72)*V(40)
! B(126) = dA(72)/dV(40)
  B(126) = RCT(72)*V(36)
! B(127) = dA(73)/dV(35)
  B(127) = RCT(73)*V(36)
! B(128) = dA(73)/dV(36)
  B(128) = RCT(73)*V(35)
! B(129) = dA(74)/dV(29)
  B(129) = RCT(74)*V(34)
! B(130) = dA(74)/dV(34)
  B(130) = RCT(74)*V(29)
! B(131) = dA(75)/dV(29)
  B(131) = RCT(75)*V(37)
! B(132) = dA(75)/dV(37)
  B(132) = RCT(75)*V(29)
! B(133) = dA(76)/dV(29)
  B(133) = RCT(76)*V(40)
! B(134) = dA(76)/dV(40)
  B(134) = RCT(76)*V(29)
! B(135) = dA(77)/dV(29)
  B(135) = RCT(77)*V(35)
! B(136) = dA(77)/dV(35)
  B(136) = RCT(77)*V(29)
! B(137) = dA(78)/dV(31)
  B(137) = RCT(78)*V(34)
! B(138) = dA(78)/dV(34)
  B(138) = RCT(78)*V(31)
! B(139) = dA(79)/dV(31)
  B(139) = RCT(79)*V(37)
! B(140) = dA(79)/dV(37)
  B(140) = RCT(79)*V(31)
! B(141) = dA(80)/dV(31)
  B(141) = RCT(80)*V(40)
! B(142) = dA(80)/dV(40)
  B(142) = RCT(80)*V(31)
! B(143) = dA(81)/dV(31)
  B(143) = RCT(81)*V(35)
! B(144) = dA(81)/dV(35)
  B(144) = RCT(81)*V(31)
! B(145) = dA(82)/dV(25)
  B(145) = RCT(82)*V(33)
! B(146) = dA(82)/dV(33)
  B(146) = RCT(82)*V(25)
! B(147) = dA(83)/dV(25)
  B(147) = RCT(83)*V(28)
! B(148) = dA(83)/dV(28)
  B(148) = RCT(83)*V(25)
! B(149) = dA(84)/dV(25)
  B(149) = RCT(84)*V(26)
! B(150) = dA(84)/dV(26)
  B(150) = RCT(84)*V(25)
! B(151) = dA(85)/dV(25)
  B(151) = RCT(85)*V(30)
! B(152) = dA(85)/dV(30)
  B(152) = RCT(85)*V(25)
! B(153) = dA(86)/dV(23)
  B(153) = RCT(86)*V(33)
! B(154) = dA(86)/dV(33)
  B(154) = RCT(86)*V(23)
! B(155) = dA(87)/dV(23)
  B(155) = RCT(87)*V(28)
! B(156) = dA(87)/dV(28)
  B(156) = RCT(87)*V(23)
! B(157) = dA(88)/dV(23)
  B(157) = RCT(88)*V(26)
! B(158) = dA(88)/dV(26)
  B(158) = RCT(88)*V(23)
! B(159) = dA(89)/dV(23)
  B(159) = RCT(89)*V(30)
! B(160) = dA(89)/dV(30)
  B(160) = RCT(89)*V(23)
! B(161) = dA(90)/dV(15)
  B(161) = RCT(90)*V(21)
! B(162) = dA(90)/dV(21)
  B(162) = RCT(90)*V(15)
! B(163) = dA(91)/dV(16)
  B(163) = RCT(91)*V(21)
! B(164) = dA(91)/dV(21)
  B(164) = RCT(91)*V(16)
! B(165) = dA(92)/dV(15)
  B(165) = RCT(92)*F(3)
! B(167) = dA(93)/dV(16)
  B(167) = RCT(93)*F(3)
! B(169) = dA(94)/dV(15)
  B(169) = RCT(94)*V(39)
! B(170) = dA(94)/dV(39)
  B(170) = RCT(94)*V(15)
! B(171) = dA(95)/dV(16)
  B(171) = RCT(95)*V(39)
! B(172) = dA(95)/dV(39)
  B(172) = RCT(95)*V(16)
! B(173) = dA(96)/dV(15)
  B(173) = RCT(96)*V(38)
! B(174) = dA(96)/dV(38)
  B(174) = RCT(96)*V(15)
! B(175) = dA(97)/dV(16)
  B(175) = RCT(97)*V(38)
! B(176) = dA(97)/dV(38)
  B(176) = RCT(97)*V(16)
! B(177) = dA(98)/dV(9)
  B(177) = RCT(98)*V(33)
! B(178) = dA(98)/dV(33)
  B(178) = RCT(98)*V(9)
! B(179) = dA(99)/dV(11)
  B(179) = RCT(99)*V(33)
! B(180) = dA(99)/dV(33)
  B(180) = RCT(99)*V(11)
! B(181) = dA(100)/dV(10)
  B(181) = RCT(100)*V(33)
! B(182) = dA(100)/dV(33)
  B(182) = RCT(100)*V(10)
! B(183) = dA(101)/dV(10)
  B(183) = RCT(101)
! B(184) = dA(102)/dV(17)
  B(184) = RCT(102)*V(33)
! B(185) = dA(102)/dV(33)
  B(185) = RCT(102)*V(17)
! B(186) = dA(103)/dV(17)
  B(186) = RCT(103)*V(30)
! B(187) = dA(103)/dV(30)
  B(187) = RCT(103)*V(17)
! B(188) = dA(104)/dV(13)
  B(188) = RCT(104)*V(32)
! B(189) = dA(104)/dV(32)
  B(189) = RCT(104)*V(13)
! B(190) = dA(105)/dV(13)
  B(190) = RCT(105)*V(37)
! B(191) = dA(105)/dV(37)
  B(191) = RCT(105)*V(13)
! B(192) = dA(106)/dV(13)
  B(192) = RCT(106)
! B(193) = dA(107)/dV(24)
  B(193) = RCT(107)*V(33)
! B(194) = dA(107)/dV(33)
  B(194) = RCT(107)*V(24)
! B(195) = dA(108)/dV(24)
  B(195) = RCT(108)*V(28)
! B(196) = dA(108)/dV(28)
  B(196) = RCT(108)*V(24)
! B(197) = dA(109)/dV(24)
  B(197) = RCT(109)*V(26)
! B(198) = dA(109)/dV(26)
  B(198) = RCT(109)*V(24)
! B(199) = dA(110)/dV(24)
  B(199) = RCT(110)*V(30)
! B(200) = dA(110)/dV(30)
  B(200) = RCT(110)*V(24)
! B(201) = dA(111)/dV(33)
  B(201) = RCT(111)*V(37)
! B(202) = dA(111)/dV(37)
  B(202) = RCT(111)*V(33)
! B(203) = dA(112)/dV(19)
  B(203) = RCT(112)*V(33)
! B(204) = dA(112)/dV(33)
  B(204) = RCT(112)*V(19)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,15)
  JVS(2) = B(161)
! JVS(3) = Jac_FULL(1,16)
  JVS(3) = B(163)
! JVS(4) = Jac_FULL(1,21)
  JVS(4) = B(72)+B(162)+B(164)
! JVS(5) = Jac_FULL(1,33)
  JVS(5) = B(73)
! JVS(6) = Jac_FULL(2,2)
  JVS(6) = -B(28)-B(30)
! JVS(7) = Jac_FULL(2,28)
  JVS(7) = B(27)
! JVS(8) = Jac_FULL(3,3)
  JVS(8) = -B(61)-B(62)
! JVS(9) = Jac_FULL(3,33)
  JVS(9) = -B(63)
! JVS(10) = Jac_FULL(3,37)
  JVS(10) = B(56)+B(57)+B(59)
! JVS(11) = Jac_FULL(4,4)
  JVS(11) = -B(102)
! JVS(12) = Jac_FULL(4,32)
  JVS(12) = B(97)
! JVS(13) = Jac_FULL(4,35)
  JVS(13) = B(98)
! JVS(14) = Jac_FULL(5,5)
  JVS(14) = -B(115)
! JVS(15) = Jac_FULL(5,33)
  JVS(15) = -B(116)
! JVS(16) = Jac_FULL(6,6)
  JVS(16) = -B(34)
! JVS(17) = Jac_FULL(6,32)
  JVS(17) = B(35)
! JVS(18) = Jac_FULL(6,33)
  JVS(18) = B(32)
! JVS(19) = Jac_FULL(6,34)
  JVS(19) = B(33)
! JVS(20) = Jac_FULL(7,7)
  JVS(20) = -B(19)-B(20)
! JVS(21) = Jac_FULL(7,30)
  JVS(21) = B(17)
! JVS(22) = Jac_FULL(7,32)
  JVS(22) = B(18)
! JVS(23) = Jac_FULL(8,8)
  JVS(23) = -B(117)
! JVS(24) = Jac_FULL(8,33)
  JVS(24) = -B(118)
! JVS(25) = Jac_FULL(9,9)
  JVS(25) = -B(177)
! JVS(26) = Jac_FULL(9,33)
  JVS(26) = -B(178)
! JVS(27) = Jac_FULL(10,9)
  JVS(27) = 0.4*B(177)
! JVS(28) = Jac_FULL(10,10)
  JVS(28) = -B(181)-B(183)
! JVS(29) = Jac_FULL(10,11)
  JVS(29) = BGS(22)*B(179)
! JVS(30) = Jac_FULL(10,33)
  JVS(30) = 0.4*B(178)+BGS(22)*B(180)-B(182)
! JVS(31) = Jac_FULL(11,11)
  JVS(31) = -B(179)
! JVS(32) = Jac_FULL(11,33)
  JVS(32) = -B(180)
! JVS(33) = Jac_FULL(12,12)
  JVS(33) = -B(50)-B(51)-B(52)
! JVS(34) = Jac_FULL(12,32)
  JVS(34) = B(48)
! JVS(35) = Jac_FULL(12,33)
  JVS(35) = -B(53)
! JVS(36) = Jac_FULL(12,37)
  JVS(36) = B(49)
! JVS(37) = Jac_FULL(13,13)
  JVS(37) = -B(188)-B(190)-B(192)
! JVS(38) = Jac_FULL(13,17)
  JVS(38) = B(186)
! JVS(39) = Jac_FULL(13,30)
  JVS(39) = B(187)
! JVS(40) = Jac_FULL(13,32)
  JVS(40) = -B(189)
! JVS(41) = Jac_FULL(13,37)
  JVS(41) = -B(191)
! JVS(42) = Jac_FULL(14,9)
  JVS(42) = 0.11*B(177)
! JVS(43) = Jac_FULL(14,10)
  JVS(43) = B(183)
! JVS(44) = Jac_FULL(14,11)
  JVS(44) = BGS(24)*B(179)
! JVS(45) = Jac_FULL(14,14)
  JVS(45) = -B(42)
! JVS(46) = Jac_FULL(14,18)
  JVS(46) = B(106)+B(107)+B(109)
! JVS(47) = Jac_FULL(14,23)
  JVS(47) = BGS(15)*B(155)+BGS(16)*B(157)
! JVS(48) = Jac_FULL(14,25)
  JVS(48) = 0.42*B(147)+B(149)
! JVS(49) = Jac_FULL(14,26)
  JVS(49) = B(150)+BGS(16)*B(158)
! JVS(50) = Jac_FULL(14,28)
  JVS(50) = 0.42*B(148)+BGS(15)*B(156)
! JVS(51) = Jac_FULL(14,30)
  JVS(51) = B(86)+B(110)
! JVS(52) = Jac_FULL(14,33)
  JVS(52) = -B(43)+B(84)+B(108)+0.11*B(178)+BGS(24)*B(180)
! JVS(53) = Jac_FULL(14,38)
  JVS(53) = B(92)
! JVS(54) = Jac_FULL(14,39)
  JVS(54) = B(82)+B(83)+B(85)+B(87)
! JVS(55) = Jac_FULL(15,15)
  JVS(55) = -B(161)-B(165)-B(169)-B(173)
! JVS(56) = Jac_FULL(15,21)
  JVS(56) = -B(162)
! JVS(57) = Jac_FULL(15,23)
  JVS(57) = BGS(25)*B(155)
! JVS(58) = Jac_FULL(15,25)
  JVS(58) = 0.4*B(147)
! JVS(59) = Jac_FULL(15,28)
  JVS(59) = 0.4*B(148)+BGS(25)*B(156)
! JVS(60) = Jac_FULL(15,38)
  JVS(60) = -B(174)
! JVS(61) = Jac_FULL(15,39)
  JVS(61) = -B(170)
! JVS(62) = Jac_FULL(16,16)
  JVS(62) = -B(163)-B(167)-B(171)-B(175)
! JVS(63) = Jac_FULL(16,21)
  JVS(63) = -B(164)
! JVS(64) = Jac_FULL(16,23)
  JVS(64) = BGS(26)*B(155)
! JVS(65) = Jac_FULL(16,24)
  JVS(65) = 0.2*B(195)
! JVS(66) = Jac_FULL(16,28)
  JVS(66) = BGS(26)*B(156)+0.2*B(196)
! JVS(67) = Jac_FULL(16,38)
  JVS(67) = -B(176)
! JVS(68) = Jac_FULL(16,39)
  JVS(68) = -B(172)
! JVS(69) = Jac_FULL(17,9)
  JVS(69) = 0.16*B(177)
! JVS(70) = Jac_FULL(17,11)
  JVS(70) = 0.17*B(179)
! JVS(71) = Jac_FULL(17,17)
  JVS(71) = -0.92*B(184)-0.5*B(186)
! JVS(72) = Jac_FULL(17,30)
  JVS(72) = -0.5*B(187)
! JVS(73) = Jac_FULL(17,33)
  JVS(73) = 0.16*B(178)+0.17*B(180)-0.92*B(185)
! JVS(74) = Jac_FULL(18,9)
  JVS(74) = 0.13*B(177)
! JVS(75) = Jac_FULL(18,11)
  JVS(75) = BGS(23)*B(179)
! JVS(76) = Jac_FULL(18,17)
  JVS(76) = 0.2*B(184)
! JVS(77) = Jac_FULL(18,18)
  JVS(77) = -B(106)-B(107)-B(109)
! JVS(78) = Jac_FULL(18,24)
  JVS(78) = 0.27*B(193)+0.2*B(195)
! JVS(79) = Jac_FULL(18,28)
  JVS(79) = 0.2*B(196)
! JVS(80) = Jac_FULL(18,30)
  JVS(80) = -B(110)
! JVS(81) = Jac_FULL(18,33)
  JVS(81) = -B(108)+0.13*B(178)+BGS(23)*B(180)+0.2*B(185)+0.27*B(194)
! JVS(82) = Jac_FULL(19,19)
  JVS(82) = -B(81)-B(203)
! JVS(83) = Jac_FULL(19,29)
  JVS(83) = B(131)
! JVS(84) = Jac_FULL(19,31)
  JVS(84) = B(139)
! JVS(85) = Jac_FULL(19,33)
  JVS(85) = -B(204)
! JVS(86) = Jac_FULL(19,35)
  JVS(86) = B(99)
! JVS(87) = Jac_FULL(19,36)
  JVS(87) = B(123)
! JVS(88) = Jac_FULL(19,37)
  JVS(88) = B(100)+B(124)+B(132)+B(140)
! JVS(89) = Jac_FULL(20,7)
  JVS(89) = 2*B(20)
! JVS(90) = Jac_FULL(20,17)
  JVS(90) = B(186)
! JVS(91) = Jac_FULL(20,18)
  JVS(91) = B(109)
! JVS(92) = Jac_FULL(20,20)
  JVS(92) = -B(39)-B(40)
! JVS(93) = Jac_FULL(20,24)
  JVS(93) = 0
! JVS(94) = Jac_FULL(20,28)
  JVS(94) = 0
! JVS(95) = Jac_FULL(20,30)
  JVS(95) = B(64)+B(66)+B(69)+B(86)+B(93)+B(110)+B(187)
! JVS(96) = Jac_FULL(20,32)
  JVS(96) = B(35)+B(37)
! JVS(97) = Jac_FULL(20,33)
  JVS(97) = B(38)-B(41)
! JVS(98) = Jac_FULL(20,37)
  JVS(98) = B(65)+B(67)+B(70)
! JVS(99) = Jac_FULL(20,38)
  JVS(99) = B(94)
! JVS(100) = Jac_FULL(20,39)
  JVS(100) = B(87)
! JVS(101) = Jac_FULL(21,15)
  JVS(101) = -B(161)
! JVS(102) = Jac_FULL(21,16)
  JVS(102) = -B(163)
! JVS(103) = Jac_FULL(21,21)
  JVS(103) = -B(72)-B(162)-B(164)
! JVS(104) = Jac_FULL(21,23)
  JVS(104) = 0
! JVS(105) = Jac_FULL(21,24)
  JVS(105) = 0
! JVS(106) = Jac_FULL(21,25)
  JVS(106) = 0
! JVS(107) = Jac_FULL(21,28)
  JVS(107) = 0
! JVS(108) = Jac_FULL(21,33)
  JVS(108) = -B(73)
! JVS(109) = Jac_FULL(21,38)
  JVS(109) = 0
! JVS(110) = Jac_FULL(21,39)
  JVS(110) = 0
! JVS(111) = Jac_FULL(22,13)
  JVS(111) = B(188)
! JVS(112) = Jac_FULL(22,17)
  JVS(112) = 0
! JVS(113) = Jac_FULL(22,22)
  JVS(113) = -B(119)
! JVS(114) = Jac_FULL(22,30)
  JVS(114) = 0
! JVS(115) = Jac_FULL(22,32)
  JVS(115) = B(189)
! JVS(116) = Jac_FULL(22,33)
  JVS(116) = -B(120)
! JVS(117) = Jac_FULL(22,34)
  JVS(117) = B(121)
! JVS(118) = Jac_FULL(22,36)
  JVS(118) = B(122)
! JVS(119) = Jac_FULL(22,37)
  JVS(119) = 0
! JVS(120) = Jac_FULL(23,23)
  JVS(120) = -B(153)-B(155)-B(157)-B(159)
! JVS(121) = Jac_FULL(23,26)
  JVS(121) = -B(158)
! JVS(122) = Jac_FULL(23,28)
  JVS(122) = -B(156)
! JVS(123) = Jac_FULL(23,30)
  JVS(123) = -B(160)
! JVS(124) = Jac_FULL(23,33)
  JVS(124) = -B(154)
! JVS(125) = Jac_FULL(24,24)
  JVS(125) = -B(193)-B(195)-B(197)-B(199)
! JVS(126) = Jac_FULL(24,26)
  JVS(126) = -B(198)
! JVS(127) = Jac_FULL(24,28)
  JVS(127) = -B(196)
! JVS(128) = Jac_FULL(24,30)
  JVS(128) = -B(200)
! JVS(129) = Jac_FULL(24,33)
  JVS(129) = -B(194)
! JVS(130) = Jac_FULL(25,24)
  JVS(130) = B(193)+0.5*B(195)+B(197)
! JVS(131) = Jac_FULL(25,25)
  JVS(131) = -B(145)-B(147)-B(149)-B(151)
! JVS(132) = Jac_FULL(25,26)
  JVS(132) = -B(150)+B(198)
! JVS(133) = Jac_FULL(25,28)
  JVS(133) = -B(148)+0.5*B(196)
! JVS(134) = Jac_FULL(25,30)
  JVS(134) = -B(152)
! JVS(135) = Jac_FULL(25,33)
  JVS(135) = -B(146)+B(194)
! JVS(136) = Jac_FULL(26,2)
  JVS(136) = B(30)
! JVS(137) = Jac_FULL(26,23)
  JVS(137) = -B(157)
! JVS(138) = Jac_FULL(26,24)
  JVS(138) = -B(197)
! JVS(139) = Jac_FULL(26,25)
  JVS(139) = -B(149)
! JVS(140) = Jac_FULL(26,26)
  JVS(140) = -B(2)-B(5)-B(7)-B(150)-B(158)-B(198)
! JVS(141) = Jac_FULL(26,28)
  JVS(141) = B(26)
! JVS(142) = Jac_FULL(26,30)
  JVS(142) = B(25)
! JVS(143) = Jac_FULL(26,32)
  JVS(143) = B(1)-B(6)-B(8)
! JVS(144) = Jac_FULL(26,33)
  JVS(144) = 0
! JVS(145) = Jac_FULL(27,5)
  JVS(145) = 0.5*B(115)
! JVS(146) = Jac_FULL(27,8)
  JVS(146) = BGS(3)*B(117)
! JVS(147) = Jac_FULL(27,22)
  JVS(147) = 0.14*B(119)
! JVS(148) = Jac_FULL(27,23)
  JVS(148) = BGS(17)*B(157)
! JVS(149) = Jac_FULL(27,26)
  JVS(149) = BGS(17)*B(158)
! JVS(150) = Jac_FULL(27,27)
  JVS(150) = -B(103)-B(104)
! JVS(151) = Jac_FULL(27,28)
  JVS(151) = 0
! JVS(152) = Jac_FULL(27,30)
  JVS(152) = 0
! JVS(153) = Jac_FULL(27,32)
  JVS(153) = 0
! JVS(154) = Jac_FULL(27,33)
  JVS(154) = -B(105)+0.5*B(116)+BGS(3)*B(118)+0.14*B(120)
! JVS(155) = Jac_FULL(27,34)
  JVS(155) = 0
! JVS(156) = Jac_FULL(27,35)
  JVS(156) = B(127)
! JVS(157) = Jac_FULL(27,36)
  JVS(157) = B(123)+B(125)+B(128)
! JVS(158) = Jac_FULL(27,37)
  JVS(158) = B(124)
! JVS(159) = Jac_FULL(27,40)
  JVS(159) = B(126)
! JVS(160) = Jac_FULL(28,23)
  JVS(160) = -B(155)
! JVS(161) = Jac_FULL(28,24)
  JVS(161) = -B(195)
! JVS(162) = Jac_FULL(28,25)
  JVS(162) = -B(147)
! JVS(163) = Jac_FULL(28,26)
  JVS(163) = B(2)
! JVS(164) = Jac_FULL(28,28)
  JVS(164) = -B(9)-B(11)-B(26)-B(27)-B(44)-B(54)-B(148)-B(156)-B(196)
! JVS(165) = Jac_FULL(28,30)
  JVS(165) = 0
! JVS(166) = Jac_FULL(28,32)
  JVS(166) = -B(12)
! JVS(167) = Jac_FULL(28,33)
  JVS(167) = -B(45)
! JVS(168) = Jac_FULL(28,34)
  JVS(168) = -B(10)
! JVS(169) = Jac_FULL(28,37)
  JVS(169) = -B(55)
! JVS(170) = Jac_FULL(29,8)
  JVS(170) = BGS(6)*B(117)
! JVS(171) = Jac_FULL(29,22)
  JVS(171) = 1.39*B(119)
! JVS(172) = Jac_FULL(29,23)
  JVS(172) = B(159)
! JVS(173) = Jac_FULL(29,24)
  JVS(173) = 0.9*B(193)+0.5*B(197)+B(199)
! JVS(174) = Jac_FULL(29,25)
  JVS(174) = B(151)
! JVS(175) = Jac_FULL(29,26)
  JVS(175) = 0.5*B(198)
! JVS(176) = Jac_FULL(29,28)
  JVS(176) = 0
! JVS(177) = Jac_FULL(29,29)
  JVS(177) = -B(129)-B(131)-B(133)-B(135)
! JVS(178) = Jac_FULL(29,30)
  JVS(178) = B(152)+B(160)+B(200)
! JVS(179) = Jac_FULL(29,32)
  JVS(179) = 0
! JVS(180) = Jac_FULL(29,33)
  JVS(180) = BGS(6)*B(118)+1.39*B(120)+0.9*B(194)
! JVS(181) = Jac_FULL(29,34)
  JVS(181) = -B(130)
! JVS(182) = Jac_FULL(29,35)
  JVS(182) = -B(136)
! JVS(183) = Jac_FULL(29,36)
  JVS(183) = 0
! JVS(184) = Jac_FULL(29,37)
  JVS(184) = -B(132)
! JVS(185) = Jac_FULL(29,40)
  JVS(185) = -B(134)
! JVS(186) = Jac_FULL(30,7)
  JVS(186) = B(19)
! JVS(187) = Jac_FULL(30,17)
  JVS(187) = -B(186)
! JVS(188) = Jac_FULL(30,18)
  JVS(188) = -B(109)
! JVS(189) = Jac_FULL(30,20)
  JVS(189) = B(40)
! JVS(190) = Jac_FULL(30,23)
  JVS(190) = -B(159)
! JVS(191) = Jac_FULL(30,24)
  JVS(191) = -B(199)
! JVS(192) = Jac_FULL(30,25)
  JVS(192) = -B(151)
! JVS(193) = Jac_FULL(30,26)
  JVS(193) = B(7)
! JVS(194) = Jac_FULL(30,28)
  JVS(194) = B(11)
! JVS(195) = Jac_FULL(30,30)
  JVS(195) = -B(13)-B(17)-B(22)-B(24)-B(25)-B(64)-B(66)-B(69)-B(86)-B(93)-B(110)-B(152)-B(160)-B(187)-B(200)
! JVS(196) = Jac_FULL(30,32)
  JVS(196) = B(8)+B(12)-B(18)-B(23)
! JVS(197) = Jac_FULL(30,33)
  JVS(197) = B(41)
! JVS(198) = Jac_FULL(30,34)
  JVS(198) = -B(14)
! JVS(199) = Jac_FULL(30,37)
  JVS(199) = -B(65)-B(67)-B(70)
! JVS(200) = Jac_FULL(30,38)
  JVS(200) = -B(94)
! JVS(201) = Jac_FULL(30,39)
  JVS(201) = -B(87)
! JVS(202) = Jac_FULL(31,5)
  JVS(202) = B(115)
! JVS(203) = Jac_FULL(31,8)
  JVS(203) = BGS(5)*B(117)
! JVS(204) = Jac_FULL(31,9)
  JVS(204) = 0.84*B(177)
! JVS(205) = Jac_FULL(31,11)
  JVS(205) = 0.83*B(179)
! JVS(206) = Jac_FULL(31,17)
  JVS(206) = 0.85*B(184)
! JVS(207) = Jac_FULL(31,19)
  JVS(207) = 0.5*B(203)
! JVS(208) = Jac_FULL(31,23)
  JVS(208) = B(153)+BGS(12)*B(155)+BGS(21)*B(157)
! JVS(209) = Jac_FULL(31,25)
  JVS(209) = B(145)+B(149)
! JVS(210) = Jac_FULL(31,26)
  JVS(210) = B(150)+BGS(21)*B(158)
! JVS(211) = Jac_FULL(31,27)
  JVS(211) = B(103)+1.5*B(104)
! JVS(212) = Jac_FULL(31,28)
  JVS(212) = BGS(12)*B(156)
! JVS(213) = Jac_FULL(31,29)
  JVS(213) = 0
! JVS(214) = Jac_FULL(31,30)
  JVS(214) = 0
! JVS(215) = Jac_FULL(31,31)
  JVS(215) = -B(137)-B(139)-B(141)-B(143)
! JVS(216) = Jac_FULL(31,32)
  JVS(216) = 0
! JVS(217) = Jac_FULL(31,33)
  JVS(217) = 1.5*B(105)+B(111)+B(113)+B(116)+BGS(5)*B(118)+B(146)+B(154)+0.84*B(178)+0.83*B(180)+0.85*B(185)+0.5*B(204)
! JVS(218) = Jac_FULL(31,34)
  JVS(218) = B(95)-B(138)
! JVS(219) = Jac_FULL(31,35)
  JVS(219) = B(96)-B(144)
! JVS(220) = Jac_FULL(31,36)
  JVS(220) = 0
! JVS(221) = Jac_FULL(31,37)
  JVS(221) = B(88)-B(140)
! JVS(222) = Jac_FULL(31,38)
  JVS(222) = B(92)
! JVS(223) = Jac_FULL(31,39)
  JVS(223) = B(89)
! JVS(224) = Jac_FULL(31,40)
  JVS(224) = -B(142)
! JVS(225) = Jac_FULL(32,4)
  JVS(225) = B(102)
! JVS(226) = Jac_FULL(32,7)
  JVS(226) = B(19)
! JVS(227) = Jac_FULL(32,12)
  JVS(227) = B(50)+B(51)+B(52)
! JVS(228) = Jac_FULL(32,13)
  JVS(228) = -B(188)
! JVS(229) = Jac_FULL(32,17)
  JVS(229) = 0
! JVS(230) = Jac_FULL(32,20)
  JVS(230) = B(39)
! JVS(231) = Jac_FULL(32,22)
  JVS(231) = B(119)
! JVS(232) = Jac_FULL(32,23)
  JVS(232) = B(159)
! JVS(233) = Jac_FULL(32,24)
  JVS(233) = B(199)
! JVS(234) = Jac_FULL(32,25)
  JVS(234) = B(151)
! JVS(235) = Jac_FULL(32,26)
  JVS(235) = -B(5)-B(7)
! JVS(236) = Jac_FULL(32,28)
  JVS(236) = B(9)-B(11)
! JVS(237) = Jac_FULL(32,29)
  JVS(237) = B(129)
! JVS(238) = Jac_FULL(32,30)
  JVS(238) = 2*B(13)-B(17)+B(25)+B(152)+B(160)+B(200)
! JVS(239) = Jac_FULL(32,31)
  JVS(239) = B(137)
! JVS(240) = Jac_FULL(32,32)
  JVS(240) = -B(1)-B(6)-B(8)-B(12)-B(18)-2*B(35)-B(37)-B(48)-B(97)-B(189)
! JVS(241) = Jac_FULL(32,33)
  JVS(241) = -B(38)+B(53)+B(120)
! JVS(242) = Jac_FULL(32,34)
  JVS(242) = B(10)+2*B(14)+2*B(15)+B(46)+B(95)+B(130)+B(138)
! JVS(243) = Jac_FULL(32,35)
  JVS(243) = B(96)-B(98)
! JVS(244) = Jac_FULL(32,36)
  JVS(244) = 0
! JVS(245) = Jac_FULL(32,37)
  JVS(245) = B(47)-B(49)
! JVS(246) = Jac_FULL(32,38)
  JVS(246) = 0
! JVS(247) = Jac_FULL(32,39)
  JVS(247) = 0
! JVS(248) = Jac_FULL(32,40)
  JVS(248) = 0
! JVS(249) = Jac_FULL(33,2)
  JVS(249) = 2*B(28)
! JVS(250) = Jac_FULL(33,3)
  JVS(250) = 2*B(61)-B(62)
! JVS(251) = Jac_FULL(33,5)
  JVS(251) = -B(115)
! JVS(252) = Jac_FULL(33,6)
  JVS(252) = B(34)
! JVS(253) = Jac_FULL(33,8)
  JVS(253) = -B(117)
! JVS(254) = Jac_FULL(33,9)
  JVS(254) = -B(177)
! JVS(255) = Jac_FULL(33,10)
  JVS(255) = -B(181)
! JVS(256) = Jac_FULL(33,11)
  JVS(256) = -B(179)
! JVS(257) = Jac_FULL(33,12)
  JVS(257) = -B(52)
! JVS(258) = Jac_FULL(33,14)
  JVS(258) = -B(42)
! JVS(259) = Jac_FULL(33,17)
  JVS(259) = -B(184)
! JVS(260) = Jac_FULL(33,18)
  JVS(260) = -B(107)
! JVS(261) = Jac_FULL(33,19)
  JVS(261) = B(81)-0.5*B(203)
! JVS(262) = Jac_FULL(33,20)
  JVS(262) = B(39)-B(40)
! JVS(263) = Jac_FULL(33,21)
  JVS(263) = -B(72)
! JVS(264) = Jac_FULL(33,22)
  JVS(264) = -B(119)
! JVS(265) = Jac_FULL(33,23)
  JVS(265) = -B(153)+BGS(14)*B(155)
! JVS(266) = Jac_FULL(33,24)
  JVS(266) = -B(193)+0.1*B(195)
! JVS(267) = Jac_FULL(33,25)
  JVS(267) = -B(145)
! JVS(268) = Jac_FULL(33,26)
  JVS(268) = 0
! JVS(269) = Jac_FULL(33,27)
  JVS(269) = -B(104)
! JVS(270) = Jac_FULL(33,28)
  JVS(270) = -B(44)+B(54)+BGS(14)*B(156)+0.1*B(196)
! JVS(271) = Jac_FULL(33,29)
  JVS(271) = 0
! JVS(272) = Jac_FULL(33,30)
  JVS(272) = 0
! JVS(273) = Jac_FULL(33,31)
  JVS(273) = 0
! JVS(274) = Jac_FULL(33,32)
  JVS(274) = -B(37)
! JVS(275) = Jac_FULL(33,33)
  JVS(275) = -B(32)-B(38)-B(41)-B(43)-B(45)-B(53)-B(63)-B(73)-B(84)-B(90)-B(105)-B(108)-B(111)-B(113)-B(116)-B(118)&
               &-B(120)-B(146)-B(154)-B(178)-B(180)-B(182)-B(185)-B(194)-B(201)-0.5*B(204)
! JVS(276) = Jac_FULL(33,34)
  JVS(276) = -B(33)+B(46)
! JVS(277) = Jac_FULL(33,35)
  JVS(277) = 0
! JVS(278) = Jac_FULL(33,36)
  JVS(278) = 0
! JVS(279) = Jac_FULL(33,37)
  JVS(279) = B(47)+B(55)-B(202)
! JVS(280) = Jac_FULL(33,38)
  JVS(280) = -B(91)
! JVS(281) = Jac_FULL(33,39)
  JVS(281) = -B(85)
! JVS(282) = Jac_FULL(33,40)
  JVS(282) = 0
! JVS(283) = Jac_FULL(34,6)
  JVS(283) = B(34)
! JVS(284) = Jac_FULL(34,26)
  JVS(284) = B(5)
! JVS(285) = Jac_FULL(34,28)
  JVS(285) = -B(9)
! JVS(286) = Jac_FULL(34,29)
  JVS(286) = -B(129)
! JVS(287) = Jac_FULL(34,30)
  JVS(287) = -B(13)+B(22)+B(24)
! JVS(288) = Jac_FULL(34,31)
  JVS(288) = -B(137)
! JVS(289) = Jac_FULL(34,32)
  JVS(289) = B(1)+B(6)+B(23)
! JVS(290) = Jac_FULL(34,33)
  JVS(290) = -B(32)
! JVS(291) = Jac_FULL(34,34)
  JVS(291) = -B(10)-B(14)-2*B(15)-B(33)-B(46)-B(95)-B(121)-B(130)-B(138)
! JVS(292) = Jac_FULL(34,35)
  JVS(292) = -B(96)
! JVS(293) = Jac_FULL(34,36)
  JVS(293) = -B(122)
! JVS(294) = Jac_FULL(34,37)
  JVS(294) = -B(47)
! JVS(295) = Jac_FULL(34,38)
  JVS(295) = 0
! JVS(296) = Jac_FULL(34,39)
  JVS(296) = 0
! JVS(297) = Jac_FULL(34,40)
  JVS(297) = 0
! JVS(298) = Jac_FULL(35,4)
  JVS(298) = B(102)
! JVS(299) = Jac_FULL(35,10)
  JVS(299) = B(181)+B(183)
! JVS(300) = Jac_FULL(35,11)
  JVS(300) = 0
! JVS(301) = Jac_FULL(35,18)
  JVS(301) = B(106)+B(107)+B(109)
! JVS(302) = Jac_FULL(35,24)
  JVS(302) = 0.2*B(193)
! JVS(303) = Jac_FULL(35,26)
  JVS(303) = 0
! JVS(304) = Jac_FULL(35,27)
  JVS(304) = B(103)+B(104)
! JVS(305) = Jac_FULL(35,28)
  JVS(305) = 0
! JVS(306) = Jac_FULL(35,29)
  JVS(306) = -B(135)
! JVS(307) = Jac_FULL(35,30)
  JVS(307) = B(93)+B(110)
! JVS(308) = Jac_FULL(35,31)
  JVS(308) = -B(143)
! JVS(309) = Jac_FULL(35,32)
  JVS(309) = -B(97)
! JVS(310) = Jac_FULL(35,33)
  JVS(310) = B(90)+B(105)+B(108)+B(182)+0.2*B(194)
! JVS(311) = Jac_FULL(35,34)
  JVS(311) = -B(95)
! JVS(312) = Jac_FULL(35,35)
  JVS(312) = -B(96)-B(98)-B(99)-2*B(101)-B(127)-B(136)-B(144)
! JVS(313) = Jac_FULL(35,36)
  JVS(313) = -B(128)
! JVS(314) = Jac_FULL(35,37)
  JVS(314) = -B(100)
! JVS(315) = Jac_FULL(35,38)
  JVS(315) = B(91)+B(94)
! JVS(316) = Jac_FULL(35,39)
  JVS(316) = 0
! JVS(317) = Jac_FULL(35,40)
  JVS(317) = 0
! JVS(318) = Jac_FULL(36,8)
  JVS(318) = BGS(4)*B(117)
! JVS(319) = Jac_FULL(36,17)
  JVS(319) = 0.15*B(184)
! JVS(320) = Jac_FULL(36,24)
  JVS(320) = 0.1*B(193)
! JVS(321) = Jac_FULL(36,26)
  JVS(321) = 0
! JVS(322) = Jac_FULL(36,28)
  JVS(322) = 0
! JVS(323) = Jac_FULL(36,30)
  JVS(323) = 0
! JVS(324) = Jac_FULL(36,32)
  JVS(324) = 0
! JVS(325) = Jac_FULL(36,33)
  JVS(325) = BGS(4)*B(118)+0.15*B(185)+0.1*B(194)
! JVS(326) = Jac_FULL(36,34)
  JVS(326) = -B(121)
! JVS(327) = Jac_FULL(36,35)
  JVS(327) = -B(127)
! JVS(328) = Jac_FULL(36,36)
  JVS(328) = -B(122)-B(123)-B(125)-B(128)
! JVS(329) = Jac_FULL(36,37)
  JVS(329) = -B(124)
! JVS(330) = Jac_FULL(36,38)
  JVS(330) = 0
! JVS(331) = Jac_FULL(36,39)
  JVS(331) = 0
! JVS(332) = Jac_FULL(36,40)
  JVS(332) = -B(126)
! JVS(333) = Jac_FULL(37,3)
  JVS(333) = B(62)
! JVS(334) = Jac_FULL(37,9)
  JVS(334) = 0.16*B(177)
! JVS(335) = Jac_FULL(37,10)
  JVS(335) = B(183)
! JVS(336) = Jac_FULL(37,11)
  JVS(336) = 0.17*B(179)
! JVS(337) = Jac_FULL(37,12)
  JVS(337) = B(50)+B(51)
! JVS(338) = Jac_FULL(37,13)
  JVS(338) = -B(190)
! JVS(339) = Jac_FULL(37,14)
  JVS(339) = B(42)
! JVS(340) = Jac_FULL(37,17)
  JVS(340) = 0
! JVS(341) = Jac_FULL(37,18)
  JVS(341) = B(106)
! JVS(342) = Jac_FULL(37,19)
  JVS(342) = B(81)
! JVS(343) = Jac_FULL(37,21)
  JVS(343) = B(72)
! JVS(344) = Jac_FULL(37,23)
  JVS(344) = BGS(13)*B(155)+BGS(2)*B(157)
! JVS(345) = Jac_FULL(37,24)
  JVS(345) = 0.7*B(193)+0.4*B(195)+0.6*B(197)
! JVS(346) = Jac_FULL(37,25)
  JVS(346) = 0.12*B(147)+B(149)
! JVS(347) = Jac_FULL(37,26)
  JVS(347) = B(150)+BGS(2)*B(158)+0.6*B(198)
! JVS(348) = Jac_FULL(37,28)
  JVS(348) = B(44)-B(54)+0.12*B(148)+BGS(13)*B(156)+0.4*B(196)
! JVS(349) = Jac_FULL(37,29)
  JVS(349) = -B(131)+B(135)
! JVS(350) = Jac_FULL(37,30)
  JVS(350) = -B(64)-B(66)-B(69)+B(86)
! JVS(351) = Jac_FULL(37,31)
  JVS(351) = B(137)-B(139)+0.5*B(141)+B(143)
! JVS(352) = Jac_FULL(37,32)
  JVS(352) = -B(48)
! JVS(353) = Jac_FULL(37,33)
  JVS(353) = B(43)+B(45)+B(63)+B(73)+B(84)+0.16*B(178)+0.17*B(180)+0.7*B(194)-B(201)
! JVS(354) = Jac_FULL(37,34)
  JVS(354) = -B(46)+B(138)
! JVS(355) = Jac_FULL(37,35)
  JVS(355) = -B(99)+2*B(101)+B(127)+B(136)+B(144)
! JVS(356) = Jac_FULL(37,36)
  JVS(356) = -B(123)+0.5*B(125)+B(128)
! JVS(357) = Jac_FULL(37,37)
  JVS(357) = -B(47)-B(49)-B(55)-2*B(56)-2*B(57)-2*B(59)-B(65)-B(67)-B(70)-B(88)-B(100)-B(124)-B(132)-B(140)-B(191)&
               &-B(202)
! JVS(358) = Jac_FULL(37,38)
  JVS(358) = B(92)
! JVS(359) = Jac_FULL(37,39)
  JVS(359) = 2*B(82)+B(85)+B(87)-B(89)
! JVS(360) = Jac_FULL(37,40)
  JVS(360) = 0.5*B(126)+0.5*B(142)
! JVS(361) = Jac_FULL(38,5)
  JVS(361) = 0.3*B(115)
! JVS(362) = Jac_FULL(38,8)
  JVS(362) = BGS(2)*B(117)
! JVS(363) = Jac_FULL(38,15)
  JVS(363) = -B(173)
! JVS(364) = Jac_FULL(38,16)
  JVS(364) = B(163)-B(175)
! JVS(365) = Jac_FULL(38,21)
  JVS(365) = B(164)
! JVS(366) = Jac_FULL(38,22)
  JVS(366) = 1.52*B(119)
! JVS(367) = Jac_FULL(38,23)
  JVS(367) = BGS(9)*B(153)+BGS(11)*B(155)+BGS(19)*B(157)+BGS(9)*B(159)
! JVS(368) = Jac_FULL(38,24)
  JVS(368) = 0.2*B(193)+0.4*B(195)+B(197)+B(199)
! JVS(369) = Jac_FULL(38,25)
  JVS(369) = 0.22*B(145)
! JVS(370) = Jac_FULL(38,26)
  JVS(370) = BGS(19)*B(158)+B(198)
! JVS(371) = Jac_FULL(38,27)
  JVS(371) = B(103)+0.5*B(104)
! JVS(372) = Jac_FULL(38,28)
  JVS(372) = BGS(11)*B(156)+0.4*B(196)
! JVS(373) = Jac_FULL(38,30)
  JVS(373) = -B(93)+BGS(9)*B(160)+B(200)
! JVS(374) = Jac_FULL(38,32)
  JVS(374) = 0
! JVS(375) = Jac_FULL(38,33)
  JVS(375) = -B(90)+0.5*B(105)+B(113)+0.3*B(116)+BGS(2)*B(118)+1.52*B(120)+0.22*B(146)+BGS(9)*B(154)+0.2*B(194)
! JVS(376) = Jac_FULL(38,34)
  JVS(376) = 0
! JVS(377) = Jac_FULL(38,35)
  JVS(377) = 0
! JVS(378) = Jac_FULL(38,36)
  JVS(378) = 0
! JVS(379) = Jac_FULL(38,37)
  JVS(379) = 0
! JVS(380) = Jac_FULL(38,38)
  JVS(380) = -B(91)-B(92)-B(94)-B(174)-B(176)
! JVS(381) = Jac_FULL(38,39)
  JVS(381) = 0
! JVS(382) = Jac_FULL(38,40)
  JVS(382) = 0
! JVS(383) = Jac_FULL(39,8)
  JVS(383) = BGS(1)*B(117)
! JVS(384) = Jac_FULL(39,9)
  JVS(384) = 0.11*B(177)
! JVS(385) = Jac_FULL(39,11)
  JVS(385) = BGS(24)*B(179)
! JVS(386) = Jac_FULL(39,15)
  JVS(386) = B(161)-B(169)
! JVS(387) = Jac_FULL(39,16)
  JVS(387) = -B(171)
! JVS(388) = Jac_FULL(39,21)
  JVS(388) = B(162)
! JVS(389) = Jac_FULL(39,22)
  JVS(389) = 0.16*B(119)
! JVS(390) = Jac_FULL(39,23)
  JVS(390) = BGS(8)*B(153)+BGS(1)*B(155)+BGS(18)*B(157)+BGS(8)*B(159)
! JVS(391) = Jac_FULL(39,24)
  JVS(391) = B(193)+B(195)+B(199)
! JVS(392) = Jac_FULL(39,25)
  JVS(392) = 1.56*B(145)+B(147)+B(149)+2*B(151)
! JVS(393) = Jac_FULL(39,26)
  JVS(393) = B(150)+BGS(18)*B(158)
! JVS(394) = Jac_FULL(39,27)
  JVS(394) = 0.5*B(104)
! JVS(395) = Jac_FULL(39,28)
  JVS(395) = B(148)+BGS(1)*B(156)+B(196)
! JVS(396) = Jac_FULL(39,29)
  JVS(396) = B(135)
! JVS(397) = Jac_FULL(39,30)
  JVS(397) = -B(86)+2*B(152)+BGS(8)*B(160)+B(200)
! JVS(398) = Jac_FULL(39,31)
  JVS(398) = B(143)
! JVS(399) = Jac_FULL(39,32)
  JVS(399) = 0
! JVS(400) = Jac_FULL(39,33)
  JVS(400) = -B(84)+0.5*B(105)+B(111)+BGS(1)*B(118)+0.16*B(120)+1.56*B(146)+BGS(8)*B(154)+0.11*B(178)+BGS(24)*B(180)&
               &+B(194)
! JVS(401) = Jac_FULL(39,34)
  JVS(401) = B(95)
! JVS(402) = Jac_FULL(39,35)
  JVS(402) = B(96)+B(99)+2*B(101)+B(127)+B(136)+B(144)
! JVS(403) = Jac_FULL(39,36)
  JVS(403) = B(128)
! JVS(404) = Jac_FULL(39,37)
  JVS(404) = -B(88)+B(100)
! JVS(405) = Jac_FULL(39,38)
  JVS(405) = B(92)
! JVS(406) = Jac_FULL(39,39)
  JVS(406) = -B(82)-B(83)-B(85)-B(87)-B(89)-B(170)-B(172)
! JVS(407) = Jac_FULL(39,40)
  JVS(407) = 0
! JVS(408) = Jac_FULL(40,5)
  JVS(408) = B(115)
! JVS(409) = Jac_FULL(40,8)
  JVS(409) = BGS(7)*B(117)
! JVS(410) = Jac_FULL(40,9)
  JVS(410) = 0.84*B(177)
! JVS(411) = Jac_FULL(40,11)
  JVS(411) = 0.83*B(179)
! JVS(412) = Jac_FULL(40,17)
  JVS(412) = B(184)
! JVS(413) = Jac_FULL(40,19)
  JVS(413) = 0.5*B(203)
! JVS(414) = Jac_FULL(40,22)
  JVS(414) = 1.39*B(119)
! JVS(415) = Jac_FULL(40,23)
  JVS(415) = B(153)+BGS(12)*B(155)+BGS(21)*B(157)+B(159)
! JVS(416) = Jac_FULL(40,24)
  JVS(416) = B(193)+0.5*B(197)+B(199)
! JVS(417) = Jac_FULL(40,25)
  JVS(417) = B(145)+B(149)+B(151)
! JVS(418) = Jac_FULL(40,26)
  JVS(418) = B(150)+BGS(21)*B(158)+0.5*B(198)
! JVS(419) = Jac_FULL(40,27)
  JVS(419) = B(103)+1.5*B(104)
! JVS(420) = Jac_FULL(40,28)
  JVS(420) = BGS(12)*B(156)
! JVS(421) = Jac_FULL(40,29)
  JVS(421) = 0
! JVS(422) = Jac_FULL(40,30)
  JVS(422) = B(152)+B(160)+B(200)
! JVS(423) = Jac_FULL(40,31)
  JVS(423) = 0
! JVS(424) = Jac_FULL(40,32)
  JVS(424) = 0
! JVS(425) = Jac_FULL(40,33)
  JVS(425) = 1.5*B(105)+B(111)+B(113)+B(116)+BGS(7)*B(118)+1.39*B(120)+B(146)+B(154)+0.84*B(178)+0.83*B(180)+B(185)&
               &+B(194)+0.5*B(204)
! JVS(426) = Jac_FULL(40,34)
  JVS(426) = -B(74)+B(95)
! JVS(427) = Jac_FULL(40,35)
  JVS(427) = -B(79)+B(96)
! JVS(428) = Jac_FULL(40,36)
  JVS(428) = 0
! JVS(429) = Jac_FULL(40,37)
  JVS(429) = -B(76)+B(88)
! JVS(430) = Jac_FULL(40,38)
  JVS(430) = B(92)
! JVS(431) = Jac_FULL(40,39)
  JVS(431) = B(89)
! JVS(432) = Jac_FULL(40,40)
  JVS(432) = -B(75)-B(77)-2*B(78)-B(80)

  RETURN
END SUBROUTINE Jac_SP_day

SUBROUTINE ros_PrepareMatrix_day ( H, gam, &
             Jac0, Ghimj, Singular )
! --- --- --- --- --- --- --- --- --- --- --- --- ---
!  Prepares the LHS matrix for stage calculations
!  1.  Construct Ghimj = 1/(H*ham) - Jac0
!      "(Gamma H) Inverse Minus Jacobian"
!  2.  Repeat LU decomposition of Ghimj until successful.
!       -half the step size if LU decomposition fails and retry
!       -exit after 5 consecutive fails
! --- --- --- --- --- --- --- --- --- --- --- --- ---
   IMPLICIT NONE
!~~~> Input arguments
   real(kind=8), INTENT(IN) ::  Jac0(LU_NONZERO)
   real(kind=8), INTENT(IN) ::  gam
!~~~> Output arguments
   real(kind=8), INTENT(OUT) :: Ghimj(LU_NONZERO)
   LOGICAL, INTENT(OUT) ::  Singular
!~~~> Inout arguments
   real(kind=8), INTENT(INOUT) :: H
!~~~> Local variables
   INTEGER(KIND=4)  :: i, ising, Nconsecutive
   real(kind=8) :: ghinv
   real(kind=8), PARAMETER :: ONE  = 1.0d0, HALF = 0.5d0
! Sparse Jacobian Data

  INTEGER, PARAMETER, DIMENSION(41) :: LU_DIAG = (/ &
       1,  6,  8, 11, 14, 16, 20, 23, 25, 28, 31, 33, &
      37, 45, 55, 62, 71, 77, 82, 92,103,113,120,125, &
     131,140,150,164,177,195,215,240,275,291,312,328, &
     357,380,406,432,433 /)

   Nconsecutive = 0
   Singular = .TRUE.
   DO WHILE (Singular)
!~~~>    Construct Ghimj = 1/(H*gam) - Jac0
     Ghimj = -ONE*Jac0
     ghinv = ONE/(H*gam)
     DO i=1,N
       Ghimj(LU_DIAG(i)) = Ghimj(LU_DIAG(i))+ghinv
     END DO
!~~~>    Compute LU decomposition
     CALL KppDecomp_day ( Ghimj, ising, N, LU_NONZERO )
     IF (ising == 0) THEN
!~~~>    If successful done
        Singular = .FALSE.
     ELSE
!~~~>    If unsuccessful half the step size; if 5 consecutive fails then return
        Nconsecutive = Nconsecutive+1
        Singular = .TRUE.
        PRINT*,'Warning: LU Decomposition returned ising = ',ising
        IF (Nconsecutive <= 5) THEN
           H = H*HALF
        ELSE
           RETURN
        END IF
      END IF
   END DO

  RETURN
END SUBROUTINE ros_PrepareMatrix_day

SUBROUTINE KppDecomp_day( JVS, IER, NVAR, LU_NONZERO )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      implicit none
      integer(kind=4), intent(in) :: NVAR, LU_NONZERO
      INTEGER(kind=4), intent(out)  :: IER
      real(kind=8), intent(inout) :: JVS(LU_NONZERO)
!local variables
      real(kind=8) :: W(NVAR), a
      INTEGER(kind=4)  :: k, kk, j, jj
! Sparse Jacobian Data

  INTEGER, PARAMETER, DIMENSION(360) :: LU_ICOL_0 = (/ &
       1, 15, 16, 21, 33,  2, 28,  3, 33, 37,  4, 32, &
      35,  5, 33,  6, 32, 33, 34,  7, 30, 32,  8, 33, &
       9, 33,  9, 10, 11, 33, 11, 33, 12, 32, 33, 37, &
      13, 17, 30, 32, 37,  9, 10, 11, 14, 18, 23, 25, &
      26, 28, 30, 33, 38, 39, 15, 21, 23, 25, 28, 38, &
      39, 16, 21, 23, 24, 28, 38, 39,  9, 11, 17, 30, &
      33,  9, 11, 17, 18, 24, 28, 30, 33, 19, 29, 31, &
      33, 35, 36, 37,  7, 17, 18, 20, 24, 28, 30, 32, &
      33, 37, 38, 39, 15, 16, 21, 23, 24, 25, 28, 33, &
      38, 39, 13, 17, 22, 30, 32, 33, 34, 36, 37, 23, &
      26, 28, 30, 33, 24, 26, 28, 30, 33, 24, 25, 26, &
      28, 30, 33,  2, 23, 24, 25, 26, 28, 30, 32, 33, &
       5,  8, 22, 23, 26, 27, 28, 30, 32, 33, 34, 35, &
      36, 37, 40, 23, 24, 25, 26, 28, 30, 32, 33, 34, &
      37,  8, 22, 23, 24, 25, 26, 28, 29, 30, 32, 33, &
      34, 35, 36, 37, 40,  7, 17, 18, 20, 23, 24, 25, &
      26, 28, 30, 32, 33, 34, 37, 38, 39,  5,  8,  9, &
      11, 17, 19, 23, 25, 26, 27, 28, 29, 30, 31, 32, &
      33, 34, 35, 36, 37, 38, 39, 40,  4,  7, 12, 13, &
      17, 20, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, &
      33, 34, 35, 36, 37, 38, 39, 40,  2,  3,  5,  6, &
       8,  9, 10, 11, 12, 14, 17, 18, 19, 20, 21, 22, &
      23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, &
      35, 36, 37, 38, 39, 40,  6, 26, 28, 29, 30, 31, &
      32, 33, 34, 35, 36, 37, 38, 39, 40,  4, 10, 11, &
      18, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, &
      36, 37, 38, 39, 40,  8, 17, 24, 26, 28, 30, 32, &
      33, 34, 35, 36, 37, 38, 39, 40,  3,  9, 10, 11, &
      12, 13, 14, 17, 18, 19, 21, 23, 24, 25, 26, 28, &
      29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40 /)
  INTEGER, PARAMETER, DIMENSION(72) :: LU_ICOL_1 = (/ &
       5,  8, 15, 16, 21, 22, 23, 24, 25, 26, 27, 28, &
      30, 32, 33, 34, 35, 36, 37, 38, 39, 40,  8,  9, &
      11, 15, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, &
      30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  5, &
       8,  9, 11, 17, 19, 22, 23, 24, 25, 26, 27, 28, &
      29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40 /)
  INTEGER, PARAMETER, DIMENSION(432) :: LU_ICOL = (/&
    LU_ICOL_0, LU_ICOL_1 /)

  INTEGER, PARAMETER, DIMENSION(41) :: LU_CROW = (/ &
       1,  6,  8, 11, 14, 16, 20, 23, 25, 27, 31, 33, &
      37, 42, 55, 62, 69, 74, 82, 89,101,111,120,125, &
     130,136,145,160,170,186,202,225,249,283,298,318, &
     333,361,383,408,433 /)

  INTEGER, PARAMETER, DIMENSION(41) :: LU_DIAG = (/ &
       1,  6,  8, 11, 14, 16, 20, 23, 25, 28, 31, 33, &
      37, 45, 55, 62, 71, 77, 82, 92,103,113,120,125, &
     131,140,150,164,177,195,215,240,275,291,312,328, &
     357,380,406,432,433 /)


      a = 0.
      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO

  RETURN
END SUBROUTINE KppDecomp_day

SUBROUTINE KppSolve_day ( JVS, X, NVAR, LU_NONZERO )
  implicit none
  integer(kind=4), intent(in) :: nvar, LU_NONZERO
! JVS - sparse Jacobian of variables
  real(kind=8), intent(in) :: JVS(LU_NONZERO)
! X - Vector for variables
  real(kind=8), intent(inout):: X(NVAR)

  X(10) = X(10)-JVS(27)*X(9)
  X(14) = X(14)-JVS(42)*X(9)-JVS(43)*X(10)-JVS(44)*X(11)
  X(17) = X(17)-JVS(69)*X(9)-JVS(70)*X(11)
  X(18) = X(18)-JVS(74)*X(9)-JVS(75)*X(11)-JVS(76)*X(17)
  X(20) = X(20)-JVS(89)*X(7)-JVS(90)*X(17)-JVS(91)*X(18)
  X(21) = X(21)-JVS(101)*X(15)-JVS(102)*X(16)
  X(22) = X(22)-JVS(111)*X(13)-JVS(112)*X(17)
  X(25) = X(25)-JVS(130)*X(24)
  X(26) = X(26)-JVS(136)*X(2)-JVS(137)*X(23)-JVS(138)*X(24)-JVS(139)*X(25)
  X(27) = X(27)-JVS(145)*X(5)-JVS(146)*X(8)-JVS(147)*X(22)-JVS(148)*X(23)-JVS(149)*X(26)
  X(28) = X(28)-JVS(160)*X(23)-JVS(161)*X(24)-JVS(162)*X(25)-JVS(163)*X(26)
  X(29) = X(29)-JVS(170)*X(8)-JVS(171)*X(22)-JVS(172)*X(23)-JVS(173)*X(24)-JVS(174)*X(25)-JVS(175)*X(26)-JVS(176)*X(28)
  X(30) = X(30)-JVS(186)*X(7)-JVS(187)*X(17)-JVS(188)*X(18)-JVS(189)*X(20)-JVS(190)*X(23)-JVS(191)*X(24)-JVS(192)*X(25)&
            &-JVS(193)*X(26)-JVS(194)*X(28)
  X(31) = X(31)-JVS(202)*X(5)-JVS(203)*X(8)-JVS(204)*X(9)-JVS(205)*X(11)-JVS(206)*X(17)-JVS(207)*X(19)-JVS(208)*X(23)&
            &-JVS(209)*X(25)-JVS(210)*X(26)-JVS(211)*X(27)-JVS(212)*X(28)-JVS(213)*X(29)-JVS(214)*X(30)
  X(32) = X(32)-JVS(225)*X(4)-JVS(226)*X(7)-JVS(227)*X(12)-JVS(228)*X(13)-JVS(229)*X(17)-JVS(230)*X(20)-JVS(231)*X(22)&
            &-JVS(232)*X(23)-JVS(233)*X(24)-JVS(234)*X(25)-JVS(235)*X(26)-JVS(236)*X(28)-JVS(237)*X(29)-JVS(238)*X(30)&
            &-JVS(239)*X(31)
  X(33) = X(33)-JVS(249)*X(2)-JVS(250)*X(3)-JVS(251)*X(5)-JVS(252)*X(6)-JVS(253)*X(8)-JVS(254)*X(9)-JVS(255)*X(10)&
            &-JVS(256)*X(11)-JVS(257)*X(12)-JVS(258)*X(14)-JVS(259)*X(17)-JVS(260)*X(18)-JVS(261)*X(19)-JVS(262)*X(20)&
            &-JVS(263)*X(21)-JVS(264)*X(22)-JVS(265)*X(23)-JVS(266)*X(24)-JVS(267)*X(25)-JVS(268)*X(26)-JVS(269)*X(27)&
            &-JVS(270)*X(28)-JVS(271)*X(29)-JVS(272)*X(30)-JVS(273)*X(31)-JVS(274)*X(32)
  X(34) = X(34)-JVS(283)*X(6)-JVS(284)*X(26)-JVS(285)*X(28)-JVS(286)*X(29)-JVS(287)*X(30)-JVS(288)*X(31)-JVS(289)*X(32)&
            &-JVS(290)*X(33)
  X(35) = X(35)-JVS(298)*X(4)-JVS(299)*X(10)-JVS(300)*X(11)-JVS(301)*X(18)-JVS(302)*X(24)-JVS(303)*X(26)-JVS(304)*X(27)&
            &-JVS(305)*X(28)-JVS(306)*X(29)-JVS(307)*X(30)-JVS(308)*X(31)-JVS(309)*X(32)-JVS(310)*X(33)-JVS(311)*X(34)
  X(36) = X(36)-JVS(318)*X(8)-JVS(319)*X(17)-JVS(320)*X(24)-JVS(321)*X(26)-JVS(322)*X(28)-JVS(323)*X(30)-JVS(324)*X(32)&
            &-JVS(325)*X(33)-JVS(326)*X(34)-JVS(327)*X(35)
  X(37) = X(37)-JVS(333)*X(3)-JVS(334)*X(9)-JVS(335)*X(10)-JVS(336)*X(11)-JVS(337)*X(12)-JVS(338)*X(13)-JVS(339)*X(14)&
            &-JVS(340)*X(17)-JVS(341)*X(18)-JVS(342)*X(19)-JVS(343)*X(21)-JVS(344)*X(23)-JVS(345)*X(24)-JVS(346)*X(25)&
            &-JVS(347)*X(26)-JVS(348)*X(28)-JVS(349)*X(29)-JVS(350)*X(30)-JVS(351)*X(31)-JVS(352)*X(32)-JVS(353)*X(33)&
            &-JVS(354)*X(34)-JVS(355)*X(35)-JVS(356)*X(36)
  X(38) = X(38)-JVS(361)*X(5)-JVS(362)*X(8)-JVS(363)*X(15)-JVS(364)*X(16)-JVS(365)*X(21)-JVS(366)*X(22)-JVS(367)*X(23)&
            &-JVS(368)*X(24)-JVS(369)*X(25)-JVS(370)*X(26)-JVS(371)*X(27)-JVS(372)*X(28)-JVS(373)*X(30)-JVS(374)*X(32)&
            &-JVS(375)*X(33)-JVS(376)*X(34)-JVS(377)*X(35)-JVS(378)*X(36)-JVS(379)*X(37)
  X(39) = X(39)-JVS(383)*X(8)-JVS(384)*X(9)-JVS(385)*X(11)-JVS(386)*X(15)-JVS(387)*X(16)-JVS(388)*X(21)-JVS(389)*X(22)&
            &-JVS(390)*X(23)-JVS(391)*X(24)-JVS(392)*X(25)-JVS(393)*X(26)-JVS(394)*X(27)-JVS(395)*X(28)-JVS(396)*X(29)&
            &-JVS(397)*X(30)-JVS(398)*X(31)-JVS(399)*X(32)-JVS(400)*X(33)-JVS(401)*X(34)-JVS(402)*X(35)-JVS(403)*X(36)&
            &-JVS(404)*X(37)-JVS(405)*X(38)
  X(40) = X(40)-JVS(408)*X(5)-JVS(409)*X(8)-JVS(410)*X(9)-JVS(411)*X(11)-JVS(412)*X(17)-JVS(413)*X(19)-JVS(414)*X(22)&
            &-JVS(415)*X(23)-JVS(416)*X(24)-JVS(417)*X(25)-JVS(418)*X(26)-JVS(419)*X(27)-JVS(420)*X(28)-JVS(421)*X(29)&
            &-JVS(422)*X(30)-JVS(423)*X(31)-JVS(424)*X(32)-JVS(425)*X(33)-JVS(426)*X(34)-JVS(427)*X(35)-JVS(428)*X(36)&
            &-JVS(429)*X(37)-JVS(430)*X(38)-JVS(431)*X(39)
  X(40) = X(40)/JVS(432)
  X(39) = (X(39)-JVS(407)*X(40))/(JVS(406))
  X(38) = (X(38)-JVS(381)*X(39)-JVS(382)*X(40))/(JVS(380))
  X(37) = (X(37)-JVS(358)*X(38)-JVS(359)*X(39)-JVS(360)*X(40))/(JVS(357))
  X(36) = (X(36)-JVS(329)*X(37)-JVS(330)*X(38)-JVS(331)*X(39)-JVS(332)*X(40))/(JVS(328))
  X(35) = (X(35)-JVS(313)*X(36)-JVS(314)*X(37)-JVS(315)*X(38)-JVS(316)*X(39)-JVS(317)*X(40))/(JVS(312))
  X(34) = (X(34)-JVS(292)*X(35)-JVS(293)*X(36)-JVS(294)*X(37)-JVS(295)*X(38)-JVS(296)*X(39)-JVS(297)*X(40))/(JVS(291))
  X(33) = (X(33)-JVS(276)*X(34)-JVS(277)*X(35)-JVS(278)*X(36)-JVS(279)*X(37)-JVS(280)*X(38)-JVS(281)*X(39)-JVS(282)&
            &*X(40))/(JVS(275))
  X(32) = (X(32)-JVS(241)*X(33)-JVS(242)*X(34)-JVS(243)*X(35)-JVS(244)*X(36)-JVS(245)*X(37)-JVS(246)*X(38)-JVS(247)&
            &*X(39)-JVS(248)*X(40))/(JVS(240))
  X(31) = (X(31)-JVS(216)*X(32)-JVS(217)*X(33)-JVS(218)*X(34)-JVS(219)*X(35)-JVS(220)*X(36)-JVS(221)*X(37)-JVS(222)&
            &*X(38)-JVS(223)*X(39)-JVS(224)*X(40))/(JVS(215))
  X(30) = (X(30)-JVS(196)*X(32)-JVS(197)*X(33)-JVS(198)*X(34)-JVS(199)*X(37)-JVS(200)*X(38)-JVS(201)*X(39))/(JVS(195))
  X(29) = (X(29)-JVS(178)*X(30)-JVS(179)*X(32)-JVS(180)*X(33)-JVS(181)*X(34)-JVS(182)*X(35)-JVS(183)*X(36)-JVS(184)&
            &*X(37)-JVS(185)*X(40))/(JVS(177))
  X(28) = (X(28)-JVS(165)*X(30)-JVS(166)*X(32)-JVS(167)*X(33)-JVS(168)*X(34)-JVS(169)*X(37))/(JVS(164))
  X(27) = (X(27)-JVS(151)*X(28)-JVS(152)*X(30)-JVS(153)*X(32)-JVS(154)*X(33)-JVS(155)*X(34)-JVS(156)*X(35)-JVS(157)&
            &*X(36)-JVS(158)*X(37)-JVS(159)*X(40))/(JVS(150))
  X(26) = (X(26)-JVS(141)*X(28)-JVS(142)*X(30)-JVS(143)*X(32)-JVS(144)*X(33))/(JVS(140))
  X(25) = (X(25)-JVS(132)*X(26)-JVS(133)*X(28)-JVS(134)*X(30)-JVS(135)*X(33))/(JVS(131))
  X(24) = (X(24)-JVS(126)*X(26)-JVS(127)*X(28)-JVS(128)*X(30)-JVS(129)*X(33))/(JVS(125))
  X(23) = (X(23)-JVS(121)*X(26)-JVS(122)*X(28)-JVS(123)*X(30)-JVS(124)*X(33))/(JVS(120))
  X(22) = (X(22)-JVS(114)*X(30)-JVS(115)*X(32)-JVS(116)*X(33)-JVS(117)*X(34)-JVS(118)*X(36)-JVS(119)*X(37))/(JVS(113))
  X(21) = (X(21)-JVS(104)*X(23)-JVS(105)*X(24)-JVS(106)*X(25)-JVS(107)*X(28)-JVS(108)*X(33)-JVS(109)*X(38)-JVS(110)&
            &*X(39))/(JVS(103))
  X(20) = (X(20)-JVS(93)*X(24)-JVS(94)*X(28)-JVS(95)*X(30)-JVS(96)*X(32)-JVS(97)*X(33)-JVS(98)*X(37)-JVS(99)*X(38)&
            &-JVS(100)*X(39))/(JVS(92))
  X(19) = (X(19)-JVS(83)*X(29)-JVS(84)*X(31)-JVS(85)*X(33)-JVS(86)*X(35)-JVS(87)*X(36)-JVS(88)*X(37))/(JVS(82))
  X(18) = (X(18)-JVS(78)*X(24)-JVS(79)*X(28)-JVS(80)*X(30)-JVS(81)*X(33))/(JVS(77))
  X(17) = (X(17)-JVS(72)*X(30)-JVS(73)*X(33))/(JVS(71))
  X(16) = (X(16)-JVS(63)*X(21)-JVS(64)*X(23)-JVS(65)*X(24)-JVS(66)*X(28)-JVS(67)*X(38)-JVS(68)*X(39))/(JVS(62))
  X(15) = (X(15)-JVS(56)*X(21)-JVS(57)*X(23)-JVS(58)*X(25)-JVS(59)*X(28)-JVS(60)*X(38)-JVS(61)*X(39))/(JVS(55))
  X(14) = (X(14)-JVS(46)*X(18)-JVS(47)*X(23)-JVS(48)*X(25)-JVS(49)*X(26)-JVS(50)*X(28)-JVS(51)*X(30)-JVS(52)*X(33)&
            &-JVS(53)*X(38)-JVS(54)*X(39))/(JVS(45))
  X(13) = (X(13)-JVS(38)*X(17)-JVS(39)*X(30)-JVS(40)*X(32)-JVS(41)*X(37))/(JVS(37))
  X(12) = (X(12)-JVS(34)*X(32)-JVS(35)*X(33)-JVS(36)*X(37))/(JVS(33))
  X(11) = (X(11)-JVS(32)*X(33))/(JVS(31))
  X(10) = (X(10)-JVS(29)*X(11)-JVS(30)*X(33))/(JVS(28))
  X(9) = (X(9)-JVS(26)*X(33))/(JVS(25))
  X(8) = (X(8)-JVS(24)*X(33))/(JVS(23))
  X(7) = (X(7)-JVS(21)*X(30)-JVS(22)*X(32))/(JVS(20))
  X(6) = (X(6)-JVS(17)*X(32)-JVS(18)*X(33)-JVS(19)*X(34))/(JVS(16))
  X(5) = (X(5)-JVS(15)*X(33))/(JVS(14))
  X(4) = (X(4)-JVS(12)*X(32)-JVS(13)*X(35))/(JVS(11))
  X(3) = (X(3)-JVS(9)*X(33)-JVS(10)*X(37))/(JVS(8))
  X(2) = (X(2)-JVS(7)*X(28))/(JVS(6))
  X(1) = (X(1)-JVS(2)*X(15)-JVS(3)*X(16)-JVS(4)*X(21)-JVS(5)*X(33))/(JVS(1))

  RETURN
END SUBROUTINE KppSolve_day

real(kind=8) FUNCTION ros_ErrorNorm ( Y, Ynew, Yerr, &
                               AbsTol, RelTol )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~> Computes the "scaled norm" of the error vector Yerr
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   IMPLICIT NONE
! Input arguments
   real(kind=8), INTENT(IN) :: Y(N), Ynew(N), &
          Yerr(N), AbsTol(N), RelTol(N)
! Local variables
   real(kind=8) :: Err, Scale, Ymax
   INTEGER(KIND=4)  :: i
   real(kind=8), PARAMETER :: ZERO = 0.0d0
   Err = ZERO
   DO i=1,N
     Ymax = MAX(ABS(Y(i)),ABS(Ynew(i)))
     Scale = AbsTol(i)+RelTol(i)*Ymax
     Err = Err+(Yerr(i)/Scale)**2
   END DO
   Err  = SQRT(Err/N)
   ros_ErrorNorm = MAX(Err,1.0d-10)
  END FUNCTION ros_ErrorNorm

END SUBROUTINE mach_kppb_adom2day_rodas3
